### ISSUE TITLE
v4.7.0 not generating "boil_" files

### ISSUE THREAD

**Issue by prieston** [volatiletech/sqlboiler#1001]
I user the folloing command to generate my models:
 `go:generate sqlboiler --wipe --tag db psql`

### What version of SQLBoiler are you using (`sqlboiler --version`)?
While using v4.6.0 boil_queries.go, boil_table_names.go and boil_types.go where generated. Upgrading to 4.7.0 is not generating them.

### What is your database and version (eg. Postgresql 10)
Postgres 13

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`export PATH=$PATH:$(go env GOPATH)/bin && npm run install-generation-deps && go generate ./common/.../ && ./update_models_for_swagger.sh && go generate ./core/..`

The `npm run install-generation-deps` runs this command
`go install github.com/volatiletech/sqlboiler/v4@latest && go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-psql@latest`

### Further information. What did you do, what did you expect?

By changing the `npm run install-generation-deps` command to 
`go install github.com/volatiletech/sqlboiler/v4@v.4.6.0 && go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-psql@latest`

The problem is fixed, so I suppose this is a problem caused by upgrading to version 4.7.0

**Comment by mradile** [comment]
I am expieriencing the same issue. Using 4.7.0 does not generate the boil_* files, going back to 4.6.0 is still working.

```bash
go install github.com/volatiletech/sqlboiler/v4@v4.6.0
go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-psql@v4.6.0

sqlboiler psql
```

sqlboiler config file:
```toml
output = "pkg/db/models"
wipe     = true
no-tests = true

[psql]
dbname = "wisag"
user   = "wisag"
pass   = "wisag"
host   = "127.0.0.1"
port   = 5433
sslmode = "disable"
```

**Comment by zikaeroh** [comment]
There's a bug in the code that was added to switch from gobindata to `go:embed`; see: https://github.com/volatiletech/sqlboiler/pull/1000#issuecomment-927514190 (fixed in that PR).

**Comment by zikaeroh** [comment]
I believe v4.7.1 should have fixed this.

**Comment by majodev** [comment]
Can confirm v4.7.1 fixes this (broken CI build of [allaboutapps/go-starter](https://github.com/allaboutapps/go-starter/pull/129) with [v4.7.0](https://github.com/allaboutapps/go-starter/pull/127) vs [v4.7.1](https://github.com/allaboutapps/go-starter/pull/129)).
