### ISSUE TITLE
Tests fail on MySQL with a BINARY(16) Primary Key

### ISSUE THREAD

**Issue by asiragusa** [volatiletech/sqlboiler#1004]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.6.0

### What is your database and version (eg. Postgresql 10)
Mysql 8.0

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
CREATE TABLE companies(
                      id BINARY(16),
                      name VARCHAR (50) NOT NULL,
                      description TEXT,
                      created_at TIMESTAMP NOT NULL,
                      updated_at TIMESTAMP NOT NULL,
                      deleted_at TIMESTAMP,
                      PRIMARY KEY (id)
);

```

### Further information. What did you do, what did you expect?
The automated tests fail when using a `BINARY(16)` Primary Key on MySQL. This seems to come from `randomize.Struct` which doesn't return a 16 binary string, but it's shorter. I manually fixed one of the tests by using a 16 bytes string for the ID:
```golang
func testCompaniesSoftDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Company{}
	if err = randomize.Struct(seed, o, companyDBTypes, true, companyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Company struct: %s", err)
	}
        // My Fix
	o.ID = []byte("TESTTESTTESTTEST")
// ...
}
```

That said, I don't think that the problem is related to the fixed string generation for the Primary Key, which should be able to be shorter than the given 16 bytes.

**Comment by aarondl** [comment]
We've generally given up on maintaining these tests especially for this or that special case (such as BINARY(16) pkeys). In general these tests produce many false positives and false negatives and aren't trustworthy.

Won't be dedicating time to fixing this.
