### ISSUE TITLE
Creates duplicate rows on concurrent process

### ISSUE THREAD

**Issue by h4yfans** [volatiletech/sqlboiler#1010]
### Further information. What did you do, what did you expect?
I trying to create a new row on the concurrent processes.

My code;
```
for index := range builders {
			wg.Add(1)
		    go func(){
			    defer wg.Done()

			    data, err := entities.Mappings(entities.MappingWhere.Specifier.EQ(filter.Specifier)).One(ctx, m.db)
			    if errors.Is(err, sql.ErrNoRows){
				      // Create if doesn't exists
				      err = map.Insert(ctx, m.db, boil.Infer())
				      if err!=nil{
					      // Log error
					      continue
				      }
			    }

				// Continue...
		    }()
}
```

My DB table;
```
+-----------+----------------------------------+---------------------------------+
|specifier  | created_at                       |updated_at                       |                      
+------------------+-------------------------------------------------------------+
|compact    | 2021-10-11 17:52:02.436988 +00:00|2021-10-11 17:52:02.436988 +00:00|  
|compact    | 2021-10-11 17:52:02.441732 +00:00|2021-10-11 17:52:02.441732 +00:00|
|compact    | 2021-10-11 17:52:02.444926 +00:00|2021-10-11 17:52:02.444926 +00:00|
+------------------+-------------------------------------------------------------+
```

Problem is, it's creating a new rows more than one in seconds.
Should I use `sync.Mutex`? I don't want to use `mutex` because it makes it slower.
Is there any other solution to this problem?

### What version of SQLBoiler are you using (`sqlboiler --version`)?
`v4.6.0`

### What is your database and version (eg. Postgresql 10)
`Postgresql13`

**Comment by stephenafamo** [comment]
You should not be using a loop variable (in this case `index`) in a goroutine.

I cannot see the rest of your function, but I assume that you may be using `index` to retrieve the values to add at some point, and that is likely what causes the duplicates since the value of `index` may have changed before it is called in the goroutine.

**Comment by aarondl** [comment]
Very likely the answer is what @stephenafamo pointed out. Thanks for answering him :)

A quick google search for `goroutines loop variables` should help.
