### ISSUE TITLE
how to use Union All on queryMod?

### ISSUE THREAD

**Issue by hizzuu** [volatiletech/sqlboiler#1021]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
4.2.0

### What is your database and version (eg. Postgresql 10)
postgres:13.3
go:1.13

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

CREATE TABLE "jobs"(
  "job_mgr_no" BIGINT NOT NULL,
  "comp_name" VARCHAR(255) NOT NULL,
  "title" VARCHAR(255) NOT NULL,
  "description" VARCHAR(255) NOT NULL,
  "kind" VARCHAR(255),
  "salary"  VARCHAR(255),
  PRIMARY KEY ("job_mgr_no")
);

CREATE TABLE "other_jobs"(
  "othre_job_mgr_no" VARCHAR(255) NOT NULL,
  "corp_name" VARCHAR(255) NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "text" VARCHAR(255) NOT NULL,
  "accept_date" DATE,
  PRIMARY KEY ("othre_job_mgr_no")
);

### Further information. What did you do, what did you expect?
I'd like to know if there is a function like union all.
I'd like to add it to []qm.QueryMod in the end.

```
        var jobs []*Job
	q := `SELECT 
			jobs.job_mgr_no,
			'' AS "othre_job_mgr_no",
			jobs.comp_name, jobs.description,
			jobs.kind, jobs.salary,
			NULL AS "accept_date" 
		FROM 
			jobs
		UNION ALL
		SELECT 
			0 AS "job_mgr_no",
			other_jobs.othre_job_mgr_no,
			other_jobs.corp_name,
			other_jobs."text",
			null AS "kind",
			null AS "salary",
			other_jobs.accept_date
		FROM 
			other_jobs`

	queries.Raw(q).BindG(ctx, &jobs)
	return jobs, nil
```

**Comment by aarondl** [comment]
There's no union all possibilities unfortunately. Got to use raw queries.
