### ISSUE TITLE
Generated code full of errors - won't build.

### ISSUE THREAD

**Issue by tomsharratt** [volatiletech/sqlboiler#1022]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
4.6.0 (Not using latest because I need soft delete functions)

### What is your database and version (eg. Postgresql 10)
Postgres 14

### Further information. What did you do, what did you expect?
After generation I noticed a lot of errors due to missing imports etc.

Trying to build shows some of these errors:
```
#11 5.135 models/invites.go:1214:27: undefined: testing
#11 5.135 models/invites.go:1221:10: undefined: randomize
#11 5.135 models/invites.go:1225:11: undefined: randomize
#11 5.135 models/invites.go:1225:38: undefined: inviteDBTypes
#11 5.135 models/invites.go:1230:8: undefined: MustTx
#11 5.135 models/invites.go:1245:11: undefined: randomize
#11 5.135 models/invites.go:1245:38: undefined: inviteDBTypes
#11 5.135 models/organizations.go:1324:33: undefined: testing
#11 5.135 models/organizations.go:1331:10: undefined: randomize
#11 5.135 models/users.go:1184:25: undefined: testing
#11 5.135 models/organizations.go:1331:10: too many errors
```

**Comment by aarondl** [comment]
Unsure how I could reproduce this. Can you give more information? Are you on a peculiar Go version or architecture? Did you override the imports in some fashion (note that overidding them REPLACES it does not add to).

**Comment by tomsharratt** [comment]
So I found if I used the latest version 4.71 it works as expected. However, soft delete is currently broken and the PR isn't merged yet.

Any idea when that fix should be released?

**Comment by aarondl** [comment]
@tomsharratt https://github.com/volatiletech/sqlboiler/releases/tag/v4.8.0

**Comment by tomsharratt** [comment]
> @tomsharratt https://github.com/volatiletech/sqlboiler/releases/tag/v4.8.0

Thanks, just tried this and got an error for test templates
```sqlboiler --wipe --add-soft-deletes psql
Error: unable to generate test output: failed to execute template: test/delete.go.tpl: template: test/delete.go.tpl:2:28: executing "test/delete.go.tpl" at <.Table.CanSoftDelete>: wrong number of args for CanSoftDelete: want 1 got 0
```

**Comment by aarondl** [comment]
Ugh :D You can skip test code generation and it should work. I'll fix that in 4.8.1 right away. Sorry about that :p

**Comment by aarondl** [comment]
Released.

**Comment by tomsharratt** [comment]
LGTM
