### ISSUE TITLE
Generation fails when using enums in schema v4.8.1

### ISSUE THREAD

**Issue by jlkiri** [volatiletech/sqlboiler#1025]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
4.8.1

### What is your database and version (eg. Postgresql 10)
MySQL 5.7

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
```
sqlboiler mysql --no-tests --output /db/models
```

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
```
Error: singleton template output: failed to execute template: main/singleton/boil_types.go.tpl: template: main/singleton/boil_types.go.tpl:78:20: executing "main/singleton/boil_types.go.tpl" at <titleCase>: wrong number of args for titleCase: want 1 got 2
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```
CREATE TABLE status (
    id SERIAL PRIMARY KEY,
    status ENUM('fail', 'success') NOT NULL
);
```

**Comment by aarondl** [comment]
Should be fixed in the latest release.
https://github.com/volatiletech/sqlboiler/releases/tag/v4.8.3
