### ISSUE TITLE
Generation of enum type information has changed in 4.8.1

### ISSUE THREAD

**Issue by michael-browner-vertiv** [volatiletech/sqlboiler#1027]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

4.8.1

### What is your database and version (eg. Postgresql 10)

Postgres 13

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

sqlboiler psql --config ${PRJBASE}/sqlboiler.toml

toml file

output              = "pkg/repository"
wipe                = true
add-global-variants = true
no-tests            = false
pkgname             = "repository"

[aliases.tables.Device.columns]
device_type = "Type"

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

Had a enum with values such as 'kvm_ip',  'serial_ip'

Old generation on 4.7.1 produced   

DeviceConnectionPathTypeKVMIP
DeviceConnectionPathTypeSerialIP

New Generation produces  4.8.1

DeviceConnectionPathTypekvm_ip
DeviceConnectionPathTypeserial_ip

**Comment by michael-browner-vertiv** [comment]
Thank you

**Comment by aarondl** [comment]
I hope this is fixed in the latest release. Let me know if not.
https://github.com/volatiletech/sqlboiler/releases/tag/v4.8.3
