### ISSUE TITLE
Generate sqlboiler using latest volatiletech/null version

### ISSUE THREAD

**Issue by cymon1997** [volatiletech/sqlboiler#1034]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
v4.8.3

### What is your database and version (eg. Postgresql 10)
mysql:8.0

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
```sh
go get -u -t github.com/volatiletech/sqlboiler/v4
go get github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql
go get github.com/volatiletech/null/v9
sqlboiler mysql
```

### Further information. What did you do, what did you expect?
Should generate with latest `github.com/volatiletech/null/v9` version. 
Actual: still use `github.com/volatiletech/null/v8` version.

**Comment by cymon1997** [comment]
Hi @aarondl, [#1033](https://github.com/volatiletech/sqlboiler/pull/1033) should fix this issue. Is there any time estimation when this PR will merged? Thanks!

**Comment by aarondl** [comment]
See comments on #1033 :(
