### ISSUE TITLE
Why sqlboiler capitalises model names containing "ApiSomething" to "APISomething"?

### ISSUE THREAD

**Issue by shaders** [volatiletech/sqlboiler#1039]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.6.0

### What is your database and version (eg. Postgresql 10)
Postgresql 10

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`	sqlboiler psql -d\
		-c sqlboiler.toml \
		--templates "${GOPATH}/pkg/mod/github.com/volatiletech/sqlboiler/v4@${SQLBOILER_VERSION}/templates" \
  		--templates "tools/generators/assets/templates/sqlboiler" \
  		--no-hooks \
  		--no-auto-timestamps`

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
Providing only relevant part
`"api_tokens":{"up_plural":"APITokens","up_singular":"APIToken","down_plural":"apiTokens","down_singular":"apiToken","columns":{"accountid":"AccountID","code":"Code","created":"Created","name":"Name","restrictions":"Restrictions","type":"Type","uid":"ID","value":"Value"}},
"event_attributes":{"up_plural":"EventAttributes","up_singular":"EventAttribute","down_plural":"eventAttributes","down_singular":"eventAttribute","columns":{"created":"Created","eventid":"EventID","name":"Name","type":"Type","uid":"ID"}}`

### Further information. What did you do, what did you expect?
**event_attributes** name generated as **EventAttributes** which is correct and consistent.
**api_tokens** converted to **APITokens** which is not consistent and not expected.

Any way to revert this to consistent casing? (i.e. "api" => "Api", not "API")

Thanks

**Comment by shaders** [comment]
Capitalisation happens here: https://github.com/volatiletech/strmangle/blob/master/strmangle.go#L283

**Comment by aarondl** [comment]
This is by design as it creates a more idiomatic Go experience:
https://github.com/golang/go/wiki/CodeReviewComments#initialisms

HTTPClient not HttpClient is the expected thing that Go programmers write and therefore what this tool strove to do. It may not have been the correct choice as we can't be exhaustive with our initialisms list but it certainly created less of an eyesore within our own code bases.

**Comment by shaders** [comment]
Thank you!

`Code generated by the protocol buffer compiler is exempt from this rule.`

Ok. That's where it struck me. I was using sqlboiler with protobuff compiler generated code. No problem, will just have another step to preprocess the code to make it "protobuff compatible"
