### ISSUE TITLE
Error if the foreign key does not explicitly specify the parent primary key

### ISSUE THREAD

**Issue by MeanSquaredError** [volatiletech/sqlboiler#1053]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.8.3

### What is your database and version (eg. Postgresql 10)
SQLite 3.34.1 2021-01-20 14:10:07 10e20c0b43500cfb9bbc0eaa061c57514f715d87238f4d835880cd846b9ealt

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
/root/go/bin/sqlboiler -c ./sqlboiler.toml /root/go/bin/sqlboiler-sqlite3

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
Attached
[sqlboiler_output.txt](https://github.com/volatiletech/sqlboiler/files/7807369/sqlboiler_output.txt)

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```
CREATE TABLE table_1 (
        table_1_id INT PRIMARY KEY
);
CREATE TABLE table_2 (
        table_2_id INT PRIMARY KEY,
        table_1_ref INT REFERENCES table_1
);
```

### Further information. What did you do, what did you expect?
I tried to generate an SQLBoiler model and expected it to generate the model code silently. Instead I get the following error:
```
unable to fetch table fkey info (table_2): sql: Scan error on column index 4, name "to": converting NULL to string is unsupported
Error: unable to initialize tables: unable to fetch table data: driver (/root/go/bin/sqlboiler-sqlite3) exited non-zero: exit status 1
```

**Comment by stephenafamo** [comment]
I guess the driver would have to be modified to understand these cases.

Also, this issue probably belongs in the driver repo: https://github.com/volatiletech/sqlboiler-sqlite3
