### ISSUE TITLE
Cannot bind foreign data into main struct

### ISSUE THREAD

**Issue by shahriar350** [volatiletech/sqlboiler#1054]
```
cart, err := models.Carts(qm.Load(models.CartRels.CartProducts),qm.Where("user_id = ?", c.Locals("user_id"))).One(context.Background(), conn.DB)
	fmt.Println(cart)
	if err != nil {
		return err
	}
	return c.JSON(cart)
```
```
{
	id: 1, created_at: null, updated_at: null, deleted_at: null, slug: "saif-7943-2", user_id: null
	created_at: null
	deleted_at: null
	id: 1
	slug: "saif-7943-2"
	updated_at: null
	user_id: null
}

```
I use Load to retrieve foreign keys but foreign data is not bound to returning data. 
How can I add a foreign key into JSON data?

**Comment by stephenafamo** [comment]
The foreign data is likely there, but not printed by JSON.

It is in the `R` attribute of the generated model, and if you check `models/cart.go` you'd likely see

```go
type Cart struct {
  // ...
  R *cartR `boil:"-" json:"-" toml:"-" yaml:"-"`
  // ...
```

**Comment by shahriar350** [comment]
> The foreign data is likely there, but not printed by JSON.
> 
> It is in the `R` attribute of the generated model, and if you check `models/cart.go` you'd likely see
> 
> ```go
> type Cart struct {
>   // ...
>   R *cartR `boil:"-" json:"-" toml:"-" yaml:"-"`
>   // ...
> ```

I can get all CartProduct data using for loop and print them into console but I cannot bind that CartProduct into Cart struct. when I return Cart, only Cart object return, not CartProduct as well with Cart.

**Comment by shahriar350** [comment]
> The foreign data is likely there, but not printed by JSON.
> 
> It is in the `R` attribute of the generated model, and if you check `models/cart.go` you'd likely see
> 
> ```go
> type Cart struct {
>   // ...
>   R *cartR `boil:"-" json:"-" toml:"-" yaml:"-"`
>   // ...
> ```

I can get all CartProduct data using for loop and print them into console but I cannot bind that CartProduct into Cart struct. when I return Cart, only Cart object return, not CartProduct as well with Cart.

**Comment by stephenafamo** [comment]
I don't exactly understand what you're saying. Can you maybe share a code example?

**Comment by shahriar350** [comment]
> I don't exactly understand what you're saying. Can you maybe share a code example?

```
{
	id: 1, created_at: null, updated_at: null, deleted_at: null, slug: "saif-7943-2", user_id: null
	created_at: null
	deleted_at: null
	id: 1
	slug: "saif-7943-2"
	updated_at: null
	user_id: null,
        CartProducts: [
                {
                         cart_id: 1,
                         product: 1,
                         quantity: 3
                }
        ]
}

```
I want my cart object like this. see here cart has CartProduct, but not added in the cart. i need when I use Load("CartProduct"), it returns Cart struct with CartProducts array.
