### ISSUE TITLE
Upsert test fails when using `GENERATED ALWAYS` Postgres syntax

### ISSUE THREAD

**Issue by MaxWaterfall** [volatiletech/sqlboiler#1059]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v4.8.3

### What is your database and version (eg. Postgresql 10)
Postgres: 14

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`sqlboiler psql --wipe`

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
CREATE TABLE example
(
    id INT GENERATED ALWAYS AS IDENTITY,
    test_col TEXT,
    test_col_2 TEXT,
    PRIMARY KEY(id)
);
```

### Further information. What did you do, what did you expect?
Apologies if this is already known, I couldn't find an issue for it.

The upsert test fails because it provides a value for the id field. I don't think postgres allows this, from the postgres [docs](https://www.postgresql.org/docs/current/sql-createtable.html):
> In an INSERT command, if ALWAYS is selected, a user-specified value is only accepted if the INSERT statement specifies OVERRIDING SYSTEM VALUE. 

[This repo](https://github.com/MaxWaterfall/sqlboiler-upsert-test-fail) demonstrates the issue.

**Comment by stephenafamo** [comment]
SQLBoiler doesn't support generated columns at the moment, so I suspect that is part of the reason this is causing issues.

But that feature is currently being worked on, fingers crossed, it would be in the next version

**Comment by MaxWaterfall** [comment]
Okay that makes sense, thank you @stephenafamo 👍

**Comment by stephenafamo** [comment]
This will be in the next release 4.8.4

However, because of the way the tests work, the upsert test with a GENERATED ALWAYS primary key is likely to fail (although with a different error message).

The generated tests are quite wonky and we either need an overhaul or to drop them entirely.
