### ISSUE TITLE
Missing (...Query).UpdateAllGP(...)

### ISSUE THREAD

**Issue by MeanSquaredError** [volatiletech/sqlboiler#1062]
The template for the UPDATE queries in `templates/main/16_update.go.tpl` seems to be lacking `(...Query).UpdateAllGP`. There is no function
```
func (q {{$alias.DownSingular}}Query) UpdateAllGP(...)...
```

The `G` and `P` versions are present but there is no `GP`. Is this intentional or just a bug in the templates?

**Comment by stephenafamo** [comment]
This is definitely not intentional.

If you can send a PR for this I'll be happy to merge.

**Comment by MeanSquaredError** [comment]
OK. I will prepare a PR shortly.
