### ISSUE TITLE
Don't generate .go files with special suffixes

### ISSUE THREAD

**Issue by cloneable** [volatiletech/sqlboiler#1067]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v4.8.3

### What is your database and version (eg. Postgresql 10)

Postgresql 10.19

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

`sqlboiler psql`

### Further information. What did you do, what did you expect?

I've got a table in an existing schema that ends with `_js` and after running sqlboiler I was stumped that the compiler couldn't find the symbols that are right there in the same package in the `table_js.go` file. It hit me then that `js` is the new pseudo GOOS for webassembly and files with `_js` get compiled conditionally.
 
So I created a schema with `bla_js`, `bla_test`, and `bla_linux` tables and sqlboiler happily generated .go files for these tables named `bla_js.go`, `bla_test.go`, and `bla_linux.go`.

sqlboiler should generate files from table names that don't use these suffixes. Maybe simply append `_table` or `_gen` or `_boil`, e.g. `bla_js_gen.go`.

**Comment by cloneable** [comment]
Thanks! That was quick!

I haven't checked yet, but does this also cover the case where a table name ends with `_test`? Will this produce a `_test_model.go` file? I'm just curious because I don't see that test case.

**Comment by stephenafamo** [comment]
No it does not. Only covers `GOOS` and `GOOARCH` suffixes.

Although now that you mention it, it should also cover `_test` suffixes.

**Comment by stephenafamo** [comment]
Done in #1069 

To be clear these won't be available until the next release
