### ISSUE TITLE
Cannot properly handle column names that contain spaces

### ISSUE THREAD

**Issue by riadafridishibly** [volatiletech/sqlboiler#1084]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
```
SQLBoiler v4.8.6
```

### What is your database and version (eg. Postgresql 10)
```
postgres (PostgreSQL) 12.10 (alpine in docker)
```

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
```
sqlboiler --wipe psql
```

And I got this, 

```
Error: unable to generate output: failed to format template

  24 
  25 // CustomerList is an object representing the database table.
  26 type CustomerList struct {ID null.Int `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
  27 	Name null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
  28 	Address null.String `boil:"address" json:"address,omitempty" toml:"address" yaml:"address,omitempty"`
>>>> 	Zip code null.String `boil:"zip code" json:"zip code,omitempty" toml:"zip code" yaml:"zip code,omitempty"`
  30 	Phone null.String `boil:"phone" json:"phone,omitempty" toml:"phone" yaml:"phone,omitempty"`
  31 	City null.String `boil:"city" json:"city,omitempty" toml:"city" yaml:"city,omitempty"`
  32 	Country null.String `boil:"country" json:"country,omitempty" toml:"country" yaml:"country,omitempty"`
  33 	Notes null.String `boil:"notes" json:"notes,omitempty" toml:"notes" yaml:"notes,omitempty"`
  34 	Sid null.Int16 `boil:"sid" json:"sid,omitempty" toml:"sid" yaml:"sid,omitempty"`

: 29:11: expected ';', found null (and 5 more errors)
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

I've loaded this database into docker postgres, and tried to generate models.

- https://www.postgresqltutorial.com/wp-content/uploads/2019/05/dvdrental.zip
- https://www.postgresqltutorial.com/postgresql-sample-database/

### Further information. What did you do, what did you expect?

```
output   = "models"
wipe     = true
add-enum-types = true

[psql]
  dbname = "dvdrental"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "pass"
  sslmode = "disable"
```

**Comment by stephenafamo** [comment]
It appears there is a column in the `customer_list` view called `zip code`, and SQLBoiler does not properly handle columns that contain spaces.

Can't give a timeline for if/when this will be fixed, but you can fix this by either changing the column name, or adding an alias in your `sqlboiler.toml` configuration.

```toml
  [aliases.tables.customer_list.columns]
  "zip code" = "ZipCode"
```

**Comment by stephenafamo** [comment]
This is no longer a problem from `v4.10.1`
