### ISSUE TITLE
Make enum values iteratable

### ISSUE THREAD

**Issue by alexykot** [volatiletech/sqlboiler#1112]
Consider the following sample enum representation in SQLBoiler generated code:

```
const (
  WorkdayMonday  = "monday"
  WorkdayTuesday  = "tuesday"
  WorkdayWednesday = "wednesday"
  WorkdayThursday = "thursday"
  WorkdayFriday  = "friday"
)
```

This works for referencing individual values, but it doesn't allow iterating all possible values in the Go code. Would be great to be able to iterate them.

Why do we need this?

We have a lot of places in our codebase where ORM enums must be aligned at all times with protobuf or internal enums representing the same values. A great way to ensure this alignment at all times is to have a unit test that would enumerate all values of one enum and validate that corresponding values exist in the other enum. This and also validating that the total length of both enums is the same will ensure at test-time that enums are perfectly aligned and type safety is preserved.

But at present, it's impossible to programmatically enumerate all enum values in SQLBoiler, or even access individual values through enumerating the enum on the other side. An internal map of all enum values similar to protobuf `<Type>_name` and  `<Type>_value` maps would solve this. There may be other solutions as well, but overall - the ability to iterate all values would be very helpful here.

**Comment by stephenafamo** [comment]
There will be a generated variable called `AllWorkday()` is a slice of all the enum values. This is already in the codebase and will be in the next release (4.9.0)

**Comment by alexykot** [comment]
Nice, will upgrade as soon as it's available.

**Comment by stephenafamo** [comment]
Did the release earlier today. Try it out. @alexykot

**Comment by alexykot** [comment]
Yep, I wrote that before looking at the latest releases. Someone on our side is already upgrading our dependencies. 
Thank you :)
