### ISSUE TITLE
Types template is missing <columnName>ColumnsWithAuto global var

### ISSUE THREAD

**Issue by nekrondev** [volatiletech/sqlboiler#1119]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

v4.8.4 upwards  (until v4.8.3 no issues)

### What is your database and version (eg. Postgresql 10)

SQL Server 13.0.5026 (SQL Server 2016)

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

sqlboiler.exe --wipe --no-auto-timestamps --no-hooks --output ${workspaceRoot}\\backend\\models -c .\\db\\sqlboiler.yaml mssql

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

no runtime issue;
generated code is missing global variable for auto columns

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)

n/a

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

n/a

### Further information. What did you do, what did you expect?

Since version 4.8.4 `01_types.go.tpl` template is missing 

```
{{if .Dialect.UseAutoColumns -}}
	{{$alias.DownSingular}}ColumnsWithAuto = []string{{"{"}}{{.Table.Columns | filterColumnsByAuto true | columnNames | stringMap .StringFuncs.quoteWrap | join ","}}{{"}"}}
{{end -}}
```
to create `<column>ColumnsWithAuto` vars for all tables in use.
However the generated boilerplate code is referencing the missing vars causing a lot of compile and linter errors.

**Comment by stephenafamo** [comment]
`{{$alias.DownSingular}}ColumnsWithAuto` is no longer generated, instead it is now `{{$alias.DownSingular}}GeneratedColumns`.

AFAIK, the templates have also all been updated accordingly except you are still using an outdated driver. Can you try again with the latest binary and driver?

If there are still any references to `{{$alias.DownSingular}}ColumnsWithAuto` can you let me know where?

**Comment by nekrondev** [comment]
Thanks @stephenafamo  I re-checked my configuration and found a mistake not updating the mssql driver. After fixing the setup generated files are working fine. 

Big sorry for the false alarm (I should have RTFM..)!
