### ISSUE TITLE
Possible mistake in templates added in [v4.9.2]

### ISSUE THREAD

**Issue by franchb** [volatiletech/sqlboiler#1120]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v4.9.2

### What is your database and version (eg. Postgresql 10)
PostgreSQL 13

### Further information. What did you do, what did you expect?

Last release v4.9.2 added this commit https://github.com/volatiletech/sqlboiler/commit/cab8d274f87fac23bbf8579bdf4c32bb64f1fdb8 :

```go
    mods = append(mods, qm.From("{{$schemaTable}}"))
    {{end -}}

    q := NewQuery(mods...)
    if len(queries.GetSelect(q)) == 0 {
        queries.SetSelect(q, []string{"{{$schemaTable}}.*"})
    }

    return {{$alias.DownSingular}}Query{NewQuery(mods...)}
```

Variable `q` is assigned but not used anywhere. Maybe this code is expected to work as:

```go
    mods = append(mods, qm.From("{{$schemaTable}}"))
    {{end -}}

    q := NewQuery(mods...)
    if len(queries.GetSelect(q)) == 0 {
        queries.SetSelect(q, []string{"{{$schemaTable}}.*"})
    }

    return {{$alias.DownSingular}}Query{q}
```

?

**Comment by stephenafamo** [comment]
Yes this is correct. Thanks for spotting it. Now fixed in `v4.10.1`
