### ISSUE TITLE
SQLite driver is broken

### ISSUE THREAD

**Issue by lzap** [volatiletech/sqlboiler#1122]
Hey, it looks like the current stable sqlite driver is broken. It now uses the different sqlite (cgo) driver, however, the connection still uses the old "sqlite3" driver name:

https://github.com/volatiletech/sqlboiler/blob/2af0c047f49c674728499e57312519e36203c496/drivers/sqlboiler-sqlite3/driver/sqlite3.go#L115

That does not work at all with the new one:

https://gitlab.com/cznic/sqlite/-/blob/v1.16.0/examples/example1/main.go#L30

Any attempt to use this version of the driver will result:

```
sql: unknown driver "sqlite3" (forgotten import?)
exit status 1
```

**Comment by lzap** [comment]
Hmmm I was able to get it working without global connection.

```
DB, err = sql.Open("sqlite", fmt.Sprintf("file:%s?_loc=UTC", "devel.db"))
```

With global connection, it does not work for some reason:

```
	boil.SetDB(DB)
```

I am getting

```

 panic: interface conversion: interface is nil, not boil.ContextExecutor
 
 -> github.com/volatiletech/sqlboiler/v4/queries.(*Query).Bind
 ->   /home/lzap/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.10.2/queries/reflect.go:133

    chitest/pkg/models.sshKeyQuery.All
```

**Comment by stephenafamo** [comment]
As far as I know, the driver should work just fine, and if it did not, you should have gotten an error in the `sql.Open` call.

If the error you get says:

```
 panic: interface conversion: interface is nil, not boil.ContextExecutor
```

Then your DB object is not present at all and remains `nil`. If it was at least present, the error would say "foo does not implement `boil.ContextExecutor` missing method foobar".   

Can you make sure the `sql.Open()` call is successful?

**Comment by lzap** [comment]
We moved to postgres, only the prototype used sqlite. Thanks!
