### ISSUE TITLE
How to append eager loading with where clause?

### ISSUE THREAD

**Issue by HeedoKang** [volatiletech/sqlboiler#1133]
For query performance, we have to use a raw query for union operation.

`query := queries.Raw(....)`

With raw query, we would like to use eager loading. 
As far as I know, eager loading except where clause is possible in the following way. 

```
queries.AppendLoad(query, ....)
queries.AppendLoad(query, ....)
```

By the way, how to add eager loading including where clause?

**Comment by stephenafamo** [comment]
This is currently not possible, but it is something we are looking to make possible in `v5`
