### ISSUE TITLE
SQLBoiler soft delete not working with auto-column

### ISSUE THREAD

**Issue by shivaluma** [volatiletech/sqlboiler#1139]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.11.0

### What is your database and version (eg. Postgresql 10)
Postgresql 12

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

wipe="true"
add-global-variants="false"
no-hooks="true"
no-tests="true"
add-enum-types="false"
add-soft-deletes="true"

[auto-columns]
    deleted = "deletedAt"
    created = "createdAt"
    updated = "updatedAt"

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
Any query to find item will cause the issue because deleted is mapping to "deleted_at", not like my own mapping.
`Cannot filter using the given query: models: failed to assign all query results to Device slice: bind failed to execute query: ERROR: column Devices.deleted_at does not exist (SQLSTATE 42703)`

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
We use a column for soft delete as deletedAt, not deleted_at.

### Further information. What did you do, what did you expect?
https://github.com/volatiletech/sqlboiler/blob/bc05a429db24e01ed0ebce9c487fe6575584936f/main.go#L184
As sqlboiler define deleted in auto-columns, i think it should work like created and updated

**Comment by shivaluma** [comment]
Hi @stephenafamo please help me to review this issue.

**Comment by longtt2705** [comment]
I have an exact same problem. Please let me know how to fix this.

**Comment by stephenafamo** [comment]
Definitely a bug. Likely forgot to use the defined auto column in a place instead of the default. Sorry about this.

I'm quite busy at the moment so I won't be able to find/fix it soon, although a PR would be highly appreciated.

**Comment by shivaluma** [comment]
Hi @stephenafamo, I have another question about how to use qm.Load, can I put another qm like where, limit, order to a eager load in the middle of the chain when using a chain of Load ? 

 For example, i want to limit the result of OrganizationUserIdOrganizationUserRoles relation to only one.
<img width="587" alt="Screen Shot 2022-06-01 at 00 53 53" src="https://user-images.githubusercontent.com/33391636/171253012-96ae33f5-60b0-4706-bd27-c91034ca3606.png">

**Comment by shivaluma** [comment]
> Definitely a bug. Likely forgot to use the defined auto column in a place instead of the default. Sorry about this.
> 
> I'm quite busy at the moment so I won't be able to find/fix it soon, although a PR would be highly appreciated.

Hey I have made a PR to fix this issue, please review it and let me know your concerns. Thank you.

https://github.com/volatiletech/sqlboiler/pull/1144

**Comment by stephenafamo** [comment]
The fix has been merged, so I'll close this. Will be included in the next release.
