### ISSUE TITLE
No `IN` and `NIN` helpers for enum types

### ISSUE THREAD

**Issue by dnaka91** [volatiletech/sqlboiler#1142]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v4.11.0

### What is your database and version (eg. Postgresql 10)

MySQL 5.7

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

```
sqlboiler --wipe --add-enum-types mysql
```

### Further information. What did you do, what did you expect?

Was expecting to get the `IN` and `NIN` helper methods for where clauses, similar to primitive types. For some reason, these are missing for enum types.

Could these be enabled for enums as well, or is there a reason against it? We have lots of enums in the DB that represent different states, so we often select over a range of applicable states and not having these helper function is a bit of a _dealbreaker_ for using `--add-enum-types`.

**Comment by stephenafamo** [comment]
In theory, this should be possible, but it is just not yet done. We'll add it when possible, I'll also add the help-wanted tag incase you or anyone else wants to whip up a PR.
