### ISSUE TITLE
Inconsistent Results from Bind

### ISSUE THREAD

**Issue by reiman2222** [volatiletech/sqlboiler#1147]
sqlboil cli version: `SQLBoiler v4.8.6`

Go version: `go version go1.17.10 darwin/amd64`

go.mod: 
```
go 1.17

require (
	github.com/DATA-DOG/go-sqlmock v1.5.0
	github.com/volatiletech/sqlboiler/v4 v4.11.0
)
```

Test to reproduce issue: 
```
// was generated by sqlboiler
var dialect = drivers.Dialect{
	LQ: 0x22,
	RQ: 0x22,

	UseIndexPlaceholders:    true,
	UseLastInsertID:         false,
	UseSchema:               false,
	UseDefaultKeyword:       true,
	UseAutoColumns:          false,
	UseTopClause:            false,
	UseOutputClause:         false,
	UseCaseWhenExistsClause: false,
}

// NewQuery initializes a new Query using the passed in QueryMods
// was generated by sqlboiler
func NewQuery(mods ...qm.QueryMod) *queries.Query {
	q := &queries.Query{}
	queries.SetDialect(q, &dialect)
	qm.Apply(q, mods...)

	return q
}

type Apple struct {
	UUID string `boil:"uuid" json:"uuid" toml:"uuid" yaml:"uuid"`
}

type Banana struct {
	UUID      string `boil:"uuid" json:"uuid" toml:"uuid" yaml:"uuid"`
	AppleUUID string `boil:"apple_uuid" json:"apple_uuid" toml:"apple_uuid" yaml:"apple_uuid"`
}

type Coconut struct {
	Apple  `boil:"apple,bind"`
	Banana `boil:"b,bind"`
}

func Test(t *testing.T) {
	db, mock, _ := sqlmock.New()
	defer db.Close()

	mockRow := mock.NewRows([]string{"uuid", "uuid", "apple_uuid"}).AddRow(
		"apple",
		"banana",
		"apple",
	)

	mock.ExpectQuery(".*").WillReturnRows(mockRow)

	query := []qm.QueryMod{
		qm.Select("apple.*", "b.*"),
		qm.From("apple"),
		qm.InnerJoin("banana b on b.apple_uuid = apple.uuid"),
	}

	var data []Coconut
	err := NewQuery(query...).Bind(context.Background(), db, &data)
	assert.Nil(t, err)
	assert.Equal(t, 1, len(data))

	fmt.Printf("Bind Result: %+v\n", data)

	assert.Equal(t, "apple", data[0].Apple.UUID)
	assert.Equal(t, "banana", data[0].Banana.UUID)
	assert.Equal(t, "apple", data[0].Banana.AppleUUID)
}
```

This was encountered while doing some simple join agains a Postgres DB. The above tests sometimes produces the correct result and sometimes does not, this seems change at compile time. Updating `mockRow := mock.NewRows([]string{"uuid", "uuid", "apple_uuid"}).AddRow(` to `mockRow := mock.NewRows([]string{"apple.uuid", "b.uuid", "b.apple_uuid"}).AddRow(` fixes the inconsistency. Which could be done in the query by renaming each field, though this is cumbersome for large tables. 

Is this an expected result of `Bind` and if so could you consider adding clarify comments to the docs for joins?

Since the standard SQL driver is positional I assumed `Bind` would respect position as well. This was probably a bad assumption on my part.

**Comment by stephenafamo** [comment]
Perhaps the documentation could be clearer, but this is a side effect of how SQL works.

When we do `SELECT apple.*, b.*`, in the rows returned, the column names are not prefixed by anything, so it is impossible for SQLBoiler to know what struct they should be bounded to. The resulting columns would look like

| uuid | uuid | apple_uuid |
-------------------------

Perhaps some fancy "best-effort" can be done to auto bind matching names, but I feel that would lead to more inconsistencies and edge cases.

A solution, is to add a variable/function that returns all the prefixed columns as a string slice for each model, for example:

```go
type Banana struct {
	UUID      string `boil:"uuid" json:"uuid" toml:"uuid" yaml:"uuid"`
	AppleUUID string `boil:"apple_uuid" json:"apple_uuid" toml:"apple_uuid" yaml:"apple_uuid"`
}

// Not 100% sold on this name yet 😅 
func PrefixedBananaColumns(prefix string) []string {
	return []string{prefix+".uuid", prefix+".apple_uuid"}
}
```

That way you can then do something like:

```go
	query := []qm.QueryMod{
		qm.Select(models.PrefixedAppleColumns("apple")...),
		qm.Select(models.PrefixedBananaColumns("b")...),
		qm.From("apple"),
		qm.InnerJoin("banana b on b.apple_uuid = apple.uuid"),
	}
```

**Comment by reiman2222** [comment]
Thank you for the feed back. I think that adding a function to prefix the column names in my code as in your example is a sufficient solution. Though I do think it might be worth while to call out this the in documentation somewhere as this was a rather tricky thing to debug.

If this is a expected result of the `Bind` function this issue can be closed.
