### ISSUE TITLE
Feature: Define relationships in config

### ISSUE THREAD

**Issue by nhuysamen-godaddy** [volatiletech/sqlboiler#1163]
This is probably a non-starter, but it would be great (albeit probably error-prone), to be able to specify relationships in config rather than relying on foreign keys. This would allow you to use sqlboiler with platform like [PlanetScale](http://planetscale.com/) that does not support foreign keys.

**Comment by stephenafamo** [comment]
This sounds interesting. If you can create a PR for this feature, I'll be happy to review it.

**Comment by tanaka-takuto** [comment]
I was just about to use SQLBoiler with PlanetScale!
I had no choice but to try to use it without foreign key constraints (no relations).
This is a long awaited feature!

**Comment by Rosswell** [comment]
imo this would be a nice feature in dbs with foreign keys as well, as afaict the reverse relationship is auto-derived, and cannot be renamed through a toml config, because the foreign key only exists on one of the tables

**Comment by stephenafamo** [comment]
@Rosswell I believe it is possible to alias the reverse relationship using the `foreign` property.

Regardless, I agree that the ability to manually define relationships would be quite useful. If only to create some "convenient" relationships that you don't necessarily need to be enforced by the DB.

**Comment by chrisngyn** [comment]
@stephenafamo Could you review this PR above?

**Comment by adsteel** [comment]
Would love to see this as well. Not being able to add non-FK columns to a join table is a limitation this would help to remove.

**Comment by stephenafamo** [comment]
Implemented in #1282
