### ISSUE TITLE
undefined: queries.SetFromEmbeddedStruct in generated models

### ISSUE THREAD

**Issue by vmato** [volatiletech/sqlboiler#1168]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.12.0

### What is your database and version (eg. Postgresql 10)
PostgreSQL 14

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler psql -o internal/models/api --no-tests

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
References to SetFromEmbeddedStruct() are Load*() methods

**Comment by stephenafamo** [comment]
Update the SQLBoiler version in your project.

That function is only available in `v4.12.0`
