### ISSUE TITLE
[mysql] Expected `DemoTrueType`, got `DemotrueType` in generated struct for Enum

### ISSUE THREAD

**Issue by MJacred** [volatiletech/sqlboiler#1174]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

v4.11.0

### What is your database and version (eg. Postgresql 10)

mariadb 10.6.8

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

sqlboiler.toml
```toml
add-enum-types   = true
enum-null-prefix = true
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

```sql
CREATE TABLE IF NOT EXISTS demo (
	id INT NOT NULL,
	content VARCHAR(15) NOT NULL,
	type ENUM('cookies', 'donutes'),
	PRIMARY KEY(id)
);
```

### Further information. What did you do, what did you expect?

**the case of one letter is wrong**:

got error in the auto-gen demo.go file: struct is actually correct

```golang
type Demo struct {
	ID      int          `boil:"id" json:"id" toml:"id" yaml:"id"`
	Content string       `boil:"content" json:"content" toml:"content" yaml:"content"`
	Type    DemoTrueType `boil:"type" json:"type,omitempty" toml:"type" yaml:"type,omitempty"`

	R *demoR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L demoL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}
```

because in the boil_types.go file, the struct created for the enum has wrong case

```golang
type DemotrueType struct {
	Val   DemoType
	Valid bool
}
```

**Comment by stephenafamo** [comment]
Will take a look sometime. Really busy now so it will take some time.

I'll add some labels in case anyone wants to help

**Comment by MJacred** [comment]
Thanks for the fix and the clarification!
