### ISSUE TITLE
Error can't evaluate field IsView in type drivers.Table after updating to 4.12.0

### ISSUE THREAD

**Issue by Southclaws** [volatiletech/sqlboiler#1182]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

4.12.0

### What is your database and version (eg. Postgresql 10)

Postgres 13

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

```
sqlboiler psql --wipe
```

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)

```
Error: unable to generate output: failed to execute template: main/17_upsert.go.tpl: template: main/17_upsert.go.tpl:1:21: executing "main/17_upsert.go.tpl" at <.Table.IsView>: can't evaluate field IsView in type drivers.Table
```

---

This worked yesterday, but this morning I just upgraded to @latest and it failed, so I checked out a specific version, 4.12.0 and it still failed with the same issue.

**Comment by stephenafamo** [comment]
Can you ensure you are running the same updated version of both the main tool and the driver?

**Comment by stephenafamo** [comment]
Closing this now. Reopen if you are still having the issue.

**Comment by StateGovernment** [comment]
Have the same issue word to word with mysql. Any solutions to this? @Southclaws @stephenafamo 
Version : SQLBoiler v3.7.1

**Comment by stephenafamo** [comment]
Update SQLBoiler and the driver and try again.

**Comment by StateGovernment** [comment]
@Southclaws @stephenafamo Updating to SQLBoiler v4.13.0 fixed the issue, thank you for helping out!
