### ISSUE TITLE
Exists and Count queries issue SELECTs to the database, but don't fire Select hooks

### ISSUE THREAD

**Issue by parnic** [volatiletech/sqlboiler#1187]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

4.13.0

### What is your database and version (eg. Postgresql 10)

PostgreSQL 14

### Further information. What did you do, what did you expect?

The 03_finishers template does not trigger any Select hooks when running a Count or Exists query despite each one issuing a SELECT sql query to do so. It seems like they should trigger these hooks, or perhaps their own Count/Exists hooks, if that's preferable.

I'm trying to build some analytics into my web application to understand how many queries are being run per endpoint so I can identify areas that need improvement. I'm using hooks to capture this information, and finding a few different ways where what I'm trying to do isn't quite covered by sqlboiler.

**Comment by stephenafamo** [comment]
The thing is, the hooks run on the objects and count/exist do not retrieve any object so it isn't clear what the hook should be attached to.

We could just send `nil` as the object when running the hook, however...

1. That would be a breaking change
2. Doesn't feel *correct* to me

**Comment by parnic** [comment]
Ah, right, that makes sense. Same problem I ran into when building the code for my discussion post #1188. Free functions can solve it, but it sounds like I'm trying to use hooks for a different purpose than they were intended.
