### ISSUE TITLE
test failure: Unable to upsert User: models: unable to upsert users: pq: INSERT with ON CONFLICT clause cannot be used with table that has INSERT or UPDATE rules

### ISSUE THREAD

**Issue by jkmpariab** [volatiletech/sqlboiler#1193]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.13.0

### What is your database and version (eg. Postgresql 10)
Postgresql 14

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
begin;

create table if not exists users(
    id serial primary key,
    name text not null
);

create table if not exists audits(
    id serial primary key,
    name text not null
);

create or replace rule update_rule as on update to users
do also insert into audits (name) values (new.name);

commit;
```

### Further information. What did you do, what did you expect?
go test ./models
expected test passes but failed

**Comment by parnic** [comment]
It sounds like you're running into this: https://github.com/volatiletech/sqlboiler#why-are-the-auto-generated-tests-failing

**Comment by jkmpariab** [comment]
> It sounds like you're running into this: https://github.com/volatiletech/sqlboiler#why-are-the-auto-generated-tests-failing

Definitely this is a Postgresql Rule functionality issue as there's no constraint in the provided reproducing sample sql!

**Comment by stephenafamo** [comment]
I don't think there is anything to be done here, so I am closing this issue.

**Comment by jkmpariab** [comment]
> I don't think there is anything to be done here, so I am closing this issue.

I do't know what to say it is a sqlboiler issue
I think you better leave this thread open until someone could suggest a workaround or let people talk about the issue

**Comment by stephenafamo** [comment]
Alright 🤷🏾‍♂️

**Comment by jkmpariab** [comment]
> Alright 🤷🏾‍♂️

I mean atm i'm circumvent my problem using triggers instead but i'd be glad if i can go with rules as they looks more performant to me in this case.

So once again i tried to figure it out what is happening in test case that triggers this problem:
It seems its an postgresql issue as with error message complaining and that problem is not related to sqlboiler if i should be honest.

What sqlboiler can/should do?
Imo you should add configuration to remove some kind of tests that user is confident about.

Any more suggestion?
I don't know more.

So feel free to close the thread.
Good luck!

**Comment by stephenafamo** [comment]
The auto-generated tests are not very reliable and any PR to improve the quality of tests will be appreciated.

I'll close this in the meantime. Thank you.
