### ISSUE TITLE
Automatically add created_at / updated_at to whitelist

### ISSUE THREAD

**Issue by westito** [volatiletech/sqlboiler#120]
When I use whitelist in update / insert method, I have to add created_at and updated_at to the white list every time. There is an option to add itt automatically?

**Comment by aarondl** [comment]
Hey westito. Sorry about the delay in response, I've been traveling for business abroad.

One of the problems that we have is that doing this prevents us from allowing the user to completely customize the whitelist. This breaks the intuitive thing about what a whitelist is. In the case where I want it updated all the time yes, it makes sense. But without adding too much extra complexity how do I tell the function to only update the field called "name" but NOT update created/updated at for whatever reasons I have at this time?

Also join us on Slack if you want to discuss in more realtime :) https://sqlboiler.from-the.cloud/

**Comment by polderudo** [comment]
Wouldn't it be nice to have some configuration where one can specify to always update the updated_at field? Only thing to take care of then would be to check if created_at is in the whitelist, and if not add it. Realy bad if one forgets to set the field manualy. Normaly if the field is present on the models, i think everyone want's to have it autoupdated, but for the once who don't want that, one could use the configuration setting.

**Comment by polderudo** [comment]
Why should one update only 'name' if the db has a field 'updated_at'. The meaning of updated_at IS to update the field every time something changes ... If one realy realy wants to not update updated_at, he can use raw-sql ...

**Comment by aarondl** [comment]
Okay, so I see three solutions to this problem and I'll probably pick one

Please vote for your favorite below:

* Let people suffer the surprise when fields that they haven't selected are updated and fallback to raw to get rid of surprising behavior 💾 
* Opt-in to auto-generated field auto-updates with a bool on the affected methods (I think there's only 3 of these? insert/update/upsert) 💿 
* Add a configuration value that turns this functionality on/off 📀

**Comment by polderudo** [comment]
I'd vote for 1. 
Or 2, but not opt-in, but opt-out. Default would be that the update is done, and one can specify not to do the update.

**Comment by aarondl** [comment]
This use case is handled by using `boil.Greylist` in v3. Greylist adds columns to the list of columns to insert, without completely the inference that sqlboiler normally does. This means created_at/updated_at will not be punted as soon as we want to specify a single column. I believe this resolves this.
