### ISSUE TITLE
ORDER BY - non effective with $ argument using `queries.Raw().Bind()`

### ISSUE THREAD

**Issue by adatob** [volatiletech/sqlboiler#1204]
Sorting using "ORDER BY" takes no effect using raw query.

The following code binds pilots ordered by "ID" instead of "name":

```
	res := models.PilotSlice{}
	err = queries.Raw("SELECT * FROM pilots ORDER BY $1 ASC LIMIT $2","name", 2).Bind(context.Background(), db, &res)
```

Table schemas according to Readme example.

**Comment by stephenafamo** [comment]
This is a limitation with the DB dialect (I assume you're using postgres) and not SQLBoiler. It is not possible to use placeholders in `LIMIT` or `ORDER BY` clauses.

[Here is a some more information](https://www.postgresql.org/message-id/1421875206968-5834948.post@n5.nabble.com)

To confirm, you can attempt the same thing with `db.QueryContext(ctx, "SELECT...", 2)` and see that it will also not work.
