### ISSUE TITLE
Forward slashes in column names and enum values are not escaped

### ISSUE THREAD

**Issue by 154pinkchairs** [volatiletech/sqlboiler#1253]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
4.14.0

### What is your database and version
MySQL 5.7.12

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
```
sqlboiler mysql --add-global-variants --no-auto-timestamps --no-tests --output storage/ --pkgname storage --wipe
```
### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
```
Error: singleton template output: failed to format template

 266 
 267                                    
 268 
 269                                    // Enum values for MKTOrderStoreProductSeason
 270                                    const (
>>>>                                    MKTOrderStoreProductSeasonA/I string = "A/I"
 272                                            MKTOrderStoreProductSeasonP/E string = "P/E"
 273                                            )
 274 
 275                                    func AllMKTOrderStoreProductSeason() []string {
 276                                            return []string{ 

: 271:33: expected ';', found '/' (and 3 more errors)
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
This can be replicated by creating a table or a column with names (not row values) containing a forward slash. As stupid as this idea may sound, mysql allows setting such names and thus even if it may seem like an edge case, these names should be properly escaped, so that the resulting variables have names with these characters removed (n.b. this also causes the generation to fail).

To be more precise, in my case the problematic column has a type enum('A/I','P/E').

### Further information. What did you do, what did you expect?
The problem seems to be related to the fact that sqlboiler adds enum values to column names. Before then, when using 4.0.4, the issue seemed not to occur.

**Comment by stephenafamo** [comment]
Just to mention that in the meantime, you can manually set aliases for these columns until SQLBoiler handles it properly.

**Comment by MJacred** [comment]
we have a similar case, but with German umlauts:
```go
const (
  StateB01   State = "B01"
  StateB01   State = "B01Ü"
)
```

This is somewhat different to the README note/warning, because the constants are generated. But sqlboiler generates duplicate constants

**Comment by founderio** [comment]
FWIW, Unicode letters, which includes umlauts, are perfectly valid identifiers in Golang, so the escaping could just accept valid values.  
Slashes are NOT letters though, obviously.

Example: https://go.dev/play/p/E0Vm7Xsnhar

Docs: https://go.dev/ref/spec#identifier Specifies:

> An identifier is a sequence of one or more letters and digits. The first character in an identifier must be a letter.

> `identifier = letter|unicode_digit .`

> `letter        = unicode_letter | "_" .`

> In [The Unicode Standard 8.0](https://www.unicode.org/versions/Unicode8.0.0/), Section 4.5 "General Category" defines a set of character categories. Go treats all characters in any of the Letter categories Lu, Ll, Lt, Lm, or Lo as Unicode letters, and those in the Number category Nd as Unicode digits.

**Comment by 154pinkchairs** [comment]
I'll try a solution that touches upon
https://github.com/volatiletech/sqlboiler/blob/master/drivers/column.go
where I'd change
```go
type Column struct {
	Name          string `json:"name" toml:"name"`
	CleanName        string `json:"-"`
	//...
func ColumnNames // ...
c.CleanName = strmangle.TitleCase(strings.ReplaceAll(c.Name, "/", "_"))
```

if it works I'll open a PR

**Comment by starsep** [comment]
Any news? 
I am still able to reproduce this in SQLBoiler v4.16.2 but ticket is closed as completed

**Comment by MJacred** [comment]
@starsep: The linked PR did not fix this (was not its purpose). This issues should be open.

I reckon the solution is to modify `func ParseEnumName` in https://github.com/volatiletech/strmangle, where you do sth. similar like `ReplaceReservedWords`. But the slash must go completely, because it invalidates the identifier.
