### ISSUE TITLE
Cannot use *Slice structs in .L.Load*() funcs

### ISSUE THREAD

**Issue by MJacred** [volatiletech/sqlboiler#1254]
### What version of SQLBoiler are you using?

> github.com/volatiletech/sqlboiler/v4 v4.14.1

> golang: 1.20.2

### What is your database and version

> MariaDB 10.6.8

### If this happened at runtime what code produced the issue?

Two tables: `Position` & `PositionText`: The latter is a table with translations for the former.  
The goal is to load for all positions the text for all languages.

```golang
list, _ := models.Positions().All(ctx, tx) // returns models.PositionSlice
models.Position{}.L.LoadPositionTexts(ctx, tx, false, &list, nil)
```

this causes the error
```
failed to set []*models.Position from embedded struct *models.PositionSlice
```

at this part in the auto-generated code
```golang
func (PositionL) LoadPositionTexts(…) {
	var slice []*Position
	var object *Position

	if singular {
		…
	} else {
		s, ok := maybePosition.(*[]*Position) // THIS fails
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePosition) // therefore the code lands here, and continues on
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePosition))
			}
		}
	}
}

func SetFromEmbeddedStruct(to interface{}, from interface{}) bool {
	toPtrVal := reflect.ValueOf(to)
	fromPtrVal := reflect.ValueOf(from)
	if toPtrVal.Kind() != reflect.Ptr || fromPtrVal.Kind() != reflect.Ptr {
		return false
	}
	toStructTyp, ok := singularStructType(to)
	if !ok {
		return false
	}
	fromStructTyp, ok := singularStructType(from)
	if !ok {
		return false
	}
	fieldNum, ok := embeddedStructFieldNum(fromStructTyp, toStructTyp) // << error triggered in here
	if !ok {
		return false
	}

}
```

`toStructTyp` and `fromStructTyp` are identical:

![4](https://user-images.githubusercontent.com/6639237/224392281-df1d0b1a-8dc4-4b86-ae50-a7638bba640c.png)

and then `embeddedStructFieldNum()` looks at the fields of `fromStructTyp` and compares it to `toStructTyp`, which of course fails…

### Proposal

the fastest (performance-wise) sqlboiler-side solution I can think of: type assertion for *Slice structs
```golang
s, ok := maybePosition.(*[]*Position)
if ok {
	slice = *s
} else {
	s2, ok := maybePosition.(*PositionSlice)
	if ok {
		slice = *s2
	} else {
		ok = queries.SetFromEmbeddedStruct(&slice, maybePosition)
		if !ok {
			return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePosition))
		}
	}
}
```

### Workaround

```golang
list, _ := models.Positions().All(ctx, tx) // returns models.PositionSlice
workaround := []*models.Position(list)
models.Position{}.L.LoadPositionTexts(ctx, tx, false, &workaround, nil)
```

**Comment by stephenafamo** [comment]
> Can you explain `so that the method can be found when binding loaded relationships`? Is this a technical requirement for code inside sqlboiler? (reflection?)

Yes. If you dig into the implementation of loading relationships, SQLBoiler tries to find a method on the struct with the required name. Since unexported methods cannot be called (without some hacks with `unsafe`), the method has to be exported.

> The function Load* has its use if you have already loaded data into memory for a different query and want to re-use that data without re-running the same query. Of course, this only makes sense if you don't always need the relationship entities anyways, but only in some code paths.

I can see how this is useful. It can of course be done for a single model like this:

```go
p, _ := models.Postition().One(ctx, db) // get the model
p.R.Texts, _ := p.Texts().All(ctx, db) // get the position's text
```

There is no easy way to do this for a slice. Perhaps we can consider also generating methods for it.

> Instead of `type PositionSlice []*Position` using `type PositionSlice = []*Position` allows all the type assertions you can think of, which allows `[]*Position` and `PositionSlice` to be passed in without any issue.

This doesn't work for SQLBoiler because extra methods are generated for `PostitionSlice` and methods cannot be attached to type aliases.

**Comment by stephenafamo** [comment]
I'm going to label this as a "Won't Fix" because it has to do with unintended usage.

Perhaps we can use a separate issue to discuss adding a loading method to the slice types.
