### ISSUE TITLE
type.JSON errors, but same data (column) switching to null.JSON works on json.Marshal of table struct

### ISSUE THREAD

**Issue by JC1738** [volatiletech/sqlboiler#1255]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.14.1

### What is your database and version (eg. Postgresql 10)
MYSQL 8

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

`	b, err := json.Marshal(page)
		if err != nil {
			l().Log.WithError(err).Error("Cannot generate JSON")
			is.NoErr(err)
		}
`

### Further information. What did you do, what did you expect?

The table being marshalled has columns that have JSON in them.  I narrowed down the issue that even if the column has data in it if the data type is **type.JSON** I get an error like this: 

**err: json: error calling MarshalJSON for type types.JSON: invalid character ',' after top-level value**

However, if I just change the data type in the generated code to **null.JSON** (which, it's not nullable, why it probably didn't use that type) I get the json marshaled correctly.

A couple of questions.  

1) Can I force all type.JSON to be null.JSON without changing my DB schema
2) Should I just in the meantime hack the generated code to get around thee issue?

**Comment by JC1738** [comment]
`[[types]]
[types.match]
  type = "types.JSON"
  nullable = false

[types.replace]
  type = "null.JSON"
`

Above gets around having to manually update the generated file.  Still not sure if this is the proper solution.

**Comment by stephenafamo** [comment]
I don't completely understand the issue.

Is the error coming from generated code? Or from trying to manually marshal JSON into the struct?

**Comment by JC1738** [comment]
Generated code makes the struct type of type.JSON.  The issue isn't marshaling into struct, it's marshaling into JSON.  Struct to JSON fails if the column within the struct is of type.JSON.   It succeeds if the column within the struct is null.JSON.  Despite fact that the column is not null and is exactly same data inside.

@stephenafamo

**Comment by stephenafamo** [comment]
Can you share some sample code please. Sorry I don't fully understand what you're describing.

Are you trying to marshal the full model into `JSON`?

**Comment by JC1738** [comment]
@stephenafamo 

`
/*     DB SCHEMA
	Table:  	Foo
	id			int
	foo_field 	JSON
	created_at	DATETIME
*/

//Run 
sqlboiler mysql

//Generated Code has
type Foo struct {
ID                          int        	`boil:"id" json:"id" toml:"id" yaml:"id"`
foo_field              types.JSON  `boil:"foo_field" json:"foo_field" toml:"foo_field" yaml:"foo_field"`
created_at          time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
}


//Code do something like
ctx := context.Background()
foo, err := dbmodels.Foo(
	Limit(5),
	OrderBy("id desc"),
).AllG(ctx)

b, err := json.Marshal(foo)
if err != nil {
	l().Log.WithError(err).Error("Cannot generate JSON")
}

//You get an error
"json: error calling MarshalJSON for type types.JSON: invalid character ',' after top-level value"

//Manually change Foo struct
type Foo struct {
	ID                 int        	`boil:"id" json:"id" toml:"id" yaml:"id"`
	foo_field      null.JSON   `boil:"foo_field" json:"foo_field" toml:"foo_field" yaml:"foo_field"`
	created_at  time.Time    `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	}

//Run exact same code
ctx := context.Background()
foo, err := dbmodels.Foo(
	Limit(5),
	OrderBy("id desc"),
).AllG(ctx)

b, err := json.Marshal(foo)
if err != nil {
	l().Log.WithError(err).Error("Cannot generate JSON")
}

//err == nil
//Nothing changed except me changing the dbmodels.Foo foo_field data type to null.JSON
`

**Comment by JC1738** [comment]
I understand, but that is not the case, the rows/fields all have valid json.  I did check for errors when it was type.JSON.  This isn't a blocker for me since forcing the null.JSON does solve it, but felt should report in case others ran across it.

**Comment by Serjlee** [comment]
I think I also encountered the same issue, I'll try to find the time and build an example schema for it. 

Like @JC1738, all the result rows had the JSONB column populated, but `types.JSON` failed in a weird way: all the rows were there, but the scanned contents had either an extra trailing `}` or missing one.

I fiddled a bit with it with interesting results:

The issue seems to stem from this way of copying the data during the Scan:
https://github.com/volatiletech/sqlboiler/blob/e6989a7f42bc2f8e83f149bef91be49be80fb10d/types/json.go#L67


Doing it the way `null.JSON` does, fixes it:
```go
	json := make([]byte, len(source))
	copy(json, source)
	*j = json
```

.. No idea why though :)

**Comment by yourtallness** [comment]
We have confirmed that switching a column from `types.JSON` to `null.JSON` also solves de-serialization errors for us.

However, semantically said column isn't nullable for us, though we might temporarily use this as a workaround.

Is there a fix forthcoming?

**Comment by yourtallness** [comment]
Note: At the end, we were able to solve our issue following the info [here](https://github.com/volatiletech/sqlboiler/issues/491#issuecomment-470389104).

**Comment by agis** [comment]
I think I'm bumping onto a similar situation. Given the following types:

```go
// sqlboiler-generated model
type Car struct {
  Metadata types.JSON `boil:"metadata" json:"metadata" toml:"metadata" yaml:"metadata"`
}

// I then embed that model into my own struct type
type MyCar struct {
  *sqbmodel.Car
}
```

Now try to marshal:

```go
car := &MyCar{&sqbmodel.Car{}}

// this doesn't work
result, err := json.Marshal(m)
fmt.Printf("error: %v\n", err)
fmt.Printf("result: %s\n", result)
// prints:
//     error: json: error calling MarshalJSON for type types.JSON: unexpected end of JSON input
//     result:

// this works
m.Metadata = []byte(`{"a": "b"}`)
result, err = json.Marshal(m)
fmt.Printf("error: %v\n", err)
fmt.Printf("result: %s\n", result)
// prints:
//     error: <nil>
//    {""metadata":{"a":"b"}}
```

I think the issue is that `types.JSON.MarshalJSON` doesn't properly handle the case where the byte slice is nil here: https://github.com/volatiletech/sqlboiler/blob/59e63d54028be0a3b89318577a80fdebd7e351cb/types/json.go#L49.

Compare this to the Go json.Marshal implementation, where it seems to handle those cases: https://cs.opensource.google/go/go/+/master:src/encoding/json/encode.go;l=805-807;bpv=0;bpt=1.

If I change `types.JSON.MarshalJSON` like so:

```go
func (j JSON) MarshalJSON() ([]byte, error) {
    if j == nil {
        return []byte("null"), nil
    }
    return j, nil
}
```

...then the aforementioned sample code prints:

```
error: <nil>
{""metadata":null}
```

If that all makes sense, I can prepare a PR to make this change.

**Comment by agis** [comment]
@stephenafamo do you think my above comment is indeed a bug in sqlboiler's types.JSON implementation?

**Comment by stephenafamo** [comment]
Maybe. Don't have the time to investigate further at the moment.

You can maybe try implementing the nil handling and see if it fixes the issues others faced
