### ISSUE TITLE
Using `auto-columns.deleted` config and `qm.WithDeleted()`

### ISSUE THREAD

**Issue by JMavs** [volatiletech/sqlboiler#1256]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.13.0

### What is your database and version (eg. Postgresql 10)
cockroach v22.2.6

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
```
sqlboiler --wipe --no-hooks --no-rows-affected --no-tests --add-soft-deletes -p crdb -o crdb crdb
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

```sql
CREATE TABLE IF NOT EXISTS kitties (
    id
        CHAR(26) NOT NULL,
    delete_time
        TIMESTAMPZ NULL
);
```

**sqlboiler.yaml**
```
crdb:
  user: user
  pass: password
  host: localhost
  port: 26257
  dbname: 'app'
  sslmode: disable
auto-columns:
  deleted: 'delete_time'
```

### Further information. What did you do, what did you expect?
Hello,
the problem that I have is that when I try to generate everything and I use it, the query modifier `qm.WithDeleted()` doesn't remove the part that is `AND ("kitties"."delete_time" is null)` in the SQL query. I checked it with the `boil.DebugMode = true`.

If I use the default `auto-columns.deleted` setting and modify my schema from `delete_time` to `deleted_at`, it works as expected.

I reivewed the code inside the repo and I saw that is because the `deleted_at` is hardcoded in the code instead of read it from the config (this commit is actually the HEAD of master).
https://github.com/volatiletech/sqlboiler/blob/66cb4680047d7801156a080ba69a3f14ef5986fc/queries/query.go#L411 

If the bug exists, any workaround in the meantime?

Thanks

**Comment by stephenafamo** [comment]
No workaround for this exists at the moment. I'll try to fix this soon.

**Comment by JMavs** [comment]
Ok, thank you @stephenafamo!

**Comment by lopezator** [comment]
I uploaded a functional early implementation here for your review @stephenafamo 

Thanks for the quick feedback!

https://github.com/volatiletech/sqlboiler/pull/1258

**Comment by JMavs** [comment]
Thanks both! @stephenafamo @lopezator 🙌 
Any idea of when would be deployed the `v4.14.2`?

Thaaaank you!!

![asdf](https://media.tenor.com/aynIt3pr3R4AAAAC/tilt-hat-gentleman.gif)

**Comment by stephenafamo** [comment]
Just tagged `v4.14.2` @JMavs
