### ISSUE TITLE
ERD tooling 

### ISSUE THREAD

**Issue by gedw99** [volatiletech/sqlboiler#1268]
Great project . Covers the corner cases ..

gor large projects a ERD like tool is useful , so you can inspect the db and it’s relationships. 

Are there any in golang ?

i suspect the atlas team might have one..

looking for recommendations

**Comment by stephenafamo** [comment]
SQLBoiler works with an existing DB and is not used to define the schema. Creating ERDs is out of the scope of what SQLBoiler does.

Any ERD tool that works with your DB will work just the same. For example, if you use Atlas for migrations and it can generate an ERD, you can it and it will work just the same.
