### ISSUE TITLE
JSON marshal nested objects error: json: unsupported value: encountered a cycle via SchemaSlice

### ISSUE THREAD

**Issue by mahmoud-eskandari** [volatiletech/sqlboiler#1269]
Hi there,
When we use `Load` to get relations of an object, sqlboiler makes cyclic object of it.

```
	artworks, err := models.Artworks(
		Limit(3),
		Load(models.ArtworkRels.Category),
	).All(context.TODO(), boil.GetContextDB())

	if err != nil {
		log.Print(err)
		ctx.JSON(err)
		return
	}

	_, err = json.Marshal(artworks)

	if err != nil {
		log.Print("JSON Error")
		log.Print(err)
		return
	}

```
I got this error because of cyclic limit in Golang json marshaler for cyclic pointer.

```
json: unsupported value: encountered a cycle via models.ArtworkSlice
```

Is there any standard solution? 
or
Will I have to make a new slice and append records and sub records into it?

**Comment by stephenafamo** [comment]
The SQLBoiler models are not typically meant to be used this way. In addition, this is also why by default, the `.R` field is ignored for json struct tags.

However, a way to solve your issue would be to generate the models using the `--no-back-referencing` flag.
