### ISSUE TITLE
psql: Upsert ignores conflict_target query parameter

### ISSUE THREAD

**Issue by agis** [volatiletech/sqlboiler#1289]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

4.11.0

### What is your database and version (eg. Postgresql 10)

Postgres 13

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
N/A

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
N/A

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
N/A

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```SQL
   Column   |            Type             | Collation | Nullable | Default 
------------+-----------------------------+-----------+----------+---------
 id         | character varying           | C         | not null | 
 foo        | character varying(255)      |           | not null | 
 brand      | boolean                     |           | not null | 
 created_at | timestamp without time zone |           | not null | now()
 updated_at | timestamp without time zone |           | not null | now()
Indexes:
    "cars_pkey" PRIMARY KEY, btree (id)
    "idx_foo" UNIQUE, btree (foo)

```

### Further information. What did you do, what did you expect?

The following call:

```go
record.Upsert(ctx, db, false, []string{"foo"}, boil.None(), boil.Infer())
```

results in the following unexpected query:
```SQL
INSERT INTO "cars" ("id", "foo", "brand", "created_at", "updated_at") VALUES ($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING
```

whereas I would expect it to result to the following:

```SQL
INSERT INTO "cars" ("id", "foo", "brand", "created_at", "updated_at") VALUES ($1,$2,$3,$4,$5) ON CONFLICT ("foo") DO NOTHING
```

I've a draft PR ready if this is indeed a bug and not something I'm misunderstanding.

**Comment by stephenafamo** [comment]
This looks like a bug, the PR would be much appreciated 🙏🏾

**Comment by agis** [comment]
@stephenafamo can we please backport this to v4, since it's a trivial bugfix?

**Comment by agis** [comment]
Thanks a lot, that would be greatly appreciated!

**Comment by agis** [comment]
This should be re-opened due to #1312.
