### ISSUE TITLE
[Feature Request] Ignore Composite Foreign Key Constraint

### ISSUE THREAD

**Issue by paulo-raca** [volatiletech/sqlboiler#1298]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler 4.14.2

### What is your database and version (eg. Postgresql 10)
PostgreSQL 14.4

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`sqlboiler psql -p dbmodels`

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

```sql
DROP TABLE IF EXISTS node;

CREATE TABLE node (
    id int PRIMARY KEY,
    parent_id int,
    root_id int NOT NULL
);

-- Sanity check: On root nodes only, parent_id=NULL and root_id=id
ALTER TABLE node
ADD CONSTRAINT check_root_is_self_if_no_parent CHECK ((root_id = id) = (parent_id IS NULL));

-- Sanity check: node.root_id is the same as nodex.parent.root_id
ALTER TABLE node
ADD CONSTRAINT unique_id_rootid UNIQUE (id, root_id);

ALTER TABLE node
ADD CONSTRAINT fk_id_rootid FOREIGN KEY (parent_id, root_id) REFERENCES node(id, root_id);
```

### Further information. What did you do, what did you expect?

For context, my database contains tree structures. Within each node I have links to the parent and root nodes (Yes, this is redundant, but having a direct link to the root makes some queries much simpler)

To ensure my DB remains consistency, I've added the `fk_id_rootid` composite constraint. which ensures all nodes in the tree have the same value of `root_id`.

This works as expected, here is a tiny test suite:
```sql
-- Success Test: Creates 1 -> 2 -> 3
INSERT INTO node(id, parent_id, root_id) values (1, NULL, 1);
INSERT INTO node(id, parent_id, root_id) values (2, 1, 1);
INSERT INTO node(id, parent_id, root_id) values (3, 2, 1);

-- Failure: violates check constraint "check_root_is_self_if_no_parent"
-- When adding a root node (parent_id=NULL), we must have (root_id = id)
INSERT INTO node(id, parent_id, root_id) values (4, NULL, 1);
-- Failure: violates foreign key constraint "fk_id_rootid"
-- When adding a child node, the root_id must match those of the parent
INSERT INTO node(id, parent_id, root_id) values (4, 3, 2);
```

However Boiler doesn't like composite relationships at all and generates broken code, where some snippets seems are repeated 4x. E.g., here is one of them:

```
// NodeRels is where relationship names are stored.
var NodeRels = struct {
	Parent      string
	Parent      string
	Parent      string
	Parent      string
	ParentNodes string
	ParentNodes string
	ParentNodes string
	ParentNodes string
}{
	Parent:      "Parent",
	Parent:      "Parent",
	Parent:      "Parent",
	Parent:      "Parent",
	ParentNodes: "ParentNodes",
	ParentNodes: "ParentNodes",
	ParentNodes: "ParentNodes",
	ParentNodes: "ParentNodes",
}
```

Here is the [full generated code](https://gist.github.com/paulo-raca/ac862ca5e083ef3f50aefc0f243f488c#file-node-go) and [sqlboiler CLI output](https://gist.github.com/paulo-raca/ac862ca5e083ef3f50aefc0f243f488c#file-boiler-output-json)

TBH I don't need this Foreign Key constraint to be exposed by Boiler at all -- Maybe there is there a way to disable it?

Thank you for looking into it!

**Comment by stephenafamo** [comment]
As it says in the README.md, [multi-column foreign keys are not supported](https://github.com/volatiletech/sqlboiler/blob/v4.15.0/README.md?plain=1#L139).

If you can send in a PR to ignore multi-column foreign keys, I will be happy to review it.
