### ISSUE TITLE
Enum collision problem

### ISSUE THREAD

**Issue by dtrinh100** [volatiletech/sqlboiler#1302]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.15.0

### What is your database and version (eg. Postgresql 10)
postgres:13.2

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler psql  

### Further information. What did you do, what did you expect?
In my toml file, I have `add-enum-types = false`, so I was not expecting it to generate enum types, which causes a collision with gqlgen generated enum types, but I am seeing it being generated in the boil types file. Is there a way to prevent this?

**Comment by stephenafamo** [comment]
Can you share a snippet of the generated types?
