### ISSUE TITLE
Exposing more table constants/metadata to facilitate metaprogramming

### ISSUE THREAD

**Issue by simon-connektica** [volatiletech/sqlboiler#1303]
Hey, I'm working on a pagination system built on top of sqlboiler and I'm trying to make it reusable and "automagic".

It would be helpful if sqlboiler exposed table metadata so that other packages can build safe APIs on top of this metadata. For instance, my paging system needs to know the primary keys of my tables to produce a deterministic ordering. 

I can use the `<Table>Columns` struct to get the list of columns in the table using reflection, but the `<table>PrimaryKeyColumns` field is private to the package. In my partifular case, just exposing `<table>PrimaryKeyColumns` would be fine, but I think it could be useful to expose more metadata as a runtime variable.

In a file such as `boil_metadata.go` there could be an object named `TableMetadata` with a list of tables, each table having a list of columns and each column having name, type, primary key, etc. information.

**Comment by stephenafamo** [comment]
You can point to a custom template when generating which could then be used to include this `TableMetadata` information to support your metaprogramming. More info here <https://github.com/volatiletech/sqlboiler#templates>
