### ISSUE TITLE
Request to revert PR #1290 (BUG)

### ISSUE THREAD

**Issue by atzedus** [volatiletech/sqlboiler#1312]
Hello! This is MAJOR changes. This change breaks unit-tests and affects many lines of codes in our project.

"INSERT INTO ... ON CONFLICT DO NOTHING" - This is VALID PostgreSQL statement means that on ANY conflict DO NOTHING.

This change breakes behavior of code like this:

```SQL
CREATE TABLE foo (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  f1_id bigint,
  f2_id bigint
)

CREATE UNIQUE INDEX ON foo(f1_id, f2_id);
```

```go
foo.Upsert(ctx, db, false, nil, boil.None(), boil.Infer())
foo.Upsert(ctx, db, false, nil, boil.None(), boil.Infer())
```

BEFORE this change:
Expected behavior: ON CONFLICT DO NOTHING. First line and second line without error.

AFTER this change:
ON CONFLICT ("id") DO NOTHING. First line inserts new line, but second line there is error: unique_violation on f1_id+f2_id.

In addition: if table does not have primary key column (that strange, not good, but may be) then there is SQL error: INSERT INTO ... ON CONFLICT () DO NOTHING

Possible solution:
`foo.Upsert(ctx, db, false, nil, boil.None(), boil.Infer())` - revert to prevoius behavior
`foo.Upsert(ctx, db, false, []string{}, boil.None(), boil.Infer())` - current behavior

**Comment by agis** [comment]
In your example, can you please provide the code that initializes `foo`?

**Comment by atzedus** [comment]
```go
Foo{
  F1ID: null.Int64From(10),
  F2ID: null.Int64From(20),
}
```

The problem is here:
https://github.com/volatiletech/sqlboiler/blob/59e63d54028be0a3b89318577a80fdebd7e351cb/drivers/sqlboiler-psql/driver/override/main/17_upsert.go.tpl#L105-L110

When len(conflictColumns) == 0 then conflict slice has primaryKeyColumns, in my example: []string{"id"}

And then it provided to call: buildUpsertQueryPostgres here:
https://github.com/volatiletech/sqlboiler/blob/59e63d54028be0a3b89318577a80fdebd7e351cb/drivers/sqlboiler-psql/driver/override/main/singleton/psql_upsert.go.tpl#L24-L29

updateOnConflict == false
conflict == []string{"id"}

Result: ON CONFLICT ("id") DO NOTHING, but call to foo.Upsert was with nil slice to conflictColumns.

**Comment by atzedus** [comment]
More valid example to reproduce is:

```go
foo1 := Foo{
  F1ID: null.Int64From(10),
  F2ID: null.Int64From(20),
}

foo1.Upsert(ctx, db, false, nil, boil.None(), boil.Infer())

foo2 := Foo{
  F1ID: null.Int64From(10),
  F2ID: null.Int64From(20),
}

foo2.Upsert(ctx, db, false, nil, boil.None(), boil.Infer())
```
