### ISSUE TITLE
AndIn generates a list of pairs instead of a flat list.

### ISSUE THREAD

**Issue by janekolszak** [volatiletech/sqlboiler#1331]
`AndIn` generates peculiar list of pairs instead of a flat list.

### What version of SQLBoiler are you using (`sqlboiler --version`)?
4.15

### What is your database and version (eg. Postgresql 10)
Postgres 15

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
AndIn

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
`IN (($22,$23),($24,$25),($26,$27)))`

### Further information. What did you do, what did you expect?

Expected something like `IN ($22, $23, $24)

**Comment by stephenafamo** [comment]
Please provide more comprehensive code samples so it is easier to understand in which cases this happens.
