### ISSUE TITLE
Non deterministic column binding when same column name across two tables (inner join)

### ISSUE THREAD

**Issue by ckcr4lyf** [volatiletech/sqlboiler#1332]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler 4.15.0

### What is your database and version (eg. Postgresql 10)
PostgreSQL 13

### DB Schema (Simplified)

```
CREATE TABLE mandate (
  id TEXT NOT NULL PRIMARY KEY,
  sender_id TEXT NOT NULL,
  customer_id TEXT NOT NULL
);

CREATE TABLE users (
  id TEXT NOT NULL PRIMARY KEY,
  customer_id TEXT NOT NULL,
  external_id TEXT NOT NULL
);

INSERT INTO mandate VALUES ('MANDATE_ID', 'PAYMENT_USER_ID', 'CUSTOMER_ABC');
INSERT INTO users VALUES ('PAYMENT_USER_ID', 'CUSTOMER_XYZ', 'EXTERNAL_ID');
```

`mandate.sender_id` is meant to be joined with `users.id`.

https://www.db-fiddle.com/f/wY9f45tSgcZQ92ZhDLBdHG/0

### Problem

I am trying to retrieve both a `mandate` and a `user` in a single query, joining on `users.id = mandate.sender_id`. I am using a custom struct like this:

```
type MandateAndUser struct {
	M models.Mandate `boil",bind"`
	U models.User `boil",bind"`
}
```

However, when I do that, it seems that `M.ID` and `U.ID` can non deterministically be swapped (same for the `customer_id` column - not they can be different even on the joined data). 

E.g. sometimes `M.ID` might actually be `PAYMENT_USER_ID`, and vice-versa.

### Expectation

I would imagine that `M.ID` should always be the `id ` from the `mandate` table.

Is there any way to fix this? I am doing a `SELECT *` because I want all columns from both tables.

**Comment by stephenafamo** [comment]
Because of the nature of SQLBoiler's design, this is not possible. You should prefix each of your columns with the table name and bing appropriately: e.g.

```go
type MandateAndUser struct {
	M models.Mandate `boil"mandate,bind"`
	U models.User `boil"user,bind"`
}
```

```sql
SELECT mandate.id as "mandate.id", user.id as "user.id" ...
```

I understand that writing the query this way is inconvenient, but it is currently the only way to make this work deterministically with the current design.

If you can send in a PR to make your expectation work I will be very happy to review.
