### ISSUE TITLE
Configuring aliases for relationships for sqlite is not working

### ISSUE THREAD

**Issue by leonlaser** [volatiletech/sqlboiler#1333]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.15.0

### What is your database and version (eg. Postgresql 10)
sqlite3

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler sqlite3

### What is the output of the command above with the `-d` flag added to it?
I included only the relevant part for the aliases, but I can also post the whole thing, if necessary.

```json
"aliases": {
  "tables": {
    "table_main": {
      ...
    },
    "table_relation": {
      ...
      "relationships": {
        "FK_0": {
          "local": "TableRelations",
          "foreign": "TableMain"
        },
        "fk_0": {
          "local": "AliasLocal",
          "foreign": "AliasRemote"
        }
      }
    }
  }
},
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

```sql
CREATE TABLE table_main (
    id TEXT PRIMARY KEY
);

CREATE TABLE table_relation (
    id TEXT PRIMARY KEY,
    table_main_id TEXT REFERENCES table_main(id)
);
```

### Further information. What did you do, what did you expect?
I am configuring aliases for a relationship:
```toml
[sqlite3]
dbname = "foreignkeys.sqlite3"

[aliases.tables.table_relation.relationships.FK_0]
local = "AliasLocal"
foreign = "AliasRemote"
````

I expected my configuration to work, but neither `local` nor `foreign` are changed in the generated sources.

The sqlite3 driver is creating names for each foreign key with an uppercase prefix `FK_`, but viper has no support for case sensitive keys, therefore my aliases are is not applied.

**Comment by leonlaser** [comment]
I just read about the alternate syntax in the docs and using `name` to overcome this problem, but maybe it would still be nice to align the case of the foreign key prefix to vipers current behavior?

**Comment by stephenafamo** [comment]
Sorry about this, I have also been bitten by Viper's lack of case sensitivity.

> but maybe it would still be nice to align the case of the foreign key prefix to vipers current behavior

I don't understand exactly what you mean. 

As far as I know there is no way to change viper's behaviour, the user can either use the alternative syntax, or we have to entirely replace Viper is SQLBoiler.

**Comment by leonlaser** [comment]
@stephenafamo I mean changing the generated names of foreign keys to lowercase in this line:
https://github.com/volatiletech/sqlboiler/blob/71f11953fe83273d17a7ff0436e79b1341f0286d/drivers/sqlboiler-sqlite3/driver/sqlite3.go#L486

**Comment by stephenafamo** [comment]
Okay, that makes sense. Kindly send in a PR and I'll be happy to merge

**Comment by stephenafamo** [comment]
Although.... I'm not sure if this should be considered a breaking change since it may break existing configuration.

**Comment by leonlaser** [comment]
Yes, I agree. Viper has an open [PR to enable case sensitivity by configuration](https://github.com/spf13/viper/pull/1673). It might be better to wait for viper to offer a solution.
