### ISSUE TITLE
Error: can't evaluate field IsView in type drivers.Table

### ISSUE THREAD

**Issue by Manojnaik1** [volatiletech/sqlboiler#1339]
**Environment:**
- SQLBoiler Version: v3.7.1

**Issue Description:**
I'm encountering an issue while running SQLBoiler with PostgreSQL. The error message is:

**$ sqlboiler psql 
Error: singleton template output: failed to execute template: test/singleton/psql_suites_test.go.tpl: template: test/singleton/psql_suites_test.go.tpl:3:37: executing "test/singleton/psql_suites_test.go.tpl" at <$table.IsView>: can't evaluate field IsView in type drivers.Table**

sqlboiler.toml file
output = "models/sqlboiler"
pkgName = "sqlboiler"
wipe = false
no-tests = true
add-enum-types = true

[psql]
    dbname = "test"
    host = "localhost"
    port = 5432
    user = "api"
    pass = "password"
    sslmode = "disable"

**Comment by stephenafamo** [comment]
> **Environment:**
> 
> * SQLBoiler Version: v3.7.1

Kindly update to the latest version (v4).  
Let me know if the issue persists
