### ISSUE TITLE
`json_extract` not working with `Bind`

### ISSUE THREAD

**Issue by chamorin** [volatiletech/sqlboiler#1351]
I'm using `sqlboiler` version `v4.15.0` with `MariaDB` version `10.5.8`

I'm running this Go code:
```go
conn := u.dbPool.MustGetConnection()

tags := make([]*dto.Tag, 0)

dao.NewQuery(
	qm.Select("JSON_EXTRACT(users.comment, '$.tags') AS tags"),
	qm.From("users"),
).BindP(ctx, conn, &tags)
```
Here are my types for `Tag` and `Comment`:
```go
type Comment struct {
	Tags []*Tag `json:"tags" boil:"tags"`
}

type Tag struct {
	Name string `json:"name" boil:"name"`
}
```
I'm running with the debug flag and here's the executed query shown in the logs:
```sql
SELECT JSON_EXTRACT(users.comment, '$.tags') AS tags FROM `users`;
[]
```
As you can see, the go code returns nothing here (empty array).

However, when I run this exact query directly in my database it returns this (which is what I would expect):
```json
[ { "name": "My Tag" } ]
```

And here's the content of my `users` table, there's only one row and here's the value for the `comment` column:
```json
{ "tags": [ { "name": "My Tag" } ] }
```

I would like for my Go code query to return the same result as the query ran directly in the database and bind to the `&tags` variable. However nothing happens and there's no error. Was wondering if it was an `sqlboiler` issue or an issue with my types?

Thanks

**Comment by stephenafamo** [comment]
I believe an error should have been returned from `Bind` telling you that it could not scan the results of the query into your slice.

The thing is, when scanning from the database, there is no way to automatically know that you intend to decode JSON.

What needs to be done in the case is to create a custom type that implements [`database/sql.Scanner`](https://pkg.go.dev/database/sql#Scanner) and in the scan method, ask it to decode the JSON you expect.

I outlined how to create such a type and even replace a generated type with this in [this answer](https://github.com/volatiletech/sqlboiler/discussions/1058#discussioncomment-1977956).

With generics, we can even create a wrapper type for this as I have done in [Bob (another ORM that I created)](https://pkg.go.dev/github.com/stephenafamo/bob@v0.25.0/types#JSON), and then use it like this `types.JSON[[]*Tag]`
