### ISSUE TITLE
sqlboiler model generation not working with Vitess (MySQL CNFC scalable) due to subqueries

### ISSUE THREAD

**Issue by aliaqa256** [volatiletech/sqlboiler#1353]
I am encountering an issue with sqlboiler when using it with Vitess (a horizontally scalable MySQL implementation based on Google's PlanetScale). The functionality that reads the database and generates models is not working as expected.

Suspected cause: I believe the issue is likely related to the use of subqueries in my vanilla MySQL queries. Vitess might not be handling them correctly, causing problems during model generation.

Expected behavior:

sqlboiler should successfully read the database schema and generate the corresponding models without any errors.

**Comment by stephenafamo** [comment]
I do not consider this a bug since SQLBoiler does not claim to support Vitess. If you can replicate this on a regular MySQL database, then I will look more into it
