### ISSUE TITLE
SqlBoiler generates wrong table struct name

### ISSUE THREAD

**Issue by iamleson98** [volatiletech/sqlboiler#1362]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
4.16.2

### What is your database and version (eg. Postgresql 10)
PostgreSQL 14.11 (Ubuntu 14.11-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
```Makefile
model-gen:
	$(GO) install github.com/volatiletech/sqlboiler/v4@latest
	$(GO) install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-psql@latest

	$(GOBIN)/sqlboiler psql
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
CREATE TABLE IF NOT EXISTS product_media (
  id varchar(36) NOT NULL PRIMARY KEY,
  created_at bigint NOT NULL,
  product_id varchar(36) NOT NULL,
  ppoi varchar(20) NOT NULL,
  image varchar(200) NOT NULL,
  alt varchar(128) NOT NULL,
  type varchar(32) NOT NULL,
  external_url varchar(256),
  oembed_data jsonb,
  sort_order integer
);
```

output:
```go
// ProductMedium is an object representing the database table.
type ProductMedium struct {
	ID          string                 `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt   int64                  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	ProductID   string                 `boil:"product_id" json:"product_id" toml:"product_id" yaml:"product_id"`
	Ppoi        string                 `boil:"ppoi" json:"ppoi" toml:"ppoi" yaml:"ppoi"`
	Image       string                 `boil:"image" json:"image" toml:"image" yaml:"image"`
	Alt         string                 `boil:"alt" json:"alt" toml:"alt" yaml:"alt"`
	Type        string                 `boil:"type" json:"type" toml:"type" yaml:"type"`
	ExternalURL model_types.NullString `boil:"external_url" json:"external_url,omitempty" toml:"external_url" yaml:"external_url,omitempty"`
	OembedData  model_types.JSONString `boil:"oembed_data" json:"oembed_data,omitempty" toml:"oembed_data" yaml:"oembed_data,omitempty"`
	SortOrder   model_types.NullInt    `boil:"sort_order" json:"sort_order,omitempty" toml:"sort_order" yaml:"sort_order,omitempty"`

	R *productMediumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L productMediumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}
```

### Further information. What did you do, what did you expect?

I think Sqlboiler does yet know how to handle plural/singular form of the word `Media`

Thanks for supporting me, mr @aarondl

**Comment by stephenafamo** [comment]
I think it is reasonable that SQLBoiler would be unable to handle all cases perfectly. It appears this is one of those cases.

My recommendation would be to manually set the alias of this specific table. [Documentation](https://github.com/volatiletech/sqlboiler?tab=readme-ov-file#aliases)

**Comment by iamleson98** [comment]
@stephenafamo 
My friend,
I just did a dictionary lookup and I found that media and medium are actually the special versions of each other.

Yes, its my fault for not doing properly research before posting question.

Thanks for reaching out.
