### ISSUE TITLE
Sqlite view model has wrong type and can't be replaced

### ISSUE THREAD

**Issue by ShinyZero0** [volatiletech/sqlboiler#1369]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

4.16.1
### What is your database and version (eg. Postgresql 10)

3.44.2
### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

`sqlboiler sqlite3`
### Further information. What did you do, what did you expect?

It generates the entity for client_balance with balance as nullable string, which is a float actually. E.g. if i do a query with `sqlite3 -json` it is float

There is [the whole repo](https://codeberg.org/shinyzero0/dubnatech-hack.git)

**Comment by ShinyZero0** [comment]
UPD: it's the same for client_statuses view too. Also, the values are valid, but i have to parse them with `strconv`

**Comment by stephenafamo** [comment]
I will label this as a bug, but I need more information

The title says it can't be replaced, can you share how you are configuring the type replacement?

**Comment by ShinyZero0** [comment]
[like that](https://codeberg.org/shinyzero0/dubnatech-hack/src/commit/6e161275ee2631cf6fcd2b4e3815d52a4421558b/sqlboiler.toml)

AFAIR i also tried matching the capitalized name and it didn't work too

**Comment by ShinyZero0** [comment]
@stephenafamo
Any updates on this? 4.16.2 still has the problem.
I tried replacing like that:

```toml
[[types]]
	[types.match]
	type = "null.String"

	[types.replace]
	type = "float32"
```

the matcher is literally copied from README so it must work, but it doesn't. I still have the `null.String` balance field.

Are there ways to add more clues to my db schema so that sqlboiler could infer the types correctly?

**Comment by ShinyZero0** [comment]
I just tried the following and it worked. I thought less matchers must match more as it uses logical AND. That "boolean values must always match" in doc sounds ambiguous imo.

```toml
[[types]]

	[types.match]
	name = "balance"
	nullable = true

	[types.replace]
	type = "float32"
```

So, i at least know how to fix it myself now. If it's not possible to do more accurate type detection on views, the issue can be closed
