### ISSUE TITLE
UUID used as a primary key causes panic when loading

### ISSUE THREAD

**Issue by korECM** [volatiletech/sqlboiler#1381]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v4.16.2

### What is your database and version (eg. Postgresql 10)
MySQL 8.0

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
CREATE TABLE IF NOT EXISTS `events`
(
    `id`              BINARY(16)                         NOT NULL PRIMARY KEY,
    `name`            VARCHAR(255)                       NOT NULL,
    `insert_dt`       DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `update_dt`       DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
)
    ENGINE = InnoDB
    DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `schedules`
(
    `id`                  BINARY(16)                         NOT NULL PRIMARY KEY,
    `event_id`            BINARY(16)                         NOT NULL,
    `insert_dt`           DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `update_dt`           DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT `schedules_event_id_fk` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON DELETE CASCADE,
)
    ENGINE = InnoDB
    DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
```

### Further information. What did you do, what did you expect?
I am using UUID as a PK, and the generated code is as follows:

```go
type Event struct {
	ID             []byte    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name           string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	InsertDT       time.Time `boil:"insert_dt" json:"insert_dt" toml:"insert_dt" yaml:"insert_dt"`
	UpdateDT       time.Time `boil:"update_dt" json:"update_dt" toml:"update_dt" yaml:"update_dt"`

	R *eventR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L eventL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}
```

As you can see in the code above, the `ID` column uses the `[]byte` type.

```go
func (eventL) LoadSchedules(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEvent interface{}, mods queries.Applicator) error {
	var slice []*Event
	var object *Event

	// ...

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &eventR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &eventR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	// ...
	return nil
}
```

However, this leads to a problem in the code as follows:

```go
		args[object.ID] = struct{}{}
```

Here, the type of the `ID` value is `[]byte`, but a slice in Golang is not hashable. Therefore, the following error occurs:

```
	panic: runtime error: hash of unhashable type []uint8
```

https://github.com/volatiletech/sqlboiler/pull/1337

This issue is suspected to have arisen from the above PR. If you use version `v4.15.0`, this problem does not occur. It's necessary to solve the performance issue with `Load`, but it would be good if it could be used without any problems even when using UUID as a PK.

**Comment by stephenafamo** [comment]
Since you're using UUIDs, I would suggest doing a type replacement to use `[16]byte` instead. This should be usable as a map key.

```toml
[[types]]
  tables = ['events', 'schedules']
  [types.match]
    name = "id"
  [types.replace]
    type = "[16]byte"
```

Until better detection of the DB type is done to use arrays instead of slices, this would be the best solution.

**Comment by korECM** [comment]
Thanks, I was wondering if there was a way to do that, but there is!

**Comment by korECM** [comment]
@stephenafamo 
Sadly... Using a replace like the one above will cause the following problems

```go
create event: pdbmodel: unable to insert into events: sql: converting argument $1 type: unsupported type [16]uint8, a array
```

Is there anything else I can try?

**Comment by stephenafamo** [comment]
Perhaps you can try an actual UUID type?

[[types]]
  tables = ['events', 'schedules']
  [types.match]
    name = "id"
  [types.replace]
    type = "uuid.UUID"
  [types.imports]
    third_party = ['"github.com/google/uuid"']

**Comment by korECM** [comment]
I created a custom UUID type that implemented `sql.Scanner`, `driver.Valuer` and replaced it with this type and it worked! Thank you very much!

**Comment by stephenafamo** [comment]
> created a custom UUID type that implemented `sql.Scanner`, `driver.Valuer` and replaced it with this type and it worked!

Glad it worked.

Both `github.com/google/uuid` and `github.com/gofrs/uuid/v5` implement the interfaces, so it may be better to use one of them. It's likely to be better optimised, depending on your needs.

**Comment by xux1217** [comment]
> Perhaps you can try an actual UUID type?
> 
> ```toml
> [[types]]
>   tables = ['events', 'schedules']
>   [types.match]
>     name = "id"
>   [types.replace]
>     type = "uuid.UUID"
>   [types.imports]
>     third_party = ['"github.com/google/uuid"']
> ```

hi, I have many tables use UUID, and these are different field name, can you suggest some method to generate it? 
I can't write it more than one hundred times, can we use field type? like BINARY(16) means UUID?

**Comment by xux1217** [comment]
Or is it possible for us to optimize the primary key of the binary field?
Many of our codes have encountered binary compatibility issues. 
Can this be implemented at the library level?
Binary itself is also sortable.

**Comment by stephenafamo** [comment]
> I have many tables use UUID, and these are different field name, can you suggest some method to generate it?

The best suggestion I have is for you to write a small script to generate the config.  
While I understand how this is tedious, unfortunately, I can't think of something easier.
