### ISSUE TITLE
Generate helpers for PostgreSQL SIMILAR TO clause

### ISSUE THREAD

**Issue by jerrysalonen** [volatiletech/sqlboiler#1391]
It would be nice to have support for [SIMILAR TO expressions](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-SIMILARTO-REGEXP) in the psql drivers. Something like

```go
models.Examples(
  models.Field.SimilarTo("(foo|bar)"),
).All(ctx, tx)
```

would generate

```sql
SELECT * FROM example WHERE field SIMILAR TO '(foo|bar)';
```

It is not too much trouble to just write something like `models.Where("field SIMILAR TO ?", "(foo|bar)")` but a helper would be nice. If this is something that is desirable I could make a PR for this

**Comment by stephenafamo** [comment]
`SIMILAR TO` is only supported for text fields, if you can limit this to the Postgres generation and only for text fields, then sure 👍🏾
