### ISSUE TITLE
Make sqlite3 db path relative to sqlboiler config file

### ISSUE THREAD

**Issue by kelzenberg** [volatiletech/sqlboiler#1407]
Having a Go project with a file structure like the following is problematic when using absolute or relative paths [as suggested](https://github.com/volatiletech/sqlboiler/tree/master/drivers/sqlboiler-sqlite3#configuration) for the sqlite3 database in the sqlboiler config.
```
| project/
| -- cmd/
| ---- main.go
| -- db/
| ---- sqlite.db
| -- sqlboiler.toml
| -- go.mod
```

`sqlboiler.toml`

```toml
[sqlite3]
dbname = "db/sqlite.db"
```

The generation command works fine if ran in root ✅
```sh
sqlboiler --config ./sqlboiler.toml --output ./models sqlite3
```

The path-adjusted Go generate command in `main.go` will fail ❌
```Go
//go:generate sqlboiler --config ../sqlboiler.toml --output ../models sqlite3
```

The sqlite3 driver is not capable of finding the database `sqlite.db` as relative paths don't match. The problem can be solved by (optionally) resolving the sqlite3 database' path relative to the sqlboiler config, not the execution context.

**Comment by stephenafamo** [comment]
While this makes sense, this would be a breaking change so I wouldn't want to make the change because we won't be able to merge it before a future v5

**Comment by stephenafamo** [comment]
> Appreciate the answer. Would you put it in the backlog for a v5 please?

Sure. Although, I'm not really keeping track of them right now.  
Perhaps if you send in a PR, I could mark it as "breaking" and leave it unmerged for now.
