### ISSUE TITLE
warning: incompatible data type detected: ltree

### ISSUE THREAD

**Issue by kaustubh-11** [volatiletech/sqlboiler#1424]
SQLBoiler v4.16.2

postgres (PostgreSQL) 14.13 (Homebrew)

sqlboiler.toml file as follows:
```
[psql]
  dbname = "myDb"
  host   = "myHost"
  port   = 5432
  user   = "myUser"
  pass   = "myPsswd"
  schema = "audit"
  sslmode = "disable"
  whitelist = ["Table 1", "Table 2", "Table 3"]
```

Command to generate models:
`$sqlboiler psql --output sqlboiler_models/audit
`
When I run this command, I get below 2 warnings. 

```
warning: incompatible data type detected: ltree
warning: incompatible data type detected: ltree

```

Table DDL:
```
CREATE TABLE audit.employee_company_details (
	ecd_id bigserial NOT NULL,
	ecd_path public.ltree NULL
}
```
Generate Model:
```
type EmployeeCompanyDetail struct {
	EcdID                  int64       `boil:"ecd_id" json:"ecd_id" toml:"ecd_id" yaml:"ecd_id"`
	EcdPath                string      `boil:"ecd_path" json:"ecd_path,omitempty" toml:"ecd_path" yaml:"ecd_path,omitempty"`
```	

Out of these 3 whitelisted tables, 2 tables are having columns with the type as ltree, so I trust, that is the reason, I am receiving those warnings. I want to understand the implications or affects it might have, and if this is something that needs to be fixed. 

Column definition in the create statement query
`	ecd_path public.ltree NULL,
`

Thanks for such an amazing thing, much love and respect!

**Comment by stephenafamo** [comment]
The warning just means that it will default to generating the type as a string which may not marshal/unmarshal properly depending on the actual DB type.

If you run into any issues using it, you can use the `types` configuration to use a custom path.

**Comment by kaustubh-11** [comment]
Thanks much @stephenafamo, it helps.
