### ISSUE TITLE
Use a decimal library for v3

### ISSUE THREAD

**Issue by aarondl** [volatiletech/sqlboiler#162]
Currently we use a string to represent decimal to avoid people doing mathematical operations on decimal types as float64, except for a bug where Postgres uses float64 currently :( :( :( Brought up in this issue: https://github.com/vattle/sqlboiler/issues/100

Also in that issue one user makes the recommendation that we just use a decimal library. I think this kind of makes sense, we were trying to stay away from dependencies but can we truly justify it since we rely so heavily on the null package? It looks stable enough that we don't have to fork it unlike some other packages we depend on.

Let your thoughts be heard here. This is still on the fence.

**Comment by pennersr** [comment]
Great! My thoughts on this point:

- Using float64 is clearly a bug, it needs to be dropped.

- Replacing it string is not helping at all. Developers would be forced to do lots of manual conversion back and forth.

- Relying on complex features such as pluggable types, while possible, is really overkill for a basic SQL use case such as decimals, hampering developer productivity.

- Decimals are a basic SQL feature, therefore a good ORM(like) package should offer support out of the box.

- If a decimal type was offered by the Go standard library we would not be having this discussion at all.

**Comment by orian** [comment]
I've used a github.com/shopspring/decimal in some projects and it worked just fine. As Go is not planning to add decimal using external lib seems plausible.

**Comment by aarondl** [comment]
@orian Are you sure that they haven't already? I was under the impression that this was one.

https://golang.org/pkg/math/big/#Float

Though it's API seems a bit cumbersome (you have to manage precision pretty carefully).

**Comment by aarondl** [comment]
Also currently I'm eyeing github.com/ericlagergren/decimal as the most likely candidate.

**Comment by orian** [comment]
As far as I understand `big.Float` is a custom precision float but still a floating point (example: https://play.golang.org/p/Xb7f4_OYi7Q)

I've previewed ericlagergren/decima, seems decent, more complex but more mature and no a real bugs opened.

What's you criteria?

**Comment by aarondl** [comment]
@orian You're correct about `big.Float`. I think the ericlagergren library is just a well made library, has some nice math features as well as much better performance.
It has few bugs and the maintainer seems generally responsive about dealing with issues.

Just a great decimal library I think is what we need since the standard lib isn't coming through for us. Something that people can rely on and is performant and useful.

**Comment by orian** [comment]
It has some Postgre support: https://github.com/ericlagergren/decimal/tree/master/sql/postgres
but does not have a distinct NullDecimal and Decimal. I've checked the code, would modifying: https://github.com/volatiletech/sqlboiler/blob/master/bdb/drivers/postgres.go be enough for start?

**Comment by aarondl** [comment]
Yep. That's the right place. We'd also need a null decimal for full support. Though I'd ask any changes to be made on the v3 branch.

**Comment by orian** [comment]
I've sent an implementation of NullDecimal: https://github.com/ericlagergren/decimal/pull/98

And I've started to work on decimal support in postgre: https://github.com/volatiletech/sqlboiler/compare/v3...orian:patch-1
I need to extend `types` package and add tests. I'll try to get it done by tomorrow (UTC+2).

**Comment by aarondl** [comment]
Done in v3. Ping @orian just so you know :)

**Comment by orian** [comment]
Thanks, I have bit of crunch time.

**Comment by saulortega** [comment]
Hello, @aarondl . Why `double precision` in postgres is Decimal? A mistake?

**Comment by aarondl** [comment]
Definitely a mistake @saulortega, fixed in rc9 freshly released.
