### ISSUE TITLE
Slices have UpdateAll but no InsertAll

### ISSUE THREAD

**Issue by nullbio** [volatiletech/sqlboiler#166]
We should consider adding an InsertAll utility function for type of ObjSlice. There exists UpdateAll (and almost all other iterations of operations), but no InsertAll. Users currently need to create a loop, and whilst it is not hard, it would be nice to have built into the generated package.

**Comment by ceshihao** [comment]
I am trying to implement `InsertAll` in templates.
However, I can not retrieve the data back to slice. 

i.e. I can insert multiple records by `insert into table_name ('x', 'y') values ('value11', 'value12'), ('value21', 'value22');` But it is difficult to know which data is inserted by the SQL like what `result.LastInsertId()` works in `Insert`.

@nullbio @aarondl Do you have any idea on it?

**Comment by aarondl** [comment]
@ceshihao I don't think there's a good performant way to do this cross-database. I think the initial suggestion here is that we simply iterate over the slice and call insert on each one individually. It's a quick and dirty helper.

**Comment by aarondl** [comment]
Decided not to implement quick and dirty helper.
