### ISSUE TITLE
Tests broken with foreign key

### ISSUE THREAD

**Issue by peppage** [volatiletech/sqlboiler#173]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v2.5.0

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```SQL
CREATE TABLE pilots (
  id integer NOT NULL,
  name text NOT NULL
);

ALTER TABLE pilots ADD CONSTRAINT pilot_pkey PRIMARY KEY (id);

CREATE TABLE jets (
  id integer NOT NULL,
  pilot_id integer NOT NULL,
  age integer NOT NULL,
  name text NOT NULL,
  color text NOT NULL
);

ALTER TABLE jets ADD CONSTRAINT jet_pkey PRIMARY KEY (id);
ALTER TABLE jets ADD CONSTRAINT jet_pilots_fkey FOREIGN KEY (pilot_id) REFERENCES pilots(id);
```

### Further information. What did you do, what did you expect?
    Jets_test.go:39: models: unable to insert into jets: pq: insert or update on table "jets" violates foreign key constraint "jet_pilots_fkey"

**Comment by nullbio** [comment]
Hi @peppage -- What database version are you using? SQLBoiler tests should be stripping foreign key constraints from the pg_dump output. It seems like for whatever reason your generated database dump has a foreign key constraint that is not being detected by the regexp patterns we have, you can see that here: https://github.com/vattle/sqlboiler/blob/master/templates_test/singleton/boil_queries_test.tpl

**Comment by peppage** [comment]
I'm on psql (PostgreSQL) 9.5.2 on Windows.

That makes a lot of sense. I did some digging and figured out it's the final \n on the regex.

I first tried copy pasting the pg_dump to a test that was using that regex to match and it works if I pg_dump the file myself. If I save "all" to a file from from the read function, (f *fKeyDestroyer) Read(b []byte), and try to match the regex it won't find it. Something weird going on with that line ending because it looks the same to me using notepad2 with line endings turned on. Both lines have "CR LF" where it's trying to match \n.

**Comment by aarondl** [comment]
@peppage I guess we should convert all `\r\n` to `\n` before for windows compatibility then? Do you think this'll fix it?

**Comment by peppage** [comment]
I think if you remove the last ```\n``` it will work. I think that would also keep working in unix as well?

    var rgxPGFkey = regexp.MustCompile(`(?m)^ALTER TABLE ONLY .*\n\s+ADD CONSTRAINT .*? FOREIGN KEY .*?;`)

**Comment by aarondl** [comment]
I was trying to figure out why that `\n` is there in the first place. IIRC the wildcard there is by default a greedy match and so it'll probably eat the rest of the file until it finds the last `;` so the suggestion won't work. You'd have to change it to be something like `[^;]+;`. And even then this may lead to false positives. It's a dirty process what we do for this. But there was no reliable way to tell Postgres to turn the things off. You could test this & PR. I don't have a windows development environment handy so reproduction is harder for me.

**Comment by aarondl** [comment]
I think this is resolved in v3 branch.
