### ISSUE TITLE
Empty arrays in Postgres are returned as nil values

### ISSUE THREAD

**Issue by sadu99** [volatiletech/sqlboiler#178]
### What version of SQLBoiler are you using?
SQLBoiler v2.4.1

### Issue
Empty arrays in Postgres, set using `{}`, are currently returned as `nil` values instead of empty Go slices. This is problematic when such fields have a `NOT NULL` constraint. 

Consider the following scenario:
1. There exists a table with an array field `x` with a `NOT NULL` constraint
2. Table contains a record where value of `x` is an empty array `{}`
3. Client makes a request to update the record but does not change the value of `x`
4. API queries the DB for the record using SQLBoiler
5. Record is returned with a `nil` value for `x`
6. API tries to update record using passed-in values from the client 
7. `model.UpdateG()` fails since SQL cannot insert `nil` in a field with a `NOT NULL` constraint

### Expected Behavior
Empty arrays in any Postgres table should be returned as empty GO slices.

Please let me know if the above is sufficient to understand the issue.

**Comment by aarondl** [comment]
Hey @sadu99, thanks for filing. Unless I'm mistaken this fix will have to wait for the infamous `v3` since it is a breaking change in the way people's code expect to deal with arrays in `sqlboiler` using Postgres. I don't think it'll be too difficult to fix (but I might eat those words later!)

**Comment by nkev** [comment]
I'm getting the same issue too and I'm not sure how to proceed. 
I think the issue is here: https://github.com/volatiletech/sqlboiler/blob/master/types/array.go#L467
Is there a work around? Even a temporary one?

**Comment by aarondl** [comment]
@nkev My understanding of this issue is that it returns `nil` instead of `[]string{}` during a select, the line you highlighted would be returning an error because it failed to parse something inside postgres and would warrant a separate issue. Can you open a new one with new details that would help debug it?

To answer your supposition: Yes, it's a fairly straightforward fix to *this* issue but I labeled it a breaking change hence it not being taken care of yet.

If someone is doing a select, and then has an if statement that's checking for nil instead of empty string that would break their code so it's not something we can take super lightly.

**Comment by nkev** [comment]
thanks, understood.

**Comment by aarondl** [comment]
PQ wouldn't have code to convert here since we're using the types that I linked in the code above. I do encourage you to open another issue, the workaround seems... insufficient somehow :)

**Comment by iorlas** [comment]
Wow, that was unexpected to see. Had this problem right now. So I was forced to use strings to manually split it into strings/ints.
This issue makes PSQL arrays impossible to use in structs(models). Damn. It is urgent bug. It really, REALLY needs to be fixed.

**Comment by aarondl** [comment]
@iorlas I don't think you had this problem since an `if` statement solves this problem. It's not that urgent since there's a workaround and it's a breaking change for others that may have inadvertently relied on it in their code. Can you confirm that you're getting empty postgres arrays being decoded as `nil`?

**Comment by nkev** [comment]
If it helps, the issue I'm having is the same as #200

**Comment by iorlas** [comment]
@aarondl if solves problem only when you scan columns explicitly instead of scan into structure. It gives me headache to scan each column manually, which was a reason to switch to sql boiler in first place. I'll reinvestigate it on business hours, will provide more details

**Comment by aarondl** [comment]
Please test the branch `fix-arrays` to see if this issue is resolved for you.

**Comment by iorlas** [comment]
@aarondl I'll check it a bit later. Right now I'm a bit overwhelmed on project :(

**Comment by nkev** [comment]
@aarondl I tested it and it does work, thank you!

**Comment by nkev** [comment]
@aarondl I'm not sure if this error is a side-effect in the `fix-arrays` branch, but after adding a new view to the database (and blacklisting it in the `sqlboiler.toml` file), when I run `sqlboiler postgres && go test -v ./models` (or even just `sqlboiler postgres`), I now get:
```
Error: template: 00_struct.tpl:12:15: executing "00_struct.tpl" at <$dot.StructTagCasing>: can't evaluate field StructTagCasing in type *boilingcore.template
```
I will test the main branch too, but thought you may recognise what's happening.

**Comment by nkev** [comment]
@aarondl Update: `sqlboiler postgres` works on the main branch with the same code, so something is wrong in the `fix-arrays` branch.

**Comment by aarondl** [comment]
Tested and works on v3 branch, no additional changes necessary. I'm guessing this was indeed fixed when I did the fix-arrays branch a while back. Just wanted to verify.
