### ISSUE TITLE
About prepared statements and SQL injection

### ISSUE THREAD

**Issue by dtrehas** [volatiletech/sqlboiler#189]
Dear Aaron / Maintainers of this project ,

Do you need also prepared statements during data insertion/update?

Do you have any recommendations about reducing the chance of sql injection?

Thank you,
Dimitris

**Comment by aarondl** [comment]
We only use placeholders and parameters and never do string building to actually add arguments in, we always string build to add placeholders like `$1` and `?`. You should just use the library normally and you shouldn't have any problems, but if you're keen on looking into it I'd never turn away someone wanting to audit the code for bad practices.
