### ISSUE TITLE
UpdateAll sql problem on mysql

### ISSUE THREAD

**Issue by ceshihao** [volatiletech/sqlboiler#190]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v2.5.1

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
Yes

### Further information. What did you do, what did you expect?

https://github.com/volatiletech/sqlboiler/blob/master/queries/query_builders.go#L167

For UpdateAll function, SQLBoiler builds a SQL like "UPDATE xxx SET (a,b) = (v1,v2)".

However, mysql seems NOT to support this syntax.

https://dev.mysql.com/doc/refman/5.7/en/update.html

**Comment by aarondl** [comment]
Hey there. I noticed that the tests don't seem to exercise this code path for some reason? I haven't actually determined why. I don't have time to look into it right now but I'll hopefully get some time to spend a good chunk of time on sqlboiler soon.

**Comment by ceshihao** [comment]
Sounds good.

I think SQLBoiler can build updateSQL like "UPDATE xxx SET a = v1, b = v2" which is compatible among mysql, pgsql and mssql.

Do you have any concern about this change?

**Comment by aarondl** [comment]
I'm not really concerned. So long as it remains compatible. I think we already had to tackle this in the regular update here: https://github.com/volatiletech/sqlboiler/pull/119/files/4718e72b6df505b6cb1a5655422bce68c367c9dd#r106773864 when nemec introduced MSSQL. Though I'm not sure if he actually did refactor them all in the end as was requested. As long as the change was comprehensive and affected all database engines and they were ok I'd be okay with it.

**Comment by ceshihao** [comment]
I open a new PR #192 for this.

Please help review it.
Thx
