### ISSUE TITLE
Configurable json tags casing

### ISSUE THREAD

**Issue by jfernstad** [volatiletech/sqlboiler#191]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v2.5.1

Hi there, 

Currently SQLBoiler generates JSON tags in `snake_case`. For us, we would like to have the option to generate json tags in `camelCase` according to https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format. 

It can easily be done with a change to the templates, however it would be nice to have this as an option at time of generation, either in the config or as an argument in to the binary. 

We're preparing a fork and we'll do all the work but I'd like some input on what the best option might be to accomplish this. 

I've done a cursory review of the repo and I haven't seen an easy way to pass data from configuration to the template parser. 

Thoughts on this?

Thanks

**Comment by aarondl** [comment]
https://github.com/volatiletech/sqlboiler/blob/master/boilingcore/templates.go#L18 This data is all passed in to the templates.

https://github.com/volatiletech/sqlboiler/blob/split-drivers/templates/00_struct.tpl#L11 You can see here what's being done. It's in fact pretty bad since it assumes `snake_case` for everything coming from the database. It should probably be coerced regardless.

Hopefully this is enough to get you going.

**Comment by jfernstad** [comment]
Thanks!

I seems I have a few options with different level of effort. Would like your thoughts on which option is preferred. 

For both options, I need to add a new parameter (naming is hard, up for discussion). 

```diff
diff --git a/boilingcore/boilingcore.go b/boilingcore/boilingcore.go
index e10c204..06df2b4 100644
--- a/boilingcore/boilingcore.go
+++ b/boilingcore/boilingcore.go
@@ -107,6 +107,7 @@ func (s *State) Run(includeTests bool) error {
 		PkgName:          s.Config.PkgName,
 		NoHooks:          s.Config.NoHooks,
 		NoAutoTimestamps: s.Config.NoAutoTimestamps,
+		TagCasingCamel:   s.Config.TagCasingCamel,
 		Dialect:          s.Dialect,
 		LQ:               strmangle.QuoteCharacter(s.Dialect.LQ),
 		RQ:               strmangle.QuoteCharacter(s.Dialect.RQ),
@@ -142,6 +143,7 @@ func (s *State) Run(includeTests bool) error {
 			PkgName:          s.Config.PkgName,
 			NoHooks:          s.Config.NoHooks,
 			NoAutoTimestamps: s.Config.NoAutoTimestamps,
+			TagCasingCamel:   s.Config.TagCasingCamel,
 			Tags:             s.Config.Tags,
 			Dialect:          s.Dialect,
 			LQ:               strmangle.QuoteCharacter(s.Dialect.LQ),
diff --git a/boilingcore/config.go b/boilingcore/config.go
index 63b0552..653885b 100644
--- a/boilingcore/config.go
+++ b/boilingcore/config.go
@@ -16,6 +16,7 @@ type Config struct {
 	NoHooks          bool
 	NoAutoTimestamps bool
 	Wipe             bool
+	TagCasingCamel   bool
 
 	Postgres PostgresConfig
 	MySQL    MySQLConfig
diff --git a/boilingcore/templates.go b/boilingcore/templates.go
index b353237..0b65f61 100644
--- a/boilingcore/templates.go
+++ b/boilingcore/templates.go
@@ -34,6 +34,9 @@ type templateData struct {
 	// Tags control which
 	Tags []string
 
+	// Generate struct tags as camelCase if true
+	TagCasingCamel bool
+
 	// StringFuncs are usable in templates with stringMap
 	StringFuncs map[string]func(string) string
 
diff --git a/main.go b/main.go
index 37fcdea..eb93eca 100644
--- a/main.go
+++ b/main.go
@@ -87,6 +87,7 @@ func main() {
 	rootCmd.PersistentFlags().BoolP("version", "", false, "Print the version")
 	rootCmd.PersistentFlags().BoolP("tinyint-as-bool", "", false, "Map MySQL tinyint(1) in Go to bool instead of int8")
 	rootCmd.PersistentFlags().BoolP("wipe", "", false, "Delete the output folder (rm -rf) before generation to ensure sanity")
+	rootCmd.PersistentFlags().BoolP("tag-casing-camel", "", false, "Generates camelCase for go structure tags names (default false (snake_case))")
 
 	// hide flags not recommended for use
 	rootCmd.PersistentFlags().MarkHidden("replace")
@@ -141,6 +142,7 @@ func preRun(cmd *cobra.Command, args []string) error {
 		NoHooks:          viper.GetBool("no-hooks"),
 		NoAutoTimestamps: viper.GetBool("no-auto-timestamps"),
 		Wipe:             viper.GetBool("wipe"),
+		TagCasingCamel:   viper.GetBool("tag-casing-camel"),
 	}
 
 	// BUG: https://github.com/spf13/viper/issues/200
```

Which is called with something like this:
```bash
./sqlboiler --basedir ./vendor/github.com/volatiletech/sqlboiler --wipe --no-tests --no-hooks mysql --tag-casing-camel=true
```

#### Option 1: 
Change to template:
```diff
diff --git a/templates/00_struct.tpl b/templates/00_struct.tpl
index fa674ae..0b364c9 100644
--- a/templates/00_struct.tpl
+++ b/templates/00_struct.tpl
@@ -8,7 +8,7 @@
 // {{$modelName}} is an object representing the database table.
 type {{$modelName}} struct {
 	{{range $column := .Table.Columns -}}
-	{{titleCase $column.Name}} {{$column.Type}} `{{generateTags $dot.Tags $column.Name}}boil:"{{$column.Name}}" json:"{{$column.Name}}{{if $column.Nullable}},omitempty{{end}}" toml:"{{$column.Name}}" yaml:"{{$column.Name}}{{if $column.Nullable}},omitempty{{end}}"`
+	{{titleCase $column.Name}} {{$column.Type}} `{{generateTags $dot.Tags $column.Name}}boil:"{{$column.Name}}" json:"{{if $dot.TagCasingCamel}}{{$column.Name | camelCase}}{{else}}{{$column.Name}}{{end}}{{if $column.Nullable}},omitempty{{end}}" toml:"{{if $dot.TagCasingCamel}}{{$column.Name | camelCase}}{{else}}{{$column.Name}}{{end}}" yaml:"{{if $dot.TagCasingCamel}}{{$column.Name | camelCase}}{{else}}{{$column.Name}}{{end}}{{if $column.Nullable}},omitempty{{end}}"`
 	{{end -}}
 	{{- if .Table.IsJoinTable -}}
 	{{- else}}
```

This is enough for us, but the template contains a bunch of embedded `if-else` which is not very clean or easy to read. 

#### Option 2: Cleaner template file
The 2nd option is to add another function to `templateFunctions` which is specific for tag casing. 

```diff
diff --git a/boilingcore/templates.go b/boilingcore/templates.go
index b353237..0b65f61 100644
--- a/boilingcore/templates.go
+++ b/boilingcore/templates.go
@@ -34,6 +34,9 @@ type templateData struct {
 	// Tags control which
 	Tags []string
 
+	// Generate struct tags as camelCase if true
+	TagCasingCamel bool
+
 	// StringFuncs are usable in templates with stringMap
 	StringFuncs map[string]func(string) string
 
@@ -191,6 +194,7 @@ var templateFunctions = template.FuncMap{
 	// Casing
 	"titleCase": strmangle.TitleCase,
 	"camelCase": strmangle.CamelCase,
+	"tagCasing": func(str string) string { return str }, // Default does nothing (= snake_case)
 
 	// String Slice ops
 	"join":               func(sep string, slice []string) string { return strings.Join(slice, sep) },
```

Giving the template this look:
```diff
diff --git a/templates/00_struct.tpl b/templates/00_struct.tpl
index fa674ae..cb675c2 100644
--- a/templates/00_struct.tpl
+++ b/templates/00_struct.tpl
@@ -8,7 +8,7 @@
 // {{$modelName}} is an object representing the database table.
 type {{$modelName}} struct {
 	{{range $column := .Table.Columns -}}
-	{{titleCase $column.Name}} {{$column.Type}} `{{generateTags $dot.Tags $column.Name}}boil:"{{$column.Name}}" json:"{{$column.Name}}{{if $column.Nullable}},omitempty{{end}}" toml:"{{$column.Name}}" yaml:"{{$column.Name}}{{if $column.Nullable}},omitempty{{end}}"`
+	{{titleCase $column.Name}} {{$column.Type}} `{{generateTags $dot.Tags $column.Name}}boil:"{{$column.Name}}" json:"{{$column.Name | tagCasing}}{{if $column.Nullable}},omitempty{{end}}" toml:"{{$column.Name | tagCasing}}{{end}}" yaml:"{{$column.Name | tagCasing}}{{if $column.Nullable}},omitempty{{end}}"`
 	{{end -}}
 	{{- if .Table.IsJoinTable -}}
 	{{- else}}
```

This would require us to be able to pass the command line argument to the `tagCasing` function somehow which is not easy, as it turns out. 

I would be ok with a solution like:
```diff
diff --git a/boilingcore/templates.go b/boilingcore/templates.go
index b353237..0145bf0 100644
--- a/boilingcore/templates.go
+++ b/boilingcore/templates.go
@@ -34,6 +34,9 @@ type templateData struct {
 	// Tags control which
 	Tags []string
 
+	// Generate struct tags as camelCase if true
+	TagCasingCamel bool
+
 	// StringFuncs are usable in templates with stringMap
 	StringFuncs map[string]func(string) string
 
@@ -101,6 +104,14 @@ func (t templateList) Templates() []string {
 
 // loadTemplates loads all of the template files in the specified directory.
 func loadTemplates(dir string) (*templateList, error) {
+
+	templateFunctions["tagCasing"] = func(str string) string {
+		if config.tagCasingCamel {
+			return strmangle.CamelCase(str)
+		}
+		return str
+	}
+
 	pattern := filepath.Join(dir, "*.tpl")
 	tpl, err := template.New("").Funcs(templateFunctions).ParseGlob(pattern)
 
```

Which would replace the default `tagCasing` function with a lambda function containing the passed in command line argument.

The problem is that `loadTemplates` is a function and not a method so it doesn't have access to the `templateData` object (also we have the `loadTemplate` function is which requires a bit of code duplication to cover all cases). We would have to change the template functions to be part of the `templateData` object or `state` object and then change how [`loadTemplates`](https://github.com/volatiletech/sqlboiler/blob/master/boilingcore/templates.go#L103) is called in [`initTemplates`](https://github.com/volatiletech/sqlboiler/blob/master/boilingcore/boilingcore.go#L184) 

Is there a 3rd option? Concerns? 

Thanks

**Comment by aarondl** [comment]
So I think this is fine. Though I would be tempted to name the parameter:
`--struct-tag-casing camel|snake` because we could one day add title casing or something else.

Option 1 is the best. We acknowledge that the templates can become unwieldy. This particular template could be cleaned up with some newlines if you felt so inclined. I think it'd improve readability a lot.

**Comment by tobbe303** [comment]
Since there are different types of struct tags perhaps something along the line of --json-tag-casing camel|snake would be appropriate?

**Comment by jfernstad** [comment]
Thanks Aaron!

While @tobbe303 has a valid point I believe devs will want a certain parity between their structures, regardless of `json`, `xml` or `yaml` formatting. I could be wrong but I chose to go with @aarondl suggestion. 

Implementation in PR #194. Grateful for any comments that could improve it.

**Comment by aarondl** [comment]
This issue refers to something that was merged, closing.

**Comment by c9s** [comment]
I am looking for the camel case option, however, I am using snake case for the table, column names and camel case for the json tag ....

looks like this PR can only switch the case for all the tags
