### ISSUE TITLE
Add generation option to remove globals

### ISSUE THREAD

**Issue by caseylmanus** [volatiletech/sqlboiler#202]
I'd like to be able to generate models without the G functions, it is bad practice to use the globals at all and I'd like the ability to generate models without this, which would reduce the code footprint of the generated code

### What version of SQLBoiler are you using (`sqlboiler --version`)?
2.5.1

**Comment by aarondl** [comment]
I agree with the use case and I in fact don't use the `G` methods anywhere either, but I don't think we'll put in the effort to make this possible. Would accept a PR for a `--no-global-methods` flag and config option that removes them.
