### ISSUE TITLE
Build FK relationship even if no FK in db schema

### ISSUE THREAD

**Issue by ceshihao** [volatiletech/sqlboiler#208]
In my case, there is no FK relationship in db schema, but i need it.

Can SQLBoiler define FK relationship in configuration file, and generate corresponding code?

e.g. 

sqlboiler.toml includes
```toml
[[key]]
  table_name: "one"

  [[key.foreign_key]]
    name: "fk_one_two_id"
    column: "two_id"
    foreign_table: "two"
    foreign_column: "id"

  [[key.foreign_key]]
    name: "fk_one_three_id"
    column: "three_id"
    foreign_table: "three"
    foreign_column: "id"

[[key]]
  table_name: "four"

  [[key.foreign_key]]
    name: "fk_four_two_id"
    column: "two_id"
    foreign_table: "two"
    foreign_column: "id"

```

**Comment by aarondl** [comment]
I think the best idea is to add an FK if you need it. Remember that FKs are JUST a convenience mechanism in `sqlboiler` and everything can be done without them, it just makes it harder. I think it's bad form to include configuration of the database outside the database so I'll respectfully close this issue as a won't fix. Sorry @ceshihao :(
