### ISSUE TITLE
Allow for querying of NULL values

### ISSUE THREAD

**Issue by payaaam** [volatiletech/sqlboiler#213]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

**Version**
`SQLBoiler v2.5.1`

**Problem**

I am unable to query for rows in which my query calls for a `NULL` value. I have tried passing in `null.Int{}` as well and it never returns any rows. It appears the only way to query for this is to use a raw query...
```golang

// My Query
domainMapNode, err := models.DomainMapNodes(os.db, qm.Where("organization_id=? AND unit_id=? AND user_id=? AND map_id=?", org.ID, nil, nil, mapId)).One()

// Returns `sql.ErrNoRows`

// Here is the struct
type DomainMapNode struct {
	ID             int       `boil:"id"`
	UnitID         null.Int  `boil:"unit_id"`
	UserID         null.Int  `boil:"user_id""`
	MapID          int64     `boil:"map_id"`
	CreatedAt      null.Time `boil:"created_at"`
	UpdatedAt      null.Time `boil:"updated_at"`
	OrganizationID int       `boil:"organization_id"`

}
// I want to return a row that is the following
// id = 1
// UnitId = nil
// UserId = nil
// MapId = 123
// OrganizationID = 1
```

I would expect that when I pass in `nil` or at least `null.Int{}`, sqlboiler would extrapolate that to `IS NULL` which is the postgres way to query nulls.

Here is the query that works correctly...
```
SELECT
    *
FROM
    "domain_map_node"
WHERE
    organization_id = $1
    AND map_id = $2
    AND user_id IS NULL
    AND unit_id IS NULL
```

I am sure I am missing something in the docs. Any advice?

**Comment by aarondl** [comment]
Well I would first say that if you're doing a hardcoded query where the value you're looking for happens to be `NULL` then you should just put that into the query. The only reason for placeholders etc. is to interpret the value correctly (quotes, no quotes, escaping etc). `NULL` is as much a keyword as `SELECT` is so it should be fine to put directly in the query.

Have you tried to see what query is occurring with your code? You can turn on debug mode to see it print out what's happening. I think in general our where clause generation will probably fail here, but I'd like to see what you see first.

Try debug mode:
https://github.com/volatiletech/sqlboiler#debug-logging

**Comment by aarondl** [comment]
I don't think this is an actual problem. Refer to answer above. Please re-open if I'm missing something and the workaround isn't adequate.
