### ISSUE TITLE
Test failure: Unable to execute setup: failed to wait for mysql command: exit status 1

### ISSUE THREAD

**Issue by ceshihao** [volatiletech/sqlboiler#220]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
2.5.1

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)

go test example -parallel 1
--defaults-file=/var/folders/2x/y4dx8dr54h14mn91vn4wf48wbqrjqn/T/optionfile580329963
bhzotphqphigzoywffgiqifnbzdeblogvcxxcdvd
exit status 1
Unable to execute setup: failed to wait for mysql command: exit status 1

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
I use example schema. (remove json type because mysql 5.6.38 not support)
https://github.com/volatiletech/sqlboiler/blob/master/testdata/mysql_test_schema.sql

go version: 1.7.5
mysql version: 5.6.38

### Further information. What did you do, what did you expect?
I found the failure is on `createCmd.Wait()`
https://github.com/volatiletech/sqlboiler/blob/master/templates_test/main_test/mysql_main.tpl#L54

As suggested in #95 #182 ,i try permissions are right.

I also try to replace createCmd to a simple `mysql --defaults-file xxx -e 'show databases'`, and this failure is gone. (Test fails due to no table creation)

Therefore, I think it may be some problem in my mysql conf? Does anyone have any hint on it?

**Comment by aarondl** [comment]
When I've seen this problem in the past, it's been a config issue. Usually that the password is not being sent and so mysql wants to do an interactive password, which is why it never completes. Since you're the owner of the process, you can check it's args and env, and the defaults file. Can you look into these things? It's hard to troubleshoot when the values are plain to see, and even harder to reproduce.

**Comment by ceshihao** [comment]
It is because MySQL config which makes the dump file cannot be imported correctly.
I fix the MySQL config.

Thanks. Close #220
