### ISSUE TITLE
Model tests should show stdout/stderr of commands on failure

### ISSUE THREAD

**Issue by Dirbaio** [volatiletech/sqlboiler#224]
pg_dump may fail under certain conditions (in my case it was due to client-server version mismatch, since I'm running pg inside a Docker container). If so, you get a not very informative "exit status 1" error:

```
$ go test ./models
exit status 1
Unable to execute setup: failed to wait for pg_dump command: exit status 1
FAIL	github.com/XX/XX/models	0.275s
```

whereas when running pg_dump directly you clearly see the issue:
```
$ pg_dump -s -U postgres -h localhost
pg_dump: server version: 10.1; pg_dump version: 9.6.5
pg_dump: aborting because of server version mismatch
```

This could be solved by printing pg_dump's stderr in case of failure.

**Comment by aarondl** [comment]
Yeah, totally agree with this.

https://github.com/volatiletech/sqlboiler/blob/master/templates_test/main_test/postgres_main.tpl#L55

It'd be pretty easy to add a buffer or something to capture it and output on error.

**Comment by namco1992** [comment]
hi @aarondl , is this issue still help wanted? I think I can try to take over this one and also for mysql and maybe mssql.

**Comment by aarondl** [comment]
@namco1992 Sure is. Though these files have been changed a lot and have been renamed and the whole 9 yards in the v3 branch, my preference is to include this there as I'm gearing up for a release of it hopefully this week. If you're looking for it in v2 for your own purposes then that's fine too, just more work to port it later to v3 :)

**Comment by namco1992** [comment]
hi @aarondl , from my understanding you've alr worked on it for v3 right? so I will just wait for the new release, thanks!

**Comment by aarondl** [comment]
No no! It still needs doing. I was just saying: We should put it in v3, not v2 :)

**Comment by namco1992** [comment]
ah sorry, sure I can try to put it in v3, but I just browsed the v3 branch and didn't find the template files which contain the DB tester, is it because the structure is changed? It would be appreciated if you can indicate how I can work on this part.

**Comment by aarondl** [comment]
The structure did change quite a bit. The db tester files now exist here for each database:

https://github.com/volatiletech/sqlboiler/blob/v3/drivers/sqlboiler-psql/driver/override/templates_test/singleton/psql_main_test.tpl
https://github.com/volatiletech/sqlboiler/blob/v3/drivers/sqlboiler-mysql/driver/override/templates_test/singleton/mysql_main_test.tpl
https://github.com/volatiletech/sqlboiler/blob/v3/drivers/sqlboiler-mssql/driver/override/templates_test/singleton/mssql_main_test.tpl

Keep in mind that in v3 the drivers are now separate binaries. So to build them I recommend you use the build script helper.

After changing templates in a driver:

```bash
# This runs go-generate for each driver, creating its bindata (drivers use bindata for their templates)
./boil.sh go-generate
# This builds each driver, which is necessary when bindata changes
./boil.sh build all
```

Feel free to jump in slack and ask questions, you'll get a faster response :)

**Comment by aarondl** [comment]
Fixed on dev.
