### ISSUE TITLE
Question: qmSelect with qm.Load

### ISSUE THREAD

**Issue by polderudo** [volatiletech/sqlboiler#225]
Is there any way to use qm.Select together with qm.Load and .Bind()?
Right now i'm doing this with qm.InnerJoin and qm.Select, followed by .Bind() but i'd like to remove that InnerJoin because it includes the fields as string.

Something like:
err:=models.Testtables(db, qm.Load("Relation"), qm.Select("field1, field2, Relation.Field1")).Bind(&myStruct)

**Comment by aarondl** [comment]
Currently there's no way to apply query mods to eager loading. It's a known issue we're planning on taking care of:
https://github.com/volatiletech/sqlboiler/issues/69

Will close this as a duplicate, thanks for submitting :)
