### ISSUE TITLE
Is there a way to customise the json annotation on the models?

### ISSUE THREAD

**Issue by Jackyjjc** [volatiletech/sqlboiler#231]
We are currently evaluating different ORM frameworks for GORM replacement in our services. I quite like this framework, however, it does not appear to be a way to change the json tags for the generated models other than modifying the files manually? 

In our existing services, the API output model is mapped 1:1 to the db model to minimise duplication. However the field names in the API model are not necessarily the same as the names of the database columns. Is there a way in sqlboiler to customise the this? Thanks!

**Comment by aarondl** [comment]
This should be able to do it? https://github.com/volatiletech/sqlboiler/blob/master/main.go#L81 Reopen if this is not what you're talking about. :)
