### ISSUE TITLE
Call model got Error :  does not compile: cannot convert db (type *sql.DB) to type models.ModelName

### ISSUE THREAD

**Issue by aloha1003** [volatiletech/sqlboiler#249]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v2.6.0

### Further information. What did you do, what did you expect?
My Problem code is [here](https://gist.github.com/aloha1003/b510485b91bf328b7b39e1c548e58a77)

I got models , but I call model in  app.go , I got below error message 
`does not compile: cannot convert db (type *sql.DB) to type models.BonusMissio`

**Comment by Dexus** [comment]
import please the mysql driver

https://github.com/go-sql-driver/mysql look at the usage...

**Comment by aarondl** [comment]
So, there's three problems here:

1. Dexus is right in that you would have to import the mysql driver for sure before this would work.
2. You've ellided part of the error message, typically if Go cannot convert a type to an interface, it'll say the reason why it couldn't do that.
3. In the sample code it looks like you're using the revel web framework and you're inside a request, please ensure that you don't call `sql.Open` on each request, as each call to that opens a pool of connections (not just one), so it's much more efficient to simply call `sql.Open` one time and store the `db` on a struct somewhere and re-use it.

**Comment by aloha1003** [comment]
Thx , I fix it .
