### ISSUE TITLE
Time Format parse error 

### ISSUE THREAD

**Issue by aloha1003** [volatiletech/sqlboiler#252]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v2.6.0

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
My DB Schema  : 
      `CREATE TABLE `bonus_mission` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT ,
  `mission_name` varchar(45) DEFAULT NULL ,
  `status` tinyint(1) DEFAULT NULL ,
  `mission_desc` mediumtext ,
  `start_time` datetime DEFAULT NULL ,
  `end_time` datetime DEFAULT NULL ,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COMMENT='retry_num_extra_bonus_rule\nretry_num_extra_bonus_rule';`

### Further information. What did you do, what did you expect?

Code is [here](https://gist.github.com/aloha1003/a4e119978a95eb221cde87f120d63a67)

I got error when `start_time` which  column type is datetime,  I got  `models: failed to execute a one query for bonus_mission: failed to bind pointers to obj: sql: Scan error on column index 4: null: cannot scan type []uint8 into null.Time:`

**Comment by aarondl** [comment]
You may try the latest release that contained fixes for time in both psql and mysql, if that doesn't resolve it we can dig in

**Comment by aarondl** [comment]
Stale, closing.

**Comment by tigp** [comment]
Hi @aarondl, thanks for great package! 

We have this problem, in the latest version, we are using `datetime` for the `created_at` and `updated_at` in the database, and getting the same error.

Is there any solution for that?

Thank you.

**Comment by aarondl** [comment]
I see that you're using mysql, in the readme it states:

> For MySQL if using the github.com/go-sql-driver/mysql driver, please activate time.Time parsing when making your MySQL database connection. SQLBoiler uses time.Time and null.Time to represent time in it's models and without this enabled any models with DATE/DATETIME columns will not work.

Are you doing this?

**Comment by tigp** [comment]
Oh, didn't notice it, we'll try that. Thanks so much for your help!
