### ISSUE TITLE
If the obj is nil in the second level will panic, such as XXX.XXX

### ISSUE THREAD

**Issue by renshaohai83** [volatiletech/sqlboiler#265]
https://github.com/volatiletech/sqlboiler/blob/7e0eca627f995e2476d637ada0c3b70ecb5d837c/templates/09_relationship_to_many_eager.tpl#L31

If the obj is nil in the second level will panic, such as XXX.XXX.
Could we add a return if the obj is nil?

Thanks,
renshaohai83

**Comment by aarondl** [comment]
What's the condition that triggers a null to appear there? Nullable foreign keys?

**Comment by aarondl** [comment]
Stale. Try dev branch it has improvements around eager loading nullable things. With one related bug in progress.
