### ISSUE TITLE
MySQL/MariaDB ssl-mode (5.6 incompatibility)

### ISSUE THREAD

**Issue by aarondl** [volatiletech/sqlboiler#273]
Originally from #262:

> In the generated code main_test.go, the makeOptionFile method provides the credentials and params for the db connection, fmt.Fprintf(tmp, "ssl-mode=%s\n", m.sslMode(m.sslmode)) will try to add the ssl-mode based on the settings. However, the DISABLED and PREFERRED are only supported in mysql 5.7 and they will be rejected in mysql 5.6. You can refer to the doc here.

I've also noticed that MariaDB Server and MySQL Client are incompatible in this way.

From 5.6 Docs:

> This option is available only for client programs, not the server. It specifies the security state of the connection to the server:
> If this option is not specified, the default is to establish an unencrypted connection. This is like the --ssl=0 option or its synonyms (--skip-ssl, --disable-ssl).
> If this option is specified, the only permitted value is REQUIRED (establish an encrypted connection if the server supports encrypted connections). The connection attempt fails if an encrypted connection cannot be established.

From 5.7 Docs:

> This option is available only for client programs, not the server. It specifies the security state of the connection to the server. These option values are permitted:
> PREFERRED: Establish an encrypted connection if the server supports encrypted connections, falling back to an unencrypted connection if an encrypted connection cannot be established. This is the default if --ssl-mode is not specified.
> REQUIRED: Establish an encrypted connection if the server supports encrypted connections. The connection attempt fails if an encrypted connection cannot be established.
> VERIFY_CA: Like REQUIRED, but additionally verify the server Certificate Authority (CA) certificate against the configured CA certificates. The connection attempt fails if no valid matching CA certificates are found.
> VERIFY_IDENTITY: Like VERIFY_CA, but additionally perform host name identify verification by checking the server's Common Name identity in the certificate that the server sends to the client. The client verifies the Common Name against the host name the client uses for connecting to the server, and the connection fails if there is a mismatch. For encrypted connections, this option helps prevent man-in-the-middle attacks. This is like the legacy --ssl-verify-server-cert option.
> DISABLED: Establish an unencrypted connection. This is like the legacy --ssl=0 option or its synonyms (--skip-ssl, --disable-ssl).

Currently SQLBoiler is using 5.7 configuration options:
https://github.com/volatiletech/sqlboiler/blob/master/templates_test/main_test/mysql_main.tpl#L72

So the question is: Do we want to support MySQL 5.6? I'm going to say no initially. But I'd also want others to chime in.

**Comment by Dexus** [comment]
No, MySQL 5.7 is the way to go and or current MariaDB 10.x and abdove

**Comment by aarondl** [comment]
Will not support old mysql.

**Comment by lunemec** [comment]
Please note, on Archlinux (2018-08-17) default MySQL implementation is MariaDB 10.1.35 where `--ssl-mode=DISABLED` doesn'ŧ work. Unfortunately there are no newer versions of MariaDB available even on archlinux.

Percona-db (client) seems to work fine.

**Comment by deavid** [comment]
I understand this decision but more than a year later I have been still impacted by this. MariaDB still does not have the newer options and it's the default packaged MySQL in Debian.

For now I'm commenting the lines for ssl-mode in models/mysql_main_test.go generated file.

Please consider adding a flag option to at least disable specifying SSL options so it can be used on localhost (where SSL does not play a big role in security). Not ideal, but at least it would be a workaround for those installations.

**Comment by aarondl** [comment]
I'm curious why the downstream projects (like sqlboiler) are left to deal with this incompatibility. Has anyone raised the issue upstream yet, is there a link to this issue in a bug tracker? Until such time as someone's attempted to push this upstream and failed we're not going to change anything.

As for our project's stance on the issue currently it doesn't seem reasonable to add workarounds for something that we don't directly support (MariaDB). We only "support" it because it's compatible with mysql, and because that's currently not true around ssl options you could say we're not supporting it until they restore that compatibility.

This also only affects the tests and so it's very low priority.

**Comment by tooolbox** [comment]
This issue has been raised upstream: https://jira.mariadb.org/browse/MDEV-22129

In that thread, Sergei raises a good point: why does the SSL mode need to be specified?

I looked into it, and I see this: (abbreviated & concatenated)
```go
viper.SetDefault("mysql.sslmode", "true")
m.sslmode = viper.GetString("mysql.sslmode")

func (m *mysqlTester) sslMode(mode string) string {
	switch mode {
	case "true":
		return "REQUIRED"
	case "false":
		return "DISABLED"
	default:
		return "PREFERRED"
	}
}

fmt.Fprintf(tmp, "ssl-mode=%s\n", m.sslMode(m.sslmode))
```

So it seems like sqlboiler specifies the `ssl-mode` based on the config file, defaulting to `REQUIRED`.  The user can alternately:
- Put `"true"` in their config (no change)
- Put `"false"` in their config (`DISABLED`)
- Put `"PREFERRED"` or `"banana"` or anything else in their config (`PREFERRED`)

Although we can get MariaDB to add `ssl-mode` to their client (at least the options that they do support) I don't see why we couldn't have a more flexible strategy for handling ssl in sqlboiler.  Since `PREFERRED` is the default, why specify it explicitly?  This method should right away support MySQL 5.6 and MariaDB, at least for tests:
```go
func (m *mysqlTester) sslMode(mode string) string {
	switch mode {
	case "true":
		return "REQUIRED"
	case "false":
		return "DISABLED"
	default:
		return "" // defaults to "PREFERRED"
	}
}

if m.sslMode != "" {
	fmt.Fprintf(tmp, "ssl-mode=%s\n", m.sslMode(m.sslmode))
}
```

It might also be worth reviewing how to make this value more pass-through for MySQL, similar to how the Postgres driver is, but I don't think it's unreal to *somehow* support passing a blank value via config, and then not writing this flag if the value is blank.

**Comment by aarondl** [comment]
@tooolbox I'd definitely look at one. So long as it changes nothing (breaks nothing I mean) then it'd be accepted if it solved the issue.

Sergei's response is very confusing here:
> MariaDB clients don't support ssl-mode. As MySQL 5.7 manual above says, one is supposed to use --ssl instead of --ssl-mode=PREFERRED and --ssl --ssl-verify-server-cert instead of --ssl-mode=VERIFY_IDENTITY.

The MySQL manual does not say that `--ssl` should be used instead of `--ssl-mode=PREFERRED`. I think his interpretation is not correct as MySQL 5.7 deprecates the use of `--ssl` and friends. Perhaps he's thinking about the server and not the client.

From the manual:
https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#encrypted-connection-options

> Note
>
> The client-side --ssl option is deprecated as of MySQL 5.7.11 and is removed in MySQL 8.0. For client programs, use --ssl-mode instead:
>
>    Use --ssl-mode=REQUIRED instead of --ssl=1 or --enable-ssl.
>
>    Use --ssl-mode=DISABLED instead of --ssl=0, --skip-ssl, or --disable-ssl.
>
>    No explicit --ssl-mode option is equivalent to no explicit --ssl option. 
>
> The server-side --ssl option is not deprecated.

Someone should possibly note this in the MDEV-22129 issue.

Whenever I look at this issue I need to re-acquaint myself with it so here's a quick summary for future-me:
* MariaDB uses old-style MySQL ssl configuration (`--ssl`, `--ssl-verify-server-cert`, --skip-ssl, `--disable-ssl`) instead of the new style in MySQL>=5.7 (`--ssl-mode`).
* MariaDB still has not fixed the incompatibility (https://jira.mariadb.org/browse/MDEV-22129) and as such users have no upgrade-out path to a resolution
* This only affects running the tests

**Comment by tooolbox** [comment]
A little update:

Someone on the MariaDB side is explaining further why it should be fixed.
> The MySQL 5.7 documentation actually says the exact opposite:
> "Consequently, --ssl and --ssl-verify-server-cert are deprecated, and are removed in MySQL 8.0."
> https://dev.mysql.com/doc/refman/5.7/en/encrypted-connections.html
> So this should probably be adjusted in order to maintain compatibility.

In the meantime I will be hopping onto this and giving a PR soon.

**Comment by aarondl** [comment]
@tooolbox What he's doing there is correcting Sergei indicating his interpretation of the documentation is incorrect (this echoes my comment in this issue above), effectively saying: MariaDB needs to fix this.

See my above post for reasoning/sources.

No PR that changes `ssl-mode` out for `ssl` will be accepted. Though I assume your PR is more targeting your previous idea:

> It might also be worth reviewing how to make this value more pass-through for MySQL, similar to how the Postgres driver is, but I don't think it's unreal to somehow support passing a blank value via config, and then not writing this flag if the value is blank.

I'm indifferent to a PR that simply doesn't provide a value if nothing is specified in the config. Keep backwards compatibility in mind.

**Comment by tooolbox** [comment]
...Well, that's a noisy bunch of references.

Yes, I got what you're saying.  No, I wouldn't propose changing back to `ssl` after the top of this thread and #117.

I think I would up at something workable.  I suppose it also opens the door for MySQL pre-5.6.
