### ISSUE TITLE
OrderBy descending

### ISSUE THREAD

**Issue by concreted** [volatiletech/sqlboiler#274]
I don't see a way to set the `OrderBy` query mod to return results in descending order. Is this possible with query mods currently, or is it necessary to write a custom query for this? 

My understanding is that custom queries with the `SQL` query mod overrides all other mods, so it wouldn't be possible to do something like:
```
clauses := []QueryMod{
		Where("user_id=?", id),
		SQL("order by created_at desc"),
	}
```
(I tried that and got `pq: syntax error at or near "order"` as expected)

**Comment by saulortega** [comment]
Just `OrderBy("id DESC")`

**Comment by concreted** [comment]
@saulortega confirmed that works, thanks! will make a pr to put this in the readme.
