### ISSUE TITLE
Exposing queries package internals

### ISSUE THREAD

**Issue by edoshor** [volatiletech/sqlboiler#276]
We use sqlboiler in almost all of our go apps and we love it. Thanks.

Quite often we reach out to Raw queries. 
Be it DB specific stuff or really complex queries we still use the library for that (binding, etc...).

It would make our lives a lot easier if the logic in `query_builders.go` would have public access.
So when we build our sql strings we could utilize the query mods system (we reuse that across the app) to generate sql snippets.

**Comment by aarondl** [comment]
@edoshor I'm glad you guys are enjoying it!

It doesn't cost us anything in any way to expose those so I'll go ahead and do this in v3.

**Comment by edoshor** [comment]
Thanks a lot. Looking for v3 then (^_^)

**Comment by aarondl** [comment]
Hey @edoshor, was looking at this briefly and was trying to understand which functions appeal in the queries module. You mentioned the query mods system but that's already completely exported. Anything specific you can give me?

**Comment by edoshor** [comment]
The main query building function [buildQuery](https://github.com/volatiletech/sqlboiler/blob/master/queries/query_builders.go#L18) was all we needed.

**Comment by aarondl** [comment]
Done.
