### ISSUE TITLE
Randomization interface

### ISSUE THREAD

**Issue by aarondl** [volatiletech/sqlboiler#284]
Randomize should have an interface so we can create types that randomize themselves, otherwise we'll never be able to keep up in randomize.go

**Comment by aarondl** [comment]
Done. See changelog and randomize package.

**Comment by saulortega** [comment]
Hi, @aarondl 

It would be good if the Randomizer interface is independent of sqlboiler, that a third-party library does not need to import `"github.com/volatiletech/sqlboiler/randomize"`.

I think that `Randomize(s * Seed, fieldType string, shouldBeNull bool)` is unnecessary. Simply `Randomize()`.

The seed can be generated by the library. The nullity can also be decided by the library. And I do not understand very well why you use fieldType, but surely it can also be ommited.

**Comment by aarondl** [comment]
@saulortega The more I thought about this. The more solution number 2 makes sense. Anything that's providing some types can re-implement this trivially. In Rob Pike's words: A little duplication is better than a little dependency. I vote we go for this approach, what do you think? This would allow the interface to use only Go types and not require a dependency on anything more than stdlib.

**Comment by aarondl** [comment]
FWIW the new interface would look like:

```go
type Randomizer interface {
    Randomize(seed *int64, fieldType string, shouldBeNull bool)
}
```

**Comment by saulortega** [comment]
That looks better than it is now, and it is the best of the three options. :+1:

**Comment by aarondl** [comment]
@saulortega Since you seem to be active, I'll pose one more question. I actually thought we could fix the problem completely by passing the `NextInt()` function around. So it actually becomes:

```
type Randomizer interface {
    Randomize(nextInt func() int64, fieldType string, shouldBeNull bool)
}
```

This is better in that nobody needs to implement things using atomic, and it also eliminates the dependency. What do you think?

**Comment by saulortega** [comment]
Yes, that is still a good option. :+1:

**Comment by aarondl** [comment]
Change done in 84770d2. It's not in any rc just yet. Keep in mind I also dropped gopkg.in from the null package with this commit.
