### ISSUE TITLE
BINARY type causes test failures

### ISSUE THREAD

**Issue by dterei** [volatiletech/sqlboiler#287]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

2.6.0

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

`sqlboiler --whitelist forever_ids mysql;`

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

```
=== RUN   TestDelete/ForeverIds     
=== PAUSE TestDelete/ForeverIds
=== CONT  TestDelete/ForeverIds          
--- FAIL: TestDelete (0.00s)                               
    --- FAIL: TestDelete/ForeverIds (0.01s)            
        forever_ids_test.go:51: want zero records, got: 1
```

Many other tests fail too.

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

```
CREATE TABLE forever_ids (
  fid BINARY(16) NOT NULL,
  cdm_cluster_id BINARY(16) NOT NULL,
  internal_id VARCHAR(128) NOT NULL,
  object_type VARCHAR(24) NOT NULL,
  PRIMARY KEY (fid),
  UNIQUE KEY original_ids (cdm_cluster_id, internal_id)
);
```

Only the `fid` column is relevant here. If I change the type of `fid` to `VARBINARY`, `CHAR` or `VARCHAR` then it works fine.

### Further information. What did you do, what did you expect?

Many tests in the test-suite fail becuase of the issues of equality with the `BINARY` type and the right-pading with `\0` when you insert a value smaller than 16. If I change the code generated to do things like this:

```
if len(o.Fid) < 16 {
  newfid := make([]byte, 16)
  copy(newfix, o.Fid)
  o.Fid = newfid
}
```

Then the test-suite will pass.

Arguably the generated code is correct as this is the expected (if ugly) behaviour of SQL/MySQL with BINARY. However, the test-suite should generate valid test cases, either by generating random `fid` values of the full length always.

Or, if binary is the wrong approach (we are storing UUIDs), then some guidance and updates to the docs would be helpful. (e..g, use `CHAR` with a 1-byte character encoding to get better semantics but storage eficiency of `BINARY`).

**Comment by dterei** [comment]
Yeah, agreed, Postgres has had a UUID type for years and in the recent MySQL-8 release rather than finally add a UUID type, they just added better functions to convert a strings representation of a UUID to a BINARY(16).

Am I correct in understanding though that this issue is just a problem for the test code? The model code itself is correct and as long as our application always uses a completely filled byte slice of length 16 we shouldn't have any issues? It's annoying the tests don't pass (and no easy solution), but can live with that if production code is fine.

**Comment by aarondl** [comment]
That's my understanding as well. The failure here is simply that our randomization is not generating full-widths which in mysql fails to compare correctly. I don't think you'll have any problems normally since we avoid this kind of reflection stuff outside the tests. Might want to do a quick test yourself just to see if you can create a record, and select one back out. If that works, I don't foresee any other problems.

**Comment by aarondl** [comment]
Hey there @dterei.

I've made a pass at randomization in sqlboiler for v3. Now any type can implement sqlboiler's randomize interface to be able to generate proper random values. This means if we were using a custom MySQLUUID type that knew how to randomize itself correctly it would work. Now, where could you put that type? We could put this type in a subpackage for mysql under the `types` package in sqlboiler and the driver could use it directly. If we don't feel like putting it into sqlboiler itself, there's a new mechanism that allows you to resolve a type at generation time according to some simple matching rules in the config: https://github.com/volatiletech/sqlboiler/tree/v3#types

Anyway, I think that this resolves this issue. But I wanted to check with you on what you think about the solutions presented.

**Comment by dterei** [comment]
@aarondl Awesome! This sounds like the right approach to, but I don't really understand when the code-generator decides to use this MySQLUUID type.

If we go with the approach you first suggest of the MySQL SQLBoiler driver using the MySQLUUID type directly, how would the driver decides when to use it? Would it just assume that all `binary(16)` columns should use it? This seems too strong to me.

If the second approach of using the `types` package and controlling the code-generation, can I specify a match like:

```
[types.match]
    type = "binary"
    length = 16

[types.replace]
    type = "MySQLUUID"
```

?

One other idea here, if the column type is the only match criteria, then I think we'd instead want to do something like have a type `binary` that captured the length of the binary too. If then the binary was shorter than say 256, we use a randomization that generates a full-length random value, otherwise, just fall-back to 1-byte randomization.

**Comment by dterei** [comment]
Yep! I think the match solution works great, for my use case I'd do exactly as you suggest and match on the type and the name of the colum. Thanks for a solution! Excited for it.

**Comment by aarondl** [comment]
Ok. Since this is done in the v3 branch I'm going to close this issue to keep the issues clean.
