### ISSUE TITLE
Caching and SetArgs method for queries

### ISSUE THREAD

**Issue by aarondl** [volatiletech/sqlboiler#289]
Currently when we create an sql query, we do a bunch of string manip. But it's conflated with the database pointer itself as well as it's arguments.

It would be nice if once a query was created it created a prepared statement that could be re-executed with different arguments, this would be MUCH faster and allow for more performant querying in general.

**Comment by aarondl** [comment]
Turns out this is a non-starter. After benchmarking some, it's almost completely useless to use prepared statements for performance.

**Comment by dbroeglin** [comment]
Hi!
I did a bit of benchmarking on my side. The results look like this:
```
pkg: github.com/picobank/instruments-sqlboiler
BenchmarkFindInstrument_SQLBoiler-8   	    5000	    280773 ns/op
BenchmarkFindInstrument_PGXStdlib-8   	   10000	    108946 ns/op
BenchmarkFindInstrument_PGXNative-8   	   20000	     86386 ns/op
```
The reason for the slower SQLBoiler bench is that `FindFoo(db, id)` does a simple sql/database `Query()` call and this is implemented in PGX as a "Prepare" followed by a "Query", hence a double round trip. The second and last examples are using PGX with the sql/database interface or with PGX's own interface. They are faster because then the prepare is done only once for the whole benchmark.

Am I missing something? I did not yet test with another Go driver for PostgreSQL. Maybe the situation is different with those ?

**Comment by aarondl** [comment]
The typically expected driver for postgres (at least what we use/test with) is the lib/pq one. If memory serves the main difference between pgx and lib/pq is that instead of doing a prepare+query pgx can do its own interpolation of arguments hence avoiding the second trip to the database (and also potentially being wrong in its interpolation). 

Given that sqlboiler works with both of these drivers I'm curious what you're expecting. We can't really commit to one or the other driver since people should continue to be able to use both.

Having said this I admit that I'm on my phone and responding with a lot of missing information. I'm not sure if we could code up a fast path if pgx is being used. Are there other reasons for the slowdown? It might be interesting to bench with lib/pq for a comparison as well.

**Comment by dbroeglin** [comment]
I finally got some time and did a quick bench with `lib/pq`, I also added a bench for a simple `QueryRow`, vs `stmt.QueryRow` :

```
BenchmarkFindInstrument_SQLBoiler_PGX-8        	    5000	    270400 ns/op	    5694 B/op	      88 allocs/op
BenchmarkFindInstrument_SQLBoiler_PQ-8         	    5000	    265532 ns/op	    3555 B/op	      72 allocs/op
BenchmarkFindInstrument_PGXStdlib_Query-8      	    5000	    258087 ns/op	    4447 B/op	      81 allocs/op
BenchmarkFindInstrument_PQStdlib_Query-8       	    5000	    245292 ns/op	    2520 B/op	      66 allocs/op
BenchmarkFindInstrument_PGXStdlib_Prepared-8   	   10000	    101748 ns/op	    2202 B/op	      51 allocs/op
BenchmarkFindInstrument_PQStdlib_Prepared-8    	   20000	     95950 ns/op	    1317 B/op	      43 allocs/op
BenchmarkFindInstrument_PGXNative_Prepared-8   	   20000	     89220 ns/op	     537 B/op	      11 allocs/op
```

Looking at the code PGX and PQ do roughly the same in their query methods. They both can do a 1 round trip query if there are no argument to the query and do it in 2 round trips with an anonymous prepare if there are. 

I'm not sure about what you said about interpolation being done locally by PGX, as it is the primary cause for this longer time is the double round trip.

Does this make sense to you ? If so, it might be useful to use prepared statements, at least for queries like `FindFoo(db, id)` where the statement is static. What do you think ?
