### ISSUE TITLE
Unable to generate direct reference to associations related through join tables

### ISSUE THREAD

**Issue by Peh-QinCheng** [volatiletech/sqlboiler#302]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
`v2.6.0`

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? 
`sqlboiler postgres`

### Problem
I have a migration file creating a join table: 

```
CREATE TABLE products_groups (
  product_id INT NOT NULL,
  group_id INT NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  FOREIGN KEY(product_id) REFERENCES products(id),
  FOREIGN KEY(group_id) REFERENCES groups(id),
  PRIMARY KEY(product_id, group_id)
);
```

However, the generated `product.go` does not generate a direct reference to `groups`. This was the result:
```
type productR struct {
	OrderItems     OrderItemSlice
	ProductsGroups ProductsGroupSlice
}
```
I was expecting something similar to what was shown in the README, 
```
type pilotR struct {
  Licenses  LicenseSlice
  Languages LanguageSlice
  Jets      JetSlice
}
```
where relationship to languages was generated instead of the join table.

Am I doing anything wrongly?

**Comment by aarondl** [comment]
This is expected behavior. You only get the straight through behavior if the only columns are the primary/foreign key. In other words delete your timestamps and it should work :)

**Comment by nii236** [comment]
Is there a reason we can't have additional columns in join tables? It would be helpful when joins need to be annotated for one reason or another.

**Comment by aarondl** [comment]
You can, but then there needs to be a way to access those columns. That's why we don't skip the model for the join table in that case. There needs to be a model available so you can fetch records and do things with it.

I suppose the main difference and the request is that if you have a `videos <-video_tags-> tags` relationship that you still get a `Tags` helper on the `Video` model and vice versa? I'm opened to any kind of proposals if you wanted to make one.

**Comment by nii236** [comment]
A simple way will be to provide generate both the join table model and the many-many model:

```
videos.Tags(...)
videos.VideosTags(...)

tags.VideosTags(...)
tags.Videos(...)
```
