### ISSUE TITLE
HasCreatedAt, HasUpdatedAt, HasDeletedAt in template

### ISSUE THREAD

**Issue by saulortega** [volatiletech/sqlboiler#304]
Because the created_at, updated_at and deleted_at columns can be considered "special" columns, they are useful for some custom template actions.

So, it would be good if there were variables that indicate if these columns exist. That way, I can create templates like:

```
{{ if .HasDeletedAt }}
o.DeletedAt = null.NewTime(time.Now(), true)
o.Update(exec, "deleted_at")
{{ else }}
o.Delete(exec)
{{ end }}
```

That, considering the limitations of the template logic: I can not redefine a variable (unless I use a function)

**Comment by aarondl** [comment]
https://github.com/volatiletech/sqlboiler/blob/d7d6aa4c3ab274f606830afeabde5709aa566c35/boilingcore/templates.go#L273
https://github.com/volatiletech/sqlboiler/blob/d7d6aa4c3ab274f606830afeabde5709aa566c35/strmangle/sets.go#L3-L4

Example usage:

```handlebars
{{$hasDeletedAt := setInclude "deleted_at" (columnNames .Table.Columns)}}
```

I think this should work for your use case. Re-open if insufficient.

**Comment by saulortega** [comment]
Nice. :)

Thank you.
