### ISSUE TITLE
mssql: `xml` column type => "char cannot be converted to money" & no relationship entries found

### ISSUE THREAD

**Issue by nadilas** [volatiletech/sqlboiler#319]
@aarondl Continueing here:

Using the schema described in: https://github.com/volatiletech/sqlboiler/issues/180#issuecomment-399787769 I had 2 different cases:
1. So after some investigations, the problem only occurs if I'm using one of my tables with an `xml` column. 
```
models: failed to assign all query results to TableAliasName slice: mssql: Cannot convert a char value to money. The char value has incorrect syntax.
```

2. `LoadXXXXX` methods find 0 entries. I'd expect to see the arguments in the `query` filled via `NewQuery` but they are not present:

Args:
![input](https://user-images.githubusercontent.com/5324856/41868067-445ce7f0-78b5-11e8-9de4-702f75e4272a.png)

Query:
![before_query](https://user-images.githubusercontent.com/5324856/41868307-f9dae7ee-78b5-11e8-9331-c4b21e974d1f.png)

**Comment by nadilas** [comment]
I’d concentrate on the second topic, because querieing the table directly without relationships (even with xml column) works. It is interpreted as string. 

The second issue from my point of view is more critical, since no errors are shown “only” no relationship records are found/returned.

**Comment by nadilas** [comment]
@aarondl could you look into that?

**Comment by aarondl** [comment]
Won't be able to take a look until next week. Sorry about that. :(

If you wanted to try to dig in I can try and guide you in the right direction.

**Comment by nadilas** [comment]
Sure. Where do I start? :)

**Comment by aarondl** [comment]
So the very first thing is to experiment with the Xml column type.

mssql: Cannot convert a char value to money. The char value has incorrect syntax

This is very odd. Unless we have a bug somewhere and that may be true this is the mssql driver failing to Scan. So a minimal reproduce of this wouldn't even involve sqlboiler. I don't see the money column anywhere in the other schema. But essentially if you make a string. Then you try to use the normal database/sql Scan method to scan that money column into it, what happens?

Also it'd probably be useful to find where that error is coming from in the mssql driver and see what cases cause it to happen (it's probably a generic error so you'll have to search for parts of it not the whole thing).

**Comment by nadilas** [comment]
Bug hunter down... ;-) changing the driver to mssql solved it. The problem only presents itself using the sqlserver driver.

**Comment by aarondl** [comment]
How bizarre. I wonder how people deal with this when using sqlserver

**Comment by whatarule** [comment]
I've solved the same problem by changing the "drivername" from "sqlserver" to "mssql" on sql.Open. Thank you for your earlier investigations.

https://godoc.org/database/sql#Open

**Comment by nadilas** [comment]
Just as a reference:
https://github.com/denisenkom/go-mssqldb/pull/638

would add support for elastic APM and still handle this issue.

```go
apmsql.Register(driverName, mssqldb.DriverInstanceMssql())
db, err = apmsql.Open(driverName, u.String())
```
