### ISSUE TITLE
Support non-snake_case conventions

### ISSUE THREAD

**Issue by shousper** [volatiletech/sqlboiler#334]
It'd be great to support other naming conventions other than snake case for existing databases. I've started a [crude PR](https://github.com/volatiletech/sqlboiler/pull/332) to expose some internals that allow extension and get the ball rolling, but there are definitely better approaches.

**Comment by aarondl** [comment]
Probably going to leave this out in favor of aliasing.

There's lots of documentation out there that supports using `snake_case` and as a comp sci student all the database courses and textbooks I saw adhere to this naming convention making it close to a "standard" in my mind. For the off-cases where it wasn't used or can't be used, aliases will have to be the answer for now unless there's compelling documentation that opposes the idea of `snake_case` being an across-the-board standard (mssql excluded of course).

**Comment by shousper** [comment]
> There's lots of documentation out there that supports using snake_case

Would you mind linking some? I genuinely couldn't find a "majority opinion" pushing for a specific convention. Personally I'm pro `snake_case` because of typical SQL case-insensitivity of DBMS metadata and the fact many off-the-shelf libraries/frameworks use it.

> textbooks I saw adhere to this naming convention making it close to a "standard" in my mind

Academia is very idealistic compared to how an industrial or commercial business is run 😄 

> compelling documentation that opposes the idea

I don't think you'll find any, but see my comment above about the commercial world 😉 

Thanks again, looking forward to using v3!

**Comment by aarondl** [comment]
First page of results from google:

snake_case supporters (50%):
https://www.sqlstyle.guide/
https://launchbylunch.com/posts/2014/Feb/16/sql-naming-conventions/#naming-conventions
https://www.xaprb.com/blog/2008/10/26/the-power-of-a-good-sql-naming-convention/
http://leshazlewood.com/software-engineering/sql-style-guide/
http://paul-m-jones.com/archives/6188

TitleCase supporters (30%):
https://stackoverflow.com/questions/7662/database-table-and-column-naming-conventions
https://www.codeproject.com/Articles/1065295/SQL-Server-Table-and-Column-Naming-Conventions
http://www.vertabelo.com/blog/technical-articles/an-unemotional-logical-look-at-sql-server-naming-conventions

mixed case and prefixes (10%):
https://www.c-sharpcorner.com/UploadFile/f0b2ed/what-is-naming-convention/

do whatever you want (10%): 
https://solutioncenter.apexsql.com/rules-of-sql-formatting-sql-naming-conventions-and-capitalization-rules/

Note that all the non-snake case results are talking about MSSQL or dealing with C#. Everything else is snake case. This obviously isn't enough to prove the existence of an unwritten "standard", but maybe you'll at least be able to see where my viewpoint comes from.

v3 was released today :) Hope it works well for you!
