### ISSUE TITLE
Incompatibility v3.0.0-rc9 with null v8.0.0

### ISSUE THREAD

**Issue by groovili** [volatiletech/sqlboiler#336]
Hi!
I'm using **sqlboiler v3.0.0-rc9**, after `dep ensure` problem appeared. Sceenshot below.
![null_error](https://user-images.githubusercontent.com/7287535/42642190-f6328600-85fe-11e8-9ef1-e85c2b54ec50.png)
I think that **problem in update of volatiletech/null**, because when I've manually changed depenencies in generated models to null.v7 error didn't appear anymore.
But it's not a solution, because latest version of sqlboiler is dependent from null v8.0.0.
Hope you can help.
Regards,
Maxim Ivanov

**Comment by aarondl** [comment]
Prior to the head of the v3 branch (unreleased and untagged) you should not be using v8 of the null package.

You should also be using gopkg.in/volatiletech/null.v7 for anything before that (this includes rc9).

Basically if you're using rc9 and earlier, use null.v7 from gopkg.in

If you're using latest v3 branch sqlboiler (there are unreleased changes on this branch, ensure that you are actually using the tag, not the branch) then you will have to use the null package normally with the v8.0.0 tag.

Check to make sure things follow the above, and if there is still a problem let me know. I don't believe there's an issue at this time, you'll have to show me the current state of your GOPATH for me to be sure. What commit of the null package is vendored, what commit is sqlboiler at etc.

**Comment by groovili** [comment]
@aarondl Thanks a lot for the quick answer, usage of v3 branch resolved the problem.
