### ISSUE TITLE
[Feature Request] Allow connection without password

### ISSUE THREAD

**Issue by shousper** [volatiletech/sqlboiler#337]
For local development and CI we don't use a password for our database connections. Could this requirement could be lifted from sqlboiler?

Alternatively, supplying the DSN instead of individual connection string components could be good 👍 

Thoughts? :)

**Comment by aarondl** [comment]
I would consider having a DSN parameter that when present took precedence over the piecemeal ones. Later we could maybe deprecate the individual args if it was desirable. I'm not really sure why they ended up separate, hold over from rails world I guess.

**Comment by aarondl** [comment]
See #351 comments for why DSN won't be added as a feature.

PR #347 fixes this issue and will be merged shortly.
