### ISSUE TITLE
Cannot create db

### ISSUE THREAD

**Issue by alishaagupta** [volatiletech/sqlboiler#345]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
createdb: could not connect to database template1: FATAL:  Peer authentication failed for user "boiler"

**Comment by aarondl** [comment]
This simply means you don't have postgres correctly configured to connect with the credentials you're providing in `sqlboiler.toml`. `createdb` is a program we call out to to make a copy of the database for running tests and it's not getting the right credentials. Also next time, please include more details in your bug report.
