### ISSUE TITLE
[Feature Request] Named parameters

### ISSUE THREAD

**Issue by shousper** [volatiletech/sqlboiler#346]
I was hunting for this feature in the driver, but it doesn't look like that's [where everyone feel it should live](https://github.com/go-sql-driver/mysql/issues/561#issuecomment-337441108). So while MySQL is unlikely to gain support soon, PostgreSQL (EDIT: nope) ~has [one client](https://github.com/jackc/pgx/issues/351) playing ball, but the~ [main client](https://github.com/lib/pq/issues/534) seems disinterested. I don't know about other drivers, we're stuck on MySQL for the time being.

Are named parameters something `sqlboiler` would consider implementing?

**Comment by aarondl** [comment]
Not really no. This is additional complexity that we simply don't need. Also it's not clear to me (as it doesn't seem clear to everyone) where it should live and especially before that decision is made I would not venture to implement anything for fear of having to rip out our implementation for the one that lands in drivers or database/sql which may have different syntax which causes breaking changes etc.

**Comment by shousper** [comment]
Fair enough 👍
