### ISSUE TITLE
models undefined

### ISSUE THREAD

**Issue by alishaagupta** [volatiletech/sqlboiler#348]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v2.7.3

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
go generate

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

models.DatabaseName(db)

models is not defined

**Comment by aarondl** [comment]
Hey there. Hard to tell from the bug report what's going on. `go generate` cannot possibly produce the error `models is not defined` as far as I can tell?

It sounds like you did a `go generate` and then attempted to write a program with `models.DatabaseName(db)`, there's no method named that unless that's one of your tables, and it might have a different name. You should also double check that you're importing the correct models package in your Go program.
