### ISSUE TITLE
Inspecting errors

### ISSUE THREAD

**Issue by diraven** [volatiletech/sqlboiler#353]
According to https://github.com/volatiletech/sqlboiler/blob/master/boil/errors.go error is hidden behind unexported boilErr struct type. How does one extract the underlying error for inspection, such as to see more details (code etc.) via `.(*pg.Error)` postgres (or any other for that matter) driver provides?

PS: it's the same for v3 branch.

Thank you.

**Comment by aarondl** [comment]
`WrapErr` is only used when `panic` occurs. Normal errors use the github.com/pkg/errors package which has a `Cause` method you can use to extract the underlying error.

**Comment by diraven** [comment]
Thank you.
