### ISSUE TITLE
Why volatiletech/sqlboiler/types does not use volatiletech/null package ?

### ISSUE THREAD

**Issue by datalinkE** [volatiletech/sqlboiler#354]
### What version of SQLBoiler are you using (`sqlboiler --version`)? 2.7.3, but this looks the same in 3.x

Not realy an issue, just a question. I see https://github.com/volatiletech/sqlboiler/blob/master/types/hstore.go#L29 :
`type HStore map[string]sql.NullString`
Why not null.String here instead?
MarshalJSON on generated structures looks bad due to default serialization of sql.NullString.
Thanks.

**Comment by aarondl** [comment]
They're just slightly modified copies of the `lib/pq` types. This looks like it just got missed.
