### ISSUE TITLE
`go test models` With database inside Docker container

### ISSUE THREAD

**Issue by andradei** [volatiletech/sqlboiler#362]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v3.0.0-rc10 (although there isn't a release candidate 10 yet, the code displays rc10, but it is v3.0.0-rc9 in reality)

### Further information. What did you do, what did you expect?

- Running cockroachdb in a Docker container
- Using the latest github.com/glerchundi/sqlboiler-crdb driver

`go test models` fails with message:

```
failed running: cockroach [sql --insecure --execute DROP DATABASE IF EXISTS tzlqfapiafxfzhlpecjdooywuqeenekhyugfezjw CASCADE]


Unable to execute setup: exec: "cockroach": executable file not found in $PATH
FAIL    github.com/MyUser/my_project/cmd/models     0.018s
```

Is there a different way to drop the database when using Docker containers?

**Comment by aarondl** [comment]
Not really. The tests assume you have the client tools installed and they can reach the DB. You can always make a shim that calls docker passing arguments through in `~/bin` to work around this I think.

**Comment by andradei** [comment]
That is a great solution. Thank you.
