### ISSUE TITLE
Bulk Insert

### ISSUE THREAD

**Issue by taxio** [volatiletech/sqlboiler#364]
Is there support for Bulk Insert? I cannot find this function in this project... : (
Is there plans to add it?

**Comment by aarondl** [comment]
It doesn't exist right now in sqlboiler. No plans to add currently. The `lib/pq` bulk insertion API is really weird and so I decided just not to bother for the time being. Use the driver directly to get the job done.

**Comment by ORESoftware** [comment]
any word on this? thanks

**Comment by ORESoftware** [comment]
bulk insert into postgres at least has a simple api:

```sql
INSERT INTO products (product_no, name, price) VALUES
    (1, 'Cheese', 9.99),
    (2, 'Bread', 1.99),
    (3, 'Milk', 2.99);
```

I assume other relational db engines have very similar syntax, so I don't see why all pg drivers wouldn't support this, seems worth implementing to me.
