### ISSUE TITLE
shows cant assign type string to a  null.string variable

### ISSUE THREAD

**Issue by vevsatechnologies** [volatiletech/sqlboiler#365]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v2.5.0

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
data insertion query is producing the issue

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
postgres

**Comment by aarondl** [comment]
The issues you've been opening are of really poor quality. I simply can't help with this amount of information. Please include more relevant details like what your "shows" table looks like. Or what your data insertion query looks like. Or even the actual compiler error message.
