### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alishaagupta** [volatiletech/sqlboiler#370]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v2.5.0

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
Data insertion query produced the error .

	for i := 0; i <= 99; i++ {

		var p models.HistoricDatum

		// p1.ExchangeName =
		p.Globaltradeid = data.Result[i].ID
		p.Quantity = data.Result[i].Quantity
		p.Price = data.Result[i].Price
		p.Total = data.Result[i].Total
		p.FillType = data.Result[i].Filltype
		p.OrderType = data.Result[i].Ordertype
		p.CreatedOn = data.Result[i].Timestamp

		err := p.Insert(db)

		panic(err.Error())
	}

HistoricDatum is the table data has to be inserted in. Only first row is inserted by this query.

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
create table historic_data (
id serial primary key not null ,
exchange_name varchar (50),
globaltradeid numeric,
tradeid numeric,
created_on varchar (100),
quantity  NUMERIC,
price numeric, 
total numeric,
fill_type varchar (20),
order_type varchar (20)

);

### Further information. What did you do, what did you expect?
I am fetching json data from an api and storing it in a db . USing the insertion query on the db shows this error. Only frst row is being inserted . I am using a for loop for the whole data, but it shows the error.

**Comment by aarondl** [comment]
I'd like to note that v2.5.0 is quite old by the way. In terms of v2 releases there's all the way up to 2.7.4 and v3.0.0 is out as well.

Which line here is creating the problem? The last line in the for loop, the panic you're seeing will always create this error message if the insert was successful.

On success `err` is `nil`, so when you try to call `Error()` on that, it will fail with the error message you're seeing. You must have an if statement to guard against this:

```go
for i := 0; i <= 99; i++ {

	var p models.HistoricDatum

	// p1.ExchangeName =
	p.Globaltradeid = data.Result[i].ID
	p.Quantity = data.Result[i].Quantity
	p.Price = data.Result[i].Price
	p.Total = data.Result[i].Total
	p.FillType = data.Result[i].Filltype
	p.OrderType = data.Result[i].Ordertype
	p.CreatedOn = data.Result[i].Timestamp

	err := p.Insert(db)

	if err != nil {
		panic(err.Error())
	}
}
```

**Comment by aarondl** [comment]
Stale.
