### ISSUE TITLE
Missing BindG method

### ISSUE THREAD

**Issue by jojomi** [volatiletech/sqlboiler#373]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v3.0.0

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

`sqlboiler mysql --add-global-variants --no-hooks --no-tests`

### Further information. What did you do, what did you expect?

I was porting v2 code like this:

```
err = models.AnniversariesG(
        qm.Select("id"),
        ...
    ).Bind(&anniversaries)
```

and expecting this to work in v3:

```
err = models.Anniversaries(
        qm.Select("id"),
        ...
    ).BindG(context.Background(), &anniversaries)
```
But the `BindG` method is not available.

Quick fix:

```
err = models.Anniversaries(
        qm.Select("id"),
        ...
    ).Bind(context.Background(), boil.GetDB(), &anniversaries)
```

This has been discussed with @aarondl in the slack channel.

**Comment by aarondl** [comment]
Re-added this function.
