### ISSUE TITLE
Hooks example

### ISSUE THREAD

**Issue by Dexus** [volatiletech/sqlboiler#377]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v3 last/master

Can you provide examples of how to use the hooks correctly?
I have a MySQL DB and would like to use binary IDs similar to the uuid. However, there is currently no real way to generate this automatically... so I think the hooks are the right choice. Or how can I do it correctly?

**Comment by aarondl** [comment]
Hooks are the only hope you have of creating an ID client-side (Go-code side).

All you do is define a function, and give it to `BeforeInsert`. Generate your ID there, shove it in the column. Should work. If not re-open. If more questions, just leave them on the closed issue, I'll continue to respond.

https://github.com/volatiletech/sqlboiler/#hooks
