### ISSUE TITLE
MSSQL driver configuration does not handle DB instances correctly

### ISSUE THREAD

**Issue by nekrondev** [volatiletech/sqlboiler#379]
If you are using a DB instance instead of a regular "host:port" configuration SQL boilers MSSQLBuilQueryString() function will not format the instance string correctly. This will result into a connection error.

Example:
``` yaml
mssql:
  dbname: mydb
  host: localhost/SQLEXPRESS
  port: 1433
  user: sa
  pass: verysecret
  sslmode: disable
  schema: dbo
```
The config example will use the SQLEXPRESS instance on localhost. As you will set "localhost/SQLEXPRESS" as the host string the backslash will be URL encoded as %2C.

The connection string will be formatted as
```
sqlserver://sa:verysecret@localhost%2CSQLEXPRESS:1433?database=mydb&encrypt=disable
```

You should fix this by checking if the host attribute contains an instance and remove the host string, but set a path instead (this is what the MSSQL driver docs recommend).

``` go
// MSSQLBuildQueryString builds a query string for MSSQL.
func MSSQLBuildQueryString(user, pass, dbname, host string, port int, sslmode string) string {
	query := url.Values{}
	query.Add("database", dbname)
	query.Add("encrypt", sslmode)

	u := &url.URL{
		Scheme: "sqlserver",
		User:   url.UserPassword(user, pass),
		Host:   fmt.Sprintf("%s:%d", host, port),
		// Path:  instance, // if connecting to an instance instead of a port
		RawQuery: query.Encode(),
	}

        // check if DB instance backslash is found
	if strings.Contains(host, "/") {
		u.Path = host
		u.Host = ""
	}

	return u.String()
}
```

**Comment by aarondl** [comment]
Thanks for raising the issue. You could have submitted a PR with this code, would have accepted as is. Fix is in master.
