### ISSUE TITLE
Decimal library doesn't compile for go v1.9

### ISSUE THREAD

**Issue by grodriguez85** [volatiletech/sqlboiler#381]
I'm trying to migrate to v3 but the new decimal library used isn't compatible in go v1.9.

This is the [issue](github.com/ericlagergren/decimal/issues/86) on ericlagergren repo.

Maybe github.com/shopspring/decimal discussed on issue [162](github.com/volatiletech/sqlboiler/issues/162) isn't a bad idea after all.

**Comment by aarondl** [comment]
Unfortunately Go 1.9 isn't supported anymore now that Go 1.11 is out. It will be up to individuals to solve this themselves. You can use the new type configuration in v3 to change out the decimal type yourself if you so choose. Though the generated tests will likely fail. Hopefully this is okay for you.

https://golang.org/doc/devel/release.html

> Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including critical security problems, in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on).
