### ISSUE TITLE
Eager loading for nullable relations

### ISSUE THREAD

**Issue by mickeyreiss** [volatiletech/sqlboiler#384]
We're using nullable relations in our MySQL schema. It seems that sqlboiler is generating the incorrect queries when we eagerly load models from this relation.

I also noticed that this use case is not currently covered in [eager_load_test.go](https://github.com/volatiletech/sqlboiler/blob/master/queries/eager_load_test.go).

The bad behavior we are seeing is that these loads unconditionally. The query that is executed is invalid SQL. (It looks like the `null.UInt64` struct is leaking into the query as `{1 true}`—I'm also curious if this _might_ be an injection attack vector as well.)

Here's the console output we're seeing with debug mode turned on:

```sql
SELECT * FROM `entities` WHERE `id` IN (?);
[{1 true}]
```

**Comment by aarondl** [comment]
You're absolutely right in that this use case (nullable relationships) is very poorly understood by the sqlboiler code. It's something we need to look at. This has been brought up in the past and if I'm honest I've been avoiding dealing with it: https://github.com/volatiletech/sqlboiler/pull/269 It's probably time to bite the bullet.

However, there's no injection possible if it's in a parameter (the `?` takes care of this) as far as I'm aware. The problem with injections is they can actually add/modify the query. Here, the worst you can do is change the value of the ID. Which in itself has probably very limited applications compared to being able to read an entire table/delete an entire database which is the surface area of most sql injection attacks.

**Comment by lunne** [comment]
Hi,
How did this pan out? I have encountered the same problem.

I have a relation that may or may not exist. It may be related to a project or it may not. When it is not related and the project_id is null it will crash.

The relation have to levels also:
qm.Load("Project")
qm.Load("Project.RelationTable")

**Comment by aarondl** [comment]
Have you tried the dev branch?

**Comment by lunne** [comment]
yes, i think so! i have checkout the branch and installed and switch my dep to branch = "master"
looks like dev and master have the same --version output but it should be set to dev. 

boiler/models.projectL.LoadProjectVersions(0x19f84e0, 0xc000026140, 0x19f9ea0, 0xc0001755c0, 0x0, 0x17ecae0, 0xc0002d51a0, 0x19f4900, 0xc00029a460, 0x0, ...)

It fails when it tries to load the nested eager-load  checking if R is nil on object that is nill.  obj.R == nil {} 

So i can modify the generated models file and under the Load function add 
```
Outer:
 for _, obj := range slice {
 if obj == nil { 
  continue
 }
```
and then in my code I check the relation
```
if relation.R != nil {
if relation.R.nestedRelation.R != nil {
// assing the value
}
}
```

Or this might be because I have not successfully switched to the dev branch? :) 



/Mathias

**Comment by aarondl** [comment]
```switch my dep to branch = "master"```

This seems wrong :) I just pushed another fix to the dev branch for nullable eager loads maybe that might also help you. Otherwise we might need a new bug report here. I'm running low on information for this issue.

**Comment by mickeyreiss** [comment]
@aarondl We are on v3.1.0 and don't seem to run into the issue any more. If I hear something more definitive either way, I'll post here.

**Comment by aarondl** [comment]
Hi @lunne. I tried again to reproduce your issue but failed on the dev branch by designing a schema based on what you've told me here.

At this point, I need you to put a lot more effort in to your bug report for me to fix this for you. What I need is a `issue.sql` file that when run creates a database that will demonstrate the problem with a query that you also provide. I don't want your database schema, just create 2-3 tables in that `.sql` file that have the same foreign key structure (no extra columns, just an `id`) as your tables in your real database. Then construct an sqlboiler query that causes the problem with that database schema.

What I tried looked like this:

```sql
drop table if exists tags;
drop table if exists videos;
drop table if exists users;

create table users (
  id serial not null primary key
);

create table videos (
  id serial not null primary key,
  user_id int,

  foreign key (user_id) references users (id)
);

create table tags (
  id serial not null primary key,
  video_id int,

  foreign key (video_id) references videos (id)
);

insert into users default values;

insert into videos (user_id) values (1);
insert into videos default values;

insert into tags (video_id) values (1);
insert into tags (video_id) values (1);

insert into tags (video_id) values (2);
insert into tags (video_id) values (2);
```

With a query that looks like:
```go
	users, err := models.Users(
		qm.Load(qm.Rels(models.UserRels.Videos, models.VideoRels.Tags)),
	).All(context.Background(), db)
```

If you could provide something similar to demonstrate your issue I can finally put this issue to rest :)

**Comment by lunne** [comment]
I understand, I will try to put together an sql and test it this week.

**Comment by lunne** [comment]
Hi, I have not been able to reproduce this yet... But it does not load the "ProjectVersion" relation as i believe it should? 

i've created this sql that should be kind of the same as the one having som problems:
```
SET FOREIGN_KEY_CHECKS = 0;
drop table if exists log_entries;
drop table if exists project_versions;
drop table if exists sub_projects;
drop table if exists projects;
SET FOREIGN_KEY_CHECKS = 1;

create table projects (
  id int not null primary key auto_increment
);
create table project_versions (
  id int not null primary key auto_increment,
  project_id int,

  foreign key (project_id) references projects (id)
);

create table sub_projects (
  id int not null primary key auto_increment,
  project_id int,
  foreign key (project_id) references project_versions (project_id)
);

create table log_entries (
  id int not null primary key auto_increment,
  project_id int,
  sub_project_id int,
  foreign key (project_id) references projects (id),
  foreign key (sub_project_id) references sub_projects (id)
);


insert into projects () values();
insert into projects () values();
insert into project_versions (project_id) values(1);
insert into project_versions (project_id) values(1);
insert into project_versions (project_id) values(2);
insert into sub_projects(project_id) values(1);
insert into log_entries() values();
insert into log_entries(project_id) values(1);
insert into log_entries(project_id, sub_project_id) values(1,1);
insert into log_entries(project_id) values(2);
insert into log_entries() values();
insert into log_entries() values();
insert into log_entries(project_id) values(2);
```
And i fetch the data by:
```
func pprint(data interface{}) string {
	buffer := new(bytes.Buffer)
	encoder := json.NewEncoder(buffer)
	encoder.SetIndent(empty, tab)

	err := encoder.Encode(data)
	if err != nil {
		return empty
	}
	return buffer.String()
}

func main() {
	var mods []qm.QueryMod = []qm.QueryMod{
		qm.Load("SubProject"),
		qm.Load("Project"),
		qm.Load("Project.ProjectVersions"),
	}

	entries, err := models.LogEntries(mods...).All(ctx, db)
	if err != nil {
		panic(err)
	}
	for _, row := range entries {
		fmt.Println("LogEntry:")
		fmt.Println(pprint(row))

		if row.R.Project != nil {
			fmt.Println("Project:")
			fmt.Println(pprint(row.R.Project))
			fmt.Println("Version:")
			pvs := row.R.Project.R.ProjectVersions
			fmt.Println(pprint(pvs))
			fmt.Println("SubProject:")
			fmt.Println(pprint(row.R.SubProject))
		}
		fmt.Println(".................................")
	}
}
```

versions of packages
```
PROJECT                             CONSTRAINT     VERSION        REVISION  LATEST   PKGS USED
github.com/go-sql-driver/mysql      ^1.4.1         v1.4.1         72cd26f   v1.4.1   1
github.com/jmoiron/sqlx             ^1.2.0         v1.2.0         d161d7a   v1.2.0   2
github.com/volatiletech/inflect     branch master  branch master  e720128   e720128  1
github.com/volatiletech/null        ^8.0.0         v8.0.0         0681ee3   v8.0.0   2
github.com/volatiletech/sqlboiler   branch dev     branch dev     5893f98   5893f98  8
```


This is from the failing project:
> ...boiler/models.projectL.LoadProjectVersions(0x1a4c620, 0xc0000b4040, 0x1a4dfe0, 0xc0001895f0, 0x0, 0x1836220, 0xc0003519a0, 0x1a48a40, 0xc0000a99a0, 0x0, ...)
>        ...boiler/models/projects.go:1280 +0x1a5
"obj" comes in as a nil:
![image](https://user-images.githubusercontent.com/7102889/50629574-6c8b4900-0f3d-11e9-9aed-863babd31606.png)


Im going to do some more debugging of this.

**Comment by lunne** [comment]
So I have cloned the tables and removed some unrelated data and now i have successfully re-created the problems.

It fails trying to load the the empty "ProjectSubContract". If at-least one ID exists it will work (this is a new bug) 

It will fail if the LogEntries has a row with no related project_id as the Project.ProjectVersions will try to load relations on a Project that is nil.

**SQL**
```
SET FOREIGN_KEY_CHECKS = 0;
drop table if exists log_entries;
drop table if exists project_versions;
drop table if exists project_sub_contracts;
drop table if exists projects;
SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE `projects` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `project_versions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `project_id` int(11) NOT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `project_number` (`project_id`),
  CONSTRAINT `project_versions_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`)
);

CREATE TABLE `project_sub_contracts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `project_id` int(11) NOT NULL DEFAULT '1',
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_projects_idx` (`project_id`),
  CONSTRAINT `fk_projects` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`)
);


CREATE TABLE `log_entries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `project_id` int(11) DEFAULT NULL,
  `project_sub_contract_id` int(11) DEFAULT NULL,
  `canceled_at` datetime DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `project_id` (`project_id`),
  KEY `log_entries_ibfk_5_idx` (`project_sub_contract_id`),
  CONSTRAINT `log_entries_ibfk_4` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`),
  CONSTRAINT `log_entries_ibfk_5` FOREIGN KEY (`project_sub_contract_id`) REFERENCES `project_sub_contracts` (`id`)
);

insert into projects () values ();
insert into project_versions (project_id) values (1);
INSERT INTO log_entries (`project_id`) VALUES (1);


insert into project_sub_contracts(project_id) values(1);  -- This will fail as it trys this query:  SELECT * FROM `project_sub_contracts` WHERE `id` IN ();
update log_entries set project_sub_contract_id = 1 where id = 1; -- this will fix the problem
INSERT INTO log_entries (`project_id`) VALUES (1); -- still will work as  the query will contain at least one ID
-- 

INSERT INTO log_entries () VALUES (); -- this will cause it to fail again as it tries to load ProjectVersions
```


**Packages:**
```
github.com/volatiletech/inflect     branch master  branch master  e720128   e720128  1
github.com/volatiletech/null        ^8.0.0         v8.0.0         0681ee3   v8.0.0   2
github.com/volatiletech/sqlboiler   branch dev     branch dev     5893f98   5893f98  8
```


**Boiler code:**
```
func pprint(data interface{}) string {
	buffer := new(bytes.Buffer)
	encoder := json.NewEncoder(buffer)
	encoder.SetIndent(empty, tab)

	err := encoder.Encode(data)
	if err != nil {
		return empty
	}
	return buffer.String()
}
func main() {
        var mods []qm.QueryMod = []qm.QueryMod{
		qm.Load("ProjectSubContract"),
		qm.Load("Project"),
		qm.Load("Project.ProjectVersions"),
	}

	entries, err := models.LogEntries(mods...).All(ctx, db)
	if err != nil {
		panic(err)
	}
	for _, row := range entries {
		fmt.Println("LogEntry:")
		fmt.Println(pprint(row))

		if row.R.Project != nil {
			fmt.Println("Project:")
			fmt.Println(pprint(row.R.Project))
			fmt.Println("Version:")
			pvs := row.R.Project.R.ProjectVersions
			fmt.Println(pprint(pvs))
			fmt.Println("SubProject:")
			fmt.Println(pprint(row.R.ProjectSubContract))
		}
		fmt.Println(".................................")
	}
}
```

**Comment by aarondl** [comment]
So, the trouble seemed to be fairly simple in the end.

The problem occurred here: 
https://github.com/volatiletech/sqlboiler/blob/4dea9a5f77e3ec6090ad455df3d408e47e077700/templates/09_relationship_to_many_eager.go.tpl#L32

When it iterates this slice it found a `nil` project and then died. The reason for this is it does the initial query:
```sql
select * from log_entries;
```

Which gives us back 3 log entries. The next query is for projectsubcontracts which doesn't do anything special. Then the one for projects:

```go
select * from projects where id in (1);
```

It then assigns all of these to the LogEntry.R struct. Then it goes to gather up the slice of objects to eager load off of for the final query (project_versions).

But when it does this it ends up gathering up the `nil` Project off of the third `LogEntry`. So the objects to eager load off of becomes:

```go
[]*Project{A, B, nil}
```

Which when it iterates over and tries to get the ID out of it nil-explodes.

I initially corrected this by simply adding an error check so it skips over nil things while iterating, but then decided it made more sense to never gather nils for eager loading in the first place.

I've pushed this to the dev branch. Thank you very much for the thorough debugging. Made it easy to finally see what was going on.

**Comment by lunne** [comment]
I have tested it and it works, Thank you!
