### ISSUE TITLE
Feature Request: Log sql execution duration in debug mode

### ISSUE THREAD

**Issue by ceshihao** [volatiletech/sqlboiler#390]
Recently I need to tune application performance.

If `DebugMode=true`, detail sql and args will be logged, and they are very helpful.

I think it is appreciated that sql execution duration is also logged in debug mode.

Please correct me if there is some way to do that.

**Comment by aarondl** [comment]
I think the appropriate way to do this is via the `context` package. There are many things that use this for tracing, debugging and performance metrics already. I suggest you look into it. I don't know much about it unfortunately.

Past that, it's possible to trace all calls to the database by implementing your own `boil.ContextExecutor` that wraps an `sql.DB` and time the calls into `sql.DB`.

Hopefully those ideas are helpful?

**Comment by zhangxue** [comment]
I think if this can be supported naturally when debug is on, it will be very helpful. Like the dev mode in Rails AR.

**Comment by aarondl** [comment]
@zhangxue I agree with the sentiment wholeheartedly. I'm open to any proposals about this. However one of the tricky parts is that it requires some setup that's driver dependent etc. I'm not sure how we would integrate it. Do you have any thoughts on how we might do it?

**Comment by aarondl** [comment]
Also fwiw I recently achieved this functionality using opencensus.io and their Go tracing/metrics libraries.

**Comment by zhangxue** [comment]
@aarondl that's great to hear. Could you please share more info on how you achieve this? Or even submit a pull request?

**Comment by aarondl** [comment]
```go
package main

import (
	"context"
	"database/sql"
	"fmt"

	"go.opencensus.io/trace"
	"github.com/opencensus-integrations/ocsql"
	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/models"

	_ "github.com/lib/pq"
)

func main() {
	driverName, err := ocsql.Register("postgres", ocsql.WithAllTraceOptions())
	if err != nil {
		panic(err)
	}

	trace.ApplyConfig(trace.Config{DefaultSampler: trace.AlwaysSample()})
	trace.RegisterExporter(new(customExporter))

	db, err := sql.Open(driverName, "CONNECTION STRING GOES HERE")
	if err != nil {
		panic(err)
	}

	ctx, span := trace.StartSpan(context.Background(), "ping")
	if err = db.PingContext(ctx); err != nil {
		panic(err)
	}
	span.End()

	ctx, span = trace.StartSpan(context.Background(), "users")
	_, err = models.Users().All(ctx, db)
	if err != nil {
		fmt.Println(errors.Cause(err))
	}
	span.End()
}

type customExporter struct{}

var (
	layout                = "15:04:05.999999999"
	_      trace.Exporter = (*customExporter)(nil)
)

func (cse *customExporter) ExportSpan(sd *trace.SpanData) {
	fmt.Printf("%-15s %s\n", sd.Name, sd.EndTime.Sub(sd.StartTime))
}
```

@ceshihao Here's some sample code to play around with.
@glerchundi The opencensus stuff seems to take this approach.

Not sure what we can do about requiring these spans though. Perhaps one top level span is good enough? Not 100% sure. I don't have that much experience with this library.

**Comment by glerchundi** [comment]
@ceshihao this is awesome, thanks for sharing!

**Comment by ceshihao** [comment]
@glerchundi 
I am glad it is helpful.
I post a simple demo in my [blog](https://ceshihao.github.io/2018/11/29/tracing-db-operations/).

**Comment by aarondl** [comment]
@ceshihao Are you satisfied with the state of this? Or are you still wanting to see something built in?

**Comment by ceshihao** [comment]
I am okay, and close the issue.

**Comment by erielmejias99** [comment]
I have seen this thread is closed but there is built-in functionality in SQLBoiler for that:
```go
	var logger log.Logger
	logger = log.NewJSONLogger(os.Stderr) // ***same io.Writer
	
	boil.SetDB(config.GetDB())
	sqlBoilerDebugCtx := boil.WithDebug(ctx, true)
	sqlBoilerLoggerDebugCtx := boil.WithDebugWriter(sqlBoilerDebugCtx, os.Stderr) // ***same io.Writer

	repository.UserRepository().GetUserByID(sqlBoilerLoggerDebugCtx, 12)
```
