### ISSUE TITLE
add go.mod stuff

### ISSUE THREAD

**Issue by wkhere** [volatiletech/sqlboiler#391]
Hi!

Are you on 1.11 + modules?

Is it possible for you to add go.mod/go.sum?

I'm switching to go modules with projects where sqlboiler is essential. 
The transitive dependencies can be guessed by the tool but it's generally better if you state them.
I think this small effort is worth doing.

cheers,
W.

**Comment by aarondl** [comment]
Hi there @wkhere there is already a standing issue for this. I'll let you read that and add your voice to it if you'd like. #382

Closing as duplicate
