### ISSUE TITLE
Interval Placeholder Problem

### ISSUE THREAD

**Issue by sachnk** [volatiletech/sqlboiler#398]
I can run the following raw psql outside of sqlboiler without any problems:

```
select * from public.challenges where (NOW() - updated_at) < interval '60 secs';
```

If I try to replicate this with sqlboiler query modules, I get a runtime error:

```
models.Challenges(qm.Where("(NOW() - updated_at) < INTERVAL ?", "60 secs")).DeleteAll(db)
```
At run time, I get the following error:

```
unable to delete all from challenges: pq: syntax error at or near \"$1\""
```
It seems like my `60 secs` placeholder isn't getting escaped properly. I've tried several combinations of escapes myself, but I can't seem to get it to work. What's the proper way to use `INTERVAL` with placeholders?

**Comment by aarondl** [comment]
@sachnk Hey there. Sorry about the late reply. Actually the value in postgres is `interval 60 secs`, so you have to put that full thing in the argument to the query.

```go
models.Challenges(qm.Where("(NOW() - updated_at) < ?", "interval 60 secs"))
```

Also it's worth mentioning if the query is static (it looks as if it is) you can hardcode the 60s and not use the `?` at all.
