### ISSUE TITLE
Error when go getting sqlboiler-mysql

### ISSUE THREAD

**Issue by tkooger** [volatiletech/sqlboiler#412]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
Version 3.1.0

### Further information. What did you do, what did you expect?

What I did: go get github.com/volatiletech/sqlboiler/drivers/sqlboiler-mysql
 github.com/volatiletech/sqlboiler/drivers/sqlboiler-mysql/driver
../../github.com/volatiletech/sqlboiler/drivers/sqlboiler-mysql/driver/mysql.go:114:12: undefined: mysql.NewConfig

What I expect: That it downloads the driver and I can use sqlboiler.

**Comment by tkooger** [comment]
This was my own fault as I had an older version of the github.com/o-sql-driver/mysql installed.

**Comment by tiger5226** [comment]
so what version worked?

**Comment by j0hnsmith** [comment]
`go get -u -t github.com/go-sql-driver/mysql` then try again.
