### ISSUE TITLE
How to use JSON API struct tags with SQLBoiler?

### ISSUE THREAD

**Issue by you-yas55** [volatiletech/sqlboiler#419]
How can I use advanced JSON API struct tags with SQLBoiler?

```
type AppsUser struct {
	AppID  uint8  `boil:"app_id" json:"app_id" toml:"app_id" yaml:"app_id" jsonapi:"primary,app_id"` <---- this should've been an App relation not a primary key but how can I do that?
	UserID uint   `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Active int8   `boil:"active" json:"active" toml:"active" yaml:"active"`
	Config string `boil:"config" json:"config" toml:"config" yaml:"config"`

	R *appsUserR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L appsUserL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}
```

**Comment by aarondl** [comment]
There is no way currently to control the tags that are generated for a model. Typically if the autogenerated stuff isn't good enough in one place, it won't be good enough in any so the workaround is to create a serializing struct that takes the pieces it needs and names things correctly. You'll notice `R` is tagged to be ignored by all those serialization libraries and so typically people will also add the actual related objects in their serialization struct as well.
