### ISSUE TITLE
Signed bigints are generating null.uint64 instead of null.int64

### ISSUE THREAD

**Issue by jkang8** [volatiletech/sqlboiler#427]
Version 3.0.0

ALTER TABLE `table_name` CHANGE COLUMN `col1` `col2` BIGINT;

I expected the go struct field to be of type null.Int64 but instead it generated null.Uint64

**Comment by aarondl** [comment]
This was fixed in v3.1.0 please check CHANGELOGs on latest releases or attempt to use the latest version before filing bugs :)

**Comment by aarondl** [comment]
https://github.com/volatiletech/sqlboiler/commit/f480b4b59158822aa6dadd67c152ee85dd40232d
