### ISSUE TITLE
postgres int renders as int vs int32

### ISSUE THREAD

**Issue by caseylucas** [volatiletech/sqlboiler#431]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v3.1.0

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

sqlboiler --wipe --no-hooks psql

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```
create table x (
 col int not null
)
```
### Further information. What did you do, what did you expect?

Per https://www.postgresql.org/docs/current/datatype-numeric.html, postgres int columns are 32 bits yet sqlboiler renders them as golang int vs int32.  Shouldn't the generated code use an int32?

Obviously the int can be cast to int32 in go, but I think int32 always explicitly matches the postgres datatype and should be used.

**Comment by louis77** [comment]
Since `int` in golang is "at least 32bit in size" and most of the builtin and library functions use int instead of int32, I guess it's just a matter of making it more convenient to render pg int to golang int. Most 64bit architectures will use 64bit of memory anyway, even for int32. So what's to be gained?

**Comment by caseylucas** [comment]
I understand your point about convenience in certain cases. 

> what's to be gained?

1. Exactness and convenience (for certain use-cases).  I happen to be using protobufs which explicitly state the size of int data and render `int32` and `int64` into structs.

2. Prevention of runtime errors when storing data. Postgres `int` will always exactly match go `int32` but go `int` will not always match postgres `int` (depending on cpu architecture.) I suppose if a developer running on a 64 bit platform uses the sqlboiler rendered structs and attempts to store values larger than 32 bits they'll get a runtime error when attempting to store the data into postgres even though manipulation of the data in go would not cause problems.

Maybe a flag/option for rendering `int32` vs `int`?  Maybe I continue casting 🙂.

**Comment by aarondl** [comment]
You can use the types configuration to change this yourself very easily if you want. See the README for details. Currently not going to change this because it's breaking.
