### ISSUE TITLE
Get to know affected fields inside hook.

### ISSUE THREAD

**Issue by tigp** [volatiletech/sqlboiler#432]
@aarondl just a questions. 

is it possible to know the affected changed fields inside hooks?

Thank you!

**Comment by aarondl** [comment]
It is not currently, no. There is no "dirty tracking" in sqlboiler whatsoever for better or worse so this is something sqlboiler simply can't know. Though it may be possible to provide the lists that `sqlboiler` has decided to insert and return if we were to break the API.

**Comment by tigp** [comment]
@aarondl thank you very much for your reply!
