### ISSUE TITLE
Exist query not matching properly

### ISSUE THREAD

**Issue by tiger5226** [volatiletech/sqlboiler#447]
I am using the following `Where` mods:

```golang
txHashMatch := qm.Where(model.InputColumns.TransactionHash+"=?", input.TransactionHash)
		txCoinBaseMatch := qm.Where(model.InputColumns.IsCoinbase+"=?", input.IsCoinbase)
		prevHashMatch := qm.Where(model.InputColumns.PrevoutHash+"=?", input.PrevoutHash)
		prevNMatch := qm.And(model.InputColumns.PrevoutN+"=?", input.PrevoutN)
```
and then the execution of the query:

```golang
model.Inputs(txHashMatch, txCoinBaseMatch, prevHashMatch, prevNMatch).ExistsGP() 
```
I checked and looking at a specific example this query should return true but it does not. I turned on query debugging and this is the query it is sending to mysql:

```
SELECT COUNT(*) FROM `input` WHERE (transaction_hash=?) AND (is_coinbase=?) AND (prevout_hash=?) AND (prevout_n=?) LIMIT 1;
[8291a6fd4af279106ca5c1efa4a1522524291011abbe3c9c43ce2d0dc6228b2b true { false} {0 false}]
```
The problem here is that it is sending defaults on a null column, so of coarse it doesn't find a match. The query generated should be:
 
```
SELECT COUNT(*) FROM `input` WHERE (transaction_hash="8291a6fd4af279106ca5c1efa4a1522524291011abbe3c9c43ce2d0dc6228b2b") AND (is_coinbase = 1) AND (prevout_hash IS NULL) AND (prevout_n IS NULL) LIMIT 1;
```

I have a massive number of if/else to add in order for null values to be supported. If there is a specific way I am supposed to be handling this please let me know.

**Comment by aarondl** [comment]
This unfortunately is something that's not handled currently. For now I would suggest creating your own helper for it which is fairly simple. The real solution is:

https://github.com/volatiletech/sqlboiler/issues/426

**Comment by tiger5226** [comment]
[Squirrel](https://github.com/Masterminds/squirrel) has a great library for generating some nice SQL. I use it in addition to SQLBoiler for more complex queries. It has exactly what you reference. I wonder if merging the two solves this problem in a nice way.

**Comment by tiger5226** [comment]
I saw the other issue, where someone posted a helper function but it did not work for me. So I actually just added the if else since it turned out that there was only one table with nullable match columns. I will close this since there is already an issue opened up.
