### ISSUE TITLE
Provide an example of AppendWhere

### ISSUE THREAD

**Issue by jones77** [volatiletech/sqlboiler#459]
I'm trying to construct a where clause with parameters that may or may not be available.

eg

```
	whereQuery := models.Table(qm.Where("active=true"))
	if request.A != "" {
		queries.AppendWhere(whereQuery.Query, "A=?", request.A)
	}
	if request.B != "" {
		queries.AppendWhere(whereQuery.Query, "B=?", request.B)
	}
	keys, err := whereQuery.All(ctx, db)
```

But it's not clear to me that I'm doing this correctly (and 'cos this doesn't work).

If someone could provide a hint I'd be much obliged.  (And I'll submit a PR to the docs once I find out.)

**Comment by jones77** [comment]
Figured it out, slices!

```
	whereQueries := []qm.QueryMod{qm.Where("active=true")}
	if request.Os != "" {
		whereQueries = append(whereQueries, qm.Where("A=?", request.A))
	}
	if request.Site != "" {
		whereQueries = append(whereQueries, qm.Where("B=?", request.B))
	}
	keys, err := models.CLPRNetworkKeys(whereQueries...).All(ctx, db)
```

lmk if you want a PR with an example somewhere, otherwise feel free to close

**Comment by aarondl** [comment]
Glad you got it. You can open a PR or not if you think it improves the documentation for newcomers. I think it's mostly Go knowledge once you see the types involved. I thought we had documented it somewhere but maybe not :)
