### ISSUE TITLE
Alaises and 'has both field and method named'

### ISSUE THREAD

**Issue by ossie-git** [volatiletech/sqlboiler#463]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v3.1.0

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

I'm currently trying sqlboiler out on the chinook SQLite database (downloadable from here - http://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip)

My sqlboiler.toml file looks like this:

```
[sqlite3]
dbname = "chinook.db"
blacklist = ["sqlite_stat1", "sqlite_sequence"]
```

I then generate the models:

```
sqlboiler --wipe sqlite3
```

When I run the tests, I get the following errors:

```
go test ./models

# lab/sqltest/models [lab/sqltest/models.test]
models/albums.go:309:6: type Album has both field and method named ArtistId
models/customers.go:340:6: type Customer has both field and method named SupportRepId
models/employees.go:349:6: type Employee has both field and method named ReportsTo
models/invoice_items.go:315:6: type InvoiceItem has both field and method named TrackId
models/invoice_items.go:329:6: type InvoiceItem has both field and method named InvoiceId
models/invoices.go:328:6: type Invoice has both field and method named CustomerId
models/tracks.go:337:6: type Track has both field and method named MediaTypeId
models/tracks.go:351:6: type Track has both field and method named GenreId
models/tracks.go:365:6: type Track has both field and method named AlbumId
models/albums_test.go:850:30: cannot call non-function local.ArtistId (type int64)
models/albums_test.go:850:30: too many errors
FAIL    lab/sqltest/models [build failed]
```

An example of one of the complaints (albums):

```
sqlite> .schema albums
CREATE TABLE IF NOT EXISTS "albums"
(
    [AlbumId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Title] NVARCHAR(160)  NOT NULL,
    [ArtistId] INTEGER  NOT NULL,
    FOREIGN KEY ([ArtistId]) REFERENCES "artists" ([ArtistId])
                ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX [IFK_AlbumArtistId] ON "albums" ([ArtistId]);

sqlite> .schema artists
CREATE TABLE IF NOT EXISTS "artists"
(
    [ArtistId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Name] NVARCHAR(120)
);
```

I decided to try to use aliases so I updated my toml to look like this:

```
[sqlite3]
dbname = "chinook.db"
blacklist = ["sqlite_stat1", "sqlite_sequence"]

[aliases.tables.albums.columns]
NewTitle = "Title"
```

The above was just to test aliases.  The associated -d section looks like this:

```
    "aliases": {
      "tables": {
        "albums": {
          "up_plural": "Albums",
          "up_singular": "Album",
          "down_plural": "albums",
          "down_singular": "album",
          "columns": {
            "AlbumId": "AlbumId",
            "ArtistId": "ArtistId",
            "Title": "Title",
            "newtitle": "Title"
          },
          "relationships": {
            "FK_0": {
              "local": "ArtistIdAlbums",
              "foreign": "ArtistId"
            }
          }
        },
        ...
        }
      }
    }
```

You'll notice that there are now two aliases to Title:

```
"Title": "Title",
"newtitle": "Title"
```

When I look at the generated .go file, I see no mention of newtitle.

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

I'm currently trying sqlboiler out on the chinook SQLite database (downloadable from here - http://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip)

### Further information. What did you do, what did you expect?

The alias should be used in the generated models

**Comment by aarondl** [comment]
When you use viper to read toml (like we do) your keys get forced to be downcased. So if you want to do aliases with non-lowercased keys you have to use the alternative syntax found in the documentation:

```toml
[sqlite3]
dbname = "chinook.db"
blacklist = ["sqlite_stat1", "sqlite_sequence"]

[[aliases.tables.albums.columns]]
name = "Title"
alias = "NewTitle"
```

```json
{
  "tables": {
    "albums": {
      "up_plural": "Albums",
      "up_singular": "Album",
      "down_plural": "albums",
      "down_singular": "album",
      "columns": {
        "AlbumId": "AlbumId",
        "ArtistId": "ArtistId",
        "Title": "NewTitle"
      }
    }
  }
}
```

I've omitted a large chunk of the debug JSON here, but you can see that your desired (I think) result was achieved. I've renamed Title to NewTitle. Sorry it took so long to get to this issue.

**Comment by aarondl** [comment]
They should solve it. Typically there's only two things that can collide, columns and the relationship helper methods. Aliasing one of those two things **for each collision/compiler error** would be necessary. It's not easy in a database like this that was named completely differently from how sqlboiler expects.

I'd be pretty surprised to see if you aliased the ArtistId column in the albums table if that top error persisted.

One tip: you should probably alias the relationships not the columns, those are responsible for the methods being generated.

**Comment by aarondl** [comment]
I think I do notice a bug at the bottom btw. Something trying to call a column name... That may be a problem but we don't know until we sort the rest out.

**Comment by dtrehas** [comment]
Any news about this issue?

**Comment by aarondl** [comment]
@dtrehas Aliases work fine for the majority of use cases. Make sure you've tried them first.
