### ISSUE TITLE
Multi tenancy support

### ISSUE THREAD

**Issue by ivishnevs** [volatiletech/sqlboiler#466]
Hi, everyone 👋
Im trying to use sqlboiler v3.2.0 as ORM for our project, but we have multi tenant architecture with isolation based on PostgreSQL schemas and it causes some issues in pair with sqlboiler.

So, to be able to generate `models` package we have to create one temporary schema (like merged one) with all tables and run `sqlboiler psql --wipe`. But then `sqlboiler` starts to use schema name in freshly generated sql queries like:
`./models/customers.go:  sql := "DELETE FROM "merged"."customers" WHERE "id"=$1"`

And this in turn does not give us the opportunity to switch tenants (schemas) in runtime.

Multi tenancy for cloud seems not like edge case... Any suggestions/workarounds?

**Comment by aarondl** [comment]
See this issue for details: https://github.com/volatiletech/sqlboiler/issues/134

Closing this as duplicate
