### ISSUE TITLE
Question: Can sqlboiler support multiple db type for a single app

### ISSUE THREAD

**Issue by mremond** [volatiletech/sqlboiler#467]
Hello,

For a product that need to be configurable and adapt to different database backends, can SQLBoiler work ?

I have seen that generation connects to a real DB for generation. However, is it expected to be able to plug the resulting content to different database type ?

Thanks !

**Comment by aarondl** [comment]
It cannot work. The code that it generates is database specific because concepts like "how do I return the ID of an insert" in postgresql vs mysql have two very different answers to the question.

One set of models can only ever work for the database from which it was generated.

**Comment by netayg** [comment]
Hey @aarondl,
Is it possible to connect to multiple DBs of the same type (postgres)?
I have  2 db servers that my app uses, but when I use SetDB the code overrides the connection of the first DB.
Is this supported/planned?

**Comment by stephenafamo** [comment]
SetDB sets the global DB so, of course, it will override the connection.

Instead, you can use the non-global methods and supply the correct DB.

**Comment by netayg** [comment]
Thank you,
Took me time to understand that - but got it right after posting this issue.
Forgot to close :)
