### ISSUE TITLE
Any function like gorm's scan ?

### ISSUE THREAD

**Issue by RXDA** [volatiletech/sqlboiler#470]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
sqlboiler v3.2.0+incompatible in go module

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
no

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
for example ,I have a model generated by sqlboiler:
```
type Category struct {
	ID                 uint16    `boil:"id" json:"id" toml:"id" yaml:"id"`
	AppID              uint8     `boil:"app_id" json:"app_id" toml:"app_id" yaml:"app_id"`
	Name               string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	
	R *categoryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L categoryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}
```
I want to select all category into below struct:
```
type customCategory struct {
	AppID              uint8     `boil:"app_id, bind" 
	Name               string    `boil:"name, bind" 
}
```
I tried like this :
```
var categories []customCategory
err := Categories(
		Select("app_id, name"),
		Where("app_id = ?", 1),
		OrderBy("id desc"),
		Limit(8),
	).BindG(context.Background(),&categories)
```
but this doesn't work.Can anyone help me ?Thanks

**Comment by aarondl** [comment]
This should work fine. Having a space before `bind` is not correct though. Struct tags don't have spaces. You also don't need the `bind` part of the struct tag.

```go
type customCategory struct {
	AppID uint8  `boil:"app_id"`
	Name  string `boil:"name"`
}
```

Try this?

**Comment by RXDA** [comment]
@aarondl It works!Thank you
