### ISSUE TITLE
failed to find key user in config Error: unable to initialize tables: unable to fetch table data: driver $GOPATH/bin/sqlboiler-mysql.exe exited non-zero: exit status 1

### ISSUE THREAD

**Issue by saicharan-virtusa** [volatiletech/sqlboiler#471]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.2.0

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler mysql

while running the above command i got the following error 
failed to find key user in config
Error: unable to initialize tables: unable to fetch table data: driver ($GOPATH\bin\sqlboiler-mysql.exe) exited non-zero: exit status 1

**Comment by aarondl** [comment]
This is a very bad bug report.

If you're having a problem with the configuration, perhaps you should show the configuration that you do have so we can find out what's missing? Please put more effort into your bug report.

**Comment by RichardLindhout** [comment]
Do you have (combined) primary keys other than id?

**Comment by RichardLindhout** [comment]
I had this when running sqlboiler command in the wrong folder xD

**Comment by SignedAdam** [comment]
For anyone who encounters this issue in the future:

I had this issue because I put
`sslmode = disable`
in the sqlboiler.toml config

put quotes around 'disable'
`sslmode = "disable"`
and it worked

**Comment by MoureDeervarse** [comment]
Sometimes I end up doing really absurd things. In this case, I was following examples and tweaking them to fit my project, which led me to put the configuration values under the [mysql] section in the 'config.toml' file, but then I was running 'sqlboiler psql'. 

Make sure you're using the correct driver for your database.

**Comment by kaustubh-11** [comment]
> I had this when running sqlboiler command in the wrong folder xD

@RichardLindhout Man, you rock, Thanks 😄  🙇
