### ISSUE TITLE
Methodless structs

### ISSUE THREAD

**Issue by e-nikolov** [volatiletech/sqlboiler#486]
In the application I'm working on some packages need to be passed data from the database, but shouldn't have the ability to call the database on their own and don't have a reference to sql.DB. Since the model generated by sqlboiler consists of go structs, it seems natural to pass them into those packages, but it is a bit confusing that the structs always contain methods that call the database.

I'm fairly new to sqlboiler so I only have a limited understanding of the best practices surrounding it, but would it make sense for sqlboiler to generate a simple methodless struct which it embeds into the main ORM struct? 

Borrowing from the pilots example from the readme:

```go
type PilotDTO struct {
  ID   int    `boil:"id" json:"id" toml:"id" yaml:"id"`
  Name string `boil:"name" json:"name" toml:"name" yaml:"name"`
}

type Pilot struct {
  *PilotDTO

  R *pilotR `boil:"-" json:"-" toml:"-" yaml:"-"`
  L pilotR  `boil:"-" json:"-" toml:"-" yaml:"-"`
}
```

This way I could pass PilotDTO to the parts of the application that don't care about the database and also embed it into my own json serializers that would be sent to the front end, where I might want to include several levels of related tables.

**Comment by e-nikolov** [comment]
Thinking about it a bit further, embedding seems to not be the best because it would break being able to do:

```go
pilot := &models.Pilot{
  ID: 3,
  Name: "john",
}
```

But perhaps a separate method could be generated on the Pilot struct to create and return a PilotDTO?

```go
pilot := &models.Pilot{
  ID: 3,
  Name: "john",
}

pilotDTO := pilot.DTO()
```

**Comment by aarondl** [comment]
I'm not actually seeing a real issue here. You said yourself that these packages "need to be passed data from the database, but shouldn't have the ability to call the database on their own and don't have a reference to sql.DB". Well if they don't have a reference to sql.DB then they don't have the ability to do anything with the database, correct? Despite the methods being available, they are missing a dependency those methods require to do anything.

This seems like a personal preference for some form of additional cleanliness. However the change you propose would break a lot of things (remember Go embedding is not inheritance, it is not an is-a relationship, it's a has-a which is key here).

I'm not seeing the payoff of the proposal outside your own codebase but I'm seeing a large detriment to the people who currently use sqlboiler. There will have to be much better justification if we were to move towards something like this.

**Comment by e-nikolov** [comment]
Yeah I realized that my initial idea with embedding would break things, so in my second comment I suggested that maybe there could just be a pilot.DTO() method that converts it to a separately generated PilotDTO struct. But I can understand that perhaps this is outside of sqlboiler's scope.

**Comment by aarondl** [comment]
Yeah. Unless there's a really good reason to implement it which I'm not currently seeing won't be doing this. Sorry!

**Comment by e-nikolov** [comment]
It should be possible to do something like this myself via `sqlboiler --templates`, right?

**Comment by aarondl** [comment]
Absolutely. At the end of the day the built in templates are just a suggestion for a templating engine. You can do however you desire :)

**Comment by e-nikolov** [comment]
For future reference, I ended up adding this template to the application's code base and configured sqlboiler to use it:

```
{{- $alias := .Aliases.Table .Table.Name -}}

// {{$alias.UpSingular}} is an object representing the database table.
type {{$alias.UpSingular}}DTO struct {
	{{- range $column := .Table.Columns -}}
	{{- $colAlias := $alias.Column $column.Name -}}
	{{- if eq $.StructTagCasing "camel"}}
	{{$colAlias}} {{$column.Type}} `{{generateTags $.Tags $column.Name}}boil:"{{$column.Name}}" json:"{{$column.Name | camelCase}}{{if $column.Nullable}},omitempty{{end}}" toml:"{{$column.Name | camelCase}}" yaml:"{{$column.Name | camelCase}}{{if $column.Nullable}},omitempty{{end}}"`
	{{- else -}}
	{{$colAlias}} {{$column.Type}} `{{generateTags $.Tags $column.Name}}boil:"{{$column.Name}}" json:"{{$column.Name}}{{if $column.Nullable}},omitempty{{end}}" toml:"{{$column.Name}}" yaml:"{{$column.Name}}{{if $column.Nullable}},omitempty{{end}}"`
	{{end -}}
	{{end -}}
}

// DTO converts the {{$alias.UpSingular}} to a {{$alias.UpSingular}}DTO struct.
func (o {{$alias.UpSingular}}) DTO() (*{{$alias.UpSingular}}DTO) {
    return &{{$alias.UpSingular}}DTO{
        {{"" }}
		{{- range $column := .Table.Columns -}}
			{{- $colAlias := $alias.Column $column.Name -}}
			{{$colAlias}}: o.{{$colAlias}},
		{{end -}}
    }
}

```
