### ISSUE TITLE
HStore: panic:not a string or sql.NullString

### ISSUE THREAD

**Issue by toyo-iacob** [volatiletech/sqlboiler#488]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.1.0

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
attrs := types.HStore{
	"key1": null.StringFrom("val1"),
	"key2": null.StringFrom("val2"),
}
pp := &models.Product{
	...
	Attributes: attrs,
}
pp.InsertG(boil.Infer())

I use Postgres. I have a table that has a hstore column. I cannot insert into it using a type safe method. If i pass a Hstore as in the example above then it passes compilation but throws panic:not a string or sql.NullString at runtime. If i try to pass it a string, then compiler won't allow me because is not type Hstore. The only way i can do is to do a raw query, which i don't like. Am i missing something ?

Later edit. Same panic thrown if you select an object that has a hstore column and then run update on all the columns.

**Comment by aarondl** [comment]
You're not missing anything other than hstore is kind of a red-headed step child. Fixed in dev branch.
