### ISSUE TITLE
Test fails with Postgres domain check constraint

### ISSUE THREAD

**Issue by JuanTorr** [volatiletech/sqlboiler#489]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### **What version of SQLBoiler are you using (`sqlboiler --version`)?**
SQLBoiler v3.2.0

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler --wipe psql
go test ./models fails 

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```SQL
CREATE DOMAIN DM_ESTADO_REGISTRO AS SMALLINT  DEFAULT 1 NOT NULL  CHECK (VALUE IN (1,2,3,4))
;

CREATE TABLE USRTUSUARIO ( 
  USU_PK_USUARIO              SERIAL NOT NULL,
  USU_NOMBRE                  TEXT NOT NULL,
  USU_FECHA_REGISTRO          TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  USU_ESTADO_REGISTRO         DM_ESTADO_REGISTRO,
CONSTRAINT PK_USRTUSUARIO PRIMARY KEY (USU_PK_USUARIO)
) 
;
 ;
```
### Further information. What did you do, what did you expect?
go test fails while trying to do an upsert 
 usrtusuario_test.go:705: Unable to upsert Usrtusuario: models: unable to upsert usrtusuario: pq: the  value for domain dm_estado_registro  violates check constraint dm_estado_registro_check

The problem is that during the test the stuct values are randomized.

**Comment by aarondl** [comment]
Unfortunately there's nothing we'll ever be able to do about this. We cannot read constraints out of the database in an agnostic way and apply them to the models in Go.

In a way the tests are correctly failing. They're saying: Without additional logic or model hooks there's ways for the models to attempt to input something invalid to the database which should be caught by client side validation.
