### ISSUE TITLE
Array query parameters

### ISSUE THREAD

**Issue by emwalker** [volatiletech/sqlboiler#492]
I am seeking information on how to pass an array parameter to SQLBoiler.  Consider the simplified query:

```golang
var tokens []string

[...snip...]

err = queries.Raw(`
select t.* from topics t
where t.name ~~* all(array[$1])
order by t.name
limit $2
`, tokens, 5).Bind(ctx, exec, &topics)
```

Is there a way to package a slice of strings that will get a query like this to work?

I _think_ I can serialize the array into a postgres string array (`'{one,two,three}'`).   But that gets into questions of string escaping, and I'm wondering if there's a way to hand an array to SQLBoiler.

**Comment by aarondl** [comment]
Look into the package: github.com/volatiletech/sqlboiler/types it has an array type in there that should help you. Re-open if it doesn't work for you.

**Comment by emwalker** [comment]
Thank you!

**Comment by emwalker** [comment]
For people who run into this in the future, you can do something like this:
```golang
param := types.Array([]string{"one", "two", "three"})
```

`param` can now be used as a positional parameter:
```golang
err = queries.Raw(`
select t.* from topics t
where t.name ~~* all($1)
order by t.name
limit $2
`, param, 5).Bind(ctx, exec, &topics)
```
