### ISSUE TITLE
UpdateColumnSet for GoZeroValues to be ignored - help wanted

### ISSUE THREAD

**Issue by Gobonoid** [volatiletech/sqlboiler#493]
I am new to sqlboiler so if I missed it or didn't understand forgive me plz.

### What version of SQLBoiler are you using (`sqlboiler --version`)?
3.2.0

### Problem description
Let's imagine a model:
```
// User is an object representing the database table.
type User struct {
	ID        string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name      string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Nickname  string    `boil:"nickname" json:"nickname" toml:"nickname" yaml:"nickname"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *transactionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L transactionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}
```
I am trying to update a single row using sql boiler models:
``` 
	if _, err := user.Update(context.Background(), s.db,
		boil.Blacklist(models.UserColumns.CreatedAt, models.UserColumns.ID)); err != nil {
		return errors.Wrap(err, "failed during save")
	}
``` 
Now this works as expected, blacklisted fields won't get updated - great!

Now assuming my user has a ```nickname``` I want to change only a single field in user model using a prefabricated model (avoiding selecting user from DB)

```
userUpdate, err := &models.User{Name: "bla"}.Update(context.Background, s.db, boil.Blacklist(models.UserColumns.CreatedAt, models.UserColumns.ID))
```
This will cause user.Nickname to be set to zero like value (empty string). Is there a way avoiding it using sql.Boiler (update field only if value is non zero like?)

For now I am using reflection to achieve it 
```
	c := boil.Blacklist(models.UserColumns.CreatedAt, models.UserColumns.ID)

	v := reflect.ValueOf(*userUpdate)
	f := reflect.TypeOf(*userUpdate)
	tc := reflect.ValueOf(models.UserColumns)
	for i := 0; i < v.NumField(); i++ {
		if f.Field(i).Name == "R" || f.Field(i).Name == "L" {
			continue
		}
		if isZero(v.Field(i)) {
			c.Cols = append(c.Cols, tc.FieldByName(f.Field(i).Name).String())
		}
	}

	return c
```
But would appreciate cleaner solution

**Comment by aarondl** [comment]
> Now assuming my user has a nickname I want to change only a single field in user model using a prefabricated model (avoiding selecting user from DB)

As for how to simply update only a specific set of columns use `Whitelist` not `Blacklist`. This ensures that only the fields you specify are updated, much easier.

As for not selecting from the database it's probably better to use UpdateAll:

```go
models.Users(models.UserWhere.ID.EQ(myID)).UpdateAll(
  models.M{models.UserColumns.Name: "bla"},
).UpdateAll(context.Background(), db)
```

Be 100% sure to use a where clause in the query above - otherwise you'll overwrite your entire table, hence the name `UpdateAll` :D

But either way will work, just make sure if you construct an object to update like you're doing you also populate it's primary key or it will be unable to find the record in the database to update.
