### ISSUE TITLE
LastInsertID Not Work on Non-autoincrement Primary Key

### ISSUE THREAD

**Issue by supercharlesliu** [volatiletech/sqlboiler#500]
# Issue Context
sqlBoilerVersion = "3.2.0"

Table Schema:

```sql
CREATE TABLE `test` (
  `userid` int(11) unsigned NOT NULL DEFAULT '0',
  `nickname` varchar(100) NOT NULL DEFAULT '',
   PRIMARY KEY (`userid`),
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```

Insert SQL:
```sql
INSERT INTO `test` (`userid`,`nickname`) VALUES (2,"testname")
```

## 1. LastInsertID only work for AUTOINCREMENT columns
As described in documentation of MySQL: https://dev.mysql.com/doc/refman/5.5/en/information-functions.html#function_last-insert-id
LastInsertID only works on AUTOINCREMENT column for the last INSERT.

So [Table. CanLastInsertID()](https://github.com/volatiletech/sqlboiler/blob/master/drivers/table.go#L49) is not correct logic:

> // CanLastInsertID checks the following:
// 1. Is there only one primary key?
// 2. Does the primary key column have a default value?
// 3. Is the primary key column type one of uintX/intX?
// If the above is all true, this table can use LastInsertId

**The correct logic should add one condition: is the only one primary key is auto increment?**

## 2. Should not use LastInsertID to query the last inserted row when the primary key is already provided.

As in the Insert template: 
```
        {{if $canLastInsertID -}}
	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	{{$colName := index .Table.PKey.Columns 0 -}}
	{{- $col := .Table.GetColumn $colName -}}
	{{- $colTitled := $colName | titleCase}}
	o.{{$colTitled}} = {{$col.Type}}(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == {{$alias.DownSingular}}Mapping["{{$colTitled}}"] {
		goto CacheNoHooks
	}
	{{- end}}

	identifierCols = []interface{}{
		{{range .Table.PKey.Columns -}}
		o.{{$alias.Column .}},
		{{end -}}
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	{{if .NoContext -}}
	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	{{else -}}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	{{end -}}
	if err != nil {
		return errors.Wrap(err, "{{.PkgName}}: unable to populate default values for {{.Table.Name}}")
	}
	{{else}}
	if len(cache.retMapping) != 0 {
		{{if .NoContext -}}
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
		{{else -}}
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
		{{end -}}
	} else {
		{{if .NoContext -}}
		_, err = exec.Exec(cache.query, vals...)
		{{else -}}
		_, err = exec.ExecContext(ctx, cache.query, vals...)
		{{end -}}
	}

	if err != nil {
		return errors.Wrap(err, "{{.PkgName}}: unable to insert into {{.Table.Name}}")
	}
	{{end}}
```

If the insert goes like:
Insert SQL:
```sql
INSERT INTO `test` (`userid`,`nickname`) VALUES (2,"testname")
```
The generated code of Insert command will raise an error(`{{.PkgName}}: unable to insert into {{.Table.Name}}`), because the `lastID` get from `result.LastInsertId()` is 0

# Expected Changes
- Add auto increment column check in `Table. CanLastInsertID()`
- In `Insert` template, check if the primary is already provided, if so, use the provided primary column value. Use `result. RowsAffected()` to check wheather the insert is success.

**Comment by aarondl** [comment]
After reviewing this I don't think there are any necessary changes here. Instead I'd push that you change your schema.

```
  `userid` int(11) unsigned NOT NULL DEFAULT '0',
```

I don't see a good use case for this. Can you explain it?

If you don't provide an id, the 0th id will be created and inserted. That can only happen once, following that any insert that tries to insert without an id will fail because of your primary key constraint. This to me is completely useless, why not just have no default at all and force the value to be present in an insert? Much more explicit and clear that the id generation is the responsibility of whatever client.

**Comment by aarondl** [comment]
Stale.
