### ISSUE TITLE
Types only for one table

### ISSUE THREAD

**Issue by GalGavu** [volatiletech/sqlboiler#501]
Hi,
I would like to ask if there is a possibility to replace types only in one table.
```
[[types]]
	[types.match]
	    name = "some_column"

	[types.replace]
	    type = "something.test"

    [types.imports]
        third_party = ['"github.com/my/something"']
```

would replace every `some_column` in database. I want to replace type only in one particular table. How to do this?

**Comment by aarondl** [comment]
There is no ability to do this and I'm not looking to support that functionality, sorry :(

**Comment by iRbouh** [comment]
@aarondl you can easily add something to distinguish the column's table (comment for example or the table name itself!!!!!!)... I do really love this package and thank you for that but your feedbacks are always negative about some basic features !!!

**Comment by aarondl** [comment]
@GalGavu This feature was added by an outside contributor in the dev branch.
