### ISSUE TITLE
Use UUID: how, where and when?

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/sqlboiler#503]
Sorry this maybe silly question: I'm newbie and I'm learning.

I love @aarondl for the amazing https://github.com/volatiletech/authboss, project that I am helping to make grow by giving my humble "informative" contribution.

Now for a new project I chose sqlboiler. What I don't understand is how to use `uuid` fields (I'll write a Wiki for newbies about this).

If I have this table (Postgresql):

```sql
CREATE TABLE "players" (
    "id"            uuid NOT NULL,
    "name"          varchar,
    "created_at"    timestamptz,
    "updated_at"    timestamptz,
    PRIMARY KEY ("id") 
)
WITHOUT OIDS;
```

and I'm using this code:

```go
player := &models.Players{
	Name: null.String{"name surname", true},
}

err := player.Insert(context.Background(), DB, boil.Infer())
dieIf(err)

fmt.Println(player.ID)
```

it gives me this error:

`[] models: unable to insert into players: pq: invalid input syntax for type uuid: ""`

**I need to generate `uuid` myself, right? On the client (Go) side? Can sqlboiler do it for me?**

I like this way very much, what I'm afraid is about performances: I need very fast and many insert and update.

Is there a "suggested" way? I read a lot and, apart from storage size, using Postgresql with uuid don't seem to be bad at all.

Also I need `UUID` instead of `INT` (serial, sequence) because of distributed nature of my project and I don't expose `uuid` or `int` anyway.

**Comment by aarondl** [comment]
Postgres can generate them (and should generate them). No wiki necessary for this as it's standard postgres behavior not related to authboss or sqlboiler :)

```
create table things (
    id uuid not null primary key default gen_random_uuid(),
```

**Comment by tilakraj9560** [comment]
I am facing the same issue, can we reopen it? I have default set on the postgres side too, i am able to insert rows directly but not from sqlboiler?
`models: unable to insert into job: pq: invalid input syntax for type uuid: ""`

```
func (c *client) SaveJob(ctx context.Context, job *models.Job) error {
	db := c.db
	err := job.Insert(ctx, db, boil.Blacklist(models.JobColumns.ID))
	if err != nil {
		return utils.WriteError(codes.Internal, utils.InternalServerError, err)
	}
	return nil
}
```

**Comment by aarondl** [comment]
Open a new issue and provide the sql schema for that table as well as the relevant section from sqlboiler debug output. It may not be recognizing your column has a default value. Either way you do not need to blacklist the ID unless there is a bug

**Comment by tilakraj9560** [comment]
sorry my bad, got the issue.  +1 for this _Either way you do not need to blacklist the ID unless there is a bug_
