### ISSUE TITLE
From GORM to SQLBoiler, extending User model for authboss interfaces

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/sqlboiler#504]
I'm migrating from GORM to this amazing project. I'm really newbie in Go.

I'm using the amazing `authboss`.

I have this table `users`:

```sql
CREATE TABLE "users" (
  "id" INT NOT NULL,
  "email" varchar NOT NULL,
  "password" text NOT NULL,
)
```

SQLBoiler is generating this struct:

```go
type User struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Email     string    `boil:"email" json:"email" toml:"email" yaml:"email"`
	Password  string    `boil:"password" json:"password" toml:"password" yaml:"password"`
}
```

In GORM I had this model:

```go
type User struct {
	gorm.Model
	Email    string `gorm:"type:varchar(100)"`
	Password string
}

func (u *User) PutPID(pid string) { u.Email = pid }
func (u *User) PutPassword(password string) { u.Password = password }
func (u User) GetPID() string { return u.Email }
func (u User) GetPassword() string { return u.Password }
```

Now with SQLBoiler I need to "extend" this model and the question concerns just that:

Am I doing well using the embedding method as below?

```go
package extendmodels

import "project/models"

type ExtendedUser struct {
	*models.User
}

func (u *ExtendedUser) PutPID(pid string) { u.Email = pid }
func (u *ExtendedUser) PutPassword(password string) { u.Password = password }
func (u ExtendedUser) GetPID() string { return u.Email }
func (u ExtendedUser) GetPassword() string { return u.Password }
```

This is necessary because of the interfaces that authboss requires:

```go
var (
	assertUser   = &extendmodels.ExtendedUser{}
	assertStorer = &DBStorer{}

	_ authboss.User         = assertUser
	_ authboss.AuthableUser = assertUser

	_ authboss.RememberingServerStorer = assertStorer
)

func (m DBStorer) Load(ctx context.Context, key string) (user authboss.User, err error) {
	userFound, err := models.Users(models.UserWhere.Email.EQ(key)).One(ctx, db.DB)
	if err != nil {
		return nil, authboss.ErrUserNotFound
	}
	return &extendmodels.ExtendedUser{userFound}, nil
}
```

I think there is not other method, right?

- type assertion? Something like: `return userFound.(extendmodels.ExtendedUser), nil`, but this can't work because `models.User` is not an interface, right?

- type conversion? Something like: `return extendmodels.ExtendedUser(*userFound), nil`, but the Go says: `Cannot convert expression of type User to type ExtendedUser`.

This is the first time I have faced such a problem in Go. I apologize in advance, @aarondl.

If the question is interesting (at least for newbies) I can update the wiki in the `authboss` integration section and vice versa.

**Comment by aarondl** [comment]
A type assertion is the correct way. Though in sqlboiler the idea is usually to simply make functions to extend your model to avoid the exact problems you're running into:

```
func SomeExtendedMethod(u *models.User) {
  // Do something
}
```

This avoids any type wrapping, is simple, I usually put these extensions/helpers in a `modelsx` package.

Your code looks correct, and I've done a similar thing in the past. I don't see a problem with it exactly.
