### ISSUE TITLE
(s XXXSlice) DeleteAll() should not return error for nil slice

### ISSUE THREAD

**Issue by nan0tube** [volatiletech/sqlboiler#506]
Currently, `emptySlice.DeleteAll()` returns an error only when `emptySlice` is `nil`. This does not allow the (preferred) usage of nil slice to make use of zero values in Go.

It also differs in behaviour with `(s XXXSlice) UpdateAll()` and `(s XXXSlice) ReloadAll()` where all empty slices do not return error.

**Comment by aarondl** [comment]
Agree, fixed on dev branch.
