### ISSUE TITLE
Upsert increment serial index even though a conflict has occurred

### ISSUE THREAD

**Issue by Keijun-KUMAGAI** [volatiletech/sqlboiler#507]
Hi! I am trying to create my first Golang application with this awesome ORM, and I think I found some bugs related to upsert function.

I'm using Postgres driver, go:1.12

My code is something like this.

```
type Organization struct {
	ID   int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name string `boil:"name" json:"name" toml:"name" yaml:"name"`
	Code string `boil:"code" json:"code" toml:"code" yaml:"code"`
}
```

```
err := newOrganization.Upsert(
	context.Background(),
	DB,
	true,
	[]string{"code"},
	boil.Infer(),
	boil.Infer(),
)
if err != nil { panic(err) }
```

I think when the Upsert method was used, the serial index is incremented at the same time, EVEN THOUGH, the Upsert didn't create a new record.
For example, I create { code: "111", name: "test_name" }, and the id is 1, of course. Then update it with the Upsert method in like three times.
After that, if I tried to create the new organization { code: "112", name: "test_name2" }  with the Upsert method, the id would be 4 in my database.

I really want to throw a PR to fix this problem, but as everyone say I'm a newbie in Golang.
If this is not a difficult fix, and someone tells me where I should fix, I would like to make a PR for that.

Thanks

**Comment by aarondl** [comment]
I'm fairly certain that this is simply postgres behavior because we never increment that value. Pretty sure this was brought up in the past. My suggestion is to try it in pure postgres with regular queries to ensure its sqlboiler's fault first and report back. Thanks for being willing to contribute :)

**Comment by Keijun-KUMAGAI** [comment]
I tried raw SQL execute, and found out it was Postgres's behavior!!

Thanks for your reply!
