### ISSUE TITLE
type replacement: db_type by default sets nullable = false

### ISSUE THREAD

**Issue by xc** [volatiletech/sqlboiler#509]
v3.2.0

If you only have db_type in [types.match] and DID NOT set nullable option, it will only replace columns where NOT NULL( meaning same as nullable = false ). 

It should omit all nullable settings in this case.

**Comment by aarondl** [comment]
Although I understand where you're coming from, I think the current behavior is desirable (however unexpected).

In our system null is a type-dividing criteria. `string` vs `null.String` and so I think it makes some sense that these stay separate and that the default is `null = false`.

The workaround of course is simply to create two type replacements one for null, one for not null.

**Comment by xc** [comment]
Thanks for the answer.
> In our system null is a type-dividing criteria
It makes sense based on this purpose.  Coping both "null" and "not null" by ignoring "null=<true/false>" is kind of confusing indeed.
