### ISSUE TITLE
Readme.md / LoadRels ?

### ISSUE THREAD

**Issue by sywesk** [volatiletech/sqlboiler#512]
In the readme, you mention a `LoadRels` method, that (after searching) doesn't seem exist. Did you mean `Load` ?

https://github.com/volatiletech/sqlboiler/blame/master/README.md#L1226

Thanks for this awesome library !

**Comment by jcloutz** [comment]
@sywesk You should be able to use this `qm.Load()`

https://github.com/volatiletech/sqlboiler/blob/master/queries/qm/query_mods.go#L101

**Comment by aarondl** [comment]
This is invalidated by changes on the `dev` branch, coming to `master` soon :)
