### ISSUE TITLE
How to add custom tag for different properties

### ISSUE THREAD

**Issue by longlongh4** [volatiletech/sqlboiler#52]
For example, I have a user model 

```
    type User struct {
    ID             int       `boil:"id" json:"id" toml:"id" yaml:"id"`
    Name           string    `boil:"name" json:"name" toml:"name" yaml:"name"`
    PasswordDigest string    `boil:"password_digest" json:"password_digest" toml:"password_digest" yaml:"password_digest"`
    Phone          string    `boil:"phone" json:"phone" toml:"phone" yaml:"phone"`
    CreatedAt      time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
    UpdatedAt      time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

    R *userR `boil:"-" json:"-" toml:"-" yaml:"-"`
    L userL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}
```

I want to change Name's tag to   

```
    Name string `boil:"name" json:"name" toml:"name" yaml:"name" valid:"Required;MinSize(5);MaxSize(26)"`  
```

so I can run my valid function to check if the parameter in http request is valid
and I also want to change passwordDiagest's json tag to `json:"-"`, so when I send user struct over http response, the password will not be included.

How to specific tags for different tables and different properties?

**Comment by aarondl** [comment]
Hey there @longlongh4.

So, we talked about adding a feature to add specific tags to each column. It's not a very hard feature to implement so we'll consider it. We would probably add something to the configuration file to be able to tweak each tag per table per column.

In the meantime I'd suggest using a validator that doesn't require struct manipulation such as https://github.com/kat-co/vala

**Comment by aarondl** [comment]
Decided we're not going to do this for the time being.
