### ISSUE TITLE
Table named "updates"

### ISSUE THREAD

**Issue by tzachshabtay** [volatiletech/sqlboiler#526]
If my table is named "updates" (and I imagine "inserts" will have the same issue), sqlboiler generates code that doesn't compile.
This is because it generates `updateColumns` in two places.

1. As a var:
```updateColumns               = []string{...}```
This comes from the table name, I believe.

2. In the Upsert method there's an argument named updateColumns (and I imagine that one is hard-coded).

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.1.0

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`sqlboiler -c ./sqlboiler.toml -o ./internal/models --wipe psql`

**Comment by stuartgrigg** [comment]
Had a go at fixing this - feedback welcome!

**Comment by aarondl** [comment]
Hi @stuartgrigg. I really appreciate you diving in and fixing it. Had you not submitted this PR the answer to this question would have simply been to use aliases to rename the table and I don't think the problem would have remained. I'll make more comments on your PR.

**Comment by aarondl** [comment]
Should be closed by Stuart's PR that's in 3.4.0 now.
