### ISSUE TITLE
Preserve extensions inside models folder during regeneration

### ISSUE THREAD

**Issue by sidot3291** [volatiletech/sqlboiler#527]
Thanks so much for creating this package.  We're also coming from ActiveRecord and were struggling other ORMs.  The DB first approach is much appreciated.

We currently extend every boiler-generated model with a corresponding package.  e.g if there's `models.Foo` we create a `foo` package.  This is where we define hooks and any helpers, e.g:
```
func CompositeField(f models.Foo) int {
  return (f.A + f.B)
}
```

We'd prefer to extend the models structs directly, e.g:
```
func (f models.Foo) CompositeField() int {
  return (f.A + f.B)
}
```

We can't really do this today since we regenerate models frequently.  But perhaps there could be a convention for preserving code inside models folder, that would allow us to extend the models directly?

**Comment by aarondl** [comment]
In this case simply fork the templates and point sqlboiler to them with the templates command line arg. Note the documentation in the Readme about this. This is of course discouraged as you lose any updates or bug fixes we make (like forking other code). Enjoy :D
