### ISSUE TITLE
Multiple Database 

### ISSUE THREAD

**Issue by Kartikkh** [volatiletech/sqlboiler#531]
I have Multiple Table to use in the project, But these tables are in a different postgres database.
So does SqlBoiler supports this?

Multiple Database config seems not to be working in sqlboiler.toml file

[psql]
  dbname = "db2"
  host   = "x.x.x.x"
  port   = 5432
  user   = "abcd"
  pass   = "12345789"
  sslmode = "disable"

[psql]
  dbname = "db1"
  host   = "x.x.x.x"
  port   = 5432
  user   = "abcd"
  pass   = "12344789"
  sslmode = "disable"

**Comment by aarondl** [comment]
Currently there is no support for one set of models to be generated for two separate databases. The typical approach here is to create two configuration files, and generate two sets of models. This should work fine, although there is no support for tables that span schemas in sqlboiler (like having a foreign key into a separate table schema). Hopefully that helps.

**Comment by FloThinksPi** [comment]
@aarondl Suppose my webserver application supports both, mysql and postgres. I thus generated both models from their respective DB.
What whould be the typical approach you talked above to use them ?

Given i have a http handler function, i would need to distinguish everytime i call a boiler operation between both databases e.g. 
``` golang
import (
...
	mysqlModels "github.com/FloThinksPi/golang-vuejs-bootstrap/internal/app/gopilot/sqlboiler/mysql"
	psqlModels "github.com/FloThinksPi/golang-vuejs-bootstrap/internal/app/gopilot/sqlboiler/postgres"
...
)

func InsertPilot(c echo.Context) error {
...
	if config.Get().DB.Type == "postgres" {
		p1 = psqlModels.Pilot{}
                p1.Name = "Larry"
                err := p1.Insert(ctx, db, boil.Infer())
....
	} else {
		p1 = mysqlModels.Pilot{}
                p1.Name = "Larry"
                err := p1.Insert(ctx, db, boil.Infer())
...
	}
...
}
```
Or as an alternative i could register different http handlers depending on the used database and implement the complete logic twice which also does not seem logical to do. 

As conditional imports are not possible in a static compiled language i see no easy method of using this right ?

**Comment by aarondl** [comment]
Yeah I don't think there's any easy way to do that :| Sorry, not built with these sorts of truly polymorphic examples in mind.

**Comment by FloThinksPi** [comment]
@aarondl we found quite a nice way around that limitation using build tags. Since both interfaces for PSQL and MYSQL are (nearly) identical, we generated them both into the same package and added build tag mysql or psql programatically after sqlboiler generated the file. One ends up with e.g.

```
-- File models/pilot_psql.go
# // +build psql
package models
....

-- File models/pilot_mysql.go
# // +build mysql
package models
....
```

At build time one would build 2 seperate binaries for each db backend. At least that way one does not poison buisniss logic with code for different db backends :) .

We also improved sqlboiler in regards to writing unittests(mocking), maybe once we make our work public we could share this all in depth with you if you are interested.
