### ISSUE TITLE
Whitelist / Blacklist / Graylist naming confusion?

### ISSUE THREAD

**Issue by k3a** [volatiletech/sqlboiler#547]
I am enjoying sqlboiler and everything seems pretty clear except I find column specifier naming a bit confusing. I memorized it as you made it but somehow naturally I would expect something like this (for insert):
- blacklist: insert all non-zero fields except these blacklisted
- whitelist: insert all non-zero fields but also those whitelisted
- only: insert only specified non-zero fields 
- exact: insert the exact list of columns (do not infer)

maybe this naming (only and exact) is not really perfect. But what I want to say is that I think whitelist usually means "make an exception to something which is not normally part of the rule. But in the case of sqlboiler it means the actual final columns to use. 

This is just my feeling and maybe I am the only one who feels it this way. Feel free to close it if you find it useless. I just wanted to give some feedback. Otherwise I am really happy with the library and thanks a lot for making it!

**Comment by aarondl** [comment]
Hi @k3a I don't disagree with you actually. I appreciate the feedback. But it's one of those things that isn't worth the time to fix now. Time being my/your time to fix it and update the docs, and the time it takes for everyone to understand and adopt the change. Would that you were around to make the suggestion when we were coming up with this stuff it probably would have been more correct, thanks for bringing it up anyway :)
