### ISSUE TITLE
opentracing support please (feature request)

### ISSUE THREAD

**Issue by thetruechar** [volatiletech/sqlboiler#551]
Hi, can we support opentracing for query and exec? Add something like below in QueryContext and ExecContext?

 ```golang
	span, _ := opentracing.StartSpanFromContext(db.ctx, "DB Query")
	span.LogFields(otlog.String("sql.query", fmt.Sprint(sql, ",", args)))
	defer span.Finish()
```

**Comment by aarondl** [comment]
You can already do tracing with opencencus using contexts. There's no work to be done here, I've done a demo of this in this youtube video as well (near the end): https://www.youtube.com/watch?v=M9bgMOLQLs8
