### ISSUE TITLE
go-sqlmock's canonical import path has changed from gopkg.in to github.com

### ISSUE THREAD

**Issue by zikaeroh** [volatiletech/sqlboiler#553]
`go-sqlmock`'s canonical import path was changed from `gopkg.in/DATA-DOG/go-sqlmock.v1` to `github.com/DATA-DOG/go-sqlmock` when they started supporting go modules.

Since `sqlboiler` still imports the library using the old path, projects using go modules to depend on `sqlboiler` will get messages about the "missing" dependency until a replace directive is added to point the old path to the new one, like:

```
replace gopkg.in/DATA-DOG/go-sqlmock.v1 => github.com/DATA-DOG/go-sqlmock v1.3.3
```

Not doing so doesn't have any major effects unless you do something like `go test all`, but I think it'd be a good idea to import the new recommended import path (and I'd be happier with one fewer `replace` to maintain).

Forgive my deletion of the template, but I didn't think it really fit.

**Comment by aarondl** [comment]
Addressed by your pull request, fixed on dev for now. Thanks very much :)
