### ISSUE TITLE
support camel case in table names

### ISSUE THREAD

**Issue by bugzpodder** [volatiletech/sqlboiler#557]
My db tables names are CamelCase, it seem to integrate weirdly with sqlboiler.  The models are generated but there are a lot of duplicate methods caused by foreign key:
For example, a UserId column would generate a UserId field and a UserId function.

Propose that a flag be added to support camel case table names.

**Comment by bugzpodder** [comment]
https://github.com/volatiletech/sqlboiler/pull/558

**Comment by aarondl** [comment]
Closing this in favor of #561
