### ISSUE TITLE
Add query mod for FORCE INDEX and USE INDEX

### ISSUE THREAD

**Issue by tiger5226** [volatiletech/sqlboiler#562]
Currently, if I am forming a query with sqlboiler, I don't have the option to specify the index to use. This becomes important for performance of the query when there are multiple filters on a large table where you want it to use a multi column index. Unfortunately, MySQL choosing the first complying index. So if you have a single column index already for a column used in your filtering then it will use that index, rather than the multi-column index you intended for it to use. 

In the meantime is there a way to insert text after the `FROM` statement so I can workaround this or do I just need to do a raw query?

**Comment by aarondl** [comment]
You can do a `.From()` on the query and add whatever you'd like there I believe. It depends how complicated the statement ends up being I suppose. If you're looking to append text to the end of your query see #214 

```
.From("thistable etc")
```
