### ISSUE TITLE
[Question] How to get complex unique key and primary key infromation.

### ISSUE THREAD

**Issue by bannzai** [volatiletech/sqlboiler#564]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
```bash
$ sqlboiler --version
SQLBoiler v3.4.0
```

## Question
Hi, I have a question. How to get information for `complex unique key` and `complex primary key` from sqlboiler? 

I want to use complex unique key and primary key informations. But I do not found these information from [mysql-driver](https://github.com/volatiletech/sqlboiler/blob/master/drivers/sqlboiler-mysql/driver/mysql.go#L186) and [Table struct](https://github.com/volatiletech/sqlboiler/blob/master//drivers/table.go#L6). 

Here is an example `mysql Create Tables SQL` for my question. So,  I want to extract user_id and hash paris from sqlboiler. (like { .UniqueInfos })

```
CREATE TABLE `user_id_hash` (
  `user_id` int(10) unsigned NOT NULL,
  `hash` varchar(32) NOT NULL,
  `name` varchar(40) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`user_id`,`hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

Thank you.

**Comment by aarondl** [comment]
It's in the PrimaryKey part of the Table struct you linked. As for compound unique keys, we don't deal with those at the moment and so sqlboiler has no accounting of it.
