### ISSUE TITLE
[Question] How to use int slice within raw query.

### ISSUE THREAD

**Issue by touyu** [volatiletech/sqlboiler#567]
I wrote as follows but it did not work well.
```go
query := queries.Raw(`SELECT * FROM users where in (?)`, []int{1, 2, 3})
query.Bind(ctx, db, &users)
```

Please let me know what kind of method there is.

**Comment by tzachshabtay** [comment]
1. Your sql is invalid, you didn't give a column name (I'm guessing id?)
2. You should import "github.com/volatiletech/sqlboiler/types" and use types.Array.

So, for example:

```go
import (
   ...
   "github.com/volatiletech/sqlboiler/types"
)

func() {
   param := types.Array([]int{1, 2, 3})
   queries.Raw(`SELECT * FROM users where id = ANY($1)`, param).Bind(...)
}

```

**Comment by aarondl** [comment]
Thanks for answering this @tzachshabtay
