### ISSUE TITLE
SQLBoiler tests require connect privileges 

### ISSUE THREAD

**Issue by hugbubby** [volatiletech/sqlboiler#579]
The platform I'm hosting my postgresql instance on, Heroku, gives developers read-write access to a database but not an administrative user. Thus, whenever I run the tests, I get:
```
dropdb: could not connect to database template1: FATAL:  permission denied for database "template1"
DETAIL:  User does not have CONNECT privilege.              
```

Until there's a way to disable the parts of the tests that do this, I'm gonna have to disable test generation and/or not run them, which sucks :(

**Comment by aarondl** [comment]
Tests are meant to be run once at the beginning in general on a developer machine, not really CI related. I'm not 100% concerned about this.
