### ISSUE TITLE
Does sqlboiler support nested queries?

### ISSUE THREAD

**Issue by kevinmu** [volatiletech/sqlboiler#581]
I'd like to write something like

"SELECT id FROM table1 WHERE id NOT IN (SELECT DISTINCT(id) FROM table2 WHERE field > 5)"

I recognize I could do a join (maybe?), but the actual query gets much more complicated and is much more clear when written out in a nested form. I also realize I could use `qm.SQL`, but the thing is I want to combine this part of the statement with other query mods, so it would be nice if I could use the querymod model.

Is this nested query format supported by sqlboilder and the querymod model? Thanks for your help!

**Comment by aarondl** [comment]
Querymods and Raw queries don't really mix. There's no good inbetween. I'd encourage you to do a raw query, but you can still `fmt.Sprintf` the `models.UserColumns.Name` like constants into it. That's what I do.
