### ISSUE TITLE
undefined ...AllColumns

### ISSUE THREAD

**Issue by muhammadnaufala** [volatiletech/sqlboiler#582]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
3.2.0 and 3.4.0

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler psql

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
models/transactions.go:848:4: undefined: transactionAllColumns

and many more

if i remove 'All' so just transactionsColumns, i didn't get error

**Comment by aarondl** [comment]
Possible you haven't updated the psql driver as well. It's a separate binary with references to this variable.

**Comment by muhammadnaufala** [comment]
ok thank you aaroondl
