### ISSUE TITLE
Cast values on user defined types (postgres)

### ISSUE THREAD

**Issue by arsham** [volatiletech/sqlboiler#585]
### SQLBoiler Version
`v3.4.0`

### Generation Command
```bash
sqlboiler --wipe --no-hooks psql
```
### Database Schema

```sql
CREATE TABLE example (
    id SERIAL PRIMARY KEY,
    some_id uuid NOT NULL
);
```

### Types
```yaml
[[types]]
  [types.match]
    db_type = "uuid"

  [types.replace]
    type = "uuid.UUID"

  [types.imports]
    third_party = ['"github.com/gofrs/uuid"']
```

### Expectation

When I insert an item this is the query that is being produced:
```sql
INSERT INTO "example" ("id","some_id") VALUES ($1,$2)
```
Is there a way to have sqlboiler include casts for user specified types?
```sql
INSERT INTO "example" ("id","some_id") VALUES ($1,$2::uuid)
```

Thank you.

**Comment by aarondl** [comment]
There is no way for it to produce that kind of query currently. Is it a problem? I use uuid in postgres and passing strings along without explicit casts is just fine.

**Comment by arsham** [comment]
Casting would be useful in some cases. Having read the part of the code that produces the placeholders (`strmangle.Placeholders`), I suppose it would add too much complexity for implementing a solution.

Thank you for this amazing library. We use sqlboiler in production and we are very please with the results.

**Comment by aarondl** [comment]
Glad to hear it @arsham, thanks for the kind words :)
