### ISSUE TITLE
[templates] provide Columns() and ColumnToTable() functionalities Slices on unique columns

### ISSUE THREAD

**Issue by bugzpodder** [volatiletech/sqlboiler#586]
If a column is unique, provide Columns() and ColumnToTable functionalities on the slice object:

For example, if User has primary key id and Unique Column email, provide:
(s *UserSlice) Ids() []int 
(s *UserSlice) IdToUser() map[int]*User
(s *UserSlice) Emails() []string
(s *UserSlice) EmailToUser() map[string]*User

**Comment by aarondl** [comment]
Can you elaborate on some use cases for this functionality?

**Comment by bugzpodder** [comment]
It's simply helpers, its something I use quiet often.  I can look into adding them to templates if thats desired.

**Comment by aarondl** [comment]
I'd rather not. We want to maintain as tight a core as possible, just the essentials. These sorts of helpers are a great candidate for a modelsx package :D Thanks for discussing the idea though!

**Comment by bugzpodder** [comment]
Sounds good!
