### ISSUE TITLE
column name not quoted for postgresql

### ISSUE THREAD

**Issue by Place1** [volatiletech/sqlboiler#591]
Hi, i'm working with a legacy DB that already uses "PascalCase" for table and column names.

I've work around a bunch of issue using aliases (thanks so much for that feature btw :D) but i've run into a problem with related entity methods. For example, [in this template](https://github.com/volatiletech/sqlboiler/blob/master/templates/04_relationship_to_one.go.tpl#L10) the `$fkey.ForeignColumn` isn't quoted so i end up with:

```
queryMods := []qm.QueryMod{
	qm.Where("ID=?", o.OtherID),
}
```

To fix the issue I need: ```qm.Where(`"ID"=?`, o.OtherID),```

Any chance this can be merged into the templates? I'm not sure about impacts on other db drivers.

Or am i supposed to work around this via a config value somehow? Thanks

**Comment by aarondl** [comment]
Ah these things should always be quoted properly. We should fix this.
