### ISSUE TITLE
Proposal: Target column by table name for types.match

### ISSUE THREAD

**Issue by stephenafamo** [volatiletech/sqlboiler#599]
When controlling the generation, it would be great to be able to create custom types for columns in specific tables.

As an example, I tend to add a "metadata" JSON column to my tables. To have an easier time, I'd like to create a specific JSON struct representation for each table. However, it does not seem that there is a way to do that.

Another example is when I want to emulate an "enum" constraint for databases that do not support it.

## Current Work Around

My current process is to name the column something unique that is unlikely to be repeated an then target that specific column to overwrite. However, this is makes my DB schema quite dirty.

**Comment by akshaylb** [comment]
+1

I see this being useful too

**Comment by kshamiev** [comment]
The necessary opportunity.
To be able to differentiate custom types within tables

example:

There are (order status) and (user status).
But these are different sets of values!

And there are a lot of such obvious tasks.
