### ISSUE TITLE
Insert issue for types.Decimal in Go v1.13 (works on v1.12)

### ISSUE THREAD

**Issue by crlssn** [volatiletech/sqlboiler#607]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.5.0

### If this happened at runtime what code produced the issue?
I'm trying to do a simple database insertion with 
```go
type Model struct {
    Value types.Decimal `boil:"value" json:"value toml:"value" yaml:"value"`
}

Model{
    Value: types.NewDecimal(&decimal.Big{})
}.Insert(context.Background(), f.db, boil.Infer())
```
it fails and returns
```
test panicked: ledger: unable to insert into accounts: pq: encode: unknown type for types.Decimal
```

### What is the output of the command above with the `-d` flag added to it?
This only returns the SQL query which I can copy and run succesfully in my postgres console.

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```pg
CREATE TABLE table (value DECIMAL(78,18) NOT NULL);
```

**Comment by crlssn** [comment]
> In my GOPATH I have ericlagergren/decimal: 0bb1631 and this works.

Yeah, that seems to be the problem. We were using the latest (at the time) `f05d339` where this problem occoured but has since bypassed it by using `apd.Decimal` from https://github.com/cockroachdb/apd. You might want to consider replacing SQLBoiler's decimal as well.

**Comment by hiromaily** [comment]
+1

**Comment by aarondl** [comment]
For those of you waiting on this issue, I suggest you do not use the `master` version of `ericlagergren` decimal as it does not currently work. This appears to be some problem with the recent addition of the new decomposer interface to Go 1.13. I'll be following up with eric.

**Comment by aarondl** [comment]
ericlagergren/decimal@v3.3.1 appears to work.

**Comment by zamai** [comment]
hey @aarondl, how were you able to use `ericlagergren/decimal@v3.3.1` in you go mod? 
I'm getting hit with the issue reported here: https://github.com/ericlagergren/decimal/issues/112 
It also seems that there is a PR attempting to fix this: https://github.com/ericlagergren/decimal/pull/139, but it isn't merged. 

Looking for a temporary workaround until `ericlagergren/decimal@v3.3.1` is available from go mod

**Comment by zamai** [comment]
Update: my workaround  was to use go1.12 until this issue would be fixed in `ericlagergren/decimal`

**Comment by aarondl** [comment]
@zamai In module mode it appears there may be nothing you can do. Eric's got to fix it in his library. When I was experimenting it was with `GOPATH` and of course there's no problems there :) As much as I love the modules feature it's sure been a disaster from obsolete tooling, to the Go command's implementation of modules being very bad to the whole semantic import path thing for major versions messing up many libraries (Eric's included)... It feels like our own py2 -> py3 :) But at least we'll make it through if we keep pushing.

**Comment by Dexus** [comment]
hey, is there any progress or when will this issue fixed? Its pritty shit if you have to switch to the old days again to use this lib. Modules should today work...

**Comment by aarondl** [comment]
@Dexus I'm not sure why you're commenting here about it as there's nothing this library can do. It's a problem with the decimal library.

Also the change was reverted in the decimal library so it should be a non-issue now.

**Comment by Dexus** [comment]
@aarondl its not...

but if you add a `replace github.com/ericlagergren/decimal => github.com/ericlagergren/decimal v0.0.0-20181231230500-73749d4874d5` to your go.mod it works now for now.

but at the end, you should add a notice to the readme for the mates that have this problem...

**Comment by aarondl** [comment]
sqlboiler doesn't support the use of modules so there's no need to do anything. If you choose to use modules you're on your own. If it works, great. If it doesn't, well you should invest into finding a solution on your own since you opted into that unbelievably painful world.

**Comment by RichardLindhout** [comment]
@aarondl A few moments later :-P

**Comment by RichardLindhout** [comment]
Not that I disagree though: https://twitter.com/RichardLindhout/status/1256555199684063232

**Comment by RichardLindhout** [comment]
Anyway this issue pops up again: replace github.com/ericlagergren/decimal => github.com/ericlagergren/decimal v0.0.0-20181231230500-73749d4874d5
 in my gomod fixed the issue.

**Comment by aarondl** [comment]
https://github.com/volatiletech/sqlboiler/#diagnosing-problems

> decimal library showing errors like: pq: encode: unknown type types.NullDecimal is a result of a too-new and broken version of the github.com/ericlargergren/decimal package, use the following version in your go.mod: github.com/ericlagergren/decimal v0.0.0-20181231230500-73749d4874d5

Replace I think is the wrong thing to use there. I'd suggest simply locking the version to this known good commit.
