### ISSUE TITLE
Expand support for whereHelperXXX.IN helper method

### ISSUE THREAD

**Issue by nwidger** [volatiletech/sqlboiler#609]
Release v3.5.0 added support for wherein helpers for `int` and `string` types (via PR #575).  In the relevant template, this is implemented via the `qm.WhereIn` function, which takes some number of `interface{}` arguments as the values to match against.  My understanding is that any type can be passed so long as it is either one of the base types supported by `database/sql` or it implements the `driver.Valuer` interface.  At generation-time I realize it may not be simple to determine if a field's type implements the `driver.Valuer` interface, but would it be possible to at least have sqlboiler's template generate `whereHelperXXX.IN` methods for any of the base types that `database/sql` supports?  I believe the base types supported by `database/sql` are documented here:

https://godoc.org/database/sql#Rows.Scan

I ran into this issue when I read the release notes for v3.5.0 and tried to use the new `whereHelperXXX.IN` method for my `int64` field only to discover that it is only generated for fields with type `int`.

I'm happy to create a PR for this once it's been accepted and any details ironed out.

**Comment by aarondl** [comment]
Wouldn't turn this down. The more static helpers the better really.

**Comment by nwidger** [comment]
Do you see any reason to not generate `whereHelperXXX.IN` helper methods for all field types?  I.e. to just remove the `if` condition surrounding the template here?

https://github.com/volatiletech/sqlboiler/blob/master/templates/00_struct.go.tpl#L50

**Comment by aarondl** [comment]
It's been too long now I'm not sure why it was done this way. One possibility is that equality for all types may be a wishy washy thing and it might net work. Another much more likely possibility is sqlboiler's crazy imports.

Each file needs to import the right packages and this needs to be known ahead of template time to inject the proper imports into the templates. At least this is how it behaves today, perhaps it would have been smarter to be able to declaratively load packages but the black magic we've added to our usage of `text/template` has reduced the kitten population significantly already.

See hacks to work around that type of problem here:
https://github.com/volatiletech/sqlboiler/blob/master/templates/01_types.go.tpl#L43

So given that I think it's best if we stick to primitive types that are supported in the database/sql package. That probably means:

```text
These:
*string
*[]byte
*int, *int8, *int16, *int32, *int64
*uint, *uint8, *uint16, *uint32, *uint64
*bool
*float32, *float64

But not these:
*interface{}
*RawBytes
*Rows (cursor value)
any type implementing Scanner (see Scanner docs)
```

Also torn on []byte, as I'm not sure the database/sql nor database drivers will do what we expect there...

**Comment by nwidger** [comment]
I see we're in rather tricky waters here.  I'm fine with restricting the helpers to just those supported by database/sql, but want to avoid having an enormous conditional in the template.  I see that there is an existing template helper `isPrimitive`:

https://github.com/volatiletech/sqlboiler/blob/df8550538fefdf62f2520e74dbfad73f1bcb84a2/boilingcore/text_helpers.go#L127:6

Would it make sense to simply use `isPrimitive` in the template or should a new helper be defined, perhaps `isSupportNatively`, which specifically returns true iff a type is natively supported by database/sql?

**Comment by aarondl** [comment]
That should be fine. Though `isPrimitive` was originally used to ensure we could use the equality operator in Go, it seems to pretty much match up exactly. Given that I'm not sure how `[]byte` would work I think it's better to avoid that anyway.
