### ISSUE TITLE
[question] does UpdateAll cast values?

### ISSUE THREAD

**Issue by quillaja** [volatiletech/sqlboiler#610]
Just a question so I can confirm the behavior I think I'm seeing. I'm using sqlboiler with a sqlite3 database. I have a column declared `DATE` which of course is a "fake" type in sqlite3. In the generated `models` package, this is a `time.Time` in the struct representation of my table, as expected.

Anyway, from my front end, I'm getting a JSON object with user-made changes to a grid widget. The grid is essentially just showing the table in my db. I'm unmarshaling the JSON object into a `map[string]interface{}` where `string` is the column name in the db and `interface{}` is the updated value from the grid widget. For dates, this unmarshals into a `string`.

When I use `UpdateAll()` on a table I can pass a `models.M` which is a `map[string]interface{}`. Super convenient, right?  However, for the DATE column, it appears the string in my own map is simply being passed through to the query & database, **not** being "coerced" (type cast?) into `time.Time` first.

Am I correct to assume this is the expected behavior?

**Comment by aarondl** [comment]
@quillaja This is expected behavior. You're required to pass something into the `UpdateAll` that your underlying sql driver (`sqlite3` in this case) can understand.
