### ISSUE TITLE
[bug?] useless SQL fired after insert

### ISSUE THREAD

**Issue by johnsiu2016** [volatiletech/sqlboiler#612]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.5.0

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
![image](https://user-images.githubusercontent.com/17636906/65815646-dca4d200-e224-11e9-9996-07ca17adefc5.png)
![image](https://user-images.githubusercontent.com/17636906/65815675-550b9300-e225-11e9-884d-83d2d66b8b80.png)

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```mysql
CREATE TABLE `course` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tutor_id` int(10) unsigned NOT NULL,
  `subject_id` int(10) unsigned NOT NULL,
  `price` int(10) unsigned DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `course_tutor_fk_idx` (`tutor_id`),
  KEY `course_subject_idx` (`subject_id`),
  CONSTRAINT `course_subject_fk` FOREIGN KEY (`subject_id`) REFERENCES `subject` (`id`),
  CONSTRAINT `course_tutor_fk` FOREIGN KEY (`tutor_id`) REFERENCES `tutor` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

### Further information. What did you do, what did you expect?
https://github.com/volatiletech/sqlboiler/blob/593a7e2d9aeec5e9748e93d7225c95c3896aa558/templates/15_insert.go.tpl#L145
I think the column name should not be titleCase ? The "ID" in the above screenshot should be "id" to make this condition pass and get rid of this SQL
```mysql
SELECT `id` FROM `course` WHERE `id`=?
```
If we have the id why we want to select the id again ?

**Comment by aarondl** [comment]
@johnsiu2016 Thanks for the report. It used to be that struct mappings were created with names that were the same as their struct, but this commit f5e6d47 changed that. This happened an insanely long time ago and so I'm surprised this bug is only coming up now, thanks very much for the report. Fixed on dev branch.
