### ISSUE TITLE
Syntax error OFFSET query in v3.6.0

### ISSUE THREAD

**Issue by kkoudev** [volatiletech/sqlboiler#631]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

3.6.0

### What is your database and version (eg. Postgresql 10)

MySQL 8.0
MariaDB 10.3

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

```golang
dbUsers, err := models.Users(
  qm.Limit(10),
  qm.Offset(0),
).AllG(ctx)
```

This code generates a query like this.

```sql
SELECT `users`.* FROM users LIMIT 10 OFFSET 0 ROWS;
```

This `ROWS` keyword is syntax error in MySQL.
Probably this fix is ​​affecting.
https://github.com/volatiletech/sqlboiler/commit/5b70000f52e7e63c8b1b677f70c2ed2374eaa06d

### Further information. What did you do, what did you expect?

Do not assign the `ROWS` keyword for OFFSET query except for SQL Server.

**Comment by manjdk** [comment]
This is what i am getting when trying to retrieve items using offset:
`"failed to assign all query results to LeaveType slice: bind failed to execute query: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ROWS' at line 1"`

**Comment by JerzyLa** [comment]
I face the same issue in our project, please fix it soon.

**Comment by kkoudev** [comment]
I've created the PR fixed this issue.
https://github.com/volatiletech/sqlboiler/pull/632

Please review it.
@aarondl

**Comment by aarondl** [comment]
Sorry about this. Was my mistake.
