### ISSUE TITLE
sqlboiler 3.6.1 cannot convert type: types.Decimal

### ISSUE THREAD

**Issue by rogerdehe** [volatiletech/sqlboiler#633]
I am using 

    sqlboiler 3.6.1
    mysql  Ver 14.14 Distrib 5.7.27

My table schema is very simple:

	CREATE TABLE `v9_member` (
	  `userid` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
	  `amount` decimal(8,2) unsigned NOT NULL DEFAULT '0.00',
	  PRIMARY KEY (`userid`)
	) ENGINE=InnoDB AUTO_INCREMENT=314481 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

I generate with config file like this:

	[mysql]
	    dbname="dbname"
	    host="localhost"
	    port=3306
	    user="user"
	    pass="pass"
	    sslmode="false"
	    testdbname="youjudata_test"
	    whitelist=["v9_member"]

It's OK for now. But then I run `go test ./models`, I got error like this:

    v9_member_test.go:613: models: unable to update v9_member row: cannot convert type: types.Decimal

**Comment by eduardhasanaj2** [comment]
@aarondl I am hitting this problem after upgrading to v3.6.1
Is there any workaround?

**Comment by aarondl** [comment]
Sorry I missed responding to this earlier. The problem is that the ericlagergren/decimal has some problems at `master`. Please revert to using a named tag: v3.3.1 works.
