### ISSUE TITLE
Custom template

### ISSUE THREAD

**Issue by Jeeyb** [volatiletech/sqlboiler#635]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.6.1

### What is your database and version (eg. Po stgresql 10)
PostgreSQL 11.5 

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

CREATE TABLE user
(   user_id integer PRIMARY KEY,  
 username VARCHAR (50) )

### Further information. What did you do, what did you expect?
I really love your lib, but i need setup custom template for generating 3 things:
1) TableNames
2) User struct(with custom tags, like 'json'/'db' etc)
3) UserColumns

Can you pls help me with templates, what templates should i take from your lib and how should i customise.
Regards and best wishes Jeeyb.

**Comment by aarondl** [comment]
Hi @Jeeyb we're not really in the business of providing support but especially not when it comes to custom templates. You'll have to dig into the code and the templates and figure it out. Good luck!
