### ISSUE TITLE
What to do with extra connection string arguments

### ISSUE THREAD

**Issue by DGollings** [volatiletech/sqlboiler#636]
Hi,

Didn't open a pull request as I'll assume you'll (rightfully) reject it.
The issue is is that I need full ssl verification for my connection, and added some options to the interface to do so whilst making the necessary changes to the crdb driver. But unfortunately these options are postgres/cockroach specific.

https://github.com/DGollings/sqlboiler/commit/9e88e40d8b362944d5355a013d69ddd95a3a31f0

What would you say would be a good way to add these extra options in a reasonably abstract manner? Even though they have different names, I assume all drivers have similar functionality?

Or add the global ability to pass extra args/options without parsing them?

So
[driver]
extra_args = ["","",""]

**Comment by aarondl** [comment]
Remember that the connection options are only for code generation. Code generation happens typically on a developers desktop where TLS is not required. You could also code gen in CI as a check to make sure Devs didn't forget to generate but there's no reason to have TLS there either.

When you actually connect to your database to use it in your app (where TLS should be used) the sqlboiler config isn't used, you create the connection string manually and likely from your own config file.

So I don't believe these are useful options.

**Comment by DGollings** [comment]
I prefer keeping things identical to production, but can understand the reasoning
