### ISSUE TITLE
MySQL driver: cannot INSERT IGNORE

### ISSUE THREAD

**Issue by Dot-H** [volatiletech/sqlboiler#637]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v3.6.0

### What is your database and version (eg. Postgresql 10)

MySQL 8

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

```golang
pdid.Upsert(dbCtx, tx, boil.Whitelist(), boil.Infer())
```

Anytime I have tried to pass an empty column list to the `updateColumns` argument I get the error
` could not build update column list`.

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```mysql
--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `uuid` bigint(20) UNSIGNED NOT NULL,
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Table structure for table `physical_did`
--

CREATE TABLE `physical_did` (
  `owner_uuid` bigint(20) UNSIGNED NOT NULL,
  `id` bigint(20) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Indexes for table `physical_did`
--
ALTER TABLE `physical_did`
  ADD PRIMARY KEY (`owner_uuid`),
  ADD UNIQUE KEY `id` (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`uuid`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `uuid` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `physical_did`
--
ALTER TABLE `physical_did`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;
--
-- Constraints for table `physical_did`
--
ALTER TABLE `physical_did`
  ADD CONSTRAINT `uuid` FOREIGN KEY (`owner_uuid`) REFERENCES `users` (`uuid`) ON DELETE CASCADE ON UPDATE CASCADE;

```

### Further information. What did you do, what did you expect?

By looking at the code I see that this is due to [this check](https://github.com/volatiletech/sqlboiler/blob/5a51e7228cba48f4f40e542504540fcd8b14b26b/drivers/sqlboiler-mysql/driver/override/templates/17_upsert.go.tpl#L102).

I don't think it should return an error since the `len(update) == 0` check is also done in the [buildUpsertQueryMySQL](https://github.com/volatiletech/sqlboiler/blob/df8550538fefdf62f2520e74dbfad73f1bcb84a2/drivers/sqlboiler-mysql/driver/override/templates/singleton/mysql_upsert.go.tpl#L14) in order to know if the function should create a `INSERT IGNORE`. Function which is called two lines after [the check causing the error](https://github.com/volatiletech/sqlboiler/blob/5a51e7228cba48f4f40e542504540fcd8b14b26b/drivers/sqlboiler-mysql/driver/override/templates/17_upsert.go.tpl#L102).

**Comment by aarondl** [comment]
Seems like a reasonable change. Going in the backlog as a bug, but because it's mysql + upsert + specific use case it's not high on the priority list. Would accept a PR.
