### ISSUE TITLE
Is UpdateAll method supposed to update `updated_at` sql column ?

### ISSUE THREAD

**Issue by SlevinWasAlreadyTaken** [volatiletech/sqlboiler#640]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v3.5.0

### What is your database and version (eg. Postgresql 10)
Postgresql 11.4

### What did you do, what did you expect?
I am using UpdateAll method to update many rows of a single model.

Since the model has an `updated_at` column and so an UpdatedAt field, I was expecting UpdateAll would set the UpdatedAt to current time as it is done in Update model method.

It seems it is not handle this way. Is that an expected behavior ?

Thanks in advance.

**Comment by aarondl** [comment]
This is actually expected. And it's because update all uses a whitelist mechanism.

If we didn't do it this way there'd be no way of preventing the timestamp update and we never want to force behaviour like that. Although it's true we could use context to stop that update. It's also true not everybody uses context yet. So we're stuck for now :/

**Comment by SlevinWasAlreadyTaken** [comment]
Thanks for the quick answer.

Then I do update myself the `updated_at` field calling UpdateAll method.
It is not a big deal but the inconsistent behavior led my team to make mistakes about it :)

Feel free to close this ticket or let it open and do not hesitate to write us here if you see a potential solution we could help to implement.

**Comment by aarondl** [comment]
This behaviour happens anywhere there's a whitelist so you do need to be careful. This is not the first time I've heard the complaint about the inconsistency.

Maybe in v4 there needs to be a pass done on this when we have a license to break things :D

**Comment by lotsofone** [comment]
if updated_at is created this way:
```
`updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
```
Will it be updated to current time?

**Comment by aarondl** [comment]
@lotsofone yes, but the database is going to update that as per its mechanics. sqlboiler won't be doing anything there.
