### ISSUE TITLE
PostgreSQL/SQLBoiler complains on `int64` slice with `AND IN (?)`

### ISSUE THREAD

**Issue by gencer** [volatiletech/sqlboiler#644]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.6.1

### What is your database and version (eg. Postgresql 10)
PostgreSQL 12

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
 --

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
```go
IDs := types.Array([]int64{1198, 1199})
// or
// IDs := types.Array(intArrayFromMethod)

modifier, err := models.Emails(
  Where("user_id = ?", UID),
  AndIn("id IN ?", IDs),
).UpdateAll(Db, mset)
```

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
--

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```
upd 0 models: unable to update all for emails: pq: invalid input syntax for type bigint: "{1198,1199}"
```
### Further information. What did you do, what did you expect?
How can i pass `int64` slice as `IN` query? Following code does not seems to work with `bigint`'s.

**Comment by gencer** [comment]
For workaround i have converted them to interface as:

```go
CIDs:= make([]interface{}, len(IDs))
for i, id:= range IDs {
CIDs[i] = id
}
```

**Comment by aarondl** [comment]
This is a known issue. Consider using the generated where helpers. There exist some for int64 now (if not merged then it's in dev branch)
