### ISSUE TITLE
[PostgresDriver] PrimaryKeyInfo does not find PK even if they exist

### ISSUE THREAD

**Issue by krostar** [volatiletech/sqlboiler#649]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
`SQLBoiler v3.6.1`

### What is your database and version (eg. Postgresql 10)
`PostgreSQL 10.8`

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`sqlboiler psql --wipe --debug`

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
```
using driver: /Users/myuser/go/bin/sqlboiler-psql
{"config":{"driver_name":"psql","driver_config":{"blacklist":null,"dbname":"<dbname>","host":"<host>","pass":"<pwd>","port":5432,"schema":"public","user":"<user>","whitelist":[<tables>]},"pkg_name":"models","out_folder":"models","debug":true,"wipe":true,"struct_tag_casing":"snake","imports":{"all":{"Standard":["\"database/sql\"","\"fmt\"","\"reflect\"","\"strings\"","\"sync\"","\"time\""],"ThirdParty":["\"github.com/friendsofgo/errors\"","\"github.com/volatiletech/sqlboiler/boil\"","\"github.com/volatiletech/sqlboiler/queries\"","\"github.com/volatiletech/sqlboiler/queries/qm\"","\"github.com/volatiletech/sqlboiler/queries/qmhelper\"","\"github.com/volatiletech/sqlboiler/strmangle\""]},"test":{"Standard":["\"bytes\"","\"reflect\"","\"testing\""],"ThirdParty":["\"github.com/volatiletech/sqlboiler/boil\"","\"github.com/volatiletech/sqlboiler/queries\"","\"github.com/volatiletech/sqlboiler/randomize\"","\"github.com/volatiletech/sqlboiler/strmangle\""]},"singleton":{"boil_queries":{"Standard":null,"ThirdParty":["\"github.com/volatiletech/sqlboiler/drivers\"","\"github.com/volatiletech/sqlboiler/queries\"","\"github.com/volatiletech/sqlboiler/queries/qm\""]},"boil_types":{"Standard":["\"strconv\""],"ThirdParty":["\"github.com/friendsofgo/errors\"","\"github.com/volatiletech/sqlboiler/boil\"","\"github.com/volatiletech/sqlboiler/strmangle\""]}},"test_singleton":{"boil_main_test":{"Standard":["\"database/sql\"","\"flag\"","\"fmt\"","\"math/rand\"","\"os\"","\"path/filepath\"","\"strings\"","\"testing\"","\"time\""],"ThirdParty":["\"github.com/spf13/viper\"","\"github.com/volatiletech/sqlboiler/boil\""]},"boil_queries_test":{"Standard":["\"bytes\"","\"fmt\"","\"io\"","\"io/ioutil\"","\"math/rand\"","\"regexp\""],"ThirdParty":["\"github.com/volatiletech/sqlboiler/boil\""]},"boil_suites_test":{"Standard":["\"testing\""],"ThirdParty":null}}},"aliases":{},"version":"3.6.1"},"driver_config":{"blacklist":null,"dbname":"<dbname>","host":"<dbhost>","pass":"<pass>","port":5432,"schema":"public","user":"<user>","whitelist":[<tables>]},"schema":"","dialect":{"lq":0,"rq":0,"use_index_placeholders":false,"use_last_insert_id":false,"use_schema":false,"use_default_keyword":false,"use_auto_columns":false,"use_top_clause":false,"use_output_clause":false,"use_case_when_exists_clause":false},"tables":null,"templates":null}
Error: primary key missing in tables (<all whitelisted tables>)
github.com/volatiletech/sqlboiler/boilingcore.checkPKeys
	/Users/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler@v3.6.1+incompatible/boilingcore/boilingcore.go:580
github.com/volatiletech/sqlboiler/boilingcore.(*State).initDBInfo
	/Users/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler@v3.6.1+incompatible/boilingcore/boilingcore.go:378
github.com/volatiletech/sqlboiler/boilingcore.New
	/Users/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler@v3.6.1+incompatible/boilingcore/boilingcore.go:91
main.preRun
	/Users/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler@v3.6.1+incompatible/main.go:205
github.com/spf13/cobra.(*Command).execute
	/Users/myuser/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:815
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/myuser/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/Users/myuser/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/Users/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler@v3.6.1+incompatible/main.go:118
runtime.main
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357
unable to initialize tables
github.com/volatiletech/sqlboiler/boilingcore.New
	/Users/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler@v3.6.1+incompatible/boilingcore/boilingcore.go:93
main.preRun
	/Users/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler@v3.6.1+incompatible/main.go:205
github.com/spf13/cobra.(*Command).execute
	/Users/myuser/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:815
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/myuser/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/Users/myuser/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/Users/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler@v3.6.1+incompatible/main.go:118
runtime.main
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
`pg_dump -U <user> -h <host> -d <db> -t <table> --schema-only > <table>.sql`

```
...
CREATE TABLE public.example (
    example_id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    ...
)
...
ALTER TABLE ONLY public.example
    ADD CONSTRAINT example_pkey PRIMARY KEY (example_id);
...
```

### Further information. What did you do, what did you expect?

I expect the generation to works as expected instead of returning an error about missing primary keys on all tables of the database.

After digging a little, I found how you check about these PK [here](https://github.com/volatiletech/sqlboiler/blob/e004393fa62ca053ec76d14df63d2e066cd2de23/drivers/sqlboiler-psql/driver/psql.go#L327), and after copy/pasting the requests, I got the same result (no rows returned), even when using a simplified request:
```
SELECT * FROM information_schema.table_constraints;
 constraint_catalog | constraint_schema | constraint_name | table_catalog | table_schema | table_name | constraint_type | is_deferrable | initially_deferred
--------------------+-------------------+-----------------+---------------+--------------+------------+-----------------+---------------+--------------------
(0 rows)
```

I found few links on internet about this issue: [here](https://stackoverflow.com/questions/39379939/how-to-access-information-schema-foreign-key-constraints-with-read-only-user-in), and [here](https://stackoverflow.com/questions/16830740/list-constraints-for-all-tables-with-different-owners-in-postgresql). Which made me realize it's probably a right-related issue.

To add more details, I have small set of read-only rights on the database when I use sqlboiler, and have no way of gaining more rights.
This query however, is working and return the right PK:
```
SELECT conname, pg_get_constraintdef(c.oid)
FROM pg_constraint c
WHERE
    conrelid::regclass::TEXT = '<table>' AND
    contype = 'p';

   conname   | pg_get_constraintdef
-------------+-----------------------
example_pkey | PRIMARY KEY (example_id)
(1 row)
```

I hope you'll be able to find a way of using another query to check about these pkey that works in all you test cases. Until then, I won't be able to use this project that seemed promising :(.

If you need me to test something, I'll be happy to.
Thanks you for your project and for sharing it with the community.

**Comment by aarondl** [comment]
Hi @krostar. I'm able to reproduce this.

From the docs:
https://www.postgresql.org/docs/current/infoschema-table-constraints.html
> The view table_constraints contains all constraints belonging to tables that the current user owns or has some privilege other than SELECT on.

So the issue is real, however `sqlboiler` is not a tool that's intended to be run against a production database generally speaking. It's supposed to be run against a development clone, and in that scenario it doesn't make sense to have a read-only user.

If there does exist a set of queries for the driver that will work irregardless of user permissions I suppose it's fine to do so but because it's to support a use case outside the scope of the project I won't be devoting any time to correcting this issue.

My suggestion is to get a `pg_dump` sans data and stand up the database on your local machine to be able to use the tool as intended. Or perhaps open a PR with all the queries adjusted for RO-users.

Thanks for the thorough bug report. If they were all this good life would be simpler :)

**Comment by krostar** [comment]
Hi @aarondl

> It's supposed to be run against a development clone, and in that scenario it doesn't make sense to have a read-only user.

The tool was not used against a production database. In my case the development database is also read-only for my user as it's does not make sens, in the context I'm working on, to have other rights since the scenario where we need to do other things than manually reading are nonexistent (migration are run by a tool with a specific user, services that handle data in the database also have a specific user, ...). Another scenario where the user would not have more right can be that the generated code is not versionned/commited and is generated at build time. In this case, the build script will run with a user which should not be able to do things on the database either.

Obviously I can, as you suggested, play with `pg_dump`, or also replay the migrations from origins to rebuilt the database locally, and run `sqlboiler` against it, but I don't want to go this way.

> If there does exist a set of queries for the driver that will work irregardless of user permissions I suppose it's fine to do so

I didn't really take the time to dig this way, so I don't know what rule the `pg_constraint` table, nor if we're supposed to use it like this. It was more of a suggestion than a wisely chosen alternative.

> perhaps open a PR with all the queries adjusted for RO-users

I'm not sure how I will be able to check if everything still work exactly as expected, for all the usecases you handle. Would you take the time, if I open a PR that made things work in my usecase,  to check for any other usecases I could have break ?

**Comment by aarondl** [comment]
@krostar I'm not super keen on accepting any pull request where the author isn't providing guarantees that it's going to work in all cases.

Where's the incentive for me? :)

The only impetus I have to even consider accepting a pull request such as this is for your own personal gain as nobody else is requesting this and nobody has since the inception of the project (quite a number of years). So I think the onus should be on yourself to guarantee the quality of your PR and to ensure that it's not going to break any users.

The final say to accept the code and the ultimate responsibility lies with me, so if there's any doubt I just close the PR and move on given that the only user of such a feature would be yourself it doesn't hurt me to do so.

I don't want this PR to come off as rude or anything. Just lazy :)
