### ISSUE TITLE
Document example of manipulate Postgresql Array and Jsonb columns

### ISSUE THREAD

**Issue by wantdrink** [volatiletech/sqlboiler#650]
Hi there,

sqlboilder supports 1d array and json(b) of postgres.
Is that possible to document the usage of array & jsonb column query/update/insert?

Thanks a lot.

**Comment by aarondl** [comment]
Hi @wantdrink. There's not much to document, simply create a database with those types you wish to use and generate the models. Your models will include things like `types.JSON` which should have enough documentation in the package to be able to use correctly.

**Comment by wantdrink** [comment]
Thanks @aarondl.
