### ISSUE TITLE
Add ent orm to benchmark in readme

### ISSUE THREAD

**Issue by ansarizafar** [volatiletech/sqlboiler#655]
Facebook has release ent https://entgo.io/ a new Go ORM for modeling and querying data. Please add ent to benchmark in readme.

**Comment by aarondl** [comment]
Not really interested in pursuing this. Someone could send a PR if they wanted though.

**Comment by ansarizafar** [comment]
I am new to Go and trying to figure out which one to use sqlboiler or ent orm that is why I asked for the benchmark. 

I want to use sqlboiler because It gives you full control. You are right no orm can create a complete DDL replacement but Model and auto migration feature like Prisma2 https://github.com/prisma/prisma2 or ent orm are very convenient features and great time savers for individual developers and small teams.

 I request you to please consider adding these features to amazing sqlboiler.
