### ISSUE TITLE
Template 17 appears to be missing

### ISSUE THREAD

**Issue by josdotso** [volatiletech/sqlboiler#658]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

```
SQLBoiler v3.6.1
```

### What is your database and version (eg. Postgresql 10)

```
mysql:5.6
```

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

```
(not looking to generate models, but instead I would like to generate a different non-go artifact (singleton).
```

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

```
Error: unable to generate output: failed to execute template: templates/17_upsert.go.tpl: template: templates/17_upsert.go.tpl:47:14: executing "templates/17_upsert.go.tpl" at <{{template "timestamp_upsert_helper" .}}>: template "timestamp_upsert_helper" not defined
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

https://github.com/datacharmer/test_db (employees.sql)

### Further information. What did you do, what did you expect?

A couple of things:
1. My template does generate output but I also get error above and sqlboiler exits non-zero.
2. Template 17 _does_ appear to be missing here: https://github.com/volatiletech/sqlboiler/tree/master/templates

Thoughts?

**Comment by aarondl** [comment]
In sqlboiler drivers are able to supply their own templates. The upsert template you're seeing is declared by the driver. This flag exists to prevent it: `--no-driver-templates` which should be able to be specified by env var/config file as well.
