### ISSUE TITLE
Feature Request: Implement Sprig Template Library

### ISSUE THREAD

**Issue by josdotso** [volatiletech/sqlboiler#659]
https://masterminds.github.io/sprig/

I'm working on a custom template requires me to +1 to the index integer of a range of table columns, but I see no easy way to do this.

Over in Helm2 (for Kubernetes), they use the Sprig library to enrich the vanilla Go Template system.

Please let me know your thoughts.

**Comment by aarondl** [comment]
I've mentioned in other threads that I would be generally fine with the inclusion of the sprig library to help create custom templates for things like grpc etc.
