### ISSUE TITLE
nil pointer dereference on TableName.R during RemoveX on 1:1 relationship

### ISSUE THREAD

**Issue by eliaperantoni** [volatiletech/sqlboiler#660]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.6.1

### What is your database and version (eg. Postgresql 10)
Postgres 10.6

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
```go
slot, err := drawer.Slot().One(ctx, s.db)
if err != nil {
	return wrapErr(err)
}

err = drawer.RemoveSlot(ctx, s.db, slot) // <--- This line panics
if err != nil {
	return wrapErr(err)
}
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
CREATE TABLE slot(
    id SERIAL PRIMARY KEY
);

CREATE TABLE drawer(
    id SERIAL PRIMARY KEY,
    slot_id INT REFERENCES slot(id)
);
```

### Further information. What did you do, what did you expect?
I fetched a Slot and then called drawer.RemoveSlot(slot) but it crashed with this message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb9a5e0]

goroutine 16 [running]:
ono/models.(*Drawer).RemoveSlot(0xc0002cc460, 0x136ca20, 0xc0004ae570, 0x1373160, 0xc0001b63c0, 0xc0002e0320, 0x0, 0x0)
        /home/elia/Documenti/code/ono/models/drawer.go:908 +0x140
```

Here's the RemoveSlot function
```go
// RemoveSlot relationship.
// Sets o.R.Slot to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *Drawer) RemoveSlot(ctx context.Context, exec boil.ContextExecutor, related *Slot) error {
	var err error

	queries.SetScanner(&o.SlotID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("slot_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.Slot = nil // <--- This is where it's crashing
	if related == nil || related.R == nil {
		return nil
	}

	related.R.Drawer = nil
	return nil
}
```

**Comment by aarondl** [comment]
Hi @eliaperantoni, I fixed this on the dev branch. If you could confirm it works for you I'd be happy to put it into a release.

**Comment by eliaperantoni** [comment]
Maybe I'm doing something wrong but it doesn't seem like the generated code is any different.
I deleted the sqlboiler binary from `$GOPATH/bin`, git cloned this repo, checked out your commit, `go install` to compile a new binary and `sqlboiler --add-global-variants --add-panic-variants --wipe psql`

**Comment by eliaperantoni** [comment]
Still panics. Here's the generated code:

```go
func (o *Drawer) RemoveSlot(ctx context.Context, exec boil.ContextExecutor, related *Slot) error {
	var err error

	queries.SetScanner(&o.SlotID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("slot_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.Slot = nil
	if related == nil || related.R == nil {
		return nil
	}

	related.R.Drawer = nil
	return nil
}
```

**Comment by aarondl** [comment]
@eliaperantoni It's important to check out the branch as I missed putting the template bindata regeneration in the same commit.

**Comment by eliaperantoni** [comment]
@aarondl Yes it works. Thanks!
