### ISSUE TITLE
Non-deterministic bind finisher with `select *`

### ISSUE THREAD

**Issue by abeins** [volatiletech/sqlboiler#664]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
v3.6.0

### What is your database and version (eg. Postgresql 10)
MySQL 5.7.28

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
See above

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
Use the pilots/jets schema in the README

### Further information. What did you do, what did you expect?

I'm seeing an issue where the `Bind` finisher is binding non-deterministically to a `NewQuery`. Taking an example from the `README`:

```
type PilotAndJet struct {
  models.Pilot `boil:",bind"`
  models.Jet   `boil:",bind"`
}

var paj PilotAndJet

err := models.NewQuery(
  Select("pilots.id", "pilots.name", "jets.id", "jets.pilot_id", "jets.age", "jets.name", "jets.color"),
  From("pilots"),
  InnerJoin("jets on jets.pilot_id = pilots.id"),
).Bind(ctx, db, &paj)
```

The above works as expected. However, I'd like to select all columns from both the `pilots` and `jets` tables instead of enumerating each column. For example:

```
type PilotAndJet struct {
  Pilot models.Pilot `boil:"pilots,bind"`
  Jet models.Jet   `boil:"jets,bind"`
}

err := models.NewQuery(
  Select("pilots.*", "jets.*"),
  From("pilots"),
  InnerJoin("jets on jets.pilot_id = pilots.id"),
).Bind(ctx, db, &paj)
```

However, this will sometimes bind `pilots.id` to `jets.id` and vice versa, and this behavior appears to be non-deterministic.

Is there a solution to this issue, without having to enumerate every column in the `Select`?

**Comment by aarondl** [comment]
Unfortunately this is not really possible to do this. The reason for this is the database gives us column names back like this:

```id, name, id, pilot_id, age, name, color```

In order to disambiguate and bind to the separate structs correctly, you must rename each column like so: `select pilots.id as "pilots.id"` and then specify the struct tag in your struct.

**Comment by stephenafamo** [comment]
It is possible to use the [strmangle](https://pkg.go.dev/github.com/volatiletech/strmangle) package to generate that list easier.. for example:

```go
pilotCols := strmangle.PrefixStringSlice("pilots", []string{"id", "age"}
jetCols := strmangle.PrefixStringSlice("jets", []string{"id", "color"}

qm.Select(strings.Join(append(pilotCols, jetCols...), ", ")
```

Perhaps we can also consider generating helper functions in the model for this.   
Maybe an exported function to return the `modelAllColumns` slice? At the very least this will make the _strmangling_ much easier.
