### ISSUE TITLE
Table-based multitenancy (tenant_id column in each table)

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/sqlboiler#666]
I'm trying to figure out how to implement a **table-based multitenancy**: `tenant_id` column in each table.

I can use a `where` statement but I think it's error-prone and having also tried Rails (and the gem `apartment`, https://github.com/influitive/apartment) I wonder if it is possible to avoid using a `where` for each query and use a "global" `switch tenant_id`.

Maybe using hooks (https://github.com/volatiletech/sqlboiler#hooks)?

Is there an example?

**Comment by maurolscla** [comment]
I think that until support for beforeSelectHooks is added hooks won't help much in your case.

**Comment by aarondl** [comment]
@frederikhors There is no support for this, it'll have to be where statements unfortunately. You could consider creating a linter for your code either based on the go/ast package or using something simple like grep to ensure that the tenant_id where is present on any query relating to "x".

**Comment by frederikhors** [comment]
So say you closed it.
😢

**Comment by aarondl** [comment]
Sorry @frederikhors. It's not a feature I'm willing to include in sqlboiler!

**Comment by frederikhors** [comment]
Just out of curiosity: have you ever had to separate the data of several "tenants" in the same database?

Using the `tenant_id` column is the most convenient way.

And the changes to make it work in sqlboiler (for you, experts) I don't think would be many.

I really don't understand.

**But it's not a criticism: your work is wonderful!**
**Thanks for what you've done so far!**

**Comment by frederikhors** [comment]
I think it's enough a pre-select hook...

**Comment by frederikhors** [comment]
To add a filter beyond every query...

**Comment by aarondl** [comment]
Hi @frederikhors. Generally I'll separate on something like schema or actual database rather than have a tenant_id. But these sorts of features aren't interesting to me to add to the core of sqlboiler. However you can supply your own templates to add it in a way.
