### ISSUE TITLE
Nullable Decimal Querymods cause panics

### ISSUE THREAD

**Issue by ImVexed** [volatiletech/sqlboiler#667]
v3.6.1 Postgres 12

Using a nullable decimal type's where helpers don't work properly with qmhelper.WhereNullEQ

https://github.com/volatiletech/sqlboiler/blob/v3.6.1/types/decimal.go#L27 
Doesn't implement the `Nullable` interface with `IsZero() bool` so when https://github.com/volatiletech/sqlboiler/blob/master/queries/qmhelper/qmhelper.go#L29 
occurs the non-pointer struct get's `reflect.ValueOf(value).IsNil()` called on it causing 
`reflect: call of reflect.Value.IsNil on struct Value`

**Comment by aarondl** [comment]
Fixed on dev branch. If you happen to try it out and it works for you let me know :) It will be released with the next release.

**Comment by ImVexed** [comment]
Fixed the issue for me :)
