### ISSUE TITLE
Models: failed to assign all query results to Users slice

### ISSUE THREAD

**Issue by tolgatanriverdi** [volatiletech/sqlboiler#671]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
 v3.6.1

### What is your database and version (eg. Postgresql 10)
Mysql

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
```
	var resErr error
	encryptedPassword := md5.New()
	encryptedPassword.Write([]byte(password))
	encryptedStr := hex.EncodeToString(encryptedPassword.Sum(nil))
	user,err := models.Users(models.UserWhere.Username.EQ(username),models.UserWhere.Password.EQ(encryptedStr)).AllG(ctx)
	if err == nil {
		if len(user) > 0 {
			result = true
		} else {
			err = errors.New("Invalid Login");
		}
	}
```

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)

Models: failed to assign all query results to Users slice

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

DROP TABLE IF EXISTS `Users`;

CREATE TABLE `Users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by tolgatanriverdi** [comment]
are there any idea about the problem?

**Comment by SlevinWasAlreadyTaken** [comment]
Did you try to generate the table using singular ? I know sqlboiler generates code and prefer the table to be singular because the function to retrieve a single record would be name FindUser where the function to list records are plural: Users. I am not sure it is the origin of your issue but it might be worth to test.

**Comment by aarondl** [comment]
@tolgatanriverdi This kind of thing can happen with column/type mismatches or number of column mismatches.

Have you maybe updated the database and forgot to regenerate your models?

**Comment by tolgatanriverdi** [comment]
I think I've found the problem . It was related with database connection ip (ip was wrong), but I wasnt expecting to see an error like this. I was expecting something like failed to connect.
