### ISSUE TITLE
doing PUT/updating from map instead of struct

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#674]
Just wondering if there might be any advantage to:

```js
var updateUserInfo = map[string]interface{}{}
```

versus

```
var updateUserInfo model.CPUser
```

is there a way to Unmarshal data into a map and use the map to populate the database?

**Comment by aarondl** [comment]
I'm not actually sure what this is referring to.

We have both ways in sqlboiler. We use the map approach for `UpdateAll`. But this loses you type safety. I can say:

```
updateUserInfo := map[string]interface{}{
   "username": 5,
}
```

and the compiler will not catch the error. This is why it's desirable to use the struct.
