### ISSUE TITLE
what is it doing? drivers such as 'sqlboiler-psql' can be autoinstalled 

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#675]
I ran:

```
$ cd "my project root with sqlboilder.toml at the root" && sqlboiler psql
```

and I got:

> Error: unable to initialize tables: unable to fetch table data: something totally unexpected happened when running the binary driver /home/oleg/go/src/github.com/channelmeter/cp-go-api/sqlboiler-psql: fork/exec /home/oleg/go/src/github.com/channelmeter/cp-go-api/sqlboiler-psql: no such file or directory

wtf is it doing lol?  why is it looking for a library driver in my project:
 /home/oleg/go/src/github.com/channelmeter/cp-go-api/sqlboiler-psql:

so I looked at the docs again:
https://github.com/volatiletech/sqlboiler#configuration

and it says:

>  When passing 'psql' here, it looks for a binary called
>  'sqlboiler-psql' in your CWD and PATH. You can also pass
>  an absolute path to a driver if you desire.

so why not include the driver in this package and then just default the location to:

```
"$GOPATH/src/github.com/volatiletech/sqlboiler/driver"
```

Am I missing something? lol

**Comment by ORESoftware** [comment]
So here is my suggestion.....If the `sqlboiler-psql` driver isn't in the PATH or CWD you are perfectly capable of putting it there for your users, here is how I did it manually:

```
go install "$GOPATH/src/github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql"
export PATH="${GOPATH}/bin:$PATH"
sqlboiler psql
```

**Comment by aarondl** [comment]
@ORESoftware The instructions clearly mention getting the driver: https://github.com/volatiletech/sqlboiler/#download

It assumes that as per the Go installation instructions you have `$GOPATH/bin` in your path. We're not going to download/compile/install software without the user's knowledge.
