### ISSUE TITLE
Unclear how to have multiple configurations in sqlboiler.toml

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#677]
I have this:

```
pkgname = "model"
output = "v1/model"

[psql]
dbname = "creatorpay"
host = "pg.channelmeter.com"
user = "postgres"
blacklist = []

[local]
dbname = "postgres"
host = "localhost"
user = "postgres"
blacklist = []
```

what i want to be able to do is run

```
sqlboiler psql
```

and

```
sqlboiler local
```

and have them both work - different postgres settings, generating diferrent models. It's not at all obvious how to do this. Should I just use two different .toml files?

```
sqlboiler-1.toml
sqlboiler-2.toml
```

?

**Comment by aarondl** [comment]
Yep. You would just use two different config files.

```sqlboiler -c local.toml psql
sqlboiler -c remote.toml psql
```

Note the label `psql` in the configuration file is a driver name and is not changeable by an end-user. It's there to provide the psql driver with it's configuration. If you named it `[local]` you'd need a driver named local to take advantage of that.
