### ISSUE TITLE
Unclear how to store passwords outside of version control

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#678]
I see an example like so:

```
[psql]
  dbname = "dbname"
  host   = "localhost"
  port   = 5432
  user   = "dbusername"
  pass   = "dbpassword"
  schema = "myschema"
  blacklist = ["migrations", "other"]
```

what I want to do is use an env variable for the password:

```
[psql]
  dbname = "dbname"
  host   = "localhost"
  port   = 5432
  user   = "dbusername"
  pass   = "$dbpassword"   // inject the password from env var
  schema = "myschema"
  blacklist = ["migrations", "other"]
```

is this possible?

**Comment by aarondl** [comment]
ENV vars are supported. Although it is poorly documented. `PSQL_*` works, so to remove the password from the configuration file and use env vars you would do: `PSQL_PASS=password`

**Comment by ORESoftware** [comment]
can we add docs for those relevant env vars and how to capture them in the .toml file?

**Comment by aarondl** [comment]
I rewrote the section on configuration in the README. It shows how to use the config vars (though does not provide an exhaustive list).
