### ISSUE TITLE
Unclear what `ctx` is - and what values it can take

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#679]
In the docs, the first instance of `ctx` is here:

![Screenshot from 2020-02-23 19-43-39](https://user-images.githubusercontent.com/11139560/75127612-e49e5c00-5674-11ea-8436-5606f977f5b4.png)

it's unclear what `ctx` is, or what it values it can take.

I see a lot of context.Background(), but I don't know what that means.

**Comment by jarleriksen** [comment]
`ctx` is indeed `context.Background()`.

`context.Background()` is what you pass to all `Finishers` along with the database.

Maybe this article will help you out: https://blog.golang.org/context

**Comment by aarondl** [comment]
Take a look at the package documentation for context:
https://golang.org/pkg/context/

**Comment by aarondl** [comment]
Also thanks @jarleriksen for the also useful Go blog about context :)
