### ISSUE TITLE
Empty where clause causes unnecessary breakdown

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#680]
I get this error:

2020/02/23 19:49:54 model: failed to assign all query results to UserTable slice: bind failed to execute query: pq: syntax error at or near ")"

when I use:

```go
	rows, err := model.UserTables(
		q.Select(mappedFields...),
		q.Limit(limit),
		q.Where("")).All(context.Background(), db)
```

the string is empty for `q.Where("")`, but if I add a condition:

```go
	rows, err := model.UserTables(
		q.Select(mappedFields...),
		q.Limit(limit),
		q.Where("handle = ?", "frog")).All(context.Background(), db)
```

then it works. however the library should be able to handle an empty where clause. for dynamic code, if the string is empty - assume the user wants it to be empty.

**Comment by jarleriksen** [comment]
I guess the best solution is to conditionally add query mods instead of using an empty string.

```go
mods := []qm.QueryMod{}

if handle != "" {
 mods = append(mods, qm.Where("handle = ?", "frog"))
}

model.UserTables(mods...).All(context.Background(), db)
```

**Comment by ORESoftware** [comment]
@jarleriksen  yeah that works, but I would hope that an empty where clause would be ignored

**Comment by aarondl** [comment]
@ORESoftware sqlboiler makes an attempt not to be magical where possible. You should know whether your inputs are valid & empty and your code should decide how to interact with databases/third party bits using that knowledge. It's more verbose, but it's also much more clear what's happening immediately looking at @jarleriksen's code. This is a tradeoff made over and over again in Go and so we continue the trend.

**Comment by ORESoftware** [comment]
@aarondl then throw with an empty where clause please
