### ISSUE TITLE
Escaping '?' in Where() query mod

### ISSUE THREAD

**Issue by jarleriksen** [volatiletech/sqlboiler#681]
Hello,

I have a query where I am checking if a key exists inside a `jsonb` column.
`qm.Where(fmt.Sprintf("file ? 'image' = %t", filterValue))`

My current issue is that the query ends up looking like:
`WHERE (file $1 'image' = true)` instead of `WHERE (file ? 'image' = true)`.

This specific query worked using Gorm because of the use of `fmt.Sprintf`.

Could it be possible to not parse `?` as a placeholder if no arguments have been passed?

I would really like to avoid having to use a Raw query because this query mod is used in combination with a lot of other query mods.

Thanks!

**Comment by jarleriksen** [comment]
I got around this by using a different operator for JSONB columns.
`qm.Where(fmt.Sprintf("file -> 'image' %s", filterValue))` where `filterValue` is either `IS NULL` or `IS NOT NULL`.

It would still be awesome to have a way to escape the `?` placeholder. However, this solves my issue.

**Comment by walez** [comment]
For anyone with this same issue, you can escape `?` using `\?`
