### ISSUE TITLE
How to call Set() as a query mod to update query

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#682]
I want to do something like:

```golang

import(
	q "github.com/volatiletech/sqlboiler/queries/qm"
)

// ...

args := []q.QueryMod{
   q.Update()  // This API doesn't exist
   q.Set()    // This API doesn't exist
}

rows, err := model.NewQuery(args...).Query(c.Database.Db)

```

but for an Update query...but I don't see q.Update()  or q.Set()

so perhaps I should use a raw query?

**Comment by aarondl** [comment]
`model.Users().UpdateAll()` exists. This means "update all the records the query would ordinarily match". Raw queries of course are always an option :)
