### ISSUE TITLE
how to return newly create id on INSERT

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#685]
We are looking to do something like this:

```sql
  INSERT INTO persons (lastname,firstname) VALUES ('Smith', 'John');
  SELECT currval('persons_id_seq');

```
with more details here:
https://stackoverflow.com/questions/2944297/postgresql-function-for-last-inserted-id

is this possible with SQLBoiler? we want to get the newly created id for every new record when we call insert

**Comment by ORESoftware** [comment]
I would think the above (INSERT + SELECT) would need to be in a transaction but idk for sure

**Comment by u24b6** [comment]
When you call Insert on an object, there are side effects on the state of the object. Namely, the id field (and presumably any other generated, autoincremented, or other database modified columns) is defined.

This is explained in the README:

* https://github.com/volatiletech/sqlboiler/blob/master/README.md#insert
* https://github.com/volatiletech/sqlboiler/blame/master/README.md#L1495

**Comment by aarondl** [comment]
Thanks for fielding the question @u24b6! He is indeed correct, sqlboiler attempts to retrieve any default value (auto-incrementing ids in mysql are just really badly implemented default values).

It uses the go sql https://golang.org/pkg/database/sql/#Result and so -that- shouldn't need a transaction. But if there are any other default values in your struct sqlboiler will do a lookup on that ID to get the rest of them back from the DB to maintain consistency between the database record and the struct.

**Comment by ORESoftware** [comment]
sorry I don't understand these answers. insert does not take two return values, only err:

```golang
m := model.Foos()
err := m.Insert()
```

so how would I get the value?

**Comment by aarondl** [comment]
> now val would have the info from the db?

Yes. val.ID or what have you will contain the primary key.

**Comment by ORESoftware** [comment]
Insert only returns one value, not a tuple. so is the id backfilled on the original model object or?

**Comment by ORESoftware** [comment]
ping ty

**Comment by aarondl** [comment]
> not a tuple. so is the id backfilled on the original model object or...?

This is exactly how it works. It sets the generated id (and any other fields with default values) on the model when you call insert.

**Comment by ORESoftware** [comment]
Ok thanks, the word "backfill" is prob the best English word I know of to describe it.
