### ISSUE TITLE
User should be able to skip execution of auto-generated boiler tests

### ISSUE THREAD

**Issue by programmer04** [volatiletech/sqlboiler#690]
## Problem
When user run Go tests in a repository:
```go
go test ./...
```
boiler autogenerated tests are executed too and there is no way to skip them. I think the possibility to skip them will be useful. They required DB to be run, so they are more like integrations tests than units.

## Possible solutions

**1. Fully backward compatible, with Go [short flag](https://golang.org/pkg/testing/#Short)**
```go
go test ./...
```
The above works like before.
To skip boiler execute:
```go
go test -short ./...
```

or with the introduction of a new boiler specific flag e.g.
```go
go test ./... -skipboiler
```

**2. Introduction of a new flag which enables boiler tests**
By default, boiler tests are not executed. To run them pass the specific flag:
```go
go test ./... -boiler
```
But other tests will be executed too unless checking for the setting of this flag in them.

Please let me know which solution is better or make your own suggestion, I'll be happy to make a PR which introduce this feature 🙂

**Comment by aarondl** [comment]
The way I deal with this is I just don't generate the tests. There's a config file option and flag for this.

**Comment by programmer04** [comment]
Thanks for the very fast answer!

Sure, but I was thinking about keeping them... These can be run as a part of an integration test suite because they have depends on external service - database. My other integrations tests cover queues, external APIs, etc. They all have external dependencies. In opposite to normal unit tests, which tests only Go code from a repository (has no dependencies) and can be run always. When integrations tests are guarded with -short can be skipped easily, when someone wants to just run unit tests.

**Comment by KlausJokinen** [comment]
> The way I deal with this is I just don't generate the tests. There's a config file option and flag for this.

```
pkgname  = "models"
output   = "internal/models"
wipe     = true
no_tests = true
no-context = true

[mysql]
  dbname  = "db"
  host    = "localhost"
  port    = 3306
  user    = "root"
  pass    = "password"
  sslmode = "false"
```

Above still generates tests, can you see something odd with my configuration?

**Comment by aarondl** [comment]
`no-tests` vs `no_tests` perhaps? Also this issue sort of fell on the floor apparently.

@programmer04 You can make a PR for this if you want. I'm kind of indifferent towards the change. Gonna close this expecting either a PR or nothing :)
