### ISSUE TITLE
Getting the Inserted Id

### ISSUE THREAD

**Issue by tolgatanriverdi** [volatiletech/sqlboiler#691]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
3.6.1

### What is your database and version (eg. Postgresql 10)
Mysql 5.6.8

### Further information. What did you do, what did you expect?

We've tried to migrate our existing database and application to sqlboiler. However  we 've lots of auto incremented keys in our database, and we need to know the result of inserted id , just after we insert it to database (Like getGeneratedKeys method in java mysql driver). I've searched through the sqlboiler code but couldnt able to find a proper way to get the inserted id for our model . You can find the code which we used to insert(or update) the data. Is there any proper way to get the auto incremented id for this data

```
func (m *OuchDb) SetPosition(ctx context.Context,pos *Positions) (error) {

	position := models.Position {
		StrategyId: int(pos.StrategyId),
		Position:   int(pos.Position),
		Price:      int(pos.LastPrice),
	}

	err := position.UpsertG(ctx,boil.Whitelist("position","price"),boil.Whitelist("strategy","position","price"))
	return err
}
```

**Comment by leopku** [comment]
Hi @tolgatanriverdi ,
Did you solve this problem? I also meet it.

**Comment by aarondl** [comment]
@leopku When you insert or upsert a model in sqlboiler, the resulting id/primary key is bound back into the struct as if by magic :)

**Comment by leopku** [comment]
> @leopku When you insert or upsert a model in sqlboiler, the resulting id/primary key is bound back into the struct as if by magic :)

awesome! 
@aarondl  Thanks a lot.
