### ISSUE TITLE
Object Mapper design/functionality?

### ISSUE THREAD

**Issue by bbros-dev** [volatiletech/sqlboiler#693]
Thank you for the effort you have put into this project and making it available as open source.

I'm new to Go and am looking for an Object Mapper library in Golang - I'm struggling to see past the sytax right now - hence this question. 
 
Essentially Object Mapper approach builds on the lessons learned from the AvtiveRecord and DataMapper patterns/conventions, as well as the implementation lessons from the like named projects.

Something with the design and functionality of [rom-rb](https://rom-rb.org/learn/).

Does your library a Object Mapper type functionality?  
If not would you kind enough to share the name of any OM libraries that your know of in Goland?

**Comment by aarondl** [comment]
@bbros-dev I'm not aware of "Object Mapper approaches" and what they entail. Given than you're effectively giving me a research project & a comparison project I'll have to pass as I don't wish to spend time on this. Instead I'll leave it to you to research sqlboiler and decide whether or not it's an "Object Mapper" or not.

I don't know of any "Object Mappers" in Go (Goland is an editor, not a programming language) so I cannot give you any recommendations.

Best of luck to you!

**Comment by bbros-dev** [comment]
@aarondl Apologies.  The question wasn't intended as a task assignment ;)  
As you note if you knew what problems OM addressed you'd say.  
Answer was perfect and complete.
