### ISSUE TITLE
How to preserve camel-case convention in `uppercaseWords`?

### ISSUE THREAD

**Issue by soonoo** [volatiletech/sqlboiler#694]
First of all thank you for the awesome software.

https://github.com/volatiletech/sqlboiler/blob/e004393fa62ca053ec76d14df63d2e066cd2de23/strmangle/strmangle.go#L25-L31

Is there a way to prevent `sqlboiler` from uppercasing above words? I tried it using aliases but failed. I'm also wondering why those words are in that list...

**Comment by aarondl** [comment]
안녕하세요. 한국사람들이 sqlboiler를 아는지 처음 알았어요. 코로나 때문에 한국분들이 굉장히 힘드신 거 들었어요 :( 조심하세요.

There is no way to prevent this other than forking and changing that list you're staring at there.

This list is there to support best practice Go naming conventions: https://github.com/golang/go/wiki/CodeReviewComments#initialisms

If it were not for this list, you would end up with a model that looks like:

```go
type User struct {
  Id string
}
```

But Go convention is:

```go
type User struct {
  ID string
}
```

Even `golint` complains about this:
```
main.go:11:2: struct field Id should be ID
```

**Comment by aarondl** [comment]
Not sure if you were debating the existence of the list, or just those few elements that you highlighted. I'd be more willing to adjust the list if that's what you were getting at.

**Comment by soonoo** [comment]
Things are getting better than before though. Thank you so much and I hope you take care of yourself! I'm not familiar with `sqlboiler` yet, it is definitely a great work.

I didn't know that such conventions exist in Go. If that's a rule, I'll follow. What I actually want to achieve is adjusting json tag from `repoID` to `repoId`. I think it's weird that forcing other languages to follow that covention too. If this isn't possible, I'll just use as it is.
```toml
[[aliases.tables]]
    name = "users"
    [[aliases.tables.columns]]
    name  = "repo_id"
    alias = "RepoId"  # this only changes struct field name. json tag is still repoID
```

**Comment by aarondl** [comment]
Ah, that may be the case for that bit of struct tag casing. The usual case is the default (snake) which should lowercase the entire string.

```      --struct-tag-casing string   Decides the casing for go structure tag names. camel, title or snake (default "snake")
```

I'm not sure if any of these options help you. In the case of camel/title, I would agree with you that it should not be doing `ID`, though currently I don't think there's any way to adjust it - neither through alias nor any other mechanism :(

**Comment by soonoo** [comment]
I used `camel` option in above comment. 😢 
Thank you for your reply anyway.
