### ISSUE TITLE
Running tests for type with uuid column gives "Unable to randomize X struct: unsupported type: uuid.UUID"

### ISSUE THREAD

**Issue by pmalekn** [volatiletech/sqlboiler#696]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
`SQLBoiler v3.6.1`

### What is your database and version
Postgresql 9.6.5

### Please provide a relevant database schema so we can replicate your issue
Simplified:

```
CREATE TABLE public.sessions (
    session_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
);
```

### Further information. What did you do, what did you expect?
When running tests with types generated with the above schema with the following config:

```
{
  "tag": [
    "db"
  ],
  "psql": {
    "dbname": "XXX",
    "host": "localhost",
    "port": 12345
  },
  "types": [
    {
      "match": {
        "db_type": "uuid",
        "nullable": false
      },
      "replace": {
        "type": "uuid.UUID",
        "nullable": false
      },
      "imports": {
        "third_party": [
          "\"github.com/google/uuid\""
        ]
      }
    }
  ]
}
```

I get the following error:

    Unable to randomize X struct: unsupported type: uuid.UUID

I know that I can disable those tests by adding them to `blacklist` in the config but can I somehow add some code or config to make those tests pass?

**Comment by pmalekn** [comment]
So one of the "solutions" to this problem might be adding something along the lines of

```go
...
	case reflect.Array:
		if typ == reflect.TypeOf(uuid.UUID{}) {
			return uuid.New()
		}
	}
```

the to https://github.com/volatiletech/sqlboiler/blob/1202692/randomize/randomize.go#L241-L288

and

```go
...
	case reflect.Array:
		if typ == reflect.TypeOf(uuid.UUID{}) {
			return uuid.UUID{}
		}
	}
```

https://github.com/volatiletech/sqlboiler/blob/1202692/randomize/randomize.go#L195-L232

But then this is not going to work for everyone as not everyone relies on `github.com/google/uuid`.

**Comment by aarondl** [comment]
Yeah. Unless sqlboiler wants to support this library out of the box it can't work (which we currently do not).

What you can do is create an sqlboiler wrapper and implement the randomizer interface and use type replaces to use it.
https://github.com/volatiletech/sqlboiler/blob/1202692/randomize/randomize.go#L17
