### ISSUE TITLE
order by desc/asc

### ISSUE THREAD

**Issue by Dexus** [volatiletech/sqlboiler#697]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.6.1

### What is your database and version (eg. Postgresql 10)
mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper

### Why i open this Ticket?
Support the order by DESC / ASC for the fields or add a documentation who to do it.

**Comment by aarondl** [comment]
Hi @Dexus. To do this you just do:

```
qm.OrderBy(`column_name desc`)
```

I think that's what you're looking for, we don't have any better ways of doing it currently.
