### ISSUE TITLE
Until views are supported they should be automatically ignored

### ISSUE THREAD

**Issue by chochihim** [volatiletech/sqlboiler#699]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v3.6.1

### What is your database and version (eg. Postgresql 10)
PostgreSQL 10.4

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`sqlboiler psql`

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
CREATE VIEW dummy_view AS
SELECT 'dummy' AS name
```

### Further information. What did you do, what did you expect?
"Error: primary key missing in tables (dummy_view)" is thrown. Why are "View" objects included in the generation process if they are not supported?

**Comment by aarondl** [comment]
It's a great question. We'd do well to ignore them in each driver. Until then you can ignore them via the table blacklist in your configuration.
