### ISSUE TITLE
FYI: version still says 3.6.1 in 3.7.0

### ISSUE THREAD

**Issue by parnic** [volatiletech/sqlboiler#707]
`sqlboiler --version` in v3.7.0 currently reports v3.6.1. Just FYI. :)

Also, unrelated, it would be great if a new Github release was created when there's a new tag so people watching releases get notified! :)

**Comment by Dot-H** [comment]
I have done a PR for this 3 days ago (#702). Waiting for the maintainers to review the one line diff

**Comment by aarondl** [comment]
Will get it soon. Also @Dot-H there's only one maintainer and it's me :p I also only look at sqlboiler once every 2-3 weeks so I apologize for the delay.
