### ISSUE TITLE
Cannot go get psql driver (incompatible?)

### ISSUE THREAD

**Issue by mg98** [volatiletech/sqlboiler#708]
I was following the getting started guide from the readme.

```
go get -u -t github.com/volatiletech/sqlboiler

# Also install the driver of your choice, there exists psql, mysql, mssql
# These are separate binaries.
go get github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql
```

But on the last command I am getting the following output:
```
go: found github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql in github.com/volatiletech/sqlboiler v3.7.0+incompatible
```

**Comment by mg98** [comment]
Could also be related to #707

**Comment by aarondl** [comment]
This is likely because you're running `go get` inside a Go module. If you are installing binaries (like sqlboiler-psql) via `go get` you must run it outside any modules.
