### ISSUE TITLE
sqlboiler conks out for weird reason

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#712]
##### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.6.1

We are using postgres. I have this .toml file:

```toml
pkgname = "model"
output = "v1/model"

[fromenv]
dbname = "$postgres_db_name"
host = "$postgres_host"
user = "$postgres_user"

[psql]
dbname = "creatorpay"
host = "172.19.160.7"
user = "postgres"
blacklist = []

```

when I run this:

```bash
sqlboiler psql
```

nothing bad happens

but when I run:

```bash
sqlboiler fromenv
```

I get:

```bash
$ sqlboiler fromenv
Error: unable to initialize tables: unable to fetch table data: 
something totally unexpected happened when running the binary driver

/home/oleg/go/src/github.com/channelmeter/cp-go-api/sqlboiler-fromenv: fork/exec 

/home/oleg/go/src/github.com/channelmeter/cp-go-api/sqlboiler-fromenv: no such file or directory

```

why is it looking for a file called `sqlboiler-fromenv`?

**Comment by KnutZuidema** [comment]
I get this same error, however it happens with any argument (that I tried). I'm using the same version.

**Comment by aarondl** [comment]
`psql` and `fromenv` are driver names. sqlboiler uses binary drivers that you install to fetch data from databases. This decouples it from its drivers a certain amount and allows greater flexibility.

fromenv isn't a driver that exists unless you've created it.
