### ISSUE TITLE
qm.Where and Interval, err: invalid input syntax for type interval

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/sqlboiler#718]
@aarondl, I read https://github.com/volatiletech/sqlboiler/issues/398, but, I'm sorry, this is not working today.

I'm trying with:

```go
_, err := models.Players(qm.Where("(NOW() - updated_at) < ?", "interval 60 secs")).DeleteAll(context.Background(), db)
```

```log
error="models: unable to delete all from players: pq: invalid input syntax for type interval: \"interval 60 secs\""
```

With debug ON:

```log
DELETE FROM "players" WHERE ((NOW() - updated_at) < $1);
[interval 60 secs]
```

**Why?**

Can you help here, @sachnk?

**Comment by frederikhors** [comment]
I'm using https://github.com/lib/pq.

**Comment by frederikhors** [comment]
Maybe this can help: https://github.com/lib/pq/issues/950

**Comment by frederikhors** [comment]
This doesn't work either:

`qm.Where("(NOW() - updated_at) < ?", "interval '60 seconds'"),`

**Comment by aarondl** [comment]
Hm. If you require a type cast then there's no way we can make that work. Your options are to use a raw query where you can perform the postgresql typecast as in that lib/pq issue, or not to use a placeholder for what appears to be a hardcoded value.
