### ISSUE TITLE
sqlboiler-psql: Support standard libpq environment variables.

### ISSUE THREAD

**Issue by tmc** [volatiletech/sqlboiler#720]
It is a bit surprising that sqlboiler's postgres driver doesn't support the [standard libpq environment variables](https://www.postgresql.org/docs/current/libpq-envars.html) such as `PGUSER`, `PGHOST`.

**Comment by aarondl** [comment]
This is an abstraction layer on top of the database engines underneath it. I don't think it's very surprising that it does not expose the implementation details of each underlying implementation.

If this were a postgres-only library then I'd agree.
