### ISSUE TITLE
ltree type in psql 

### ISSUE THREAD

**Issue by DarkAulius** [volatiletech/sqlboiler#721]
when we generate ORM model from postgres 11 the type ltree is converted in string

**Comment by aarondl** [comment]
This is normal. See the README for type replacements.

**Comment by DarkAulius** [comment]
i've add this in toml file but the sqlboiler don't bind new type, Where am I doing wrong?

[[types]]

  [types.match]
    type = "ltree"

  [types.replace]
    type = "LTree"

    [types.imports]
    third_party = ['"gitazure/imok/simple-server-go/types"']

**Comment by aarondl** [comment]
From the docs:

```
  # The match is a drivers.Column struct, and matches on almost all fields.
  # Notable exception for the unique bool. Matches are done
  # with "logical and" meaning it must match all specified matchers. Boolean values
  # are only checked if all the string specifiers match first, and they
  # must always match.
  # Not shown here: db_type is the database type and a very useful matcher
  [types.match]
    type = "null.String"
    nullable = true
```

match itself is a [drivers.Column](https://pkg.go.dev/github.com/volatiletech/sqlboiler/v4@v4.0.0/drivers?tab=doc#Column) struct. `type` is the Go type which will probably be `string`. `db_type` is probably what you want to match on. You can use `--debug` to see the contents of the Column struct for your tables.

**Comment by DarkAulius** [comment]
thanks solved!
