### ISSUE TITLE
Are 3.0.1+ versions officially released?

### ISSUE THREAD

**Issue by kanchengzhu** [volatiletech/sqlboiler#725]
On [release page](https://github.com/volatiletech/sqlboiler/releases), v3.0.1 is marked as latest release. Are later versions officially released and ready for production?

**Comment by aarondl** [comment]
They are. I stopped publishing releases because they just pointed at the changelog and that's boring. But I decided to start again since people can watch for new releases on github in that way. 3.7.1 has just been published.
