### ISSUE TITLE
Postgres `oid` type represented as string

### ISSUE THREAD

**Issue by ImVexed** [volatiletech/sqlboiler#729]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
v3.6.1

### What is your database and version (eg. Postgresql 10)
Postgres 12

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`sqlboiler --wipe psql`

### Further information. What did you do, what did you expect?

Using a table with a field like:
```sql
blob oid not null
```

results in code generated that treats `blob` as a string when the https://www.postgresql.org/docs/9.4/datatype-oid.html reference states it is a `four byte unsigned integer`

**Comment by aarondl** [comment]
Not wanting to challenge your use case too much. But are you sure that that's the type you want?

> Object identifiers (OIDs) are used internally by PostgreSQL as primary keys for various system tables. Type oid represents an object identifier. There are also several alias types for oid: regproc, regprocedure, regoper, regoperator, regclass, regtype, regrole, regnamespace, regconfig, and regdictionary. Table 8.26 shows an overview.

> The oid type is currently implemented as an unsigned four-byte integer. Therefore, it is not large enough to provide database-wide uniqueness in large databases, or even in large individual tables.

It's really a postgres internals type. Typical users should be using: https://www.postgresql.org/docs/12/datatype-numeric.html

Having said all that I'd accept a use case that adds this as an int32 to the postgresql driver.

**Comment by ImVexed** [comment]
I'm equally not sure if I should be using it as a column type, and am currently using an `integer` to store the field, however, constantly having to flip between `int32` and `uint32` to interface with libraries like pgx for Large Object manipulation is tedious.

I'll take a look at making a PR.

**Comment by aarondl** [comment]
Fixed by #731
