### ISSUE TITLE
Duplicate structs in MySQL for composite foreign key

### ISSUE THREAD

**Issue by saifeer** [volatiletech/sqlboiler#730]
Hi,

I want to understand if composite foreign keys are supported in SQLBoiler or if I am doing something wrong.  

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.7.1

### What is your database and version (eg. Postgresql 10)
5.7.23 - MySQL Community Server 

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
Duplicate declaration in the model files:
```
var SubscriptionRels = struct {
	PurchasedProducts string
	PurchasedProducts string
}{
	PurchasedProducts: "PurchasedProducts",
	PurchasedProducts: "PurchasedProducts",
} 
```
### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
We have a Subscription table where the PK is composite (id, version). The same subscription can have multiple versions depending on how it was updated. There is a Purchased Product table that has a many to one relationship with the Subscription table. There are other columns in both table but I have removed them as I cannot share the entire structure.
```
CREATE TABLE `subscriptions` (
  `id` int(10) UNSIGNED NOT NULL,
  `version` int(5) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `subscriptions`
  ADD PRIMARY KEY (`id`,`version`);

CREATE TABLE `purchased_products` (
  `id` int(10) UNSIGNED NOT NULL,
  `subscription_id` int(10) UNSIGNED NOT NULL,
  `subscription_ver` int(5) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `purchased_products`
  ADD PRIMARY KEY (`id`),
  ADD KEY `PP_subs_fk` (`subscription_id`,`subscription_ver`);
ALTER TABLE `purchased_products`
  ADD CONSTRAINT `PP_subs_fk` FOREIGN KEY (`subscription_id`,`subscription_ver`) REFERENCES `subscriptions` (`id`, `version`);
```

### Further information. What did you do, what did you expect?
After the generation, duplicate structs are constructed in Subscriptions and PurchasedProducts as stated above. I could solve this problem by adding another id column to the Subscription table and using that to uniquely identify a version of a subscription and use that in the foreign key constraint in the purchased product table and it will all work I think. However, I dont think its ideal. What I am trying to do is not completely unheard of (https://dba.stackexchange.com/questions/112116/implementing-versioning-system-with-mysql). 

Am I doing something wrong or is this a limitation of SQLBoiler?

**Comment by aarondl** [comment]
This is indeed a limitation of sqlboiler. It only supports a single column foreign key atm! Sorry about that.

**Comment by saifeer** [comment]
Hi @aarondl 
Thanks for your reply. Is this something that could be part of the limitations in the readme? I think its a pretty significant limitation for any DB design that has a table with a composite primary key having a one-to-many relationship with any other table because the FK in all those cases would always be a composite FK - whatever be the actual usecase.

**Comment by aarondl** [comment]
Done here: 90e290e
