### ISSUE TITLE
Couple questions

### ISSUE THREAD

**Issue by KlausJokinen** [volatiletech/sqlboiler#735]
I was looking at the example of how to update a specific row.
Isn't it inefficient?

```
// Find a pilot and update his name
pilot, _ := models.FindPilot(ctx, db, 1)
pilot.Name = "Neo"
rowsAff, err := pilot.Update(ctx, db, boil.Infer())
```

First, you must query the database to retrieve the pilot and after that you "send it back".

Would it be possible to show more examples? Like
`"UPDATE pilots SET name = "Neo" WHERE address= OddAddress 123"` but with SQLBoiler and if even possible with SQLBoiler generated constants?

There is a high possibility, that I don't understand all the magic which is going on behind the scenes with SQBoiler.

The second question is how to use context efficiently with SQLBoiler? I've tried to google around examples where there are more than a couple of lines in main.go but without a result.

Thanks for the great tool 👍

**Comment by aarondl** [comment]
Hello @KlausJokinen. You can create an update query without first getting a model, look into the following:

```models.Pilots(models.PilotWhere.Age.GT(5)).UpdateAll(ctx, db, models.M{
  models.PilotColumns.Age: 27,
})```

> Would it be possible to show more examples? Like
"UPDATE pilots SET name = "Neo" WHERE address= OddAddress 123" but with SQLBoiler and if even possible with SQLBoiler generated constants?

It is of course possible, but it won't be done. Time is precious and there's only one of me left on this project!

> The second question is how to use context efficiently with SQLBoiler? I've tried to google around examples where there are more than a couple of lines in main.go but without a result.

This is sort of outside the scope of sqlboiler. context is a generic Go consequence that has permeated through the entire ecosystem. There's only 2 uses for context directly in sqlboiler: Adding debug info to a single query, cancelling timestamp generation. You can find helpers to create these contexts in the `boil` package. Past that, you simply pass your `http` handler request's context in to all your sqlboiler methods and one day if you ever start cancelling http requests your database requests also get cancelled.
