### ISSUE TITLE
v4.1.0: SQL model generation fails

### ISSUE THREAD

**Issue by mehdiym** [volatiletech/sqlboiler#736]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

v4.1.0

### What is your database and version (eg. Postgresql 10)

MariaDB 10.3

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

Generating models worked with 3.7, but fails with 4.1:

```
unable to fetch table column info (friend_requests): Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'c.column_default))),
	c.is_nullable = 'YES',
		exists (
			select c.column_name
' at line 9
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

I can send that to you if needed.

**Comment by speatzle** [comment]
I get the same error when using MariaDB. Seems to be related to this PR: #733 . Specifically this commit: https://github.com/volatiletech/sqlboiler/commit/956d421291e2aea62f6ac56c740347df919d482b

**Comment by oderwat** [comment]
Hi. I was the author of that commit. For some reason, a comma got lost at the end of a line. I commented in the commit and hopefully, this gets fixed very soon! Sorry about this!

**Comment by aarondl** [comment]
The real travesty here is that we still haven't replaced our old CI that would have caught this. v4.1.1 is released to fix this.

**Comment by mehdiym** [comment]
Thank you it works now.

**Comment by aarondl** [comment]
As a happy side effect to this issue, our CI has been ported to GH actions and is again operational :)
