### ISSUE TITLE
How to generate helper method for finding a record by an unique field?

### ISSUE THREAD

**Issue by razonyang** [volatiletech/sqlboiler#738]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v4.1.1

### What is your database and version (eg. Postgresql 10)
MariaDB 10.4.12

### Further information. What did you do, what did you expect?

Assume `users` table contains a unique field named `username`, is it possible to generate a helper method something like `FindUserByUsername`?

**Comment by aarondl** [comment]
The templates can be passed in via command-line argument (meaning you can tailor them to fit your purpose).

It is possible to generate this kind of helper. Though it's unlikely we'll put it in the main templates, there's enough generated code as without a big function per unique field!
