### ISSUE TITLE
Count should return 0 when sql.ErrNoRows returned

### ISSUE THREAD

**Issue by jseriff** [volatiletech/sqlboiler#74]
When calling Count() on a query that has no matching records, It would be best to get a 0 response instead of a wrapped error.  Each invocation to Count has three paths that have to be handled:

1) number response
2) wrapped error - count is really 0 (sql.ErrNoRows)
3) wrapped error - other error

I think most users of count would expect path 2 to roll into path 1 - if someone specifically needs to handle path 2 separately, that can still be done by checking for 0.

**Comment by aarondl** [comment]
Will get to this tomorrow :) There was a reason behind it and I need to do some archaeology to make sure I don't make a new bug.

**Comment by aarondl** [comment]
So, digging in a little bit, I'm actually genuinely surprised that this is happening. Since the count() stuff looks like this:

```go
	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
```

So it's modifying your query to be a count, and removing all your select statements. And therefore I'm not sure when you could ever have this happen. Can you provide a minimal recreate? Even if the table were completely empty you shouldn't get the sql.ErrNoRows.

**Comment by aarondl** [comment]
@jseriff Did you have a recreate for this?

**Comment by jseriff** [comment]
@aarondl Sorry, I've been focused on other projects, and havent come back to this yet.  I will try and get you one soon.

**Comment by aarondl** [comment]
@jseriff No problem. I've got a branch with some fixes relating to exists, I'll slap this in there when we figure out what's going on.

**Comment by aarondl** [comment]
@jseriff Making a pass on v3 probably soon. Any chance of getting some motion on this? It's a pesky one that should be easy to fix :) No problem if you're too busy tho.

**Comment by jseriff** [comment]
Sorry, I had to table our migration to sql boiler (although i am using it in some side projects).  I don't have a reproduction for this issue handy.

**Comment by aarondl** [comment]
@jseriff Any specific reasons? Maybe we could spend some time addressing them sometime. Would like to make it work for many use cases. :)

**Comment by jseriff** [comment]
Primarily just a timing issue - we have a large project using Gorm that we were considering migrating, but have been focused on other tasks.  I'd like to get back to converting it over at some point, but just haven't yet had the spare time to get back to it.

**Comment by aarondl** [comment]
Going to close this one as stale until we get some more info.
