### ISSUE TITLE
Selection of an augmented view of a sqlboiler-generated model using struct embedding yields missing data

### ISSUE THREAD

**Issue by kurt-stolle** [volatiletech/sqlboiler#740]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v3.7.1

### What is your database and version (eg. Postgresql 10)

Postgresql 12

### If this happened at runtime what code produced the issue?

```go
var coupons []*struct {
    models.Coupon
    IsValid bool `boil:"is_valid"`
}

err := models.Coupons(
    Select("*, is_valid_coupon(coupon_id) as is_valid"),
).Bind(ctx, db, &coupons)
if err != nil {
    return fmt.Errorf("could not load extended coupons view: %v", err)
}

fmt.Printf("loaded: %#v", coupons)  // []struct{...}{...} with all values zero except is_valid.
```

### Please provide a relevant database schema so we can replicate your issue
```sql
create table coupons (coupon_id serial primary key, code varchar(20), discount int);
create function is_valid_coupon(_coupon_id coupons.coupon_id%TYPE) returns boolean as
$$
begin
    return true; -- omitted for this example: check whether the coupon is already referenced by an order.
end;
$$ language plpgsql stable;
insert into coupons (code, discount) values ('foo',1);
```

### Further information. What did you do, what did you expect?
In the context of a webshop, I want to select the result of a procedure that checks that validity of a coupon code for every coupon that is selected, essentially selecting a view consisting of all the columns of `coupons` plus an extra column `is_valid`. I expected the embedding of `models.Coupon` to allow the selection of a view that has an extra column which evaluates the procedure `is_valid_coupon(coupon_id)`. 

However, this yields a result where the embedded struct's values are all zero, even though the `is_valid` field _does_ hold the expected result.

Interestingly, when the code works fine if I replace the embedding of `models.Coupon` with a literal copy of fields found in the generated definition of this type. 

This does somewhat feel like I am doing something outside the intended use-case. Is there another way to approach this application?

**Comment by aarondl** [comment]
In order to bind into a struct you must use the struct tag: `boil:",bind"` this is described in the documentation for the bind method: https://pkg.go.dev/github.com/volatiletech/sqlboiler/queries?tab=doc#Bind (see section on Bind Rules).

Please re-open of this was not the cause of the issue.
