### ISSUE TITLE
Error in sqlboiler v4 models import path generation 

### ISSUE THREAD

**Issue by andradei** [volatiletech/sqlboiler#741]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v4.1.1

### What is your database and version (eg. Postgresql 10)

Postgres 12.2 on Docker

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

`sqlboiler --wipe psql`

### Further information. What did you do, what did you expect?

After updating the tool and the driver via:
`go get -u -t github.com/volatiletech/sqlboiler`
and
`go get -u -v github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql`

It generates almost all new paths for go modules correctly, but I noticed some are still wrong. This is strange to me because after reading the source files that generate those, the import paths seem correct. But here are the issues I found:

- On `psql_main_test.go`
  - github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql/driver
should be
github.com/volatiletech/sqlboiler/`v4`/drivers/sqlboiler-psql/driver

  - github.com/volatiletech/sqlboiler/randomize
should be
github.com/volatiletech/randomize

- On one of my generated models
  - github.com/volatiletech/sqlboiler/types
should be
github.com/volatiletech/sqlboiler/`v4`/types

---

There might be others, but those three caught my attention.

So the generated code, while valid Go, is not importing the right modules. This causes compilation errors because , for example, `github.com/volatiletech/null` was imported by the generated code, but I'm passing the function a `github.com/volatiletech/null/v8` and those types aren't the same as far as the compiler can tell.

It also causes `go mod tidy` to import both the module-compatible and the module-incomatible versions of sqlboiler, resulting in a `go.mod` like this:

```
module github.com/My/Project
go 1.14

require (
        ...
	github.com/volatiletech/sqlboiler v3.7.1+incompatible // indirect
	github.com/volatiletech/sqlboiler/v4 v4.1.1
	...
)
```

I don't know if my tools got updated right, maybe an older sqlboiler-psql is still on my system after I ran `go get -u -v github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql`, I don't seem to have a way to print its version (since it is tied to sqlboiler itself).

Such a strange issue...

**Comment by andradei** [comment]
Got it working after running the following commands outside of my project's module directory

`go get -u -t -v github.com/volatiletech/sqlboiler`
and
`go get -u -v github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql`

When you were reluctant to support go modules, now I know why...

**Comment by barrettho** [comment]
go get -u -t github.com/volatiletech/sqlboiler
go get -u -t github.com/volatiletech/sqlboiler/drivers/sqlboiler-mysql
