### ISSUE TITLE
v4 generates imports from v3 

### ISSUE THREAD

**Issue by troian** [volatiletech/sqlboiler#742]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.1.1

### What is your database and version (eg. Postgresql 10)
Postgresql 10

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`//go:generate go run github.com/volatiletech/sqlboiler/v4 --no-back-referencing --wipe psql`

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
generated `psql_upsert.go` and few other files imports inappropriate imports
```go
package models

import (
	"fmt"
	"strings"

	"github.com/volatiletech/sqlboiler/drivers"
	"github.com/volatiletech/sqlboiler/strmangle"
)
```

### Further information. What did you do, what did you expect?
```go
package models

import (
	"fmt"
	"strings"

	"github.com/volatiletech/sqlboiler/v4/drivers"
	"github.com/volatiletech/strmangle"
)
```

Other broken imports
`github.com/volatiletech/sqlboiler/types/pgeo`
expected
`github.com/volatiletech/sqlboiler/v4/types/pgeo`

`github.com/volatiletech/null`
expected
`github.com/volatiletech/null/v8`

**Comment by aarondl** [comment]
This is almost certainly because the psql driver was not reinstalled. The changelog does mention you should do this on the go.mod update. Please re-open if this is not the case.

**Comment by troian** [comment]
How does it relate to `github.com/volatiletech/strmangle` though?

**Comment by aarondl** [comment]
@troian Not sure what you mean. That's just another one of the changed imports that requires a driver rebuild.
