### ISSUE TITLE
v4 - converted uint to unsupported type uint64

### ISSUE THREAD

**Issue by eldad87** [volatiletech/sqlboiler#747]
I just upgraded from v3 to v4 (automatically by switching dep to mod).
Using v4, a Select operation that used to work now fail with the following error:
`"models: unable to select from businesses: bind failed to execute query: sql: converting argument $1 type: driver ColumnConverter error converted uint to unsupported type uint64","errorVerbose":"sql: converting argument $1 type: driver ColumnConverter error converted uint to unsupported type uint64\nbind failed to execute query\ngithub.com/volatiletech/sqlboiler/v4/queries.(*Query).Bind\n\t/go/src/github.com/eldad87/go-boilerplate/vendor/github.com/volatiletech/sqlboiler/v4/queries/reflect.go:148...`

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v4.1.1

### What is your database and version (eg. Postgresql 10)
MySQL v5.7

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

1. Select:
```
bBusiness, err := models.FindBusiness(c, bs.db, 10000)
```
2. Debug mode enabled:
```
app_1              | select * from `businesses` where `id`=?
app_1              | [10000]
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```
CREATE TABLE `businesses` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `website` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
```

### Further information. What did you do, what did you expect?
I'm using `github.com/ericlagergren/decimal v0.0.0-20181231230500-73749d4874d5` as instructed.

**Comment by aarondl** [comment]
Hmm. I'm not exactly seeing what's going on here. I tested this exact thing with these versions:

```
	github.com/go-sql-driver/mysql v1.5.0
	github.com/ericlagergren/decimal v0.0.0-20181231230500-73749d4874d5
	github.com/volatiletech/null/v8 v8.1.0
	github.com/volatiletech/randomize v0.0.1
	github.com/volatiletech/strmangle v0.0.1
```

With sqlboiler pointing to my working dir which is at commit: 7f09d62 (this is not v4.1.1 but not very far away and I don't think there's anything that would break this between them).

I tried both with a record in the DB and finding that record, as well as no records in the DB and finding nothing.

Not sure where to go from here. Have you made sure that your sqlboiler-mysql driver has been rebuilt after switching to the go mod stuff?

**Comment by eldad87** [comment]
Hi,
You can try using my project.

**Setup**
```
git clone git@github.com:eldad87/go-boilerplate.git
cd go-boilerplate
git checkout migrate_to_mod
docker-compose build
// The next one is going to take a minute or two as it sync the vendor folder with host on boot
docker-compose up app
```

**Sent request**
```
curl 'http://localhost:8080/v1/business/1'
// {"Error":"models: unable to select from businesses: bind failed to execute query: sql: converting argument $1 type: driver ColumnConverter error converted uint to unsupported type uint64","FieldViolations":null}
```


**DB details**
```
DSN: root:root@tcp(localhost:3306)/boilerplate?charset=utf8&parseTime=True&loc=UTC&multiStatements=true

User: root
Password: root
DB: boilerplate
```

**Generate SQLBoiler:** 
```
make sqlboiler
# The generated code is located in src/app/mysql/models
```

**Useful tools (Run on the host)**

- Access project's shell
```
make shell
```
- Run `go mod vendors` and sync the updates with the host
```
make vendors
```

**Comment by eldad87** [comment]
Hi @aarondl ,
Please let me know if there is anything I can do to help you troubleshot this issue.

**Comment by aarondl** [comment]
Hi @eldad87. Is this still an issue for you? I am not really interested in running your big application and docker-compose things. Can you please create a smaller reproduction of the issue?

**Comment by eldad87** [comment]
Hi @aarondl,
Yes, the issue is still relevant.
I will try to narrow it down to a single container and simplify the execution process.

**Comment by eldad87** [comment]
I was able to resolve the issue by removing the DB instrumentation package & code:
```
import (
	instrumentedsql "github.com/luna-duclos/instrumentedsql"
	instrumentedsqlOpenTracing "github.com/luna-duclos/instrumentedsql/opentracing"
)

func main() {
...
	sql.Register("instrumented-mysql", instrumentedsql.WrapDriver(databaseDriver.MySQLDriver{}, instrumentedsql.WithTracer(instrumentedsqlOpenTracing.NewTracer(false))))
	db, err := sql.Open("instrumented-mysql", conf.GetString("database.dsn"))
...
}
```
