### ISSUE TITLE
Invalid binding syntax generated for soft deletion on mysql driver

### ISSUE THREAD

**Issue by viuts** [volatiletech/sqlboiler#748]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.1.1

### What is your database and version (eg. Postgresql 10)
MySQL 5.7

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
Under function `Deleted` with soft deletion enabled
```go
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE `testing` SET %s WHERE `id`=$1",
			strmangle.SetParamNames("`", "`", 0, wl),
		)
```

$1 produced the error in runtime

```
xerrors.wrapError("unexpected database error: orm: unable to delete from testing: Error 1054: Unknown column '$1' in 'where clause'")
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
  CREATE TABLE testing (
    id bigint(20) NOT NULL AUTO_INCREMENT,
    deleted_at datetime,
    created_at datetime NOT NULL,
    updated_at datetime NOT NULL,
    PRIMARY KEY (id),
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

### Further information. What did you do, what did you expect?
`$1` should be `?` following other generated syntax

**Comment by aarondl** [comment]
Fixed in v4.1.2, thanks for the report!
