### ISSUE TITLE
Upsert call in docs seems outdated

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#752]
I have this:

```
			err := m.Upsert(ctx, db, false, nil, boil.Infer())
```

but there error is "not enough args to call upsert"

The docs say this in the readme:
https://github.com/volatiletech/sqlboiler#upsert

so it seems like the docs are outdated

**Comment by aarondl** [comment]
Upsert varies by driver unfortunately. The best way to find documentation for the generated software is to run godoc for the package itself.
