### ISSUE TITLE
NOT IN query mod with no args always evaluates to false

### ISSUE THREAD

**Issue by nwidger** [volatiletech/sqlboiler#754]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

$ sqlboiler --version
SQLBoiler v4.0.0

### What is your database and version (eg. Postgresql 10)

SQLite3

### Further information. What did you do, what did you expect?

There is no `qm.WhereNotIn`, thus I tried to use `qm.WhereIn` to generate a `NOT IN` where query mod:

```go
var vals []interface{}
qm.WhereIn(fmt.Sprintf(`"foobars" NOT IN ?`), vals...)
```

This works fine and generates a query such as

```
SELECT * FROM "foo" WHERE "foo" NOT IN (1, 2, 3);"
```

so long as `vals` is not empty.  If `vals` is empty, however, the query mod results in:

```
SELECT * FROM "foo" WHERE (1=0);"
```

I tracked this odd behavior down to this special behavior for `whereKindIn` in the query builder code:

https://github.com/volatiletech/sqlboiler/blob/50beb2f5634a449d07cdb2fe7ee2638f08b6be65/queries/query_builders.go#L386

```go
// WHERE IN () is invalid sql, so it is difficult to simply run code like:
// for _, u := range model.Users(qm.WhereIn("id IN ?",uids...)).AllP(db) {
//    ...
// }
// instead when we see empty IN we produce 1=0 so it can still be chained
// with other queriesfunc (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
```

I believe that this behavior makes sense for `IN` queries, but I'm not convinced it makes sense for `NOT IN` queries.  Unfortunately, it seems like the query builder does not differentiate between `IN` and `NOT IN`.  The where helpers in the generated model code also use `qm.WhereIn` for `NOT IN` query mods:

```go
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

So my question is, I am doing something wrong?  Is this behavior really expected?  Is there a better way to produce a `NOT IN` query mod?  Or is this something that should be fixed within SQLBoiler itself?
```

**Comment by nwidger** [comment]
As a workaround to the issue, this is the wrapper for `qm.WhereIn` that I'm using to generate `WHERE NOT IN` query mods that, in my mind, function correctly:

```go
func WhereNotIn(field string, values ...interface{}) qm.QueryMod {
	if len(values) == 0 {
		return qm.Where(`1=1`)
	}
	return qm.WhereIn(fmt.Sprintf(`"%s" NOT IN ?`, field), values...)
}
```

**Comment by aarondl** [comment]
Ah yes, this is a horrible side-effect from that horrible change :D

I'm still not sure we did the right thing there. We'll have to get a fix out for this right away.

**Comment by aarondl** [comment]
Hopefully fixed in dev branch by 569dd00

**Comment by nwidger** [comment]
@aarondl Thanks so much for fixing this, I really appreciate it!

**Comment by aarondl** [comment]
@nwidger Thanks for pointing it out. Also amazing catch on the docs (fixed them). Would that all my minor mistakes like that were caught :D

**Comment by nwidger** [comment]
@aarondl No problem!  I figured since I didn't open a PR for my own issue the least I could do is give your commit a once over. :)

**Comment by istrau2** [comment]
@nwidger @aarondl I am not seeing the NIN helpers in my generated code:

```
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}
```

using sqlboiler version v4.1.2, what am i doing wrong?

**Comment by aarondl** [comment]
@istrau2 Please open a new issue and fill out the template including the schema for the table for which you are not seeing the where helper generated.
