### ISSUE TITLE
pgx support

### ISSUE THREAD

**Issue by azcorp-cloud** [volatiletech/sqlboiler#759]
I try create a wrapper over native pgx conn pool, but boil.Executor interface has method Query() with return type sql.Rows, witch is not interface type. Can you create rows interface? It would be very nice.

**Comment by aarondl** [comment]
If I do this then I'm pretty sure we lose compatibility with the `*sql.DB`, and `*sql.Tx` types, and would ruin the main purpose of the interface. So we can't do this :(

**Comment by SebastianM** [comment]
@aarondl The lib/pq is now in maintenance mode. Maybe it's something to reconsider now.

**Comment by jbowa** [comment]
+1

**Comment by aarondl** [comment]
Sounds okay to me. Waiting for a great PR ;)

**Comment by kindermoumoute** [comment]
Hello, I don't have a great PR but is it possible to reopen the issue to make it clear this is still an ongoing issue? 🙏
