### ISSUE TITLE
SELECT with explicit columns (not SELECT *)

### ISSUE THREAD

**Issue by yarelm** [volatiletech/sqlboiler#764]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
3.7.1

### What is your database and version (eg. Postgresql 10)
Postgresql 11

### Further information. What did you do, what did you expect?
Hi,

I'm looking for a way to issue a select query that will provide all columns in the specified table.
It's basically a "SELECT *", but I want the query to be explicit about the columns, and not use a wildcard. (I'm doing DDL schema migrations and `SELECT *` has it's quirks)

I noticed there is a `qm.Select()` function, but it requires me to manually provide it with all column names.
I also noticed there is a `tableAllColumns` variable in the models package, but I can't access it since it is private.

Any ideas?
Thanks

**Comment by aarondl** [comment]
Hi there. I think the only way we want to support naming out all the columns is to name out all the columns. I don't want to export things like `tableAllColumns` because they're mostly implementation details. Currently not looking to do this.
