### ISSUE TITLE
How to generate models for many-to-many join table?

### ISSUE THREAD

**Issue by longngn** [volatiletech/sqlboiler#779]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.7.1

### What is your database and version (eg. Postgresql 10)
PostgresQL 12

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler psql --config configs/sqlboiler.toml
```toml
wipe                           = true
no_tests                     = true
add-global-variants = true
```

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
N/A

### Further information. What did you do, what did you expect?

If the many-to-many join table follow the convention, SQLBoiler will not generate model for it. What if I want to query directly on the join table for optimization while having the type-safety of generated models? How do I instruct SQLBoiler to generate models for those table?

**Comment by aarondl** [comment]
sqlboiler removes these tables to remove clutter from the models package. You can query them with raw queries.

If you -must- have them you can add an extra column to the join table (like a created_at) or anything else which will signal to sqlboiler that it's not safe to omit the table because the user may need data from it.

**Comment by longngn** [comment]
@aarondl Using raw queries is not type-safe and adding extra unnecessary columns would also clutter the table/model itself. How about we add a flag and/or config to tell sqlboiler to generate join table so users can use type-safe query and don't need to add "hack" columns?

**Comment by aarondl** [comment]
@longngn Using raw queries is necessary and you will not get through an entire project without using them. sqlboiler is intentionally incapable of performing every possible query. It's just there to take the boilerplate away from simple things.

Having said that I'm not completely opposed to adding a flag to prevent them from being omitted and would accept a PR for it. The flag should be called: `--no-omit-pure-jointables`.

**Comment by dahu33** [comment]
Was this solved / implemented at the end? Looking for the same feature as it's quite useful / efficient to query the join table directly (e.g. to get all the group IDs of a user).
