### ISSUE TITLE
Enum for postgres ?

### ISSUE THREAD

**Issue by alexisvisco** [volatiletech/sqlboiler#786]
Hi, thanks for this fantastic "orm". 

Are-you planning or is existing a enum feature for postgres like there is in MYSQL ?

Thanks for reading.

**Comment by alexisvisco** [comment]
This is the migration I am using, I have seen that you are supporting enum for postgrs so I don't understand why my enums are not generated :/   https://hastebin.com/yawuceyole.sql

**Comment by aarondl** [comment]
Please fill out the issue template if you have an issue. Thanks.
