### ISSUE TITLE
Test ToMany function fails due to composite unique constraint of two columns

### ISSUE THREAD

**Issue by vtamilselvan141** [volatiletech/sqlboiler#787]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.1.2

### What is your database and version (eg. Postgresql 10)
Cockroachdb  v19.2.5

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
 sqlboiler --wipe crdb  --config="sqlboiler.toml"

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
CREATE TABLE A(                                                               
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),                                             
    X UUID NOT NULL,                                                                
    created_at TIMESTAMPTZ NOT NULL,                                                        
    updated_at TIMESTAMPTZ NOT NULL,                                                        
    deleted_at TIMESTAMPTZ NULL,                                                                           
)       

CREATE TABLE B(                                                               
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),                                             
    data JSONB NOT NULL,         
    a_id UUID NOT NULL REFERENCES A(id),                                               
    created_at TIMESTAMPTZ NOT NULL,                                                        
    updated_at TIMESTAMPTZ NOT NULL,                                                        
    deleted_at TIMESTAMPTZ NOT NULL DEFAULT '1970-01-01',                                                            
    UNIQUE(a_id, delete_at)
);                   
                                                                   
### Further information. What did you do, what did you expect?

- Since table, B's column a_id refers to table A (foreign key relationship) and a_id is not unique on its own, the SQL boiler assumes the relationship to be A -> B (One to Many) which is correct.
- But the issue is while generating the test case, it doesn't look into the constraint UNIQUE(a_id, deleted_at) due to which it tries to insert two rows of the same a_id with default deleted_at value which is 1970-01-01.
- This creates a unique(a_id, deleted_at) constraint violation and the test fails

**Comment by aarondl** [comment]
This is a known issue with the generated tests. Unfortunately the tests are simply not compatible with as many databases as sqlboiler itself is. It was sort of a short-sighted design to think we could remove only foreign key constraints and somehow be able to work around the rest of the constraints.

This will not be fixed because it's simply too much work for very little payoff. Thanks for the report.
