### ISSUE TITLE
Get raw sql string from query builder

### ISSUE THREAD

**Issue by erencay** [volatiletech/sqlboiler#792]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.2.0

Is it possible take a look at what is the built sql string looks like?

```
users, err := models.Users(
        qm.Expr(
            models.UserWhere.Username.EQ(username),
            qm.Or2(models.UserWhere.Nickname.EQ(nickname)),
            qm.Or2(models.UserWhere.Email.EQ(email)),
        ),
    ).AllG(ctx)
```

How do I ensure this chain of commands actually generated the exact same query I intend it to be?

**Comment by arsham** [comment]
You can set the debug mode to true just before your query:
```go
boil.DebugMode = true
```

**Comment by aarondl** [comment]
Thanks for fielding this question @arsham. He is correct that's how you'd do it. Alternatively you can also turn on something like `log_statement=all` in postgresql (I usually leave this on on my development machines/docker containers) to be able to look at its logs and see all the queries occurring. mysql/mssql no doubt will have an equivalent I'm sure.
