### ISSUE TITLE
[Feature Request] Custom struct tag arguments

### ISSUE THREAD

**Issue by wych42** [volatiletech/sqlboiler#796]
We want to custom struct json tag arguments for some type field.

For example a int64 id should have tag `json:"id,string"`.

As this data maybe used in JavaScript, and the built-in JSON.parse can't process integer large than 2^32.

**Comment by aarondl** [comment]
If you're using the built-in JSON package (https://golang.org/pkg/encoding/json/) then `json:"id,string"` is invalid. There is no way of controlling the output type from a struct Marshalling unless you change the type itself. To that end you could tell sqlboiler to replace the Go type with a string. See the README section on types.

It's also not clear how you propose to control these custom struct tags.

**Comment by wych42** [comment]
> If you're using the built-in JSON package (https://golang.org/pkg/encoding/json/) then `json:"id,string"` is invalid. There is no way of controlling the output type from a struct Marshalling unless you change the type itself. 

It's valid, quote from: 
>The "string" option signals that a field is stored as JSON inside a JSON-encoded string. It applies only to fields of string, floating point, integer, or boolean types. This extra level of encoding is sometimes used when communicating with JavaScript programs:
```
Int64String int64 `json:",string"`
```


> It's also not clear how you propose to control these custom struct tags.
Issue title changed to "feature request", I currently modified the code to add this `string` option to all filed using `_id` as suffix(which match the guide of db schema inside the team). and I am thinking about a more general solution.

**Comment by aarondl** [comment]
There was some talk on Slack about someone drafting up a proposal for this feature. Just so you're aware :)

**Comment by wych42** [comment]
Can I be invited to sqlboiler's Slack(if it's not privated team).

**Comment by aarondl** [comment]
@wych42 It's public. Just click the link in readme :)

**Comment by wych42** [comment]
Found it in the badge under the logo, no wonder I didn't get search result in web page.
