### ISSUE TITLE
Find by unique constraint function generation

### ISSUE THREAD

**Issue by randallmlough** [volatiletech/sqlboiler#798]
This is more of a question/request.

Is it possible to get sqlboiler (or a custom template) to generate helper functions that are based on unique constraints?

sqlboiler already generates a helper func to find a model by it's primary key (ie. `Find[MODEL]()`). But what if I also want a helper func to get generated for a unique constraint like, email or session_token?

Something like, `func FindBy[CONSTRAINT]()` would be really handy.

**Comment by aarondl** [comment]
This is possible with a set of custom templates. If you look at the `--debug` output you'll see that columns contain information on whether or not they're unique when they get to code generation stage. If you play with that you'd be able to create something. As this was a question I will close it as I'm considering it answered. Just post here if you have any follow-up questions :)

**Comment by uded** [comment]
Actually, I have a similar problem. Would be interesting to see this as an example or, possibly, an optional extension. This pattern is quite common in SQL world.
