### ISSUE TITLE
Unix timestamp support?

### ISSUE THREAD

**Issue by flanyanero** [volatiletech/sqlboiler#800]
I have a Postgres DB that stores timestamps as unix timestamps (bigint) and am having trouble getting it to work with the automated timestamps for `created_at` and `updated_at` (which I was hoping it would treat as `time.Time` fields).  Is there a workaround or something I can do to keep working with unix timestamps in the DB?  Thanks!

If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
4.2.0

### What is your database and version (eg. Postgresql 10)
Postgresql 11

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```
create table account (
    created_at bigint not null default extract(epoch from now()),
    updated_at bigint not null default extract(epoch from now())
);
```

**Comment by aarondl** [comment]
Hi @flanyanero, unfortunately there's no way that automatic timestamps can work with a non time.Time field. It specifically looks for that type to know that it's okay to do automated timestamps iirc.

I can't think of a workaround that exists that would allow it to continue to work. You could perhaps attempt to use sqlboiler's hook system to mimic the functionality though.

Also I'd suggest that you migrate your database away from this scheme. Postgres has great date/time types: https://www.postgresql.org/docs/current/datatype-datetime.html and I'd encourage you to use them. Not only are they storage efficient but then you can also query them more easily.
