### ISSUE TITLE
[Question] null package version and release tag

### ISSUE THREAD

**Issue by andradei** [volatiletech/sqlboiler#804]
The https://github.com/volatiletech/null package is named `github.com/volatiletech/null/v8` on its [`go.mod`](https://github.com/volatiletech/null/blob/master/go.mod#L1) but its release tags are all `v6`.

Somehow it all still works, but would it be better if _name_ and _tag_ were consistent with each other?

**Comment by aarondl** [comment]
@andradei Click the "Show newer tags" in the releases screen, there exists the following tags past v6:

```
v7.0
v7.0.0
v7.1
v7.1.0
v8.0.0
v8.1.0
```

We just didn't add "Github Releases" to those tags. I added a Github release for v8.1.0 just so its there now. :p
