### ISSUE TITLE
export models.R for mocking

### ISSUE THREAD

**Issue by mrkagelui** [volatiletech/sqlboiler#805]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
v4.2.0

### What is your database and version (eg. Postgresql 10)
Postgresql 12.2
### Further information. What did you do, what did you expect?
In unit testing, I mock the return data from my actual model for the upper layer. In a particular func, I eager load and return the object with its relationships; then I realized that I can't mock this relationship. e.g.,

my func:
```go
func GetBoxWithItems(ctx context.Context, id string) (*Box, error) 
```
where `Box.R` has `Items`.

In my test with mock, I wish to do:
```go
box.R = &BoxR{Items: items}
...
return box
```

I know there's `box.AddItems`, but that will take in the executor. Is there a reason you don't export the relationship?

**Comment by arsham** [comment]
You can do `box.R = box.R.NewStruct()` and then populate the struct. Would that work in your use-case?

**Comment by mrkagelui** [comment]
oh wow didn't know that, thank you @arsham !
