### ISSUE TITLE
Docs request - how to isolate/narrow transaction context 

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#810]
I am trying to figure out how to reduce/narrow the transaction isolation level, so that I don't lock up the entire database for each transaction. Is there documentation on how to do this?

I assume it's something this:

```golang
tx, err :=  db.Begin(context.Background(), TxOptions{ something something here })
```

**Comment by ORESoftware** [comment]
I am wondering if the is a way to lock certain tables / rows, instead of something bigger like the whole db.

**Comment by aarondl** [comment]
@ORESoftware sqlboiler does nothing about locking. If you open a transaction there is some implicit locks in say postgres that occur, but it's up to you to figure out what locks occur and if that's sufficient for your use case.

The queries you make control the locking. For example in postgresql:

```
select * from jobs where id = 5 for update
```

```
lock table jobs;
```

sqlboiler doesn't really concern itself with these things. There is one or two query mods that help with it though.
