### ISSUE TITLE
Many to many generated code doesn't match examples

### ISSUE THREAD

**Issue by Tiltorito** [volatiletech/sqlboiler#812]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v4.2.0

### What is your database and version (eg. Postgresql 10)

Postgresql 12

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

sqlboiler psql

### Further information. What did you do, what did you expect?

I have the same issue as the person who posted this on stackoverflow:

https://stackoverflow.com/questions/55746637/how-to-perform-a-many-to-many-query-with-sqlboiler

Personally my join table is the following:

![Screenshot 2020-07-28 at 17 24 46](https://user-images.githubusercontent.com/31311538/88693732-8aa83380-d0f7-11ea-8024-2f94cc951224.png)
 
and the code that was generated:
```go
type userR struct {
        // ....
	UsersTaughtSubchapters UsersTaughtSubchapterSlice `boil:"UsersTaughtSubchapters" json:"UsersTaughtSubchapters" toml:"UsersTaughtSubchapters" yaml:"UsersTaughtSubchapters"`
}
```

I would expect to be able to access the subchapters directly

Just noticed that the doc says:

_Join tables should use a composite primary key.
For join tables to be used transparently for relationships your join table must have a composite primary key that encompasses both foreign table foreign keys and no other columns in the table. For example, on a join table named user_videos you should have: primary key(user_id, video_id), with both user_id and video_id being foreign key columns to the users and videos tables respectively and there are no other columns on this table._

However, this might not always be desirable - are there any workarounds for that?

**Comment by aarondl** [comment]
There are no workarounds for this unfortunately! If you want additional columns (in your case id) sqlboiler cannot transparently remove the table for you.
