### ISSUE TITLE
How to mitigate dialect version differences

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#816]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

##### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.2.0

##### What is your database and version (eg. Postgresql 10)
PostgreSQL (ver. 11.6)

#### Problem

We run, `go generate` but it seems to mix and match /v4/ and / so we get this:

```
v1/model/cm2_balance.go:933:41: cannot use dialect (type "github.com/volatiletech/sqlboiler/v4/drivers".Dialect) as type
 "github.com/volatiletech/sqlboiler/drivers".Dialect in argument to buildUpsertQueryPostgres
```

is there a way to mitigate this problem?

**Comment by aarondl** [comment]
This seems like you've generated your models with the wrong version of the postgres driver. Please ensure you have the latest version of the `sqlboiler-psql` driver installed as it's responsible for the `buildUpsertQueryPostgres` function and it has no references currently to the old non v4 drivers package.
