### ISSUE TITLE
Equivalent of "Blacklist" to use in "Select" query modifier?

### ISSUE THREAD

**Issue by cedricvanrompay** [volatiletech/sqlboiler#817]
I want to retrieve all columns except one from a table. I noticed [`boil.Blacklist`](https://pkg.go.dev/github.com/volatiletech/sqlboiler/v4@v4.2.0/boil?tab=doc#Blacklist) that seems to do what I want (blacklisting columns), except it seems to only be made for `Insert()` and `Update()` on model objects, and it does not seem like I can use it in a query modifier.

Is there a way to use `Blacklist` when retrieving data (with or without `qm.Select`)?
If not, how would you advise to implement column blacklisting to give to `qm.Select`?

**Comment by aarondl** [comment]
There is no way to do this unfortunately. And as it's mainly an edge case I don't think we'll add anything in sqlboiler to support it. Sorry bout that.
