### ISSUE TITLE
SQLboiler generating model for every postgres partition table.

### ISSUE THREAD

**Issue by unique1o1** [volatiletech/sqlboiler#818]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
sqlboiler v4.2.0

### What is your database and version (eg. Postgresql 10)
Postgresql 12

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler --wipe psql

### Further information. What did you do, what did you expect?
I thought only the parent table's model would be created

**Comment by aarondl** [comment]
Need more information. What is a parition (assuming partition) table? Can you give an example of a set of tables for which you believe sqlboiler is generating the incorrect thing?

Please put a bit more effort into your bug report.

**Comment by syllabix** [comment]
When using partitions, you can instruct sql boiler to generate these tables via the blacklist configuration options in your sqlboiler.toml config. 

So if you have a table, say - `products` and you create three partitions, naming them `products_n` - your sqlboiler.toml should look like:

`
[psql]
dbname = "my-database"
host = "postgres"
blacklist = [
   "products_1",
   "products_2",
   "products_3",
]
# additional config here
`

**Comment by unique1o1** [comment]
> Need more information. What is a parition (assuming partition) table? Can you give an example of a set of tables for which you believe sqlboiler is generating the incorrect thing?
> 
> Please put a bit more effort into your bug report.

I'm using postgres's Declarative Partitioning with range method on a Date column. So for table `transaction`, there are 4 partition tables(for now). 

Like:
1. `transaction_q1`
2. `transaction_q2`
3. `transaction_q3`
4. `transaction_q4`

And sqlboiler is generating models for all 5 tables including the parent table `transaction`. And the relationship helper methods were only generated for the partition tables and not the parent tables.

**Comment by unique1o1** [comment]
> So if you have a table, say - `products` and you create three partitions, naming them `products_n` - your sqlboiler.toml should roughly look like:

Is there a wildcard character support for doing this? Since I'm using a range method partition on a `Date` column, the partition table will grow every 3 months. And adding it manually is cumbersome

**Comment by syllabix** [comment]
I am not aware of wild card support - that said have you tried? If indeed there is not, I would suggest modifying your build strategy by _not_ including these partitions in the environment where you are generating your sqlboiler code. Instead - generate the latest partitions via a scheduled job or on demand in your production/running environment.

**Comment by unique1o1** [comment]
That's definitely one way of doing it. But I would rather not. I think I will just go with sqlx with this one.
Thanks though
