### ISSUE TITLE
SELECT ... FOR UPDATE

### ISSUE THREAD

**Issue by mfzl** [volatiletech/sqlboiler#819]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
`SQLBoiler v3.6.1`

### What is your database and version (eg. Postgresql 10)
`postgres (PostgreSQL) 12.3`

This is more of a question or maybe a feature request. It's not obvious from the document if it's possible to lock rows on select.

https://www.postgresql.org/docs/9.0/sql-select.html#SQL-FOR-UPDATE-SHARE

It would be something good to have if it's already not there. What's the best practice to handle such cases right now when using `sqlboiler`. Things that are not explicitly supported. I'm trying to avoid interpolating strings as much as possible.

**Comment by aarondl** [comment]
See this function:
https://pkg.go.dev/github.com/volatiletech/sqlboiler/v4@v4.2.0/queries/qm?tab=doc#For

**Comment by mfzl** [comment]
Thanks a lot.

> What's the best practice to handle such cases right now when using sqlboiler. Things that are not explicitly supported. I'm trying to avoid interpolating strings as much as possible.

I would still like to know what the best practice is for doing that. For example it's common to use `SKIP LOCKED` when using `SELECT ... FOR UPDATE`. But I'm not sure from the docs how I would apply that

**Comment by aarondl** [comment]
You can still just use the `for` qm for that. Sort of a hack but this would work: `qm.For('update skip locked')`
