### ISSUE TITLE
Feature: Specify Custom Primitives

### ISSUE THREAD

**Issue by tooolbox** [volatiletech/sqlboiler#825]
I saw #609 added `.IN()` helper methods for all primitive types, which is great!

I'm interested in extending this to *custom* primitive types.  For example:

```go
type MyInt int32 // wishes he were a real primitive type
```

If I use the `types` config to specify `mypkg.MyInt` for a column, I unfortunately lose the `.IN()` helper.  I looked through the code and I understand why this is.

What do we think about configuration that extends the `isPrimitive` function, to allow a user to specify that custom types are primitives and so should benefit from these extra helper methods, and any other gifts SQLBoiler bestows upon card-carrying primitive types?

I could put it in the `types` section of the config, or a fully new section, as desired.

Also, I'm aware that this is perhaps very niche, and most users wouldn't think to configure such things until they run into the lack of it, but I'm open to other suggestions.  Detecting a trailing `int` or `string` in the name of the type seems like going too far.

**Comment by aarondl** [comment]
It's mostly a case of "do we need it"? I suppose if throughout your system if you were using int32s as ids it'd be frustrating not to be able to.

sqlboiler's feature set grows so much every day, so maybe it'd be more interesting to come up with more ergonomic ways of dealing with `in` queries in the query builders rather than try to bless other types. The notion of a `primitive` may also be used in other places where the distinction should still be made since it is very much a Go sql package distinction being made. Not 100% sure on that.

**Comment by tooolbox** [comment]
> It's mostly a case of "do we need it"? I suppose if throughout your system if you were using int32s as ids it'd be frustrating not to be able to.

I can hack around it, but it's a bit like trying to take an extra step down a staircase when you've reached the bottom.

> sqlboiler's feature set grows so much every day, so maybe it'd be more interesting to come up with more ergonomic ways of dealing with in queries in the query builders rather than try to bless other types. The notion of a primitive may also be used in other places where the distinction should still be made since it is very much a Go sql package distinction being made. Not 100% sure on that.

That sounds neat, but honestly that's not concrete enough for me to execute given my relatively limited knowledge of the package.  If you want to expand on that I'm interested, but not a huge deal.

Thanks for SQLBoiler :)

**Comment by aarondl** [comment]
> I can hack around it, but it's a bit like trying to take an extra step down a staircase when you've reached the bottom.

I love this haha.

Okay, new question for you then. Is it worth it to have all this extra complexity when `qm.WhereIn` is going to work for this use case?

**Comment by tooolbox** [comment]
> I love this haha.

😄 

> Okay, new question for you then. Is it worth it to have all this extra complexity when `qm.WhereIn` is going to work for this use case?

Eh, probably not.  That is what I ended up using, after all.

I think I'm good on this, thanks for the discussion 👍
