### ISSUE TITLE
2 or more depth eagerly loading null check.

### ISSUE THREAD

**Issue by e4drcf** [volatiletech/sqlboiler#826]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v2.4.0

### What is your database and version (eg. Postgresql 10)
mysql 5.7

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
`runtime error: invalid memory address or nil pointer dereference`

### Further information. What did you do, what did you expect?
I've used Load method with 2 depth.
like following:
Load ("firstTable.secondTable.thirdTable")
in case of `null` inside first table it gives an error. 
because it can't find relationships for null.

**Comment by e4drcf** [comment]
I think it's also related to v3.
because code is the same.

**Comment by aarondl** [comment]
If you could put together a small self-contained and reproducible example schema + query that would be appreciated.
