### ISSUE TITLE
How to mock sqlboiler queries

### ISSUE THREAD

**Issue by smalav-cpi** [volatiletech/sqlboiler#828]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.2.0

### What is your database and version (eg. Postgresql 10)
mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper

### Further information. What did you do, what did you expect?

I have got following methods and i am writing unit tests for them, so will have to mock the queries.
FYI : automodel is the package where all generated models are present(like device.go for device table).

```
func (m *Message) updateDevice(parentID int, data map[string]interface{}) (rows int64, err error) {
    rows, err = automodel.Devices(qm.Where(automodel.DeviceColumns.ParentID+"=?", parentID)).UpdateAll(context.Background(), db.GetMaster(), data)
    if err != nil {
        return 0, err
    }
    return rows, err
} 


func (m *Message) getDeviceByID(ID int) (res *automodel.Device, err error) {
    res, err = automodel.Devices(qm.Where("id=?", ID)).One(context.Background(), db.GetSlave())
    if err != nil {
        return nil, err
    }
    return res, nil
}
```
I want to know a way to mock the sqlboiler queries.

**Comment by aarondl** [comment]
I'd recommend an approach like datadog's sql mock library. It interacts very cleanly with sqlboiler.
