### ISSUE TITLE
load related models with a limit doesn't seem to work as expected

### ISSUE THREAD

**Issue by vladvelici** [volatiletech/sqlboiler#835]
I have a piece of code that looks a little bit like this (simplified example):

	posts, err := models.Posts(
		qm.Load(models.PostsRels.Comments,
			qm.OrderBy("posted_at DESC"),
			qm.Limit(3),
		),
	).All(tx)

What I mean is to load the most recent 3 comments for **each** post. What I get is actually 3 comments in total. Am I misunderstanding how this is supposed to work?

**Comment by aarondl** [comment]
@vladvelici yes because that query is actually a second query that fetches ALL the related posts at the same time unfortunately. It's generally quite useful for filtering etc but doesn't work sense in this case.
