### ISSUE TITLE
Incorrect version in dialect import in psql_upsert.go

### ISSUE THREAD

**Issue by Primetalk** [volatiletech/sqlboiler#836]
Thank you for this great project! It looks very impressive.

If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v4.2.0

### What is your database and version (eg. Postgresql 10)
Postgres 13

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`sqlboiler psql`

`sqlboiler.toml` contents:
```
output   = "my_models"
wipe     = true
no-tests = true

[psql]
  dbname = "mydb"
  host   = "localhost"
  port   = 5432
  user   = "myuser"
  pass   = "mypassword"
  schema = "public"
  blacklist = ["migrations", "other"]
  sslmode = "disable"
```

### Further information. What did you do, what did you expect?
Run generation for the first time. Works fine except that in `psql_upsert.go` it imports 
```
	"github.com/volatiletech/sqlboiler/drivers"
```
instead of 
```
	"github.com/volatiletech/sqlboiler/v4/drivers"
```
After fixing this it builds.

**Comment by jeffmvr** [comment]
Yep, we are also seeing the same problem.

**Comment by aarondl** [comment]
This is probably due to not having reinstalled the sqlboiler-psql binary after having updated sqlboiler itself.

https://github.com/volatiletech/sqlboiler/blob/v4.2.0/drivers/sqlboiler-psql/driver/psql.go#L617

Note the import that you're replacing is indeed the correct one in the source code as far as I can tell.

Closing as I don't think there's an issue here.

**Comment by Primetalk** [comment]
@aarondl thank you for your prompt response.

I wonder, are instructions here: https://github.com/volatiletech/sqlboiler#download correct? In particular, psql driver version. Thanks in  advance.
