### ISSUE TITLE
Nested Relationship Struct JSON Response

### ISSUE THREAD

**Issue by Akkadius** [volatiletech/sqlboiler#839]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

v4.2.0 :snoopdogmeme:

### What is your database and version (eg. Postgresql 10)

5.7.31-34 Percona Server (GPL)

### Issue

First of all, amazing work on sqlboiler, I love it

The only thing I'm really jonesing for is an easy way to reflect back the relationship tree without mapping response structs

I have a project where I'm procedurally generating the API using SQLBoiler and it works out incredibly well. Because this is aimed towards privately editing ones own game database I've put a query language on top of the rest endponts that make it easy for a person to easily manipulate their response from the request. Example

```
http://localhost:3000/api/v1/npc_types?where=name_like_Lord_Nagafen&orderBy=id&orderDirection=desc
```

Example `npc_types_controller.go`
```go
func (e *NPCTypeController) getNPCTypes(c echo.Context) error {
	npcTypes, _ := models.NPCTypes(parseQueryModsFromQueryParams(c)...).AllG()

	return c.JSON(http.StatusOK, npcTypes)
}
```

Example Response

```json
[
    {
        "id": 32040,
        "name": "Lord_Nagafen",
        "lastname": "",
        "level": 55,
        "race": 49,
        "class": 1,
        "bodytype": 29,
        "hp": 32000,
        "mana": 0,
        "gender": 2,
        "texture": 0,
        "helmtexture": 0,
        "herosforgemodel": 0,
        "size": 6,
        "hp_regen_rate": 23,
        "mana_regen_rate": 0,
        "loottable_id": 4027,
        "merchant_id": 0,
        "alt_currency_id": 0,
        "npc_spells_id": 25,
        "npc_spells_effects_id": 0,
        "npc_faction_id": 243,
        "adventure_template_id": 0,
        "trap_template": 0,
        "mindmg": 85,
        "maxdmg": 218,
        "attack_count": -1,
        "npcspecialattks": "SEQMCND",
        "special_abilities": "1,1^10,1^13,1^14,1^15,1^17,1^21,1^23,1^26,1^37,10",
        "aggroradius": 225,
        "assistradius": 0,
        "face": 0,
        "luclin_hairstyle": 0,
        "luclin_haircolor": 0,
        "luclin_eyecolor": 0,
        "luclin_eyecolor2": 1,
        "luclin_beardcolor": 0,
        "luclin_beard": 0,
        "drakkin_heritage": 0,
        "drakkin_tattoo": 0,
        "drakkin_details": 0,
        "armortint_id": 0,
        "armortint_red": 0,
        "armortint_green": 0,
        "armortint_blue": 0,
        "d_melee_texture1": 0,
        "d_melee_texture2": 0,
        "ammo_idfile": "IT10",
        "prim_melee_type": 28,
        "sec_melee_type": 28,
        "ranged_type": 7,
        "runspeed": 1.5,
        "MR": 340,
        "CR": 70,
        "DR": 340,
        "FR": 425,
        "PR": 340,
        "Corrup": 34,
        "PhR": 15,
        "see_invis": 1,
        "see_invis_undead": 1,
        "qglobal": 0,
        "AC": 230,
        "npc_aggro": 0,
        "spawn_limit": 0,
        "attack_speed": -17,
        "attack_delay": 18,
        "findable": 0,
        "STR": 174,
        "STA": 174,
        "DEX": 174,
        "AGI": 174,
        "_INT": 174,
        "WIS": 174,
        "CHA": 174,
        "see_hide": 0,
        "see_improved_hide": 0,
        "trackable": 1,
        "isbot": 0,
        "exclude": 1,
        "ATK": 100,
        "Accuracy": 100,
        "Avoidance": 0,
        "slow_mitigation": 0,
        "version": 0,
        "maxlevel": 0,
        "scalerate": 100,
        "private_corpse": 0,
        "unique_spawn_by_name": 0,
        "underwater": 0,
        "isquest": 1,
        "emoteid": 0,
        "spellscale": 100,
        "healscale": 100,
        "no_target_hotkey": 0,
        "raid_target": 0,
        "armtexture": 0,
        "bracertexture": 0,
        "handtexture": 0,
        "legtexture": 0,
        "feettexture": 0,
        "light": 0,
        "walkspeed": 0,
        "peqid": 0,
        "unique_": 0,
        "fixed": 0,
        "ignore_despawn": 0,
        "show_name": 1,
        "untargetable": 0,
        "charm_ac": 0,
        "charm_min_dmg": 0,
        "charm_max_dmg": 0,
        "charm_attack_delay": 0,
        "charm_accuracy_rating": 0,
        "charm_avoidance_rating": 0,
        "charm_atk": 0,
        "skip_global_loot": 0,
        "rare_spawn": 0,
        "stuck_behavior": 0,
        "model": 0,
        "flymode": -1,
        "always_aggro": false
    }
]
```

All of the query mod builder logic goes through a single function that ends up getting reused in a lot of procedurally generated endpoints

`parser.go`
```go

const (
	equalDelimiter  = "__"
	likeDelimiter   = "_like_"
	selectDelimiter = "."
	whereDelimiter  = "."
)

func parseQueryModsFromQueryParams(c echo.Context) []qm.QueryMod {
	queryMods := []qm.QueryMod{}

	// selects
	selectParam := c.QueryParam("select")
	selects := make([]string, 0)
	for _, selectString := range strings.Split(selectParam, selectDelimiter) {
		if len(selectString) == 0 {
			continue
		}

		selects = append(selects, selectString)
	}

	if len(selects) > 0 {
		queryMods = append(queryMods, qm.Select(selects...))
	}

	// where filters
	whereParam := c.QueryParam("where")
	for _, filter := range strings.Split(whereParam, whereDelimiter) {
		if len(filter) == 0 {
			continue
		}

		// parse where field = value
		wheres := strings.Split(filter, equalDelimiter)
		if len(wheres) > 1 {
			queryMods = append(queryMods, qm.Where(fmt.Sprintf("%v = ?", wheres[0]), wheres[1]))
		}

		// parse where field like '%value%'
		wheres = strings.Split(filter, likeDelimiter)
		if len(wheres) > 1 {
			queryMods = append(queryMods, qm.Where(fmt.Sprintf("%v like ?", wheres[0]), fmt.Sprintf("%%%v%%", wheres[1])))
		}
	}

	// order
	orderByParam := c.QueryParam("orderBy")
	if len(orderByParam) > 0 {
		orderDirection := "asc"
		orderDirectionParam := c.QueryParam("orderDirection")
		if len(orderDirectionParam) > 0 {
			orderDirection = orderDirectionParam
		}

		queryMods = append(queryMods, qm.OrderBy(fmt.Sprintf("%v %v", orderByParam, orderDirection)))
	}

	return queryMods
}
```

Now that I have context out of the way with the above, there's hundreds of tables like this with tons of relationships and it would be very easy to add query param logic for requesting relationships to be included in the output dynamically. 

However this is a little difficult with having to procedurally generate custom response objects for every controller as well when I would think this should all be available to expose naturally in sqlboiler as it is in GORM https://www.thetopsites.net/article/54984956.shtml

I could have a param that is as such `?links=table1,table2,table3` which in `parseQueryModsFromQueryParams` simply tries to append eager loading the necessary relationships and including them in the response which would beautiful 

I know you've responded to other threads suggesting to just creating your own response struct which I agree and makes sense when you're manually wiring, but in a dynamic case such as this where I get code reuse out of 100's of tables, how much work would it be to get sqlboiler to expose those relationships to json naturally ?

Again, incredible work on this, really love it, just really missing this one piece that I've had in frameworks like Laravel's Eloquent relationship resolvers and GORM's relationship resolvers for API responses

**Comment by aarondl** [comment]
You could consider forking the templates to expose R. Or just run a post-process on the sqlboiler generated code, pretty easy to find the R struct field and change its json tag.

We could also make the decision that we could expose relationships behind some sort of config option. Since people seem to want to do this time and time again.

**Comment by Akkadius** [comment]
I would gladly donate for having relationships exposed via config option so I could continue using sqlboiler versus choosing to use something like gorm (Not that GORM is bad, I like it too)

**Comment by aarondl** [comment]
I think you should choose the correct tool for your use case. If GORM has the features already and does it well, then I think you should use that. Every one of these types of projects has different trade-offs.

As for donation, if someone's interested in collecting it to implement the feature that'd be great. Personally I won't be following up and I only mention that as I'm the sole maintainer so it'd be someone from the outside that would complete it.
