### ISSUE TITLE
Raw sql and in/any

### ISSUE THREAD

**Issue by polderudo** [volatiletech/sqlboiler#841]
On mysql (5.7) and raw queries it seems not possible to use any:

```
ids := types.Array([]int{1, 2, 3, 5, 6})
sql := `select * from tab where id=any(?)`
err := queries.Raw(sql, ids).Bind(...)
```

throws an "invalid SQL" error.

i tried 
`sql := `select * from tab where id=any(select ?)``
which will not throw an error, but also does not return any values, but works on mysql 

Any hints on how to use this on mysql?

**Comment by aarondl** [comment]
I don't think mysql understands the array data type. `types.Array` specifically is for postgresql. I think you just have to come up with another way to do it for mysql :\
