### ISSUE TITLE
Multiple configuration with override

### ISSUE THREAD

**Issue by stephenafamo** [volatiletech/sqlboiler#849]
I would like to be able to use multiple configurations and override them.

## Use case

I generate my models locally, and while I definitely want to check in the types configuration to git, I don't want to have to check in my local DB credentials.

Since I am currently ignoring my `sqlboiler.toml` file, if I set up the project on a new computer, I lose all my custom types and aliases.

I would like to be able to do something like `sqlboiler -c sqlboiler.db.toml -c sqlboiler.types.toml`. Except that is already possible.

**Comment by aarondl** [comment]
@stephenafamo you can use direnv for your psql configuration and check in the remainder of the configuration file. We generally check in a seed file to our projects so devs can copy it and change whatever they need to, and the collection of type aliases etc would be in there. Not the best, not the worst :)

Probably won't be putting in a feature to directly support this as I think there's workarounds that exist.

**Comment by stephenafamo** [comment]
Assuming I could send in a PR for this which is backwards compatible, would you be interested in merging it?

**Comment by aarondl** [comment]
Not on this one. There's just too many ways to work around it with fairly generic tooling. Sorry!

**Comment by stephenafamo** [comment]
Alright. No problem
