### ISSUE TITLE
Eager loading non foreign key relationships

### ISSUE THREAD

**Issue by mfzl** [volatiletech/sqlboiler#852]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.2.0

### What is your database and version (eg. Postgresql 10)
Postgresql 12

This is a question since I didn't see it mentioned in the documents. Is it possible to eager load related rows with no foreign keys.

**Comment by aarondl** [comment]
You have to do it manually with `Where` things. Without a foreign key it's impossible for sqlboiler to know there's a relationship there. I'd argue that it's impossible for your devs to know too, and I'd suggest adding them very soon! :D
