### ISSUE TITLE
Custom relation implementations

### ISSUE THREAD

**Issue by tmc** [volatiletech/sqlboiler#853]
Context: with PostGIS and geographic information, there are relationships between tables that are interesting to express and leverage that aren't based on primary key lookups. For example, being able to relate one table to another via an `ON ST_Intersects(table1.geom, table2.geom)` relationship can be meaningful.

It doesn't appear that via configuration there's much control over the relationship/association generation code in this project (though I haven't dug in that deeply).

Are there current or planned facilities to allow some customization of how relations/associations are implemented?

**Comment by aarondl** [comment]
Nope. They're really only done by foreign key. sqlboiler sort of missed the mark on the GIS stuff. It was never considered during development so it's support is underwhelming at best.
