### ISSUE TITLE
Confused about insert column set modes (infer vs greylist, etc)

### ISSUE THREAD

**Issue by subsonik** [volatiletech/sqlboiler#859]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.3.0

### What is your database and version (eg. Postgresql 10)
Sqlite 3.28.0

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
```go
customerObject := models.Customer{Name: customer.Name}
if err := customerObject.Insert(context.Background(), database.DBConn, boil.Infer()); err != nil {
    io.WriteString(w, err.Error())
    return
}
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
CREATE TABLE IF NOT EXISTS customers (
      id          INTEGER PRIMARY KEY,
      created_at  DATETIME NOT NULL,
      updated_at  DATETIME NOT NULL,
      deleted_at  DATETIME,
      name        TEXT NOT NULL
  );
```

### Further information. What did you do, what did you expect?
Hi,

I've just started with sqlboiler and I'm a little confused about the difference between the insert column set modes (infer vs greylist, etc). What I'd like to happen is: using the schema above, insert just a name value, have sqlboiler automatically insert created_at and updated_at, and return the autoincremented id.

So, ideally, after the insert, I should end up with a struct populated with: the generated id, sqlboiler generated created_at + updated_at, and my specified name value. deleted_at would be null.

This might be ridiculously easy, but I've check the documentation and searched through existing issues, and am still struggling to make this work. Maybe I'm just being a little stupid here (sorry!). 😛 

Excellent library btw, this will hopefully save me a lot of time on a new project I'm working on!

Thanks.

**Comment by subsonik** [comment]
Oops, I neglected to mention above that the following error is produced:

`models: unable to populate default values for customers: sql: no rows in result set`

And enabling debug output reveals the following SQL queries are ran:

```
INSERT INTO "customers" ("created_at","updated_at","deleted_at","name") VALUES (?,?,?,?)
[{2020-11-10 14:19:51.357226 +0000 UTC true} {2020-11-10 14:19:51.357226 +0000 UTC true} {0001-01-01 00:00:00 +0000 UTC false} {WWF true}]
SELECT "id" FROM "customers" WHERE "id"=?
{0 false}
```

The row appears to be inserted but fetching the return results fails.

**Comment by aarondl** [comment]
The issue appears to be that you're not passing in an `id` in your struct. The insert's missing one. Normally this is done via autoincrement ids and then you don't have to pass one in.
