### ISSUE TITLE
WhereIn with inner select

### ISSUE THREAD

**Issue by mg98** [volatiletech/sqlboiler#867]
Hello! This is less a problem, but rather a question. 

I want to construct a query with sqlboiler that represents this SQL statement:

```
SELECT COUNT(*) FROM recipes WHERE recipe_category_id IN (SELECT id FROM recipe_categories rc WHERE rc.recipe_category_id = 1);
```

I was trying to achieve that with the `qm.WhereIn` method but struggled in the implementation of the inner select statement. Is there a way to do this using that or are inner selects not supported?

This is how I'm doing it currently:
```
count, err = models.Recipes(qm.SQL(
			"SELECT COUNT(*) FROM recipes WHERE recipe_category_id IN (SELECT id FROM recipe_categories rc WHERE rc.recipe_category_id = $1)",
			obj.ID,
		)).CountG(ctx)
```

**Comment by aarondl** [comment]
Because you're using a subquery for your `where in` clause this isn't strictly supported by sqlboiler and you should continue to use what you're doing here. You could change it to this if you preferred:

```
count, err = models.Recipes(qm.SQL(
    qm.Where(`recipe_category_id IN (SELECT id FROM recipe_categories rc WHERE rc.recipe_category_id = $1)`, obj.ID),
).CountG(ctx)
```
