### ISSUE TITLE
Error while generating model in mysql when ANSI_QUOTES mode is enabled

### ISSUE THREAD

**Issue by alexsander-souza** [volatiletech/sqlboiler#868]
```
/usr/local/go/bin/go generate ./models
unable to fetch table column info (*********): Error 1054: Unknown column '%MariaDB%' in 'field list'
Error: unable to initialize tables: unable to fetch table data: driver (/go/bin/sqlboiler-mysql) exited non-zero: exit status 1
```

If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.3.0

### What is your database and version (eg. Postgresql 10)
MySQL Server 8.0.21-1debian10

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sh -c "PATH=$(go env GOPATH)/bin:$PATH sqlboiler -o . --config ./sqlboiler.toml --no-back-referencing --add-soft-deletes mysql"

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
N/A

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
N/A

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
It happens whatever the schema is. The issue is the use of double quotes as string delimiter in a query in `func (m *MySQLDriver) Columns()`

**Comment by aarondl** [comment]
Closing and using PR instead of this to track.
