### ISSUE TITLE
Error about mysqldump in auto generated tests

### ISSUE THREAD

**Issue by MONAKA0721** [volatiletech/sqlboiler#869]
```
mysqldump: Couldn't execute 'SELECT COLUMN_NAME, 
JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"') 
FROM information_schema.COLUMN_STATISTICS
WHERE SCHEMA_NAME = '<pkgname>' AND TABLE_NAME = 'goose_db_version';': 
Unknown table 'COLUMN_STATISTICS' in information_schema (1109)
```

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.2.0

### What is your database and version (eg. Postgresql 10)
5.7.31 MySQL Community Server (GPL)

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
```
sqlboiler --wipe -c config/sqlboiler.toml -p <pkgname> mysql
```

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
N/A

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
N/A

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
It happens whatever the schema is. The issue is caused about `mysqldump`.

### Further information. What did you do, what did you expect?

I know how to solve this problem.
This problem is caused by difference of version inconsistency about mysqldump.
If apply mysqldump >= 8  to MySQL < 8, this error message is gotten.
To avoid, add '--skip-column-statistics' to mysqldump command.
In the code, 
https://github.com/volatiletech/sqlboiler/blob/6ccc92cffb06c37bd14183ea1e103ff942aee22b/drivers/sqlboiler-mysql/driver/override/templates_test/singleton/mysql_main_test.go.tpl#L67
change to
```
dumpCmd := exec.Command("mysqldump", m.defaultsFile(), "--no-data", "--skip-column-statistics", m.dbName)
```
I want this change depending on mysql version.

**Comment by aarondl** [comment]
I don't think we have to worry about supporting mismatched versions of mysqldump and mysql server, it's hard enough keeping up with just mariadb vs mysql at the supposed "same" versions.

We won't be fixing this I don't think. Sorry!

**Comment by gabstv** [comment]
I did a workaround on my project by running `sed` after I run `sqlboiler mysql`:
```sh
# replace a line on mysql_main_test.go that would otherwise fail on mariadb
RUNTIMEOS=$(uname -s)
if [[ $RUNTIMEOS == "Darwin" ]]; then
  sed -i'.bak' -e 's/dumpCmd := exec.Command("mysqldump", m.defaultsFile(), "--no-data", m.dbName)/dumpCmd := exec.Command("mysqldump", m.defaultsFile(), "--skip-column-statistics", "--no-data", m.dbName)/g' internal/database/models/mysql_main_test.go
  rm internal/database/models/mysql_main_test.go.bak
else
  sed -i 's/dumpCmd := exec.Command("mysqldump", m.defaultsFile(), "--no-data", m.dbName)/dumpCmd := exec.Command("mysqldump", m.defaultsFile(), "--skip-column-statistics", "--no-data", m.dbName)/g' internal/database/models/mysql_main_test.go
fi
```
