### ISSUE TITLE
Fail go test with foreign keys

### ISSUE THREAD

**Issue by moutend** [volatiletech/sqlboiler#870]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

```console
$ sqlboiler --version
SQLBoiler v4.2.0
```

### What is your database and version (eg. Postgresql 10)

psql (13.0, server 10.12)

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

```console
$ sqlboiler psql
```

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

```console
$ go test
```

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)

```console
--- FAIL: TestDelete (0.00s)
    --- FAIL: TestDelete/Jets (0.02s)
        jets_test.go:48: models: unable to insert into jets: pq: insert or update on table "jets" violates foreign key constraint "jet_pilots_fkey"
        jets_test.go:52: models: unable to delete from jets: pq: current transaction is aborted, commands ignored until end of transaction block
        jets_test.go:59: models: failed to count jets rows: pq: current transaction is aborted, commands ignored until end of transaction block
--- FAIL: TestQueryDeleteAll (0.00s)
    --- FAIL: TestQueryDeleteAll/Jets (0.00s)
        jets_test.go:81: models: unable to insert into jets: pq: insert or update on table "jets" violates foreign key constraint "jet_pilots_fkey"
        jets_test.go:85: models: unable to delete all from jets: pq: current transaction is aborted, commands ignored until end of transaction block
        jets_test.go:92: models: failed to count jets rows: pq: current transaction is aborted, commands ignored until end of transaction block
...
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

I use this schema copied from the sqlboiler's README.

```sql
CREATE TABLE pilots (
  id integer NOT NULL,
  name text NOT NULL
);

ALTER TABLE pilots ADD CONSTRAINT pilot_pkey PRIMARY KEY (id);

CREATE TABLE jets (
  id integer NOT NULL,
  pilot_id integer NOT NULL,
  age integer NOT NULL,
  name text NOT NULL,
  color text NOT NULL
);

ALTER TABLE jets ADD CONSTRAINT jet_pkey PRIMARY KEY (id);
ALTER TABLE jets ADD CONSTRAINT jet_pilots_fkey FOREIGN KEY (pilot_id) REFERENCES pilots(id);

CREATE TABLE languages (
  id integer NOT NULL,
  language text NOT NULL
);

ALTER TABLE languages ADD CONSTRAINT language_pkey PRIMARY KEY (id);

-- Join table
CREATE TABLE pilot_languages (
  pilot_id integer NOT NULL,
  language_id integer NOT NULL
);

-- Composite primary key
ALTER TABLE pilot_languages ADD CONSTRAINT pilot_language_pkey PRIMARY KEY (pilot_id, language_id);
ALTER TABLE pilot_languages ADD CONSTRAINT pilot_language_pilots_fkey FOREIGN KEY (pilot_id) REFERENCES pilots(id);
ALTER TABLE pilot_languages ADD CONSTRAINT pilot_language_languages_fkey FOREIGN KEY (language_id) REFERENCES languages(id);
```

### Further information. What did you do, what did you expect?

After running `sqlboiler psql`, the models directory was generated and the `go build` succeeded. However, `go test` failed with foreign key constraints.

The sqlboiler supports generation with foreign keys, but not testing? The generated tests seems filling each struct fields with randomized values:

```go
// e.g. jets_test.go

	o := &Jet{}
	if err = randomize.Struct(seed, o, jetDBTypes, true, jetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Jet struct: %s", err)
	}
```

Anyway, I found the `--no-tests` flag. I use this flag as a workaround.

**Comment by aarondl** [comment]
Foreign keys are specifically stripped out during testing. We make a copy the DB and get rid of them via regex. If they're defined maybe slightly weirdly maybe they won't be removed and there could be a bug in there. It all uses a bunch of weird psql and database dumping but it seems to be working fine in CI and my local machine.

Do you have the psql tool installed? I think it'd take a bit of local debugging to figure out why the fkeys aren't getting stripped.

**Comment by arthurspa** [comment]
@aarondl , sorry for hijacking this issue, but I was wondering what's the reason sqlboiler strips out the FKs for testing. Is it for improved performance?
