### ISSUE TITLE
qm.Limit(0) is treated as no limit

### ISSUE THREAD

**Issue by longngn** [volatiletech/sqlboiler#871]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

v4.2.0

### What is your database and version (eg. Postgresql 10)

Postgresql 12

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

Use with QueryMod `qm.Limit(0)` will produce SQL query without any limit. It's because query builder check for `limit int` empty value which is also `0`: https://github.com/volatiletech/sqlboiler/blob/master/queries/query_builders.go#L241

### Further information. What did you do, what did you expect?

The SQL command generated should has `LIMIT 0`

**Comment by longngn** [comment]
I suggest using `limit *int` instead to distinct between 0 and null value

**Comment by aarondl** [comment]
I don't think we should be making any changes to support executing an empty query. Is there a use case to back up why this is important?

**Comment by longngn** [comment]
> I don't think we should be making any changes to support executing an empty query. Is there a use case to back up why this is important?

I was writing an API where client can send `limit` and `offset` directly for pagination. The API returns total and items list. However, in some page, client only needs to display total count so it set `limit: 0` in expect of selecting no data. This is based on assumption that in SQL, `LIMIT 0` returns no data. However, sqlboiler removes the `LIMIT` clause so the API unexpectedly query all data and our developers didn't notice that until a the data get large.

**Comment by aarondl** [comment]
Perhaps I'm being stubborn but I think the correct fix here is to disallow bad inputs from the users. Having said that it -is- technically a valid query even if very silly and I'd accept a PR to fix this bug.
