### ISSUE TITLE
Does sqlboiler support CASE statement?

### ISSUE THREAD

**Issue by elfgoh** [volatiletech/sqlboiler#873]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
3.4.0

### What is your database and version (eg. Postgresql 10)
Postgresql 9.6

I have a use case where I need to use the `CASE` statement, similar to the snippet. Question: is this supported in sqlboiler using helper methods? If it isn't, do I need to use `queries.Raw()`, or is there a workaround using something like [generated columns](https://www.postgresql.org/docs/12/ddl-generated-columns.html)(not supported in 9.6) or [triggers](https://www.postgresql.org/docs/9.6/plpgsql-trigger.html)? Any advice will be greatly appreciated 🙇 

```
SELECT 
	 CASE WHEN alphaValue IS NULL THEN 'False' ELSE 'True' END AS hasAlphaValue
FROM someTable
```

**Comment by aarondl** [comment]
Just noting your sqlboiler version is quite old! (1 yr 7 months). May want to consider upgrading.

There are no query mods that help with case statements. But they are supported in `qm.Select` itself. The problem is if you're changing the type then Bind() will complain if the type you've returned no longer matches the type that's possible for the struct it's binding into.

With a custom struct binding & a `qm.Select` it will work as long as you make sure the types and names match up :)

**Comment by elfgoh** [comment]
Thanks for your suggestions! Will definitely work towards upgrading.

Based on my rudimentary understanding, I am slightly confused with regards as to how to use `qm.Select` for my use case, since `has_alpha_value` isn't a field that exists. I am also unclear for my use case where I want all the fields in the model generated by sqlboiler, followed by the additional field that doesn't exisit (`has_alpha_value`)

To verify my understanding, I am going to write some code based on this dbfiddle, and please let me know if I am on the right track https://www.db-fiddle.com/f/f5B3kNpnrux8XEHPQuHNBR/1

<details>

```
CREATE TABLE my_table(
	id SERIAL PRIMARY KEY,
  	alpha_letter text NOT NULL,
  	alpha_value text
);

INSERT INTO my_table (alpha_letter, alpha_value)
VALUES
	('alpha','one'),
  	('bravo', null), 
	('charlie', 'three'),
	('delta','four'),    
	('echo', null),
	('foxtrot', 'six');

SELECT * FROM my_table;
SELECT
	alpha_letter, alpha_value,
	CASE WHEN alpha_value IS NULL THEN 'FALSE' ELSE 'TRUE' END AS has_alpha_value
FROM my_table;
```

</details>

```
// Generated by sqlboiler
type MyTable struct{
    AlphaLetter string `json:"alphaLetter"`
    AlphaValue string `json:"alphaValue"`
}

// Custom struct where I want all the fields from models.MyTable, plus additional custom fields
type MyTableCustom struct{
    models.MyTable.AlphaLetter `boil:",bind"
    models.MyTable.AlphaValue `boil:",bind"
    HasAlphaValue bool `boil:",bind"
}

var myTableCustom MyTableCustom

err := models.NewQuery(
Select("my_table.alpha_letter", "my_table.alpha_value", "CASE WHEN alpha_value IS NULL THEN 'FALSE' ELSE 'TRUE' END AS has_alpha_value"),
From("my_table")
)).Bind(ctx, db, &myTableCustom)
```

**Comment by aarondl** [comment]
This is correct so long as bind is putting the right thing in the right places (struct tags/struct field names must be very precise to work with bind).

Your understanding on select is fine. You basically just name it `as something` and then make sure Bind() can put `something` into a struct based on struct tags or the struct field names.
