### ISSUE TITLE
Support for SQL Server 2008 R2

### ISSUE THREAD

**Issue by blitzd** [volatiletech/sqlboiler#875]
I know that the docs say SQL Server 2012+, but I am wondering what would need to be done to support MS SQL 2008 R2. 

I have been able to generate models fine against 2008 R2, but when trying to then use the models in simple queries there are never any results returned. 

Things like .Count() seem to work fine, but the basic .FindXXX() ones don't return any results, .Raw equivalents of the same simple queries I am trying to do also don't appear to work (no results).

When I am viewing debug output it looks like the queries it is generating are all fine - but, they just don't seem to return results back.

I'm just trying to get a sense of whether the gap between this working and not working is a minor one... thanks for any insights you can provide!

**Comment by blitzd** [comment]
I think this actually may be a different issue than I was thinking it was - the problem actually seems to be that the parameter that is being passed in here is somehow always 1:

```
c, err := models.FindDimAudit(ctx, db, 2)
if err != nil {
	log.Fatalf("Error occurred finding audit: %+v\n", err)
}

fmt.Printf("Found AuditKey %d\n", c.AuditKey)
```

My output when running that:

```
select * from [dw].[DimAudit] where [AuditKey]=$1
[2]
Found AuditKey 1
```

...it was returning nil results on my 2008 R2 database because the tables I was querying with it simply didn't have a record with the ID of 1.

Any ideas?

**Comment by blitzd** [comment]
I see the problem now - it looks like you have a bug with the parameterization of queries on SQL Server. This is what I caught with the SQL profiler from my above query:

```
exec sp_executesql N'select * from [dw].[DimAudit] where [AuditKey]=$1',N'@p1 bigint',@p1=2
```

And that basically gets translated to:

`select * from [dw].[DimAudit] where [AuditKey]=1`

...because the $ is ignored in TSQL. The proper parameterization should look like this:

`exec sp_executesql N'select * from [dw].[DimAudit] where [AuditKey]=@p1',N'@p1 bigint',@p1=2`

...which properly uses the parameter passed in, and thus returns the correct record.

**Comment by aarondl** [comment]
I think the issue here is driver-related and hasn't got anything to do with sqlboiler *exactly*. We rely on the fact that $1 works in both psql and mssql and if that's not the case currently all bets are off :D

https://github.com/denisenkom/go-mssqldb#query-parameter-token-replace-driver-mssql

**Comment by lohmanndouglas** [comment]
I am having the same issue and both sqlboil driver and denisenkom driver.

```
Edit: Just to be clear - the above tests were performed on an instance of SQL 2016, NOT 2008 R2.
```

I would like to know if someone is using sqlBoiler with sql server and made it work
