### ISSUE TITLE
Binding inner structures

### ISSUE THREAD

**Issue by mg98** [volatiletech/sqlboiler#894]
_SQLBoiler v3.7.1/ Postgresql 12_

I would like to know if there is a more smooth way to achieve what I am trying to with this code:

```
type MealQuantity struct {
	NutritionalProfileID int
	MealID               int
	Quantity             int
}

var mqs []MealQuantity

if err = models.NewQuery(
	qm.Select("meal_id", "nutritional_profile_id", "count(*) as quantity"),
	qm.From("orders"),
	qm.Where("menu_id=?", menu.ID),
	qm.Where("meal_id is not null"),
	qm.GroupBy("nutritional_profile_id, meal_id"),
).Bind(ctx, tx, &mqs); err != nil {
	return nil, err
}

var result []*graph_model.MealQuantity
for _, mq := range mqs {
	meal, err := models.FindMeal(ctx, tx, mq.MealID)
	if err != nil {
		return nil, err
	}

	np, err := models.FindNutritionalProfile(ctx, tx, mq.NutritionalProfileID)
	if err != nil {
		return nil, err
	}

	result = append(result, &graph_model.MealQuantity{
		Meal:               meal,
		NutritionalProfile: np,
		Quantity:           mq.Quantity,
	})
}
```

**Explanation:** I want to grasp some grouped data from the database. The result (`graph_model.MealQuantity`) has the following structure:

```
type MealQuantity struct {
	Meal               *models.Meal               `json:"meal"`
	NutritionalProfile *models.NutritionalProfile `json:"nutritional_profile"`
	Quantity           int                        `json:"quantity"`
}
```

I was by the way trying to work with what is demonstrated here: https://github.com/volatiletech/sqlboiler#binding But it did not work for me, the data of the structs would not get attached and have default/ nil values. I will not post the code here so the issue description does not get too bloated.

**Comment by aarondl** [comment]
The trick with binding is to ensure that nested structs have nested-looking names as results in the query. By default SQL engines produce bad names for select queries. If I do this:

```
select user.id, video.id ...
```

The column names for this select become `id, id`.

In order to make recursive binding work the way you want it to you have to rename the columns to include the prefix of the struct field name you want it to bind into.

```
select meal_id as meal.id
```

This type of thing.
