### ISSUE TITLE
"Has both field and method named Type" issue for foreign key "enum" (lookup table) - aliasing not working

### ISSUE THREAD

**Issue by yourtallness** [volatiletech/sqlboiler#896]
## SQL Boiler Version

3.6.1

## Issue description

Given:

- a ` resource_types` table that acts as an enum, with a text column named `name`
- an `applications` table with a `type` column that references `resource_types.name`

SQLBoiler will generate both a `Type` attribute and a `Type()` method for the resulting `Application`.
It also refers to the `applications` as `TypeApplications` in the generated `ResourceType`.

I understand this is a consequence of the foreign key not ending in `_id`, so I tried to use aliases to set the association names explicitly.

## Aliases tried

I've tried adding the following to the toml used by generation:

```
[aliases.tables.applications.relationships.type]
  local = "Application"
  foreign = "ResourceType"
```

It makes no difference, please advise.

P.S. Or could I skip the lookup table model generation and avoid the issue entirely?

**Comment by yourtallness** [comment]
Solved my issue by using the following exclusions:

```
blacklist = ["schema_migrations", "resource_types"]
```

Just for the info, if I can get an explanation why the alias approach did not work, that'd be great.

**Comment by aarondl** [comment]
There has been quite a few changes since 3.6.1 including bug fixes to alias related bits. It could help to update sqlboiler.
