### ISSUE TITLE
Count and Offset use incompatible types

### ISSUE THREAD

**Issue by slessard** [volatiletech/sqlboiler#897]
The generated `Count` method for my table returns an `int64` which is what I expect since Postgres can have an unlimited number of rows. 

    // Count returns the count of all Organization records in the query.
    func (q organizationQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {

There is an issue with the `qm.Offset` method. As defined it only takes an `int`. 

    func Offset(offset int) QueryMod {

This means that on 32-bit systems it is impossible to offset to rows above approximately 2,000,000,000.

I expect the framework to use a uniform integer type for all operations involving the number of rows in a table

**Comment by aarondl** [comment]
This is a fair point. Though it's a breaking change as integral types do not have any implicit conversions.

Other things to consider is that we have to constantly cater to the lowest common denominator so whether it goes to int64 or int32 is a real issue.

**Comment by stephenafamo** [comment]
I think using `int64` is the better call. Most DB systems default to using `int64`, and even the [driver.Valuer](https://pkg.go.dev/database/sql/driver#Value) interface also prefers `int64`.

I've made this change to Limit and Offset on the v5 branch with [this commit](https://github.com/volatiletech/sqlboiler/commit/17c42f95178e2e5ee84b8fc78fa8b5d776c13931).
