### ISSUE TITLE
cannot find package "github.com/hashicorp/hcl/hcl/printer"

### ISSUE THREAD

**Issue by elstr** [volatiletech/sqlboiler#904]
When running build on my docker img for boiler I'm getting the following error:
`cannot find package "github.com/hashicorp/hcl/hcl/printer"`
I have no clue on how to fix this since it's an inner dep.

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.3.1

### What is your database and version (eg. Postgresql 10)
PostgreSQL 13.1

### Further information. What did you do, what did you expect?
I'm building a docker image for boiler and I get the following error:

```

Step 9/18 : RUN env GO111MODULE=off go get github.com/volatiletech/sqlboiler
 ---> Running in df12eb292cc1
cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
        /usr/local/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
        /go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)


```

This is my docker image 
```
FROM golang:1.15 as build

ARG driver
ENV GOOSE_DRIVER=$driver

RUN mkdir -p /go/src/bitbucket.org/smalls-grpc-server
WORKDIR /go/src/bitbucket.org/smalls-grpc-server
COPY . .
RUN go get github.com/volatiletech/sqlboiler/v4
RUN go get github.com/volatiletech/null/v8
RUN go get -v github.com/volatiletech/sqlboiler
RUN go get github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql

ENTRYPOINT ["sqlboiler", "psql", "--wipe"]
```

Thanks!

**Comment by smtheard** [comment]
@elstr I also ran into this issue and was able to work around it by installing the 4.3.1 release instead of the latest (4.4.0)

```
go get -u -t  github.com/volatiletech/sqlboiler@6ccc92c
```

**Comment by elstr** [comment]
My team and I where able to fix this by using `github.com/volatiletech/null/v8 v8.1.1` and changing the order of runs in our docker image.

Current gomod, maybe it helps someone
```
github.com/volatiletech/null/v8 v8.1.1
github.com/volatiletech/randomize v0.0.1
github.com/volatiletech/sqlboiler/v4 v4.4.0
github.com/volatiletech/strmangle v0.0.1
```

Current boiler docker image
```
RUN go get github.com/volatiletech/sqlboiler/v4
RUN env GO111MODULE=off go get github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql
RUN go get github.com/volatiletech/null/v8
```

Hope it helps. 
Best,

**Comment by wsantos** [comment]
@aarondl I'm also having this issue, and this hack didn't work for me.

**Comment by aarondl** [comment]
I'm not sure what's wrong here since it seems to work fine outside of Docker, but I actively discourage the use of Docker for self contained Go binaries. Docker's never been supported by this project as you can see from the lack of README instructions or Dockerfile. You're unfortunately on your own, good luck!

**Comment by kevinlang** [comment]
I'm also hitting this error, and am not on Docker.

I found what was pulling in this dep by using `go mod graph`:
```
$ go mod graph | grep hashicorp
github.com/spf13/viper@v1.6.3 github.com/hashicorp/hcl@v1.0.0
github.com/hashicorp/hcl@v1.0.0 github.com/davecgh/go-spew@v1.1.1
github.com/spf13/viper@v1.4.0 github.com/hashicorp/hcl@v1.0.0
```

And then found [this issue](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md#cannot-find-package) which links to [this workaround](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md#cannot-find-package). TLDR, you need to have `GO111MODULE=on`. Will want to run outside of any go repository to avoid modifying any `go.mod` file when rerunning the command.

Once Go 1.1.6 has wider adoption, I think the fix here is to update the installation docs instead to be:
```
go install github.com/volatiletech/sqlboiler@latest
```

Which is outlined in the [1.16 release notes](https://blog.golang.org/go116-module-changes#TOC_4.).

**Comment by wsantos** [comment]
That was exactly what I did, install on a WSL instance outside my project but with Modules on.

**Comment by KonstantinKuklin** [comment]
same problem

**Comment by aakashRajur** [comment]
go installed via homebrew [ref](https://formulae.brew.sh/formula/go)

`go version` yields `go version go1.16 darwin/amd64` 

`GO111MODULE=off go get -u -t github.com/volatiletech/sqlboiler` as outlined in documentation fails with the exact error

tried `go install github.com/volatiletech/sqlboiler@latest`, installs an older version. Specifically `v3.7.1` when invoking `sqlboiler --version`

transient solution that worked for me

`cd $GOPATH/src/github.com/volatiletech/sqlboiler`

`go build -o $GOPATH/bin/sqlboiler main.go`

now, `sqlboiler --version` yields `v4.4.0`

**Comment by mmohaveri** [comment]
As far as I understand, based on [this issue](https://github.com/spf13/viper/issues/1076), the problems is that sqlboiler's Readme is suggesting using `GO111MODULE=off` to avoid messing project's `go.mod`. But when we turn off go modules, go get will try to fetch the latest version of all the packages, and the latest version of `hashicorp/hcl` is not compatible with viper.

My solution was to create a temporary go module (by creating a new folder and running `go mod init example.com/example`, and install sqlboiler there).

**Comment by aarondl** [comment]
I created a new workspace where I could try installing in various ways.

What did not work (our documented installation method):
```
GO111MODULE=off go get -u -t github.com/volatiletech/sqlboiler
```

What did work:
```
// Go 1.15 and below
GO111MODULE=on go get -u -t github.com/volatiletech/sqlboiler/v4
GO111MODULE=on go get -u -t github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-psql

// Go 1.16 only
go install github.com/volatiletech/sqlboiler/v4@latest
go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-psql@latest
```

Keep in mind that @kevinlang's suggestion is incorrect and will give you an old version of sqlboiler because it's missing the /v4 suffix.

I am going to amend our README instructions to include the two working methods. I expect there may still be problems with the Go 1.15 parts but I'm not really too concerned. Go's backwards compatibility is excellent and I think in general most people upgrade Go versions very quickly. It won't be long until this project migrates to `embed` anyway.
