### ISSUE TITLE
GetContextDB returns nil

### ISSUE THREAD

**Issue by tilakraj9560** [volatiletech/sqlboiler#908]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
`SQLBoiler v4.4.0`

### What is your database and version (eg. Postgresql 10)
`psql (PostgreSQL) 13.1`

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
```
sqlboiler psql
output   = "models"
wipe     = true
no-tests = false

[psql]
.......

```
### If this happened at runtime what code produced the issue? (if not applicable leave blank)
```
if err := user.Insert(context.TODO(), boil.GetContextDB(), boil.Infer()); err != nil {
        return err
}
```

### Further information. What did you do, what did you expect?

```
sqlDB, err := sql.Open("postgres", connection)
if err != nil {
        return nil, err
}

//set sql boiler globally
boil.SetDB(sqlDB)
```

Now to insert anything i tried using contexts and when i do the `boil.GetContextDB`, it comes out to be nil. I presume `sql.Open` returns me the `Executor` interface instead of `ContextExecutor`. 

Do i need to implement the methods or is there any other way to do it?

**Comment by jasonlaw** [comment]
Hi, may I know how did you solve the issue? I am having the same problem here. However, I am using mysql. Thanks.

**Comment by ducpham01** [comment]
Hi, for those who encounter this kind of error, make sure you are using `boil.SetDB(sqlDB)` and `boil.GetContextDB` from the same package. 

For example, if you `boil.SetDb()` using `github.com/volatiletech/sqlboiler/boil` but calling `boil.GetContextDB()` using `github.com/volatiletech/sqlboiler/v4/boil` it would return nil because you are not using the same global var.
