### ISSUE TITLE
generation fails on postgres version < 9.3

### ISSUE THREAD

**Issue by vvarma** [volatiletech/sqlboiler#909]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
v4.4.0

### What is your database and version (eg. Postgresql 10)
Postgres 9.1

The error is 
` unable to fetch table column info (accounts_deviceid): pq: syntax error at or near "select"` 
Based on my debugging this is because of the LATERAL join that was introduced since v3. https://github.com/volatiletech/sqlboiler/blob/master/drivers/sqlboiler-psql/driver/psql.go#L244
 
Ideally, if there could be a compatibility matrix published for each version of sqlboiler then that would have helped debug this issue faster.

**Comment by aarondl** [comment]
Ah sorry about that. None of the unsupported versions of postgres are supported. Should work fine with everything that is though.

https://www.postgresql.org/support/versioning/
