### ISSUE TITLE
The imports in the `psql_upsert.go` file seem to be incorrect for v4

### ISSUE THREAD

**Issue by stephen776** [volatiletech/sqlboiler#918]
The imports in the `psql_upsert.go` file seem to be incorrect for v4. When running `sqlboiler --wipe psql` I get the upsert file generated without the `v4` in the path. This results in the following error at build time:

![image](https://user-images.githubusercontent.com/565167/109340684-53d5ff80-7837-11eb-8691-8ac29e91a6f7.png)

the generated imports:

![image](https://user-images.githubusercontent.com/565167/109340443-05286580-7837-11eb-97a8-9909134771cc.png)

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v4.4/.0

**Comment by aarondl** [comment]
https://github.com/volatiletech/sqlboiler/blob/master/drivers/sqlboiler-psql/driver/psql.go#L612-L623

I think this is related to an old version of `sqlboiler-psql`. Remember that it's a separate binary that needs to be installed separately.

The `strmangle` import is not incorrect as it's a v1 package in our root nowadays.
