### ISSUE TITLE
Fail to insert: sqlboiler does "where id=0" in the final select after the insert

### ISSUE THREAD

**Issue by hongshaoyang** [volatiletech/sqlboiler#927]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.4.0

### What is your database and version (eg. Postgresql 10)
MySql 5.7

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`sqlboiler -c sqlboiler.toml --wipe mysql`

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
`order.Insert(exec, boil.Infer())`

debug sql log:
```
SELECT `id` FROM `priced_orders` WHERE `id`=? AND `completed_local_date`=?
0 20210316
```

error log:
```
sql: no rows in result set
models: unable to populate default values for priced_orders
git.xxx.co/billing/models.(*PricedOrder).Insert
        /Users/shaoyanghong/GolandProjects/billing/models/priced_orders.go:507
<rest of stacktrace redacted>
```

code at generated models file around L507:
<img width="1035" alt="Screenshot 2021-03-16 at 7 47 08 PM" src="https://user-images.githubusercontent.com/19281800/111304250-79b13000-8690-11eb-8015-f9e4997dcac2.png">

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

```
CREATE TABLE `priced_orders`
(
    `id`                   bigint      NOT NULL AUTO_INCREMENT,
    `completed_local_date` int(8)      NOT NULL DEFAULT 0,
    -- etc other columns 
    `deleted_id`           bigint      NOT NULL,
    `created_at`           timestamp   NULL     DEFAULT CURRENT_TIMESTAMP,
    `updated_at`           timestamp   NULL     DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at`           timestamp   NULL     DEFAULT NULL,
    PRIMARY KEY (`id`, `completed_local_date`),
)
    PARTITION BY RANGE (`completed_local_date`) (
        PARTITION p20201231 VALUES LESS THAN (20210101)
        );
```
### Further information. What did you do, what did you expect?
sqlboiler is doing a "where id=0" in the final select after the insert. what is this for and why?

**Comment by hongshaoyang** [comment]
Marking this as possibly related to #461

**Comment by aarondl** [comment]
Yep. This is a duplicate. Lets continue conversation over there.
