### ISSUE TITLE
Json is not null when NullDecimal is null state

### ISSUE THREAD

**Issue by komem3** [volatiletech/sqlboiler#934]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
`SQLBoiler v4.5.0`

### Further information. What did you do, what did you expect?

When I try to make the following code json, the result is not null when NullDecimal is null state.
This looks essentially the same problem as #404, but it's also a problem that can be solved with the addition of MarshalJSON.

```go
package main

import (
	"encoding/json"
	"log"

	"github.com/volatiletech/sqlboiler/types"
)

type Device struct {
	BuyingPrice types.NullDecimal `json:"buying_price"`
}

func main() {
	d := Device{BuyingPrice: types.NewNullDecimal(nil)}

	b, err := json.Marshal(d.BuyingPrice.Big)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("value: %#v\njson: %s\n", d.BuyingPrice.Big, string(b))

	b, err = json.Marshal(d.BuyingPrice)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("value: %#v\njson: %s\n", d.BuyingPrice, string(b))

	bytes, err := json.Marshal(d)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("%s\n", string(bytes))
}
```

output
```shell
2021/04/07 12:13:55 value: <nil>
json: null
2021/04/07 12:13:55 value: %!v(PANIC=Format method: runtime error: invalid memory address or nil pointer dereference)
json: "\u003cnil\u003e"
2021/04/07 12:13:55 {"buying_price":"\u003cnil\u003e"}
```

**Comment by aarondl** [comment]
The import path `"github.com/volatiletech/sqlboiler/types"` is incorrect and will be using an old version of types. It should be `/v4/types`.

Once you've fixed this, and if you're still experiencing the issue can you please show your module versions for `ericlagergren/decimal` and `sqlboiler`? Thanks

**Comment by komem3** [comment]
I updated the import and got the same output. ([playground](https://play.golang.org/p/JkTqOc5J4pN))
My versions are below.

```shell
$ cat go.mod
module niljson

go 1.16

require github.com/volatiletech/sqlboiler/v4 v4.5.0

$ cat go.sum | grep ericlagergren/decimal
github.com/ericlagergren/decimal v0.0.0-20181231230500-73749d4874d5 h1:HQGCJNlqt1dUs/BhtEKmqWd6LWS+DWYVxi9+Jo4r0jE=
github.com/ericlagergren/decimal v0.0.0-20181231230500-73749d4874d5/go.mod h1:1yj25TwtUlJ+pfOu9apAVaM1RWfZGg+aFpd4hPQZekQ=
```

**Comment by aarondl** [comment]
Thanks for the reproduce. Have a fix in flight for this.

**Comment by komem3** [comment]
> Have a fix in flight for this.

I'm sorry that what does this mean? Does that mean it's being fixed?

**Comment by aarondl** [comment]
Yes :) It will be available soonish.
