### ISSUE TITLE
Duplicate Relationship Error?

### ISSUE THREAD

**Issue by dtrinh100** [volatiletech/sqlboiler#938]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
4.5.0.

### What is your database and version (eg. Postgresql 10)
13.2

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler psql

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
```
var UserKeyRels = struct {
	UserAccount string
	UserAccount string
}{
	UserAccount: "UserAccount",
	UserAccount: "UserAccount",
}

// userKeyR is where relationships are stored.
type userKeyR struct {
	UserAccount *User `boil:"UserAccount" json:"UserAccount" toml:"UserAccount" yaml:"UserAccount"`
	UserAccount *User `boil:"UserAccount" json:"UserAccount" toml:"UserAccount" yaml:"UserAccount"`
}
```
### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

```
CREATE TABLE IF NOT EXISTS user_account (
   user_key_id INT,
   CONSTRAINT fk_user_key FOREIGN KEY (user_key_id) REFERENCES user_key(id)
);

```

```
CREATE TABLE IF NOT EXISTS user_key (
   id INT DEFAULT nextval('key_seq') PRIMARY KEY,
   key VARCHAR(255) NOT NULL,
   UNIQUE(key)
);

ALTER TABLE user_key ADD COLUMN IF NOT EXISTS user_account_id INT;
ALTER TABLE user_key DROP CONSTRAINT IF EXISTS fk_user_account;
ALTER TABLE user_key ADD CONSTRAINT fk_user_account FOREIGN KEY (user_account_id) REFERENCES user_account(id) ON DELETE SET NULL;

```
### Further information. What did you do, what did you expect?

Originally when I generated the code awhile back using sqlboiler version 4.1.2, it worked and looked like this:

```
// UserKeyRels is where relationship names are stored.
var UserKeyRels = struct {
	UserAccount  string
	UserAccounts string
}{
	UserAccount:  "UserAccount",
	UserAccounts: "UserAccounts",
}

// userKeyR is where relationships are stored.
type userKeyR struct {
	UserAccount  *User     `boil:"UserAccount" json:"UserAccount" toml:"UserAccount" yaml:"UserAccount"`
	UserAccounts UserSlice `boil:"UserAccounts" json:"UserAccounts" toml:"UserAccounts" yaml:"UserAccounts"`
}
```

**Comment by aarondl** [comment]
Can you show this table and any table that references it via foreign key from the `--debug` output?

**Comment by aarondl** [comment]
Note that generally when this occurs it's because there's a composite foreign key somewhere.
