### ISSUE TITLE
generated columns are ignored

### ISSUE THREAD

**Issue by jakecoffman** [volatiletech/sqlboiler#941]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

4.5.0

### What is your database and version (eg. Postgresql 10)

Postgres 12

### Further information. What did you do, what did you expect?

Due to #762 (via #266) generated columns are ignored. The models don't contain the columns so the data won't bind.

The main reasoning behind this is that Insert or Update would infer the columns, and since SQLBoiler has no concept of a read-only column it would try to insert data into this generated column which fails.

A workaround to this would have been to `boil.Blacklist` the column, or use the top level config to blacklist the column which would have removed it from the model just as #762 does.

Instead, due to #762 there is no way to use a generated column at all except by doing manual queries and binding to a different struct.

**Comment by stephenafamo** [comment]
This will be in the next release 4.8.4
