### ISSUE TITLE
Unit testable code without a database

### ISSUE THREAD

**Issue by vladvelici** [volatiletech/sqlboiler#945]
Is there a way to write unit tests for functions that work with structs generated by SQLBoiler without using a database.

Imagine a schema like

    CREATE TABLE posts (id integer not null primary key);
    CREATE TABLE comments (id integer not null primary key, post_id integer references posts (id));

which generates a struct that look a little bit like this:

    type Post struct {
        ID int
        R *postR
        L postL
    }

    type postR struct {
        Comments []CommentSlice
    }

Now, the type `postR` is unexported which makes sense most of the time. The notable exception is when writing unit tests. Consider functions like the following, in a different package (since we don't want those to get wiped on regeneration):

    func PostPopularityScore(post *models.Post) float32 {
         // uses post.R.Comments and some values from the post itself.
    }
    
    func PostsPopularity(post []*models.Post) float32[] {
    }

What do you think is the best way to test such functions in isolation (no db and queries involved)? Is there a different way to write those functions instead? Thanks!

**Comment by aarondl** [comment]
It being unexported doesn't mean much. The biggest restriction is that you can't create the value. But there's a workaround because people have asked for it in the past.

```
myPost.R = myPost.R.NewStruct()
```

That should be sufficient for unit testing. Let me know if not.

**Comment by vladvelici** [comment]
This is great. I wasn’t aware of the NewStruct method. Thanks.
