### ISSUE TITLE
Proposal support custom database/table name

### ISSUE THREAD

**Issue by wudi** [volatiletech/sqlboiler#957]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v4.5.0

### What is your database and version (eg. Postgresql 10)

MySQL 5.7

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

sqlboiler mysql 

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

Rule of database name split:  

```
db_foo_01
db_foo_02
... 
db_foo_100
```

Rule of table name split: 
```
t_boo_01
t_boo_02 
... 
t_boo_100
```

### Further information. What did you do, what did you expect?

Have the ability to replace or override table name. Not hardcode.

eg:

```go
// users.go
// Code generated by SQLBoiler 
var UserDB = func (_ context.Context) string {
	return "users"
}


// Users retrieves all the records using an executor.
func Users(mods ...qm.QueryMod) userQuery {
    // mods = append(mods, qm.From("`users`")) // replace by below
	mods = append(mods, qm.From("`" + UserDB() + "`"))
	return userQuery{NewQuery(mods...)}
}

```

```go
// overwrite default func
models.UserDB = func(ctx context.Context) string {
   
   // Retrieve db name from ctx or execute some rules and return db name

   return "db_foo_02" 
}
```

Table name in the same way.

In reality, Many companies use the hard way to split up the database or table.
Proposal support custom database or table name.

Cheers

**Comment by wudi** [comment]
```go
// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
   ...
   sql := fmt.Sprintf("UPDATE `%s` SET %s WHERE %s",
        UserDB(),
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userPrimaryKeyColumns, len(o)))
   ...
}
```

**Comment by wudi** [comment]
I am glad to do it.

**Comment by aarondl** [comment]
Hi @wudi I'm not ready to commit to anything around sharding/multi-tenancy. Table name via context is a pretty simplistic solution but I don't want to implement anything we're not going to have forever.

The world of sharding/multi-tenancy goes pretty deep and there's crazy packages like:
https://github.com/blastrain/octillery
https://github.com/evalphobia/wizard
https://github.com/go-pg/sharding

Not sure what approach we should be taking etc.

**Comment by wudi** [comment]
THX for reply and references.
