### ISSUE TITLE
IsNull() helper not generated when first encountered text array is NOT NULL

### ISSUE THREAD

**Issue by mwieser** [volatiletech/sqlboiler#964]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
`SQLBoiler v4.5.0`

### What is your database and version (eg. Postgresql 10)
`Postgres 12.4`

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE a_table (
    id uuid NOT NULL DEFAULT uuid_generate_v4 (),
    some_array text[] NOT NULL,
    CONSTRAINT a_table_pkey PRIMARY KEY (id)
);

CREATE TABLE b_table (
    id uuid NOT NULL DEFAULT uuid_generate_v4 (),
    some_array text[],
    CONSTRAINT b_table_pkey PRIMARY KEY (id)
);
```

### Further information. What did you do, what did you expect?
I encountered an issue with the generation of the `whereHelpertypes_StringArray` methods. So far we only had nullable `text[]` columns in our spec and we were able to use `IsNull()` and `IsNotNull()` as QueryMods. I created a table today starting with the letter 'a' with a `text[] NOT NULL` column. This moved the helper methods into the file for the new table. The issue is that because this column is `NOT NULL` the `IsNull()` and `IsNotNull()` helper are not generated and are therefore not available for columns which are nullable.

I expected `IsNull()` and `IsNotNull()` to be generated regardless of the table name. When swapping a_table and b_table in the provided example the methods are generated and it works as expected.

**Comment by aarondl** [comment]
Fixed in dev branch 7a6cca0
