### ISSUE TITLE
Generation Error: "error calling Column: could not find column alias for" likely alias issue.

### ISSUE THREAD

**Issue by FloThinksPi** [volatiletech/sqlboiler#966]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

4.6.0

### What is your database and version (eg. Postgresql 10)

Postgres 13.3

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

```sqlboiler psql -o internal/app/notes/sqlboiler/cc -d```

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

```
Error: template: templates/07_relationship_to_one_eager.go.tpl:9:22: executing "templates/07_relationship_to_one_eager.go.tpl" at <$ftable.Column>: error calling Column: could not find column alias for: .isolation_segment_guid
failed to execute template: templates/07_relationship_to_one_eager.go.tpl
github.com/volatiletech/sqlboiler/v4/boilingcore.executeTemplate
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.6.0/boilingcore/output.go:258
github.com/volatiletech/sqlboiler/v4/boilingcore.executeTemplates
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.6.0/boilingcore/output.go:136
github.com/volatiletech/sqlboiler/v4/boilingcore.generateOutput
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.6.0/boilingcore/output.go:56
github.com/volatiletech/sqlboiler/v4/boilingcore.(*State).Run
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.6.0/boilingcore/boilingcore.go:196
main.run
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.6.0/main.go:256
github.com/spf13/cobra.(*Command).execute
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.6.0/main.go:122
runtime.main
        /home/flo/.gvm/gos/go1.16.4/src/runtime/proc.go:225
runtime.goexit
        /home/flo/.gvm/gos/go1.16.4/src/runtime/asm_amd64.s:1371
unable to generate output
github.com/volatiletech/sqlboiler/v4/boilingcore.(*State).Run
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.6.0/boilingcore/boilingcore.go:197
main.run
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.6.0/main.go:256
github.com/spf13/cobra.(*Command).execute
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/flo/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.6.0/main.go:122
runtime.main
        /home/flo/.gvm/gos/go1.16.4/src/runtime/proc.go:225
runtime.goexit
        /home/flo/.gvm/gos/go1.16.4/src/runtime/asm_amd64.s:1371
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

https://gist.github.com/FloThinksPi/28a4d128b63c070f45f79aee39e1863d

### Further information. What did you do, what did you expect?
 I am pretty sure i hit a misnamed col and should cope with that according to https://github.com/volatiletech/sqlboiler/#aliases
However the output is not usefull, i am not sure which table the field is in that was problematic and its foreign key relations that have issues.
Any ideas on this ?

**Comment by FloThinksPi** [comment]
Hm i blacklisted the isolation_segments table and it runs through. So it must be a key in there that is not named according to schema. But i also noticed that the generated Code has some errors, unknown symbol "whereHelpernull_String" and others like this. Hmmm.

**Comment by aarondl** [comment]
```Error: template: templates/07_relationship_to_one_eager.go.tpl:9:22: executing "templates/07_relationship_to_one_eager.go.tpl" at <$ftable.Column>: error calling Column: could not find column alias for: .isolation_segment_guid```

Seems like you're not also blacklisting this column perhaps? It's trying to look up information for it. It will be something that has a fkey to it or from it.

**Comment by FloThinksPi** [comment]
@aarondl yea we were able to use it with:
```
[aliases.tables.service_instance_shares.relationships.fk_target_space_guid]
local   = "SharedServiceInstances"
foreign = "Spaces"
```
As well as dropping a combined foreign key(as this relation is not really needed and just for postgres to check referenced entries really exist)

Yet from the error message it was quite difficult to find out which column/table is the problematic one.
