### ISSUE TITLE
Unmarshal cannot be applied to types.NullDecimal when the Json value is null.

### ISSUE THREAD

**Issue by rikudesu** [volatiletech/sqlboiler#975]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

`SQLBoiler v4.6.0
`
### Further information. What did you do, what did you expect?

If you try to unmarshal the following Json into a struct using types.NullDecimal, you will get the following error.
A sample code has been prepared. It is as follows.

**Code**
https://play.golang.org/p/lNabmlCBkCy
```
package main

import (
	"encoding/json"
	"log"

	"github.com/volatiletech/sqlboiler/v4/types"
)

func main() {
        // success pattern
	j := `{"value":2.0}`
	jstruct := struct {
		Value types.NullDecimal `json:"value"`
	}{}
	if err := json.Unmarshal([]byte(j), &jstruct); err != nil {
		log.Fatalf("%v", err)
	}
	log.Printf("json: %v", jstruct)

       // error pattern
	j = `{"value":null}`
	if err := json.Unmarshal([]byte(j), &jstruct); err != nil {
		log.Fatalf("%v", err)
	}
	log.Printf("json: %v", jstruct)
}
```

**Output**
```
// success pattern
2009/11/10 23:00:00 json: {2.0}

// error pattern 
2009/11/10 23:00:00 invalid syntax
```

---

Ideally, no error will occur and nil will be inserted into the struct.
Are there any plans to support this?

**Comment by aarondl** [comment]
Fixed in dev.
