### ISSUE TITLE
Custom singleton imports overrides other singleton imports.

### ISSUE THREAD

**Issue by bemasher** [volatiletech/sqlboiler#989]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

```
SQLBoiler v4.5.0
```

### What is your database and version (eg. Postgresql 10)

```
PostgreSQL 13.3
```

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

```go
//go:generate sqlboiler --templates=boil_tmpl,boil_tmpl_test psql
```

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)

Instead of the entire output, below is a diff of the output when the relevant configuration is omitted vs present.

```patch
--- without_imports.json	2021-08-28 22:49:46 +0000
+++ with_imports.json	2021-08-28 22:48:36 +0000
@@ -51,28 +51,16 @@
         ]
       },
       "singleton": {
-        "boil_queries": {
-          "Standard": null,
-          "ThirdParty": [
-            "\"github.com/volatiletech/sqlboiler/v4/drivers\"",
-            "\"github.com/volatiletech/sqlboiler/v4/queries\"",
-            "\"github.com/volatiletech/sqlboiler/v4/queries/qm\""
-          ]
-        },
-        "boil_types": {
-          "Standard": ["\"strconv\""],
-          "ThirdParty": [
-            "\"github.com/friendsofgo/errors\"",
-            "\"github.com/volatiletech/sqlboiler/v4/boil\"",
-            "\"github.com/volatiletech/strmangle\""
-          ]
-        },
         "psql_upsert": {
           "Standard": ["\"fmt\"", "\"strings\""],
           "ThirdParty": [
             "\"github.com/volatiletech/sqlboiler/v4/drivers\"",
             "\"github.com/volatiletech/strmangle\""
           ]
+        },
+        "time_int": {
+          "Standard": ["\"time\"", "\"encoding/json\"", "\"database/sql/driver\"", "\"fmt\""],
+          "ThirdParty": null
         }
       },
       "test_singleton": {

```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

Not applicable.

### Further information. What did you do, what did you expect?
For an API, I am occasionally converting generated models to JSON directly and would like to represent time as a millisecond Unix timestamp in the marshaled output. I've created a custom type that embeds a `time.Time`.

This type is written in a new singleton template:

```go
// time_int.go.tpl

type TimeInt struct {
	time.Time
}

func (t TimeInt) MarshalJSON() ([]byte, error) {
	msec := t.UnixMilli()
	return json.Marshal(msec)
}

func (t *TimeInt) UnmarshalJSON(buf []byte) error {
	var msec int64
	err := json.Unmarshal(buf, &msec)
	if err != nil {
		return err
	}

	t.Time = time.UnixMilli(msec)

	return nil
}

func (t TimeInt) Value() (driver.Value, error) {
    return t.Time, nil
}

func (t *TimeInt) Scan(src interface{}) error {
    fmt.Printf("%T\n", src)
}
```

And replaced everywhere `time.Time` is used in `sqlboiler.toml`.

```toml
[[types]]
  [types.match]
    type = "time.Time"
  
  [types.replace]
    type = "TimeInt"
```

The imports are also set on this new template. This is where the problem is introduced. The configuration below appears to nuke all of the default imports for the other singletons that come with sqlboiler, which is seen in the diff above.

```toml
[imports.singleton."time_int"]
  standard = ['"time"', '"encoding/json"', '"database/sql/driver"', '"fmt"']
```

How should I be including this new singleton template and setting the imports without causing sqlboiler to omit imports in the other singleton templates?

**Comment by aarondl** [comment]
The correct way to approach this is to have your type not inside the sqlboiler templates as that's unnecessary. The templates can be told to import any package and will happily use your type even if it's not inside the templates.

The imports in the way you're overriding them are meant as a replacement, not as an addition for more control if you're overriding templates (which as I mentioned isn't necessary here).

https://github.com/volatiletech/sqlboiler/#types

Note the ability to add imports to custom types here.
