### ISSUE TITLE
doc update request - password should be given via `password` key instead of `pass` for postgres database

### ISSUE THREAD

**Issue by gowthamgts** [volatiletech/sqlboiler#995]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.6.0

### What is your database and version (eg. Postgresql 10)
psql 13

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
use `pass` instead of `password`

### Further information. What did you do, what did you expect?
wasted some time on this, looks like it's also documented on pq driver's ref - https://pkg.go.dev/github.com/lib/pq#section-readme. it would be great if we include this somehow in documentation.

**Comment by aarondl** [comment]
Sorry I'm sort of confused. Was this when you were creating your own lib/pq connection string? Or in sqlboiler's config? Not 100% sure what you're referring to.

If it's the case that you're referring to creating the connection string for your own application that has nothing to do with sqlboiler and we should not be copying documentation in to rot if things change in those libraries. You may also not be using lib/pq (it is deprecated for pgx apparently now too btw).

**Comment by gowthamgts** [comment]
hey @aarondl thanks for your time on this. Here's the code:

```
connString := fmt.Sprintf(
        "dbname=%s host=%s port=%s user=%s password=%s sslmode=%s",
	os.Getenv(EnvDBName),
	os.Getenv(EnvDBHost),
	os.Getenv(EnvDBPort),
	os.Getenv(EnvDBUser),
	os.Getenv(EnvDBPass),
	os.Getenv(EnvDBSslMode),
)

db, err := sql.Open("postgres", connString)
```

am i doing it wrong? sorry, i do not have a detailed background on psql drivers in golang.

**Comment by aarondl** [comment]
This is correct. However again this doesn't have anything to do with sqlboiler (very intentionally). The postgresql driver you use to actually use the generated code sqlboiler makes no difference so long as it conforms to the interface we expect and thus to correctly instantiate their connection string you'd have to look in their docs not ours.

Will close this.

**Comment by gowthamgts** [comment]
sure thanks
